### PR TITLE
[Inference] Fix enable_memory_optimize logic when enable mkldnn

### PR DESCRIPTION
**Pull request by jiweibo**
### PR types

Others
### PR changes

Others
### Describe

fix for mkldnn https://github.com/PaddlePaddle/Paddle/issues/48750

### CODE REVIEW

**Comment by sfraczek** [comment]
We will run tests ASAP and see if it works. Thanks.

**Comment by sfraczek** [comment]
ppyoloe works, I'm waiting for some more tests until tomorrow.

**Comment by jiweibo** [comment]
> ppyoloe works, I'm waiting for some more tests until tomorrow.

@sfraczek Excuse me, what is the test result? If there is still a problem, I will change it back to the original logic.
```c++
if (enable_memory_optim_ && use_mkldnn_) {
  enable_memory_optim_ = false;
}
```

**Comment by sfraczek** [comment]
Hi, on our jenkins pipeline we are debugging a problem that pip cannot install deprecated sklearn requirement from paddleseg 2.5.0 found in requirements_no_cuda.txt from paddleTest repo and one more error that still prevent me from finishing tests.

**Review by sfraczek — APPROVED** [review]
In my opinion, you can go ahead and merge it. I don't know when validation will be available and I only have data that it fixes problems. If it breaks anything we can work on this later.

**Review by sfraczek — APPROVED** [review]
LGTM!

**Review by paulinagacek — APPROVED** [review]
LGTM! It fixed problems with bert and ppyolo models.

**Comment by jiweibo** [comment]
> In my opinion, you can go ahead and merge it. I don't know when validation will be available and I only have data that it fixes problems. If it breaks anything we can work on this later.

Thanks very much.

**Review by qingqing01 — APPROVED** [review]

**Pull request merged**
