### PR TITLE
[ROCM] update fluid operators for rocm (part8), test=develop

### PR DESCRIPTION
**Pull request by qili93**
### PR types

New features

### PR changes

OPs

### Describe

[ROCM] update fluid operators for rocm (part8)

### CODE REVIEW

**Review by pangyoki — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]
LGTM for PADDLE_ENFORCE

**Review by GaoWei8 — APPROVED** [review]
LGTM for op benchmark

**Review by luotao1 — APPROVED** [review]
LGTM For const_cast

**Pull request merged**
