### PR TITLE
grpc:remove patch command and file of grpc to Improved quality of Paddle Repo

### PR DESCRIPTION
**Pull request by zhwesky2010**
Reslove issue #21612  **[grpc]**

**remove patch command and file of grpc to Improved quality of Paddle Repo**

### CODE REVIEW

**Review by luotao1 — APPROVED** [review]
LGTM @gongweibao Please have a double check!

**Comment by gongweibao** [comment]
patch都已经打入到包里去了是吗？

**Review by gongweibao — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
> patch都已经打入到包里去了是吗

是的，都打入了。

**Pull request merged**
