### PR TITLE
Adding corresponding hl_fini() for each hl_init() used

### PR DESCRIPTION
**Pull request by botov**
The leak rootcause is a programming error. According my understanding, for each hl_init() method call that allocate memory (GPU and CPU) there should be corresponding hl_fini() method call.

5 places have been identified where this rule is broken. 4 in MultiGradientMachine and one in ParallelNeuralNetwork.

We use DeepSpeech working over PaddlePPaddle V2 in our project. The leak was consistently reproducible during inference (2 training threads on 2 CUDA devices). For leak detection nvidia-smi tool was used. No leaks are identified after the fix. We run 12 hours test session - ~180 000 audio files were inferred - no GPU memory growth detected.

### CODE REVIEW

**Comment by botov** [comment]
Fixes https://github.com/PaddlePaddle/Paddle/issues/10373

**Comment by botov** [comment]
@JiayiFeng @gongweibao Could you please review the change?

**Comment by JiayiFeng** [comment]
Hi, would you please sign the cla license first? Or I can not merge your pr. Thanks!

**Comment by botov** [comment]
@JiayiFeng Hm, that's strange - I signed it before but it indicates that I did not do that. When I go to the details page it shows: "You have signed the CLA for PaddlePaddle/Paddle". Have you seen this before?

**Comment by JiayiFeng** [comment]
Maybe you can try `git commit --amend --date=now` and `git push --force` again to restart the license check.

**Comment by botov** [comment]
@JiayiFeng thanks for the advice. Eventually managed to pass the check.

**Comment by JiayiFeng** [comment]
@botov Great! My colleagues are reviewing this PR now. Will merge it ASAP if everything is OK. Thanks for your contribution!

**Comment by botov** [comment]
@JiayiFeng Are there any updates on this?

**Comment by panyx0718** [comment]
Thanks for fixing this leak! @botov could you resolve the code conflicts? We moved many codes to paddle/legacy

**Comment by botov** [comment]
@panyx0718 It's ready!

**Review by panyx0718 — APPROVED** [review]

**Pull request merged**
