### PR TITLE
add swiglu spmd

### PR DESCRIPTION
**Pull request by zhiqiu**
### PR types

New features
### PR changes

OPs
### Description

add swiglu spmd rule
Pcard-76459

### CODE REVIEW

**Review by heavyrain-lzy — APPROVED** [review]
LGTM for YAML

**Review by pkuzyc — APPROVED** [review]
LGTM

**Review by From00 — APPROVED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by phlrain — APPROVED** [review]

**Pull request merged**
