### PR TITLE
add test_conv2d_op to exclusively test case list

### PR DESCRIPTION
**Pull request by wopeizl**
test=develop

### CODE REVIEW

**Comment by luotao1** [comment]
Why add `test_conv2d_op` to exclusively test case list, is there some error?

**Comment by wopeizl** [comment]
> Why add `test_conv2d_op` to exclusively test case list, is there some error?

Seems this case run out of memory when GPU memory is under 4GB, and we have one machine with 4GB only.

**Comment by luotao1** [comment]
> Seems this case run out of memory when GPU memory is under 4GB, and we have one machine with 4GB only.

How about adding this explanation in the codes?

**Comment by wopeizl** [comment]
close this since the test case may randomly fail on other part

**Pull request closed without merging**
