### PR TITLE
Inception fusion operator.

### PR DESCRIPTION
**Pull request by qingqing01**
1.  Inception fusion:

    Speedup:

    run 1000 times:

    ```
    inception_a1:  523.8522 ms ->  252.816 ms
    inception_a2:  579.2627 ms -> 251.684 ms
    inception_a3:  580.5288 ms -> 245.702 ms
    ```

2. Support horizontal layer fusion in conv_fusion_op. 
3. Add conv search strategy for variable-length input.

### CODE REVIEW

**Review by Superjomn — DISMISSED** [review]
LGTM

**Review by Superjomn — APPROVED** [review]
LGTM

**Review by NHZlX — APPROVED** [review]
LGTM

**Review by panyx0718 — APPROVED** [review]
Approve since no new const_cast is added

**Pull request merged**
