### PR TITLE
Minor typo fix: rete -> rate.

### PR DESCRIPTION
**Pull request by songzy12**
### PR types
Bug fixes

### PR changes
Docs

### Describe
Just a minor typo fix.

### CODE REVIEW

**Comment by songzy12** [comment]
> 2021-10-11 23:45:37 Please find RD for approval first, and then find TPM for approval.
> 2021-10-11 23:45:37 0. You must have  one TPM approval for API documents change:
> 2021-10-11 23:45:37  jzhang533/ZhangJun, dingjiaweiww/DingJiaWei, Heeenrrry/LiKunLun, TCChenlong/ChenLong for general API docs
> 2021-10-11 23:45:37  PangHua/XiangHui for distributed related API docs
> 2021-10-11 23:45:37  twismon/WangYunKai, CheQiXiao/CheQiXiao for inference related API docs.

@jzhang533 hi Jun, per the above error message, it seems this change needs your approval.

Thanks!

**Comment by songzy12** [comment]
Maybe @dingjiaweiww  @Heeenrrry  @TCChenlong

**Review by TCChenlong — APPROVED** [review]
Thanks for your contributing ！

**Comment by songzy12** [comment]
I just realized this PR has not been merged. 
Do we know what is still missing for this one?

**Pull request closed without merging**
