### PR TITLE
[Typing][C-79] Add type annotations for `python/paddle/incubate/nn/functional/swiglu.py`

### PR DESCRIPTION
**Pull request by Turingg**
### PR Category

User Experience

### PR Types

Improvements

### Description

类型标注：
python/paddle/incubate/nn/functional/swiglu.py

### Related links

https://github.com/PaddlePaddle/Paddle/issues/65008

@SigureMo @megemini

### CODE REVIEW

**Review by megemini — APPROVED** [review]
LGTM ～

**Comment by SigureMo** [comment]
PR 描述要按照模板来，不能修改格式

**Review by SigureMo — APPROVED** [review]
LGTMeow

**Comment by Turingg** [comment]
> PR 描述要按照模板来，不能修改格式

好嘞

**Pull request merged**
