### PR TITLE
eltwises + scale fuse pass

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Performance optimization

### PR changes
OPs

### Describe
- add support for elementwises in `operator_scale_onednn_fuse_pass`,
- extend elementwise_add unittest to cover all activations

### CODE REVIEW

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by sfraczek — APPROVED** [review]
LGTM

**Comment by sfraczek** [comment]
@kolinwei please see and approve if this change of test is ok.

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM

**Review by jczaja — APPROVED** [review]
LGTM

**Pull request merged**
