### PR TITLE
Fix div 0 error of case11: paddle.nn.functional.max_pool1d/max_pool2d/max_pool3d

### PR DESCRIPTION
**Pull request by RedContritio**
### PR types

Bug fixes

### PR changes

OPs

### Describe

- #49919
- #49927 

### Solution

- 限制 stride != 0

### CODE REVIEW

**Review by wanghuancoder — COMMENTED** [review]
为这个case加个单测吧

**Comment by RedContritio** [comment]
> 为这个case加个单测吧

已添加

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by weisy11 — APPROVED** [review]
LGTM

**Pull request merged**
