### PR TITLE
add distribute fpn proposals op, test=develop

### PR DESCRIPTION
**Pull request by jerrywgz**
TODO: add gpu kernel

### CODE REVIEW

**Comment by jerrywgz** [comment]
> TODO: add gpu kernel

DONE

**Comment by jerrywgz** [comment]
image
image

**Comment by shanyi15** [comment]
1. please add sth for this parameter: name
image
2. which indicate-->which indicates
3. formula is better to be written by latex format
===
then please preview again

**Comment by jerrywgz** [comment]
image
image

**Comment by shanyi15** [comment]
image

**Comment by jerrywgz** [comment]
image

**Comment by jerrywgz** [comment]
image

**Review by shanyi15 — DISMISSED** [review]
format lgtm, please check the examples, thanks!

**Review by panyx0718 — DISMISSED** [review]
LG API

**Comment by jerrywgz** [comment]
image
image
image

**Review by shanyi15 — APPROVED** [review]
LGTM

**Review by panyx0718 — APPROVED** [review]

**Pull request merged**
