### PR TITLE
[Test mv] mv python/paddle/fluid/tests/unittests/distributed_passes 2 test/dist…

### PR DESCRIPTION
**Pull request by KimBioInfoStudio**
### PR types

Others
### PR changes

Others
### Describe

Others

### CODE REVIEW

**Comment by KimBioInfoStudio** [comment]
Pending on other test which need file from this pr's original path

image

**Comment by luotao1** [comment]
> Pending on other test which need file from this pr's original path

33 任务已经重新释放了，有兴趣的话可以把33任务也一起做了

**Comment by KimBioInfoStudio** [comment]
> > Pending on other test which need file from this pr's original path
> 
> 33 任务已经重新释放了，有兴趣的话可以把33任务也一起做了

有兴趣，没时间 🐶 🐶

**Comment by luotao1** [comment]
需要解决下单测失败的问题
image
这些yaml配置文件没挪出来是不是失败的原因

**Comment by KimBioInfoStudio** [comment]
PR https://github.com/PaddlePaddle/Paddle/pull/52885 已经合入，该PR关闭

**Pull request closed without merging**
