### PR TITLE
Add communication strategy group

### PR DESCRIPTION
**Pull request by LiYuRio**
### PR types

New features

### PR changes

Others

### Describe

Implement hybrid communication strategy

### CODE REVIEW

**Review by haohongxiang — APPROVED** [review]
LGTM for MoE

**Review by ForFishes — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM for 
`set_tests_properties(test_strategy_group PROPERTIES TIMEOUT "120")`

**Review by ForFishes — APPROVED** [review]
LGTM

**Pull request merged**
