### PR TITLE
[XPU]Add flip ut

### PR DESCRIPTION
**Pull request by wz1qqx**
### PR types

Bug fixes
### PR changes

OPs
### Description

- add flip ut as review

### CODE REVIEW

**Review by XiaociZhang — COMMENTED** [review]
需要增加更多test case（一般要5个以上）

**Comment by wz1qqx** [comment]
> 需要增加更多test case（一般要5个以上）

done

**Review by ZibinGuo — APPROVED** [review]
LGTM

**Comment by ZibinGuo** [comment]
您的邮件已收到，我将尽快回信。谢谢您！Your email has been received and I will reply as soon as possible. Thank you！

**Pull request closed without merging**
