### PR TITLE
fix dataloader waning & add gpu tensor notice.

### PR DESCRIPTION
**Pull request by heavengate**
### PR types
Bug fixes

### PR changes
APIs

### Describe

- fix DataLoader warning for `np.bool`
- add GPU tensor operation notice in DataLoader doc

### CODE REVIEW

**Review by TCChenlong — APPROVED** [review]
LGTM

**Review by TCChenlong — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]
LGTM

**Review by LielinJiang — APPROVED** [review]

**Comment by heavengate** [comment]
new PR: https://github.com/PaddlePaddle/Paddle/pull/31763

**Pull request closed without merging**
