### PR TITLE
Enable workspace optimization for cudnn flash attention

### PR DESCRIPTION
**Pull request by Wong4j**
### PR types
Performance optimization

### PR changes
OPs

### Description
Enable workspace optimization for cudnn flash attention

### CODE REVIEW

**Review by zyfncg — DISMISSED** [review]

**Comment by jeng1220** [comment]
@Wong4j ,
PR-CI-GpuPS shows errors:
```
2023-12-25 00:05:22 The following tests FAILED: 
2023-12-25 00:05:22 	2038 - test_fuse_dot_product_attention_pass (Failed)
2023-12-25 00:05:22 	2039 - test_fused_dot_product_attention_op (Failed)
2023-12-25 00:05:22 	917 - test_fused_dot_product_attention_pass (Failed)
```

**Comment by Wong4j** [comment]
The `workspace_opt` is only a feature for Hopper GPU and not applicable on Ampere. So this PR needs to wait for Baidu to add a new Hopper GPU for CI.

**Comment by onecatcn** [comment]
> The `workspace_opt` is only a feature for Hopper GPU and not applicable on Ampere. So this PR needs to wait for Baidu to add a new Hopper GPU for CI.

@vivienfanghuagood will arrange testing on Hopper GPU and will update the results here

**Comment by Wong4j** [comment]
Note:
Need to add compile option `-DWITH_CUDNN_FRONTEND`
Need cuDNN version >= 8.9.6.50

**Comment by zhink** [comment]
Under the Hopper architecture, the L40S machine can work normally and the accuracy is correct.

**Review by zyfncg — APPROVED** [review]

**Pull request merged**
