### PR TITLE
[CodeStyle][C401&C402] replace unnecessary generator set and dict

### PR DESCRIPTION
**Pull request by Ainavo**
### PR types

Others
### PR changes

Others
### Describe

[C401](https://beta.ruff.rs/docs/rules/unnecessary-generator-set/) 将生成器中的 `set()` 替换成 `{}`，使 python 代码更易理解，同时提升代码运行效率，具体如下：

> It is unnecessary to use set around a generator expression, since there are equivalent comprehensions for these types. Using a comprehension is clearer and more idiomatic.
> Examples
> ```Python
> set(f(x) for x in foo) #这里相当于先创建 generator `(f(x) for x in foo)` 之后在调用 `set` 转换成集合。
> ```
> Use instead:
> ```Python
> {f(x) for x in foo} #这里直接创建了 set comprehension，可以省去一步函数的调用，因此可以优化性能。
> ```
> Notes:可以通过调用 dis 模块查看字节码。
> ```Python
> import dis
> 
> dis.dis(compile("set(f(x) for x in foo)", "<string>", "exec"))
> 
> dis.dis(compile("{f(x) for x in foo}", "<string>", "exec"))
> ```
> <p align="right"> —— <a href="https://beta.ruff.rs/docs/rules/unnecessary-generator-set/">unnecessary-generator-set (C401)</a></p>

[C402](https://beta.ruff.rs/docs/rules/unnecessary-generator-dict/) 将生成器中的 `dict((x, f(x)) for x in foo)
` 替换成 `{x: f(x) for x in foo}`，使 python 代码更易理解，同时提升代码运行效率，具体如下：

> It is unnecessary to use dict around a generator expression, since there are equivalent comprehensions for these types. Using a comprehension is clearer and more idiomatic.
> Examples
> ```Python
> dict((x, f(x)) for x in foo) #这里相当于先创建 generator `((x, f(x)) for x in foo)` 之后在调用 `dict` 转换成字典。
> ```
> Use instead:
> ```Python
> {x: f(x) for x in foo} #这里直接创建了 dict comprehension，可以省去一步函数的调用，因此可以优化性能。
> ```
> Notes:可以通过调用 dis 模块查看字节码。
> ```Python
> import dis
> 
> dis.dis(compile("dict((x, f(x)) for x in foo)", "<string>", "exec"))
> 
> dis.dis(compile("{x: f(x) for x in foo}", "<string>", "exec"))
> ```
> <p align="right"> —— <a href="https://beta.ruff.rs/docs/rules/unnecessary-generator-dict/">unnecessary-generator-dict (C402)</a></p>

参考链接：
- [unnecessary-generator-set (C401)](https://beta.ruff.rs/docs/rules/unnecessary-generator-set/)
- [unnecessary-generator-dict (C402)](https://beta.ruff.rs/docs/rules/unnecessary-generator-dict/)
- [flake8 plugin to help you write better list/set/dict comprehensions](https://pypi.org/project/flake8-comprehensions/)

Tracking issue:
- https://github.com/PaddlePaddle/Paddle/issues/51729

### CODE REVIEW

**Review by SigureMo — APPROVED** [review]
LGTM

同 #51839 没修改配置，可以在之后 PR 里一并修改

**Comment by SigureMo** [comment]
PR-CI-Coverage 卡住一天没动了，可以 re-run 下 @Ainavo

**Comment by SigureMo** [comment]
PR-CI-Coverage 有单测超时了，再 re-run 一下吧 @Ainavo

**Comment by Ainavo** [comment]
> 

好的呢~~~

**Pull request merged**
