### PR TITLE
add common dtypes as paddle's dtypes

### PR DESCRIPTION
**Pull request by iclementine**
### PR types

Function optimization

### PR changes

APIs

### Describe

add common dtypes as attribute of paddle. `paddle.float32`, `paddle.float64` are now objects. They can be used as `dtype` argument in many functions.

### CODE REVIEW

**Review by willthefrog — COMMENTED** [review]
this approach would result in similar behavior as `paddle.Tensor`, i.e., `print(uint8)  # VarType.UINT8`

**Comment by iclementine** [comment]
> this approach would result in similar behavior as `paddle.Tensor`, i.e., `print(uint8) # VarType.UINT8`

The __repr__  of `VarDesc.VarType` has already been change by 

https://github.com/PaddlePaddle/Paddle/blob/cd74b20759d9f41c5a0064d6c9ecdaf160594ff0/python/paddle/fluid/dygraph/varbase_patch_methods.py#L448

图片

what I meant is the type of dtype, e.g., `type(uint8)` or `print(uint8)`

**Review by willthefrog — COMMENTED** [review]
LGTM, @jzhang533  @XiaoguangHu01

**Review by jzhang533 — APPROVED** [review]
lgtm

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
