### PR TITLE
Cherrypick seq pad

### PR DESCRIPTION
**Pull request by JiayiFeng**
cherry-pick `sequence_pad_op` to 0.15 release.

### CODE REVIEW

**Review by kuke — DISMISSED** [review]
LGTM

**Comment by panyx0718** [comment]
It seems the CI is not triggered, Can you push something new to try to trigger it?

**Comment by JiayiFeng** [comment]
I tried, but it seems that it's still not working...

**Review by panyx0718 — APPROVED** [review]
In general, we don't add new feature. But I guess it's OK for this  time

**Pull request merged**
