### PR TITLE
[cherry-pick 2.3] Back port of "Fix to #38693 (minimal UT) "

### PR DESCRIPTION
**Pull request by jczaja**
### PR types

 Bug fixes
### PR changes
 Others
### Describe

Back port of fix to https://github.com/PaddlePaddle/Paddle/issues/38693 .

### CODE REVIEW

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@XieYunshen Please approve setting timeout for test (this is backport of PR #41026 that you approved)

**Review by XieYunshen — APPROVED** [review]
LGTM for `set_tests_properties(test_mkldnn_conv3d_op PROPERTIES TIMEOUT 300)`

**Comment by lidanqing-vv** [comment]
@baoachun Please help mering this bug fix cherry-pick PR. Thanks

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
