### PR TITLE
[NewIR] Modify xx_new_ir_mode into xx_pir_mode

### PR DESCRIPTION
**Pull request by DrRyanHuang**
### PR types

Others

### PR changes

Others

### Description

xx_new_ir_mode 替换为 xx_pir_mode
- https://github.com/PaddlePaddle/Paddle/issues/56880

### CODE REVIEW

**Comment by DrRyanHuang** [comment]
@Aurelius84 打扰了，麻烦杰哥看下
```
2023-09-11 23:00:15 ****************
2023-09-11 23:00:15 0. You must have one RD (XiaoguangHu01,chenwhql,zhiqiu,Xreki,luotao1,qili93,Aurelius84) approval for python/paddle/base/framework.py, which manages the underlying code for fluid.
2023-09-11 23:00:15 There are 1 approved errors.
2023-09-11 23:00:15 ****************
```

**Review by Aurelius84 — DISMISSED** [review]

**Review by tianshuo78520a — APPROVED** [review]

**Review by wanghuancoder — DISMISSED** [review]
LGTM

**Review by sunzhongkai588 — DISMISSED** [review]
LGTM for docs

**Review by Aurelius84 — APPROVED** [review]

**Review by zhhsplendid — APPROVED** [review]

**Review by sunzhongkai588 — APPROVED** [review]
LGTM

**Review by jeff41404 — APPROVED** [review]

**Review by wanghuancoder — APPROVED** [review]

**Pull request merged**
