### PR TITLE
[PHI decoupling]migrate device_wrapper.h from fluid to phi

### PR DESCRIPTION
**Pull request by DrRyanHuang**
### PR types

Others 

### PR changes

Others 

### Describe

- 67  paddle/fluid/platform/device/device_wrapper.h
- https://github.com/PaddlePaddle/Paddle/issues/47615

### CODE REVIEW

**Comment by DrRyanHuang** [comment]
@YuanRisheng 打扰了，想问下这个 timeout 该怎么改嘞

```
2023-01-10 10:47:19 The following tests FAILED: 
2023-01-10 10:47:19 	1976 - test_elementwise_add_mkldnn_op (Timeout)
2023-01-10 10:47:19 	2192 - test_mkldnn_conv_concat_relu_mkldnn_fuse_pass (Timeout)
2023-01-10 10:47:19             	1548 - test_dist_se_resnext_nccl (Timeout)
2023-01-10 10:47:19             	1976 - test_elementwise_add_mkldnn_op (Timeout)
2023-01-10 10:47:19             	2192 - test_mkldnn_conv_concat_relu_mkldnn_fuse_pass (Timeout)
```

**Comment by YuanRisheng** [comment]
> @YuanRisheng 打扰了，想问下这个 timeout 该怎么改嘞
> 
> ```
> 2023-01-10 10:47:19 The following tests FAILED: 
> 2023-01-10 10:47:19 	1976 - test_elementwise_add_mkldnn_op (Timeout)
> 2023-01-10 10:47:19 	2192 - test_mkldnn_conv_concat_relu_mkldnn_fuse_pass (Timeout)
> 2023-01-10 10:47:19             	1548 - test_dist_se_resnext_nccl (Timeout)
> 2023-01-10 10:47:19             	1976 - test_elementwise_add_mkldnn_op (Timeout)
> 2023-01-10 10:47:19             	2192 - test_mkldnn_conv_concat_relu_mkldnn_fuse_pass (Timeout)
> ```

Rerun一下试试

**Comment by DrRyanHuang** [comment]
有一个单测报错了，可能是单测的bug ?

https://github.com/PaddlePaddle/Paddle/pull/49615


```
2023-01-10 14:06:53 ======================================================================
2023-01-10 14:06:53 ERROR: test (test_trt_convert_reduce.TrtConvertReduceTest)
2023-01-10 14:06:53 ----------------------------------------------------------------------
2023-01-10 14:06:53 Traceback (most recent call last):
2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce.py", line 180, in test
2023-01-10 14:06:53     self.run_test()
2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py", line 749, in run_test
2023-01-10 14:06:53     for prog_config in self.sample_program_configs(*args, **kwargs):
2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce.py", line 119, in sample_program_configs
2023-01-10 14:06:53     if not self.is_program_valid(program_config):
2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce.py", line 35, in is_program_valid
2023-01-10 14:06:53     for x in attrs[0]["dim"]:
2023-01-10 14:06:53 KeyError: 'dim'
```

**Comment by YuanRisheng** [comment]
> 有一个单测报错了，可能是单测的bug ?
> 
> #49615
> 
> ```
> 2023-01-10 14:06:53 ======================================================================
> 2023-01-10 14:06:53 ERROR: test (test_trt_convert_reduce.TrtConvertReduceTest)
> 2023-01-10 14:06:53 ----------------------------------------------------------------------
> 2023-01-10 14:06:53 Traceback (most recent call last):
> 2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce.py", line 180, in test
> 2023-01-10 14:06:53     self.run_test()
> 2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py", line 749, in run_test
> 2023-01-10 14:06:53     for prog_config in self.sample_program_configs(*args, **kwargs):
> 2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce.py", line 119, in sample_program_configs
> 2023-01-10 14:06:53     if not self.is_program_valid(program_config):
> 2023-01-10 14:06:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce.py", line 35, in is_program_valid
> 2023-01-10 14:06:53     for x in attrs[0]["dim"]:
> 2023-01-10 14:06:53 KeyError: 'dim'
> ```

今天有人合入了有问题的代码，等待修复吧

**Review by YuanRisheng — COMMENTED** [review]
device_wrapper.h似乎只是重命名了一下，该文件里的头文件还是fluid头文件，我们原则上不允许为了解耦当前Fluid头文件而引入额外其他Fluid头文件

**Comment by DrRyanHuang** [comment]
> device_wrapper.h似乎只是重命名了一下，该文件里的头文件还是fluid头文件，我们原则上不允许为了解耦当前Fluid头文件而引入额外其他Fluid头文件

好的，我修改一下

**Pull request closed without merging**
