### PR TITLE
fix doc of alpha_dropout/dropout/dropout2d/dropout3d/npair_loss

### PR DESCRIPTION
**Pull request by huangjun12**
### PR types
Bug fixes

### PR changes
Docs

### Describe
fix en doc of alpha_dropout/dropout/dropout2d/dropout3d/npair_loss

### CODE REVIEW

**Comment by huangjun12** [comment]
image
image

**Comment by huangjun12** [comment]
image
image
image

**Comment by huangjun12** [comment]
image
image

**Comment by huangjun12** [comment]
image
image
image

**Comment by huangjun12** [comment]
image
image
image

**Comment by huangjun12** [comment]
image
image
image

**Comment by huangjun12** [comment]
image
image

**Comment by huangjun12** [comment]
image
image
image

**Comment by huangjun12** [comment]
image
image

**Comment by huangjun12** [comment]
image
image

**Comment by huangjun12** [comment]
image
image

**Comment by huangjun12** [comment]
image
image

**Comment by huangjun12** [comment]
image
image

**Review by TCChenlong — APPROVED** [review]
LGTM

**Pull request merged**
