### PR TITLE
set no moment warning in opt.

### PR DESCRIPTION
**Pull request by wuhuachaocoding**
### PR types

Others
### PR changes

Others
### Description

set warning in optimizer when the state_dict has no moment .

### CODE REVIEW

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by wanghuancoder — DISMISSED** [review]
LGTM

**Review by gongweibao — CHANGES_REQUESTED** [review]
需要增加`restrict=True`和`ignore_name=[]`两个参数，不能简单的只是把assert改成warning。

**Pull request closed without merging**
