### PR TITLE
Zeros like

### PR DESCRIPTION
**Pull request by zhoukunsheng**
this commit  exposes interface for fill_zeros_like_op.

### CODE REVIEW

**Comment by zhoukunsheng** [comment]
image

**Comment by zhoukunsheng** [comment]
resolve #16492

**Comment by shanyi15** [comment]
image

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Comment by zhoukunsheng** [comment]
image
thanks, please review again.

**Review by shanyi15 — DISMISSED** [review]

**Review by XiaoguangHu01 — DISMISSED** [review]

**Review by shanyi15 — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]

**Pull request merged**
