### PR TITLE
Fix the invalid list operation on save_inference_model function.

### PR DESCRIPTION
**Pull request by guomingz**
This bug was found on int8 calibration tool integration.
This is a corner case when the program has the feed(or  fetch) type op.

If we remove the one obj from the list, especially on the List iteration, the index will change dynamically.
In other words, the original implementation will missing the target.
So my fixing is collect the index firstly, and then delete it in reverse sequence.

### CODE REVIEW

**Comment by guomingz** [comment]
hello @luotao1 i found the  continuous-integration/travis-ci/pr was failed due to style checking.
i followed the http://paddlepaddle.org/documentation/docs/zh/1.1/advanced_usage/development/contribute_to_paddle.html instructions and also ran the pre-commit locally. 

But i still couldn't pass the pre-ci. Would u please give me some hints on it?

**Comment by luotao1** [comment]
```
yapf.....................................................................Failed
```
please paste the pre-commit local result

**Comment by guomingz** [comment]
> ```
> yapf.....................................................................Failed
> ```
> please paste the pre-commit local result

Thank you for hint. i  rerun the `pre-commit run yapf` again and fix the issue reported by tool. 
It looks the travis pre-ci has passed.

**Comment by guomingz** [comment]
hi @luotao1 i found the pre-ci was failed due to one unittest case(test_dist_simnet_bow ) is timeout.
How can i verify or reproduce this issue locally?
I'm doubt this issue was raised by pre-ci server itself, can i rerun it without new commit?

**Comment by luotao1** [comment]
http://ci.paddlepaddle.org/viewLog.html?buildId=30386&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tail
```
[09:38:16][Step 1/1] The following tests FAILED:
[09:38:16][Step 1/1] 	212 - test_dist_simnet_bow (Timeout)
```
@typhoonzero Could you help see this random fail?
@guomingz You can rerun the PR_CI.

**Comment by guomingz** [comment]
> @typhoonzero



> http://ci.paddlepaddle.org/viewLog.html?buildId=30386&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tail
> 
> ```
> [09:38:16][Step 1/1] The following tests FAILED:
> [09:38:16][Step 1/1] 	212 - test_dist_simnet_bow (Timeout)
> ```
> @typhoonzero Could you help see this random fail?
> @guomingz You can rerun the PR_CI.

Hi @luotao1  i entered the teamcity page and click the run button again on the right top corner.

It seems that there's problem ` Failed to perform checkout on agent: '/usr/bin/git -c credential.helper= ls-remote origin' command failed.`

Shall i need to modify the original code by adding one line blank to trigger the so-called rerun?

@typhoonzero would u please help me take a look on this timeout issue? Is it raised by env rather than code itself?

**Comment by luotao1** [comment]
@guomingz The computer room was maintained in Nov 24th, and stoped a lot of jobs. Please rerun again.

**Comment by guomingz** [comment]
> @guomingz The computer room was maintained in Nov 24th, and stoped a lot of jobs. Please rerun again.

OK.  Just clicked the run button again.

**Comment by guomingz** [comment]
Hi @luotao1 
I found the MAC_PR_CI took more than 12 hours to finish the testing. Is there any potential hang issue on pre-ci system? Please help to check. 
Thank you in advance

**Comment by luotao1** [comment]
Please merge with the latest code to trigger the MAC_PR_CI. The reason:
- We add `MAC_PR_CI` after this PR, thus, it could not be auto-triggered.
- There is some bug in `MAC`, fixed by #14552. Thus, you must merge with the latest code.

**Comment by guomingz** [comment]
> Please merge with the latest code to trigger the MAC_PR_CI. The reason:
> 
> * We add `MAC_PR_CI` after this PR, thus, it could not be auto-triggered.
> * There is some bug in `MAC`, fixed by #14552. Thus, you must merge with the latest code.

OK。  I reran the PRE_CI(Paddle) and got the ` Failed to perform checkout on agent: '/usr/bin/git -c credential.helper= ls-remote origin' command failed.
exit code: -1` again. Is the computer room maintaining today?

**Comment by luotao1** [comment]
Please use `test=develop` to trigger `MAC_PR_CI`
> Failed to perform checkout on agent: '/usr/bin/git -c credential.helper= ls-remote origin' command failed. exit code: -1

The network is not stabled. You can rerun if you encounter again.

**Comment by luotao1** [comment]
close due to #14631

**Pull request closed without merging**
