### PR TITLE
Add seq2seq api related code

### PR DESCRIPTION
**Pull request by guoshengCS**
- Add gather_tree op to be used in beam search.
- Add stack mode for tensor_array_to_tensor OP to pack tensors in array.
- Add more dtype support for expand, gather_nd, fill_constant and fill_constant_batch_size_like.
- Add for_cpu for fill_constant_batch_size_like and make reduce_any/reduce_all use input decided place to make bool tensor always on cpu, which is restriction of while_op.
- Add seq2seq api.

### CODE REVIEW

**Comment by guoshengCS** [comment]
The usage is as follow:

```python
import paddle.fluid as fluid
import paddle.fluid.layers as layers
from paddle.fluid.layers import LSTMCell, RNNCell, rnn, BeamSearchDecoder, dynamic_decode
from paddle.fluid.contrib.layers import basic_lstm


class EncoderCell(RNNCell):
    def __init__(self, num_layers, hidden_size, dropout_prob=0.):
        self.num_layers = num_layers
        self.hidden_size = hidden_size
        self.dropout_prob = dropout_prob
        self.lstm_cells = []
        for i in range(num_layers):
            self.lstm_cells.append(LSTMCell(hidden_size))

    def call(self, step_input, states):
        new_states = []
        for i in range(self.num_layers):
            out, new_state = self.lstm_cells[i](step_input, states[i])
            step_input = layers.dropout(
                out, self.dropout_prob) if self.dropout_prob > 0 else out
            new_states.append(new_state)
        return step_input, new_states

    @property
    def state_shape(self):
        return [cell.state_shape for cell in self.lstm_cells]


class DecoderCell(RNNCell):
    def __init__(self, num_layers, hidden_size, dropout_prob=0.):
        self.num_layers = num_layers
        self.hidden_size = hidden_size
        self.dropout_prob = dropout_prob
        self.lstm_cells = []
        for i in range(num_layers):
            self.lstm_cells.append(LSTMCell(hidden_size))

    def attention(self, hidden, encoder_output, encoder_padding_mask):
        query = layers.fc(hidden,
                          size=encoder_output.shape[-1],
                          bias_attr=False)
        attn_scores = layers.matmul(
            layers.unsqueeze(query, [1]), encoder_output, transpose_y=True)
        if encoder_padding_mask is not None:
            attn_scores = layers.elementwise_add(attn_scores,
                                                 encoder_padding_mask)
        attn_scores = layers.softmax(attn_scores)
        attn_out = layers.squeeze(
            layers.matmul(attn_scores, encoder_output), [1])
        attn_out = layers.concat([attn_out, hidden], 1)
        attn_out = layers.fc(attn_out, size=self.hidden_size, bias_attr=False)
        return attn_out

    def call(self,
             step_input,
             states,
             encoder_output,
             encoder_padding_mask=None):
        lstm_states, input_feed = states
        new_lstm_states = []
        step_input = layers.concat([step_input, input_feed], 1)
        for i in range(self.num_layers):
            out, new_lstm_state = self.lstm_cells[i](step_input, lstm_states[i])
            step_input = layers.dropout(
                out, self.dropout_prob) if self.dropout_prob > 0 else out
            new_lstm_states.append(new_lstm_state)
        out = self.attention(step_input, encoder_output, encoder_padding_mask)
        return out, [new_lstm_states, out]


start_token = 0
end_token = 1
src_vocab_size = 10000
trg_vocab_size = 10000
num_layers = 2
hidden_size = 512
dropout_prob = 0.2
max_grad_norm = 5.0
learning_rate = 0.001
beam_size = 4
max_length = 100

src = layers.data(name="src", shape=[-1, 1, 1], dtype='int64')
src_len = layers.data(name="src_len", shape=[-1], dtype='int32')

trg = layers.data(name="trg", shape=[-1, 1, 1], dtype='int64')
trg_len = layers.data(name="trg_len", shape=[-1], dtype='int32')
label = layers.data(name="label", shape=[-1, 1, 1], dtype='int64')

src_embeder = lambda x: layers.embedding(x,
                                         size=[src_vocab_size, hidden_size],
                                         param_attr=fluid.ParamAttr(
                                             name="src_embedding"))

trg_embeder = lambda x: layers.embedding(x,
                                         size=[trg_vocab_size, hidden_size],
                                         param_attr=fluid.ParamAttr(
                                             name="trg_embedding"))

encoder_cell = EncoderCell(num_layers, hidden_size, dropout_prob)
encoder_output, encoder_final_state = rnn(
    cell=encoder_cell,
    inputs=src_embeder(src),
    sequence_length=src_len,
    is_reverse=False)

src_mask = layers.sequence_mask(
    src_len, maxlen=layers.shape(src)[1], dtype='float32')
encoder_padding_mask = (src_mask - 1.0) * 1000000000
encoder_padding_mask = layers.unsqueeze(encoder_padding_mask, [1])

decoder_cell = DecoderCell(num_layers, hidden_size, dropout_prob)
decoder_initial_states = [
    encoder_final_state, decoder_cell.get_initial_states(
        batch_ref=encoder_output, shape=[hidden_size])
]

# training
decoder_output, _ = rnn(
    cell=decoder_cell,
    inputs=trg_embeder(trg),
    initial_states=decoder_initial_states,
    sequence_length=None,
    encoder_output=encoder_output,
    encoder_padding_mask=encoder_padding_mask)

output_layer = lambda x: layers.fc(x,
                                   size=trg_vocab_size,
                                   num_flatten_dims=len(x.shape) - 1,
                                   param_attr=fluid.ParamAttr(name="output_w"),
                                   bias_attr=False)

loss = layers.softmax_with_cross_entropy(
    logits=output_layer(decoder_output), label=label, soft_label=False)
loss = layers.reduce_mean(loss)

fluid.clip.set_gradient_clip(clip=fluid.clip.GradientClipByGlobalNorm(
    clip_norm=max_grad_norm))
optimizer = fluid.optimizer.Adam(learning_rate=learning_rate)
optimizer.minimize(loss)

# inference
encoder_output = BeamSearchDecoder.tile_beam_merge_with_batch(encoder_output,
                                                              beam_size)
encoder_padding_mask = BeamSearchDecoder.tile_beam_merge_with_batch(
    encoder_padding_mask, beam_size)
beam_search_decoder = BeamSearchDecoder(
    decoder_cell,
    start_token,
    end_token,
    beam_size,
    embedding_fn=trg_embeder,
    output_fn=output_layer)
outputs, _ = dynamic_decode(
    beam_search_decoder,
    inits=decoder_initial_states,
    max_step_num=max_length,
    encoder_output=encoder_output,
    encoder_padding_mask=encoder_padding_mask)
```

**Comment by guoshengCS** [comment]
辛苦大家主要review下rnn.py中api的内容，使用示例先贴在了这里 https://github.com/PaddlePaddle/Paddle/pull/19820#issuecomment-539413317

目前还有一些未调整的内容如之前反馈：

~~1.  在layers下增加rnn.py有循环引用的问题（需要引用contrib下的BasicGRUUnit等，contrib下又引用了layers，目前通过延迟import暂时解决）~~
~~2.  rnn.py下定义rnn接口导致layers.__init__ 失败问题（执行 from .rnn import *; __all__ += rnn.__all__是吧，rnn模块被函数覆盖率），目前代码中还使用的是`dynamic_rnn`~~
3.  contrib下存在decoder.py与BeamSearchDecoder，用于LoDTensor，之前有遗漏，BeamSearchDecoder命名需要重新

**Comment by guoshengCS** [comment]
[这里](https://github.com/PaddlePaddle/FluidDoc/pull/1489)贴出了API中文文档以供参考

**Comment by guoshengCS** [comment]
@raindrops2sea @XiaoguangHu01 @kuke @luotao1 
目前还有一个CI需要几位的apporve才能跑，麻烦可以先简单看下哈，可以先review中文文档  https://github.com/PaddlePaddle/FluidDoc/pull/1489
image

**Review by luotao1 — DISMISSED** [review]

**Review by kuke — DISMISSED** [review]
LGTM

**Review by raindrops2sea — DISMISSED** [review]

**Review by wanghaoshuang — DISMISSED** [review]

**Review by xyzhou-puck — DISMISSED** [review]
LGTM.

**Review by luotao1 — DISMISSED** [review]

**Review by wanghaoshuang — DISMISSED** [review]

**Review by XiaoguangHu01 — DISMISSED** [review]

**Review by raindrops2sea — DISMISSED** [review]

**Review by kuke — DISMISSED** [review]

**Review by kuke — DISMISSED** [review]

**Review by wanghaoshuang — DISMISSED** [review]

**Review by luotao1 — DISMISSED** [review]

**Review by XiaoguangHu01 — DISMISSED** [review]

**Review by luotao1 — DISMISSED** [review]

**Review by wanghaoshuang — DISMISSED** [review]

**Review by kuke — DISMISSED** [review]

**Review by luotao1 — DISMISSED** [review]

**Review by kuke — DISMISSED** [review]

**Review by wanghaoshuang — DISMISSED** [review]

**Review by raindrops2sea — DISMISSED** [review]

**Review by kuke — APPROVED** [review]

**Review by luotao1 — APPROVED** [review]

**Review by luotao1 — APPROVED** [review]

**Review by wanghaoshuang — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]

**Review by raindrops2sea — APPROVED** [review]

**Pull request merged**
