### PR TITLE
Added comment with request for enhancement

### PR DESCRIPTION
**Pull request by wojtuss**
This adds a `TODO` comment according to https://github.com/PaddlePaddle/Paddle/issues/13550#issuecomment-430133585

### CODE REVIEW

**Review by luotao1 — DISMISSED** [review]
LGTM!

**Comment by luotao1** [comment]
please add `test=develop` in commit, to trigger the CI

**Comment by wojtuss** [comment]
> please add `test=develop` in commit, to trigger the CI

Done.

**Review by luotao1 — APPROVED** [review]
LGTM! Thanks for adding comment!

**Pull request merged**
