### PR TITLE
fix examples, test=document_fix

### PR DESCRIPTION
**Pull request by ceci3**
### PR types

Others

### PR changes

Docs

### Describe

fix english examples for instance_norm, LeakyReLU, weight_norm, remove_weight_norm, SyncBatchNorm
chinese docs: https://github.com/PaddlePaddle/FluidDoc/pull/2925

### CODE REVIEW

**Comment by ceci3** [comment]
image
instance_norm

**Comment by ceci3** [comment]
image
remove_weight_norm

**Comment by ceci3** [comment]
image
weight_norm

**Comment by ceci3** [comment]
image
SyncBatchNorm

**Comment by ceci3** [comment]
image
LeakyReLU

**Review by jzhang533 — APPROVED** [review]
lgtm

**Review by zhiqiu — APPROVED** [review]
LGTM, instance_norm is used in static graph

**Pull request merged**
