### PR TITLE
[Need approval] Add AdamW-CPU FP32 JIT assembly kernel

### PR DESCRIPTION
**Pull request by wozna**
### PR types

New features
### PR changes

OPs 
### Describe

This PR adds AdamW JIT assembly kernel. This feature was requested by https://github.com/PaddlePaddle/Paddle/issues/41950

Before in AdamW, all params were computed with Eigen https://github.com/PaddlePaddle/Paddle/blob/34ac7b74c216bd02d44d9bc57b1537343adc0934/paddle/phi/kernels/funcs/adam_functors.h#L426 and then Adam JIT assembly kernel was used. 

In this PR AdamW JIT implementation, params are calculated with vector instructions in the same loop where params and momentums are calculated. 

Results for VGG training script "test_image_classification.py"
100 batches of 128 images 
 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz

Average kernel time [ms]
| Threads | AdamW with Eigen | AdamW JIT |
|---------|------------------|-----------|
| 1       | 0.0667           | 0.0655724 |
| 20      | 0.133347         | 0.118731  |

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by wozna** [comment]
@Aganlengzi In `PR-CI-Coverage` there is problem in all recent PRs 
`File "/paddle/tools/check_pr_approval.py", line 28, in check_approval
  if review["state"] == "APPROVED":`
Can it be fixed somehow?

@chenwhql In the file `phi/kernels/cpu/adamw_kernel.cc` I used JIT kernel and approval is needed for that. Could you please check this?

**Comment by Aganlengzi** [comment]
> @Aganlengzi In `PR-CI-Coverage` there is problem in all recent PRs
> `File "/paddle/tools/check_pr_approval.py", line 28, in check_approval if review["state"] == "APPROVED":`
> Can it be fixed somehow?

hi, re-run will be ok.

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@Aganlengzi  Could you please help with the PR-CI-APPROVAL ?
```
2022-05-06 05:41:32 2022-05-06 05:41:32 (3.19 MB/s) - 已保存 “bk.txt” [5/5])
2022-05-06 05:41:38 ****************
2022-05-06 05:41:39 0. You must have one RD (chenwhql, MingMingShangTian, YuanRisheng or zyfncg) approval for the including paddle/fluid header in paddle/phi files( paddle/phi/kernels/cpu/adamw_kernel.cc).
```

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]

**Pull request merged**
