### PR TITLE
[Fluid Clean] remove pixel_shuffle, fsp_matrix, where, sign, unique, unique_with_counts

### PR DESCRIPTION
**Pull request by heyanru01**
### PR types

Others
### PR changes

APIs
### Describe

remove pixel_shuffle, fsp_matrix, where, sign, unique, unique_with_counts in paddle.fluid.layers.nn

### CODE REVIEW

**Comment by yingshengBD** [comment]
LGTM

**Comment by heyanru01** [comment]
layers.where用paddle.nonzero替代，test_where_index只与layers.where相关

**Review by jzhang533 — APPROVED** [review]
LGTM for API removing

**Review by XieYunshen — APPROVED** [review]
LGTM
单测删除

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by hong19860320 — APPROVED** [review]
LGTM

**Pull request merged**
