### PR TITLE
Clean Fluid APIs in padde.fluid.layers.nn

### PR DESCRIPTION
**Pull request by GhostScreaming**
### PR types
Others

### PR changes
APIs

### Describe
Clean Fluid APIs in python/paddle/fluid/layers/nn.py, and migrate spectral_norm and row_conv APIs, and remove ont_hot.
Including following files:
1. python/paddle/fluid/layers/nn.py
2. python/paddle/fluid/tests/unittests/collective/fleet/parallel_dygraph_transformer.py
3. python/paddle/fluid/tests/unittests/dist_transformer.py
4. python/paddle/fluid/tests/unittests/dygraph_to_static/transformer_dygraph_model.py
5. python/paddle/fluid/tests/unittests/ipu/test_one_hot_op_ipu.py
6. python/paddle/fluid/tests/unittests/test_imperative_auto_prune.py
7. python/paddle/fluid/tests/unittests/test_imperative_load_static_param.py
8. python/paddle/fluid/tests/unittests/test_layers.py
9. python/paddle/fluid/tests/unittests/test_one_hot_op.py
10. python/paddle/fluid/tests/unittests/test_row_conv_op.py
11. python/paddle/fluid/tests/unittests/test_runtime_and_compiletime_exception.py
12. python/paddle/fluid/tests/unittests/test_spectral_norm_op.py
13. python/paddle/static/nn/__init__.py
14. python/paddle/static/nn/common.py

### CODE REVIEW

**Review by sneaxiy — DISMISSED** [review]

**Review by XieYunshen — DISMISSED** [review]
LGTM

**Review by XieYunshen — DISMISSED** [review]

**Review by jzhang533 — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by sneaxiy — DISMISSED** [review]

**Review by XieYunshen — DISMISSED** [review]
LGTM

**Review by jzhang533 — DISMISSED** [review]

**Review by sneaxiy — DISMISSED** [review]

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by jzhang533 — DISMISSED** [review]

**Review by XieYunshen — DISMISSED** [review]
LGTM for 单测删除

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]

**Pull request merged**
