### PR TITLE
Fix the KL algorithm bug when calculated the size of tensor.

### LINKED ISSUE #17184: 关于离线量化中calibration代码的一些疑惑
1. 关于P_sum的计算
image
image
image
image
从上述代码来看，P_sum的值其实是预测采样时进行迭代的次数。实际上应该为activation_blob中元素的总个数，此处代码应为`P_sum = len(activation_blob.flatten())`。
2. 
下述链接处代码的一些疑惑：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/int8_inference/utility.py#L674

image
根据674行代码的上下文可知min_kl_index必然大于等于starting_iter，若min_kl_index=0，则必然是因为starting_iter等于0，那么while循环条件就不会成立，最后min_kl_index=starting_iter=0。即这段if语句就算成立也是什么都没有做，请问这段代码是否是冗余的呢？

### PR DESCRIPTION
**Pull request by guomingz**
resolve #17184

Fix the KL algorithm bug when calculated the size of tensor.

With this fixing， below table shows the latest KL effort on mobilenetv1(measured via python api)

|  KL status  | top-1 | top-5 |
| :--- | :----: | ----: |
|Disabled| 70.22% | 89.46% |
| Enabled   | 70.48%      | 89.54%    |

### CODE REVIEW

**Review by wzzju — DISMISSED** [review]
LGTM.

**Comment by guomingz** [comment]
hi @luotao1  it seems that pre-ci tests for this PR were frozen since the day before yesterday. i also can't find the tests on the [team city queue](http://ci.paddlepaddle.org/queue.html).  

Is there anything wrong with the pre-ci system?  Or what can i  do to solve this issue?

**Comment by luotao1** [comment]
please add `test=develop` in commit info.

**Comment by guomingz** [comment]
> please add `test=develop` in commit info.

thanks for reminder

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
