### PR TITLE
[cherry-pick2.4]docs fix

### PR DESCRIPTION
**Pull request by Ligoml**
### PR types

Others
### PR changes

Docs
### Describe

https://github.com/PaddlePaddle/Paddle/pull/46165
https://github.com/PaddlePaddle/Paddle/pull/45752
https://github.com/PaddlePaddle/Paddle/pull/45488
https://github.com/PaddlePaddle/Paddle/pull/46422
https://github.com/PaddlePaddle/Paddle/pull/46659
https://github.com/PaddlePaddle/Paddle/pull/46927
https://github.com/PaddlePaddle/Paddle/pull/46738
https://github.com/PaddlePaddle/Paddle/pull/47040

### CODE REVIEW

**Review by jzhang533 — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]
LGTM after conflicts resolved

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
