### PR TITLE
[Bug fix] Fix for matmul_v2 6D x 2D oneDNN

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Bug fixes

### PR changes
OPs

### Describe
Fix for matmul_v2 6D x 2D oneDNN. It is a fix for #36217

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Review by wozna — APPROVED** [review]
LGTM

**Comment by baoachun** [comment]
@jakpiase Hi, could you please cherry-pick this pr to 2.2 branch?

**Comment by jakpiase** [comment]
@baoachun I have made a cherry-pick to release2.2 branch

**Pull request merged**
