### PR TITLE
Move Fluid C++ code from /paddle to /paddle/fluid

### PR DESCRIPTION
**Pull request by wangkuiyi**
Fixes https://github.com/PaddlePaddle/Paddle/issues/8345

### CODE REVIEW

**Comment by wangkuiyi** [comment]
The CI failed at the stage of building the wheel package:

```
[01:41:10][Step 1/1] error: package directory '/paddle/build/paddle/framework' does not exist
[01:41:10][Step 1/1] make[2]: *** [python/build/.timestamp] Error 1
```

I have no clue with the process that builds the wheel package. Could @Yancey1989 @typhoonzero please help me with this? Thanks!

**Comment by typhoonzero** [comment]
@wangkuiyi should change this line: https://github.com/wangkuiyi/Paddle/blob/154368b1a0f81dda8393a9aa8687d7da44b3bead/python/setup.py.in#L112

**Comment by luotao1** [comment]
In order to `make paddle_docs` sucussfully, should change:
https://github.com/wangkuiyi/Paddle/blob/a6c1bffa471798fa36829c8cb24c9bd993bd2baf/paddle/fluid/operators/CMakeLists.txt#L4
from `set(pybind_file ${PADDLE_SOURCE_DIR}/paddle/pybind/pybind.h)`
to `set(pybind_file ${PADDLE_SOURCE_DIR}/paddle/fluid/pybind/pybind.h)`

And change the file in `.gitignore`: https://github.com/PaddlePaddle/Paddle/blob/develop/.gitignore#L36
from `paddle/pybind/pybind.h`
to `paddle/fluid/pybind/pybind.h`

**Comment by luotao1** [comment]
`paddle/string` should be moved to `paddle/fluid/string` as well

**Pull request merged**
