### PR TITLE
FC + activation fuse passes

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Performance optimization

### PR changes
OPs

### Describe
- fuse fc with all supported activations,
- extend unit test for new cases,
- clean FCMKLDNN pattern up.

### CODE REVIEW

**Comment by Silv3S** [comment]
@XieYunshen could you please approve changes in unit test? I extended `test_mkldnn_fc_mish_fuse_pass` as `test_mkldnn_fc_activation_fuse_pass`. Newly added unit test covers all supported activations.

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by yaomichael** [comment]
@jiangjiajun can you help review and approve?

**Review by yeliang2258 — DISMISSED** [review]
LGTM

**Comment by Silv3S** [comment]
@chalsliu could you please approve changes in unit test? I extended test_mkldnn_fc_mish_fuse_pass as test_mkldnn_fc_activation_fuse_pass. Newly added unit test covers all supported activations.

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM 
单测替换

**Pull request merged**
