### PR TITLE
Reduce inference library size and compile time

### PR DESCRIPTION
**Pull request by chalsliu**
### PR types
Others

### PR changes
Others

### Description
Reduce inference library size and compile time.

### CODE REVIEW

**Review by jiweibo — APPROVED** [review]
LGTM

**Comment by chalsliu** [comment]
使用方式：

1、编译前执行：python tools/remove_grad_op_and_kernel.py --only_kernel
2、cmake 参数加上： -DREDUCE_INFERENCE_LIB_SIZE=ON

**Review by qingqing01 — APPROVED** [review]

**Comment by chalsliu** [comment]
效果：

1. with third_party pre-compiled
2. 90并发编译

whl_so_SIZE      ->     size of libpaddle.so
infer_so_SIZE    ->      size of libpaddle_inference.so


| REDUCE | WITH_PYTHON | STRIP |    ARCH_NUM    | whl_so_SIZE      | infer_so_SIZE    |
|:------:|:-----------:|:-----:|:--------------:|------------------:|------------------:|
|   OFF  |      ON     |   ON  | 2 (sm_80 sm_86) |             960M |             924M |    65.0 mins |
|   ON   |      ON     |   ON  | 2 (sm_80 sm_86) |  678M <br />  **(-282M)**   ✅  |   643M <br />    **(-281M)**    ✅ |
|   OFF  |     OFF     |   ON  | 2 (sm_80 sm_86) |               NA |             922M |    53.0 mins |
|   ON   |     OFF     |   ON  | 2 (sm_80 sm_86) |               NA |             639M     <br />    **(-283M)**    ✅  | 
|   OFF  |     ON      |   ON  | 5 (sm_61 sm_70 sm_75  sm_80 sm_86)     |            2.0G  |             2.0G   | 
|   ON   |     ON      |   ON  | 5 (sm_61 sm_70 sm_75  sm_80 sm_86)     |       1.4G         <br />    **(-613M)**    ✅         |   1.4G      <br />    **(-613M)**    ✅          |

**Comment by luotao1** [comment]
@qingqing01 @chalsliu @jiweibo 请问 [tools/infer_prune_patches/](https://github.com/PaddlePaddle/Paddle/tree/develop/tools/infer_prune_patches) 还需要维护么？

**Pull request merged**
