### PR TITLE
CI - Improve example code check 

### PR DESCRIPTION
**Pull request by haowang101779990**
#18228 
Major Updates:

1. Prettified Log Print : ONLY failed example codes are printed in the console. The effect looks like this:
And a set of guidance to reperform the script locally on error is printed afterwards:
图片

If lucky enough, there's no mistakes found in example codes, it just prompts the successful message.
图片

1. Add arguments cpu|gpu [sd] for better functionality.

1. Add standard comments to the script for it's obsecure

1. Use "subprocess.returncode" to check whether the example code is successful. [Unix-based OS only]

1. Add copyright to the top

### CODE REVIEW

**Comment by luotao1** [comment]
@tianshuo78520a @xsrobin Please review at it.

**Comment by haowang101779990** [comment]
also @guru4elephant  This is the latest update to CI example check. Looking forward for your review, many thx.

**Comment by tianshuo78520a** [comment]
减少了很多无用的日志，并且加上了出现错误的解决办法。我觉得没问题，希望再速度上可以加快些。

**Comment by luotao1** [comment]
@haowang101779990 @tianshuo78520a 速度上是还没开多线程么？有速度对比么？

**Comment by haowang101779990** [comment]
> @haowang101779990 @tianshuo78520a 速度上是还没开多线程么？有速度对比么？
多线程还没开，正在调试

**Comment by luotao1** [comment]
好的，多线程可以作为下一个PR

**Review by guru4elephant — APPROVED** [review]
LGTM

**Pull request merged**
