### PR TITLE
Move out sequential and replace save_dygraph and load_dygraph

### PR DESCRIPTION
**Pull request by GGBond8488**
### PR types
Others

### PR changes
APIs

### Describe

because of https://github.com/PaddlePaddle/Paddle/pull/48477, we don't move out the `sequrntial` from fluid, now 
the dynamic to static has been migrated, so the sequential is migrated to paddle.nn

And the migration of Sequential depends on the removal of save_dygraph and load_dygraph, so submit the two together

### CODE REVIEW

**Review by chalsliu — DISMISSED** [review]

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Review by Aurelius84 — APPROVED** [review]
LGTM for PADDLE_NEED_CONVERT_APIS

**Review by kolinwei — APPROVED** [review]

**Review by lanxianghit — APPROVED** [review]

**Review by zhwesky2010 — APPROVED** [review]
LGTM for rm parallel_UT

**Review by jzhang533 — APPROVED** [review]
LGTM for API migration

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
