### PR TITLE
Added vanilla LSTM and LSTM with peepholes oneDNN fp32 kernel

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
This PR adds vanilla LSTM and LSTM with peepholes oneDNN kernel to PaddlePaddle. Currently only fp32 is supported, but bf16 and int8 will be added in future.

### CODE REVIEW

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 Could you please start your review? PR-CI-APPROVAL needs your an approval to pass.

**Comment by jakpiase** [comment]
Moved some code inside is_cached block, so it will be executed only once.

**Review by jczaja — DISMISSED** [review]
LGTM

**Review by luotao1 — DISMISSED** [review]

**Comment by luotao1** [comment]
Please solve the conflict

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
