### PR TITLE
Add int8 GRU kernel

### PR DESCRIPTION
**Pull request by grygielski**
### PR types
New features

### PR changes
OPs

### Describe
This PR adds int8 GRU kernel along with UTs.

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by grygielski** [comment]
@luotao1 Can you look at the approval CI failure?

**Review by luotao1 — APPROVED** [review]
```

2020-09-10 15:33:29 ****************
2020-09-10 15:33:29 0. Developers are not allowed to set the check_dygraph field directly, which is set to True by default. If you need to change the check_dygraph field, you must have one RD (phlrain (Recommend) or lanxianghit) review and approve. 
2020-09-10 15:33:29 The code that do not meet the specification are as follows:
2020-09-10 15:33:29  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_int8_mkldnn_op.py : 
2020-09-10 15:33:29 +        self.check_output(check_dygraph=False, atol=self.error_margin)
```
Since fusion_gru_int8_mkldnn_op does not use in dygraph. LGTM

**Review by phlrain — APPROVED** [review]
LGTM for check_dygraph

**Comment by luotao1** [comment]
@grygielski 

### You're Invited: Claim Your Custom PaddlePaddle Contributor Badge!
Baidu Open Source Office is looking for those of you who have quietly contributed to PaddlePaddle. We’ve prepared a special token of appreciation just for you—a custom commemorative badge engraved with your name.

image


Over the years, every step forward PaddlePaddle has taken has been made possible by your code, your passion, and your youth. Maybe you once submitted a line of code late at night, maybe you kindly answered a question in the community, or maybe it’s been a while since you last contributed…
But we’ve never forgotten you.

This time, we’re not just looking to reconnect with your code—we want to relive those years we burned brightly together.
Come join us—let’s once again—“reclaim our youth”!

If you’d like to take part, please send your **name, phone number, and a brief self-recommendation** to:
📧 [ext_paddle_oss@baidu.com](https://mailto:ext_paddle_oss@baidu.com/)
⏰ Deadline: **September 10th, 10:00 AM**
📌 Feel free to write your self-recommendation in your own style～
💡 No committee referral or repository write access is required—every past contributor is warmly welcome to join!

**Pull request merged**
