### PR TITLE
[hybrid] remove the using of global ring in hybrid parallel

### PR DESCRIPTION
**Pull request by wangxicoding**
### PR types

Others
### PR changes

Others
### Describe

1、Refine some code of c_comm_init_op.
2、c_gen_{nccl,bkcl,hccl}_id_op add Attr(ring_id) to distinguish different group's comm_id broadcast.
3、Remove the using of global ring in hybrid parallel.

### CODE REVIEW

**Comment by Baibaifan** [comment]
LGTM for NPU

**Review by Baibaifan — APPROVED** [review]
LGTM for NPU

**Review by gongweibao — APPROVED** [review]
LGTM

**Review by JZ-LIANG — COMMENTED** [review]
LGTM

**Review by sandyhouse — APPROVED** [review]
LGTM

**Pull request merged**
