### PR TITLE
[MKL-DNN] Pooling refactoring

### PR DESCRIPTION
**Pull request by jczaja**
This PR is refactoring pooling mkl-dnn op & grad op so it is easier to switch to mkl-dnn 1.0 later on

### CODE REVIEW

**Comment by luotao1** [comment]
Please solve the conflict

**Comment by jczaja** [comment]
@grygielski Could you please review this PR?

**Review by grygielski — APPROVED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
