### PR TITLE
Fix release/1.3 Executor doc

### PR DESCRIPTION
**Pull request by sneaxiy**
image
image

### CODE REVIEW

**Review by panyx0718 — DISMISSED** [review]

**Comment by haowang101779990** [comment]
LGTM @shanyi15

**Comment by shanyi15** [comment]
will this update be cherry-picked to develop branch?

**Comment by shanyi15** [comment]
updated preview:

image
image

**Comment by shanyi15** [comment]
cherry-pick to develop:https://github.com/PaddlePaddle/Paddle/pull/16005

**Review by shanyi15 — APPROVED** [review]
LGTM

**Pull request merged**
