### PR TITLE
[CINN] Package the cinn tile config into whl

### PR DESCRIPTION
**Pull request by BiynXu**
### PR Category
CINN

### PR Types
Others

### Description
Pcard-74042
Package the cinn tile config into whl.
https://github.com/PaddlePaddle/Paddle/pull/67473 同步修改

### CODE REVIEW

**Review by 0x45f — APPROVED** [review]

**Comment by zhangbo9674** [comment]
setup.py 也需要支持相同的逻辑

**Review by zyfncg — APPROVED** [review]
LGTM

**Comment by BiynXu** [comment]
> setup.py 也需要支持相同的逻辑

**Comment by BiynXu** [comment]
> setup.py 也需要支持相同的逻辑

https://github.com/PaddlePaddle/Paddle/pull/67473  之前已经合入了setup.py的修改

**Review by zhangbo9674 — APPROVED** [review]
LGTM for setup.py.in

**Pull request merged**
