### PR TITLE
[cherry-pick] FC/matmul(v2) + scale fuse pass (#47127)

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Performance optimization

### PR changes
OPs

### Describe
- fuse FC with scale,
- fuse matmul and matmul_v2 with scale,
- add unit tests.

### CODE REVIEW

**Review by zh794390558 — APPROVED** [review]
LGTM

**Comment by onecatcn** [comment]
@yeliang2258 This PR looks ready for merge, please help see what you can do.

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Comment by yeliang2258** [comment]
refs: https://github.com/PaddlePaddle/Paddle/pull/47127

**Review by ZeyuChen — APPROVED** [review]

**Pull request merged**
