### PR TITLE
Reduce test_calibration test time by using large batchsize

### PR DESCRIPTION
**Pull request by chuanqi129**
To reduce test_calibration test time. Please @luotao1 have a review on it.

### CODE REVIEW

**Comment by luotao1** [comment]
please pass the travis-ci.

**Comment by luotao1** [comment]
```
[01:52:41]582/624 Test #616: test_calibration ....................................   Passed  134.42 sec
```
It seems `using large batchsize` don't have many benefits.

**Comment by chuanqi129** [comment]
> ```
> [01:52:41]582/624 Test #616: test_calibration ....................................   Passed  134.42 sec
> ```
> It seems `using large batchsize` don't have many benefits.

Is it necessary to download data and models for each test? If so, the download phase will take up most of the time. I have verified it locally, this test takes about 50 seconds when the download phase is not included.

**Comment by luotao1** [comment]
> Is it necessary to download data and models for each test? If so, the download phase will take up most of the time. 

Download data and models are already cached.

**Review by luotao1 — APPROVED** [review]
LGTM. But we still need speedup this unit-test.

**Pull request merged**
