### PR TITLE
Fix the node's order issue when the content of graph is changed

### PR DESCRIPTION
**Pull request by yihuaxu**
When [PR#15601](https://github.com/PaddlePaddle/Paddle/pull/15601) is run, we found that the compare result between native and analysis predictor be shown the accuracy issue. The reason is  that the changed order of operators result in the  difference when the same name of output variable was used other place. So far, this PR can be helpful for it.
   As detail, please refer the below figures that describe the key difference. We can easily find that **lookup_table(15)** and **lookup_table(20)** have the same name of output variable, named as **embedding_0.tmp_0**.  if **lookup_table(20)**(table: src_pos_enc_table(21)) is executed early than **lookup_table(15)**(table: src_word_emb_table(16)), it will result in the output of **lookup_table(15)** will be used by **scale(18)** and as one input of **elementwise_add(23)**. If the variable name is same, other operator can only get the last content.

Associated PR： [PR#15601](https://github.com/PaddlePaddle/Paddle/pull/15601)

image
**Figure I: The result of native predictor**

image
**Figure II: The result of analysis predictor that the graph be changed**

image
**Figure III: The topology of transformer graph**

### CODE REVIEW

**Comment by yihuaxu** [comment]
@panyx0718 Please help us review this PR. It changed graph_helper.cc file.


[16:17:27]	+ API_CHANGE=paddle/fluid/framework/ir/graph_helper.cc
[16:17:27]	+ echo 'checking paddle/fluid/framework/ir/graph.h change, PR: 16088, changes: paddle/fluid/framework/ir/graph_helper.cc'
[16:17:27]	+ '[' paddle/fluid/framework/ir/graph_helper.cc ']'
[16:17:27]	+ '[' 16088 '!=' '' ']'
[16:17:27]	+ '[' paddle/fluid/framework/ir/graph.h == paddle/fluid/API.spec ']'
[16:17:27]	++ curl -H 'Authorization: token 5ae37427a95d9e51fb0ea3c71121b75d5c2ebefa' 'https://api.github.com/repos/PaddlePaddle/Paddle/pulls/16088/reviews?per_page=10000'
[16:17:27]	++ python /paddle/tools/check_pr_approval.py 1 2887803
[16:17:27]	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[16:17:27]	                                 Dload  Upload   Total   Spent    Left  Speed
[16:17:28]	
[16:17:28]	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[16:17:29]	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[16:17:29]	100     5  100     5    0     0      3      0  0:00:01  0:00:01 --:--:--     3
[16:17:29]	+ APPROVALS=FALSE
[16:17:29]	+ echo 'current pr 16088 got approvals: FALSE'
[16:17:29]	+ '[' FALSE == FALSE ']'
[16:17:29]	+ '[' paddle/fluid/framework/ir/graph.h == paddle/fluid/API.spec ']'
[16:17:29]	+ echo 'You must have panyx0718 approval for the api change! paddle/fluid/framework/ir/graph.h'
[16:17:29]	+ exit 1
[16:17:36]	Process exited with code 1

**Comment by yihuaxu** [comment]
start a review

**Comment by luotao1** [comment]
LGTM @panyx0718 Could you help review it?
```
[16:17:27][Step 1/1] + '[' paddle/fluid/framework/ir/graph_helper.cc ']'
[16:17:27][Step 1/1] + '[' 16088 '!=' '' ']'
[16:17:27][Step 1/1] + '[' paddle/fluid/framework/ir/graph.h == paddle/fluid/API.spec ']'
[16:17:27][Step 1/1] ++ curl -H 'Authorization: token 5ae37427a95d9e51fb0ea3c71121b75d5c2ebefa' 'https://api.github.com/repos/PaddlePaddle/Paddle/pulls/16088/reviews?per_page=10000'
[16:17:27][Step 1/1] ++ python /paddle/tools/check_pr_approval.py 1 2887803
[16:17:27][Step 1/1]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[16:17:27][Step 1/1]                                  Dload  Upload   Total   Spent    Left  Speed
[16:17:28][Step 1/1] 
[16:17:28][Step 1/1]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[16:17:29][Step 1/1]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[16:17:29][Step 1/1] 100     5  100     5    0     0      3      0  0:00:01  0:00:01 --:--:--     3
[16:17:29][Step 1/1] current pr 16088 got approvals: FALSE
[16:17:29][Step 1/1] + APPROVALS=FALSE
[16:17:29][Step 1/1] You must have panyx0718 approval for the api change! paddle/fluid/framework/ir/graph.h
[16:17:29][Step 1/1] + echo 'current pr 16088 got approvals: FALSE'
```

**Review by panyx0718 — APPROVED** [review]
why is this a bug? this randomness in graph should be correctly handled by pass and executor.

**Comment by luotao1** [comment]
> why is this a bug?

@panyx0718 It causes the accuracy diff between native and analysis mode of transformer model.
The reason is that the changed order of operators result in the difference when the same name of output variable was used other place.

**Comment by yihuaxu** [comment]
> > why is this a bug?
> 
> @panyx0718 It causes the accuracy diff between native and analysis mode of transformer model.
> The reason is that the changed order of operators result in the difference when the same name of output variable was used other place.

@panyx0718 From transformer model's graph, there are the same output names used by different operators. Actually it can be as the way to optimize the memory allocation, but it brings the dependency problem between two or more operators. If the order is randomness, it mean that the accuracy will be random.

**Pull request merged**
