### PR TITLE
Add bert prim and cinn test

### PR DESCRIPTION
**Pull request by 0x45f**
### PR types

Others
### PR changes

Others
### Describe

Add bert prim and cinn test

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM for
`set_tests_properties(test_bert_prim_cinn PROPERTIES TIMEOUT 500)`

**Review by luotao1 — APPROVED** [review]
LGTM for `@unittest.skipIf`

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
