### PR TITLE
[oneDNN]rename macro to PADDLE_WITH_DNNL

### PR DESCRIPTION
**Pull request by xinyu-intel**
### PR types
Function optimization

### PR changes
Others

### Description
rename macro from PADDLE_WITH_MKLDNN to PADDLE_WITH_DNNL

### CODE REVIEW

**Review by YangQun1 — APPROVED** [review]

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by xinyu-intel** [comment]
@XiaoguangHu01 @zyfncg @qingqing01 @vivienfanghuagood Hi, can you help review the changes of the PR? Thanks:)

**Review by vivienfanghuagood — APPROVED** [review]
LGTM

**Review by zyfncg — DISMISSED** [review]

**Review by YangQun1 — APPROVED** [review]

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by zhangbo9674 — APPROVED** [review]
LGTM for new_executor

**Review by zyfncg — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Comment by xinyu-intel** [comment]
@qingqing01 Hi, can you help on review this PR? Many thanks:)

**Review by qingqing01 — APPROVED** [review]

**Pull request merged**
