### PR TITLE
unify cpu context, part1

### PR DESCRIPTION
**Pull request by zhiqiu**
### PR types

Function optimization
### PR changes

Others
### Describe

ATT， unify paddle::platform::CPUContext and phi::CPUContext.

- make code clean and eazy to mantain
- reduce function and class template to reduce compilation time

### CODE REVIEW

**Review by jiweibo — APPROVED** [review]
LGTM for cpu context

**Review by chalsliu — APPROVED** [review]
LGTM for deleting unit-test test_phi_device_context.

**Review by chenwhql — APPROVED** [review]

**Review by raindrops2sea — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by ZzSean — APPROVED** [review]
LGTM for OP-Benchmark

**Pull request merged**
