### PR TITLE
Fix mp async reduce cast

### PR DESCRIPTION
**Pull request by zhurou603**
### PR types
Bug fixes

### PR changes
Others

### Description
fix error when weight's dtype is not equal to dy's dtype

### CODE REVIEW

**Comment by luotao1** [comment]
请问您是个人开发者还是和Paddle有项目合作呢？

**Comment by zhurou603** [comment]
项目合作



---Original---
From: "Tao ***@***.***&gt;
Date: Fri, Nov 10, 2023 11:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/Paddle] Fix mp async reduce cast (PR #58858)




 
请问您是个人开发者还是和Paddle有项目合作呢？

**Comment by Caozhou1995** [comment]
rebase一下develop，重新过一下CI

**Comment by zhurou603** [comment]
> rebase一下develop，重新过一下CI

重新跑了

**Review by FeixLiu — APPROVED** [review]
LGTM

**Pull request merged**
