### PR TITLE
Fea/fusion seqconv add

### PR DESCRIPTION
**Pull request by tensor-tang**
fuse seqconv + elementwise_add + relu

multi label 1.50216ms => 1.39491ms, 7.68% speedup on v3

### CODE REVIEW

**Comment by tensor-tang** [comment]
1.50216ms => 1.39491ms, 7.68% speedup on v3.

**Review by Superjomn — APPROVED** [review]
LGTM

**Review by Superjomn — APPROVED** [review]
LGTM

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
