### PR TITLE
[oneDNN] Fix to conv2d grad with groups

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Bug fixes 

### PR changes
OPs 

### Describe
PR is fixing conv2d grad oneDNN kernel execution for situation when there are groups e.g. training of mobilenet via dygraph.
Problem is that oneDNN for groups is having filter's shape size 5D while paddle expects 4D.

### CODE REVIEW

**Review by arlesniak — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@luotao1  Please take a look at this PR, this PR fix the MobileNetV1 MKLDNN training

**Review by luotao1 — APPROVED** [review]

**Review by grygielski — APPROVED** [review]
LGTM

**Review by wojtuss — APPROVED** [review]
LGTM

**Pull request merged**
