### PR TITLE
Fix to issue #25537

### LINKED ISSUE #25537: CPU预测模型开启MKLDNN后报错
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.1
    2）CPU：Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz, MKLDNN
    3）GPU：无
    4）系统环境：CentOS release 6.3 (Final)、Python 2.7.15
- 复现信息：
百度内部提出，复现代码和模型，请hi上联系 guguiyuan

- 问题描述：
模型使用了pool2d op开启mkldnn报错，未使用的可正常运行
错误信息如下
image
image

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Bug fixes

### PR changes
Others

### Describe
fix #25537.

Fix a misuse of Tensor::layout for purpose of oneDNN NHWC arrangment implementation and It does adjust transpose oneDNN kernel for NHWC arrangmeent. Tranpose kernel has to be modified as this is oneDNN kernel , but it does produce non-oneDNN tensor , so output shape for NHWC model has to be matched.

### CODE REVIEW

**Comment by jczaja** [comment]
@arogowie-intel , @arlesniak  Please review

**Comment by jczaja** [comment]
@wojtuss , @wozna , @arlesniak , @arogowie-intel  Please review

@luotao1 PR-CI-Windows is in mending mode since yesterday. I tried to close/reopen PR but no impact visible. Could you please advice how to proceed?

**Review by luotao1 — APPROVED** [review]
LGTM! 
> PR-CI-Windows is in mending mode since yesterday.

Some network fails, and I have record it true manually.

**Comment by jczaja** [comment]
@luotao1 Thanks very much for explanation

**Pull request merged**
