### PR TITLE
Review AMD porting effect only

### PR DESCRIPTION
**Pull request by sabreshao**

### CODE REVIEW

**Comment by dzhwinter** [comment]
Thanks for this PR and your guy's hard work!
Seems we do not have any design problem, our heterogeneous device design fit the AMD needs well. There are tons of HIPC macro and Cuda kernel launch function substitution, context, and the nccl, cudnn like libraries utils related code need to modify, no other job need to pay attention. Please correct me if I had missed some important details.

Considering that not all of our CI machines equipped with the ROCm chip, the CI fails. There are some issues I'm wondering:
1. I have seen some commented out test cases in the source code, is float16 fully supported in ROCm now? 
2. Last time you have mentioned, there are some ROCm libraries are not compatible yet. As I looked into the code, there is only nccl2 communicated through different nodes feature is commented out. Is there any other library we needed?
3. The commit history needs a cleanup, there is a lot of [Do Not Merge] commits sitting there, that does not follow the project style.
4.  seems Upstream to 0.14.0 also needs to do some jobs. These two branches have diverged and have a very large gap. 
5. Is it possible to provide a Hip compiler/Hip libraries installed docker image, and launch it on the CI system? I remember we have a machine equipped with the AMD cards.

Thanks!

**Comment by dzhwinter** [comment]
Since you have launched the image-classification related models, is there any numbers benchmarked can be shared with us?

**Comment by sunway513** [comment]
Hi @dzhwinter , thanks for reviewing the PR!

1. I have seen some commented out test cases in the source code, is float16 fully supported in ROCm now?
-- float16 is in our plan, we'll enable those functionalities after finishing the fp32 implementation. 

2. Last time you have mentioned, there are some ROCm libraries are not compatible yet. As I looked into the code, there is only nccl2 communicated through different nodes feature is commented out. Is there any other library we needed?
-- So far we only miss the NCCL2 internal-node function equivalences. Here's the list of current supported ROCm libraries:
•	cuBLAS --> rocBLAS/hipBLAS
•	cuRAND --> rocRAND/hipRAND
•	cuSPARSE --> hcSPARSE/hipSPARSE
•	cuDNN --> MIOpen
•	THRUST --> THRUST
•	Eigen --> hipeigen
•	NCCL --> RCCL, limit to NCCLv1.0 compatibility 
•	CUB --> rocPRIM

3. The commit history needs a cleanup, there is a lot of [Do Not Merge] commits sitting there, that does not follow the project style.
-- Yes, as you've noticed this PR is for evaluation purpose only. If you look at the merged PRs, we typically squash the commit history before submitting.

4. seems Upstream to 0.14.0 also needs to do some jobs. These two branches have diverged and have a very large gap.
-- Right, this is well understood :-)

5. Is it possible to provide a Hip compiler/Hip libraries installed docker image, and launch it on the CI system? I remember we have a machine equipped with the AMD cards.
-- Yes, we can provide any required Dockerfile to facilitate the Paddle internal CI system. Let's make it a priority if you also agree. It will be helpful to validate our future patches.

**Comment by dzhwinter** [comment]
Here we have a test result on resnet50.  The performance can reach 67.36383 images/s. 

```txt
----------- resnet Configuration Arguments -----------
batch_size: 64
data_format: NCHW
data_set: flowers
device: GPU
infer_only: False
iterations: 30
model: resnet_imagenet
pass_num: 100
skip_batch_num: 5
use_cprof: False
use_fake_data: False
use_nvprof: False
with_test: False
------------------------------------------------
Pass: 0, Iter: 1, Loss: 5.937105, Accuracy: 0.000000
Pass: 0, Iter: 2, Loss: 4.976709, Accuracy: 0.015625
Pass: 0, Iter: 3, Loss: 4.868117, Accuracy: 0.000000
Pass: 0, Iter: 4, Loss: 4.722062, Accuracy: 0.062500
Pass: 0, Iter: 5, Loss: 5.396973, Accuracy: 0.015625
Pass: 0, Iter: 6, Loss: 5.282404, Accuracy: 0.015625
Pass: 0, Iter: 7, Loss: 4.901555, Accuracy: 0.015625
Pass: 0, Iter: 8, Loss: 4.908227, Accuracy: 0.046875
Pass: 0, Iter: 9, Loss: 4.829288, Accuracy: 0.015625
Pass: 0, Iter: 10, Loss: 5.340429, Accuracy: 0.000000
Pass: 0, Iter: 11, Loss: 5.174506, Accuracy: 0.031250
Pass: 0, Iter: 12, Loss: 4.740067, Accuracy: 0.031250
Pass: 0, Iter: 13, Loss: 5.112551, Accuracy: 0.031250
Pass: 0, Iter: 14, Loss: 5.370184, Accuracy: 0.000000
Pass: 0, Iter: 15, Loss: 5.296190, Accuracy: 0.015625
Pass: 0, Iter: 16, Loss: 5.043025, Accuracy: 0.015625
Pass: 0, Iter: 17, Loss: 5.100718, Accuracy: 0.046875
Pass: 0, Iter: 18, Loss: 5.250133, Accuracy: 0.015625
Pass: 0, Iter: 19, Loss: 4.740262, Accuracy: 0.015625
Pass: 0, Iter: 20, Loss: 5.078549, Accuracy: 0.078125
Pass: 0, Iter: 21, Loss: 5.539989, Accuracy: 0.031250
Pass: 0, Iter: 22, Loss: 5.278331, Accuracy: 0.031250
Pass: 0, Iter: 23, Loss: 5.108489, Accuracy: 0.000000
Pass: 0, Iter: 24, Loss: 5.418751, Accuracy: 0.031250
Pass: 0, Iter: 25, Loss: 5.679834, Accuracy: 0.000000
Pass: 0, Iter: 26, Loss: 5.163983, Accuracy: 0.015625
Pass: 0, Iter: 27, Loss: 5.378008, Accuracy: 0.000000
Pass: 0, Iter: 28, Loss: 5.207434, Accuracy: 0.000000
Pass: 0, Iter: 29, Loss: 5.853270, Accuracy: 0.000000
Pass: 0, Iter: 30, Loss: 5.625842, Accuracy: 0.031250
Pass: 0, Loss: 5.210766, Train Accuray: 0.020312


Total examples: 1600, total time: 23.75162, 67.36383 examples/sed

```

**Pull request closed without merging**
