### PR TITLE
[MoE] Random routing

### PR DESCRIPTION
**Pull request by sljlp**
### PR types

New features
### PR changes

OPs
### Describe

add random_routing op for gshard gate in moe

### CODE REVIEW

**Review by wanghuancoder — DISMISSED** [review]
LGTM for skipIf

**Review by ForFishes — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LG API

**Review by wanghuancoder — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request closed without merging**
