### PR TITLE
add set default dtype, get default dtype

### PR DESCRIPTION
**Pull request by ForFishes**
### PR types

New features 
### PR changes

APIs
### Describe

add "set_default_dtype" ,"get_default_dtype"

### CODE REVIEW

**Review by jzhang533 — CHANGES_REQUESTED** [review]
you may need to define alias in 'python/paddle/__init__.py ', so that the api could be exposed as `paddle.set_default_dtype`

**Review by jzhang533 — DISMISSED** [review]
lgtm

**Review by zhiqiu — DISMISSED** [review]
LGTM

This PR changes Linear, is it consistent with the old models?

**Review by jzhang533 — APPROVED** [review]
lgtm

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by zhiqiu — APPROVED** [review]
LGTM

**Pull request merged**
