### PR TITLE
Open fuse all reduce option

### PR DESCRIPTION
**Pull request by chengduoZH**
This PR's work includes:
- [x] Open fuse all reduce option.
- [x] Use `boost::optional<bool> ` as the type of `fuse_all_optimizer_ops`, `fuse_all_reduce_ops`, `fuse_broadcast_ops`. If user not set those option, `BuildStrategy` will set those option accordding to other config. If user enable those options, but some option conflicts with other config, `BuildStrategy` will print warnning info.

### CODE REVIEW

**Review by gongweibao — DISMISSED** [review]
👍🏻

**Review by gongweibao — DISMISSED** [review]
👍🏻

**Review by luotao1 — DISMISSED** [review]
LGTM for `checking paddle/fluid/framework/ir/graph.h change, PR: 19765, changes: paddle/fluid/framework/ir/graph_helper.cc`. It seems miss hit in CI rules.

**Review by gongweibao — DISMISSED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
