### PR TITLE
reduce runtime of unit-tests in windows-trt

### PR DESCRIPTION
**Pull request by lizexu123**
### PR types

Others
### PR changes

Others
### Description

Pcard-71501
优化了trt单测 Timeout 问题，优化单测及效果如下表：
测试环境：T4，cuda11.6，cudnn8.4，trt8.6.1.6

单测 | 优化前时长 | 优化后时长
-- | -- | --
test_trt_convert_grid_sampler | 388.841s | 132.216s
test_trt_convert_stack | 671.266s | 76.367s
test_trt_convert_top_k_v2 | failed | 45.309s
test_trt_convert_einsum(3个case) | 434.383s | 267.905s
test_trt_convert_unsqueeze2 | 689.616s | 116.763s
test_trt_convert_squeeze2 | 703.340s | 173.682s

### CODE REVIEW

**Review by vivienfanghuagood — APPROVED** [review]
please modify the title of the PR

**Comment by lizexu123** [comment]
> please modify the title of the PR

已修改

**Review by vivienfanghuagood — APPROVED** [review]
please modify the title of the PR

**Comment by xuxinyi389** [comment]
LGTM

**Review by yuanlehome — APPROVED** [review]

**Pull request merged**
