### PR TITLE
Fused elementwise_(mul/div)

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Others

### PR changes
OPs

### Describe
- convert `elementwise_(mul/div)` to `fused_elementwise_(mul/div)`

### CODE REVIEW

**Comment by Silv3S** [comment]
@HulekJakub please review

**Review by HulekJakub — DISMISSED** [review]
LGTM

**Comment by Silv3S** [comment]
@Aurelius84, @zhhsplendid could you please approve registration of new ops? Supported datatypes of oneDNN fused ops match datatypes of already registered oneDNN base ops

**Review by YuanRisheng — APPROVED** [review]

**Review by Aurelius84 — APPROVED** [review]
LGTM for data type registeration

**Pull request merged**
