### PR TITLE
2.0rc api rename

### PR DESCRIPTION
**Pull request by liuhuiCNN**
### PR types
Function optimization

### PR changes
APIs

### Describe
(1) rename count_include_pad--> exclusive
(2) return_indices-->return_mask
(3) remove track_running_stats

### CODE REVIEW

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]
lgtm

**Comment by liuhuiCNN** [comment]
move to #28184

**Pull request closed without merging**
