### PR TITLE
support mean,softmax_with_cross_entropy on Baidu Kunlun

### PR DESCRIPTION
**Pull request by yghstill**
### PR types

New features
### PR changes

OPs
### Describe

support mean,softmax_with_cross_entropy on Baidu Kunlun

### CODE REVIEW

**Review by tink2123 — APPROVED** [review]
LGTM

**Comment by QingshuChen** [comment]
精度设置ok

**Review by Xreki — APPROVED** [review]
LGTM for the change of atol and max_relative_error.

**Review by luotao1 — APPROVED** [review]
LGTM for op_test.py

**Pull request merged**
