### PR TITLE
[MLU]add sync_batch_norm op 1/2

### PR DESCRIPTION
**Pull request by qipengh**
### PR types

New features
### PR changes

OPs
### Describe

add  code of sync_batch_norm_op

### CODE REVIEW

**Comment by qipengh** [comment]
测试报告：
image
image

**Review by ronny1996 — APPROVED** [review]
LGTM

**Review by qili93 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM for `    set_tests_properties(test_sync_batch_norm_op_mlu_baseline PROPERTIES TIMEOUT
                                                                         120)`

**Pull request merged**
