### PR TITLE
[test]mv fluid op fused to test

### PR DESCRIPTION
**Pull request by gouzil**
### PR types

Others
### PR changes

Others
### Description

mv fluid op fused to `test/cpp/fluid/fused`

### CODE REVIEW

**Review by tianshuo78520a — DISMISSED** [review]

**Review by zhiqiu — DISMISSED** [review]
LGTM

**Review by luotao1 — DISMISSED** [review]

**Comment by luotao1** [comment]
需要解决下冲突

**Comment by gouzil** [comment]
> 需要解决下冲突

Done

**Comment by luotao1** [comment]
又冲突了

**Comment by gouzil** [comment]
> 又冲突了

Done

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
