### PR TITLE
[Move selected_rows PR #3] Change the relationship of [include/Cmake].

### PR DESCRIPTION
**Pull request by veyron95**
### PR types
Others

### PR changes
Others 

### Describe
A series of jobs where selected_rows moves from Fluid to Pten.
There are 5 PR to complete the migration work in expected.

PR 1: Renamed selected_rows.* to selected_rows_utils.* [PR39037](https://github.com/PaddlePaddle/Paddle/pull/39037)
PR 2: Added selected_rows.* and rw_lock.h to Pten [PR39087](https://github.com/PaddlePaddle/Paddle/pull/39087)

#### This is PR 3: Change the relationship of [include/Cmake.
1) Delete Class SelectedRows in selected_rows_utils.* under Fluid, leaving only a few serialization methods; 
2) Modify the [include/cmake] relationship;
3) Use pten::SelectedRows in Fluid;
4) Remove rw_lock.h, rw_lock_test.cc in Fluid;

#### follow-up work：
PR 4: Selected_Rows inherits from TensorBase.
PR 5: VisitDataType --> pten::DataType

### CODE REVIEW

**Review by XieYunshen — DISMISSED** [review]
LGTM 
单测迁移

**Review by jim19930609 — DISMISSED** [review]

**Review by ZzSean — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by chenwhql — DISMISSED** [review]

**Review by ZzSean — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by jim19930609 — DISMISSED** [review]

**Review by chenwhql — DISMISSED** [review]

**Review by XieYunshen — DISMISSED** [review]

**Review by XieYunshen — APPROVED** [review]

**Review by ZzSean — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]

**Review by YuanRisheng — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
