### PR TITLE
[CHERRY-PICK] Added caching to oneDNN FC and op+unsqueeze2 and op+reshape2 fuse passes

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
[CHERRY-PICK] Added caching to oneDNN FC and op+unsqueeze2 and op+reshape2 fuse passes. It is a cherry-pick of both #47391 and #47234

### CODE REVIEW

**Comment by jakpiase** [comment]
Currently the PR is failing due to `2022-11-05 00:08:03 fatal: unable to access 'https://gitlab.mpcdf.mpg.de/mtr/pocketfft.git/': Unknown SSL protocol error in connection to gitlab.mpcdf.mpg.de:443 ` error, I'll restart it a couple times during the weekend to check if it will be fixed

**Comment by jakpiase** [comment]
@yeliang2258 @zh794390558 please ask somebody to approve CI-Approval and merge

**Review by zhiqiu — APPROVED** [review]
LGTM

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Pull request merged**
