### PR TITLE
fix compile error

### LINKED ISSUE #5159: Compiling error of current develop branch, /paddle/paddle/operators/auc_op.cc:25:30: error: 'paddle::framework::InferShapeContextBase' has not been declared
```
[14:39:28]	/paddle/paddle/operators/auc_op.cc:25:30: error: 'paddle::framework::InferShapeContextBase' has not been declared
[14:39:28]	void InferShape(framework::InferShapeContextBase *ctx) const override {
[14:39:28]	^
[14:39:28]	/paddle/paddle/operators/auc_op.cc:25:8: error: 'void paddle::operators::AucOp::InferShape(int*) const' marked 'override', but does not override
[14:39:28]	void InferShape(framework::InferShapeContextBase *ctx) const override {
[14:39:28]	^
[14:39:28]	In file included from /paddle/paddle/framework/ddim.h:21:0,
[14:39:28]	from /paddle/paddle/framework/tensor.h:23,
[14:39:28]	from /paddle/paddle/framework/eigen.h:17,
[14:39:28]	from /paddle/paddle/operators/auc_op.h:16,
[14:39:28]	from /paddle/paddle/operators/auc_op.cc:15:
[14:39:28]	/paddle/paddle/operators/auc_op.cc: In member function 'void paddle::operators::AucOp::InferShape(int*) const':
[14:39:28]	/paddle/paddle/operators/auc_op.cc:26:25: error: request for member 'HasInput' in '* ctx', which is of non-class type 'int'
[14:39:28]	PADDLE_ENFORCE(ctx->HasInput("Inference"),
[14:39:28]	^
[14:39:28]	/paddle/paddle/platform/enforce.h:207:42: note: in definition of macro 'PADDLE_ENFORCE'
[14:39:28]	::paddle::platform::throw_on_error(__VA_ARGS__); \
[14:39:28]	^
[14:39:28]	/paddle/paddle/operators/auc_op.cc:28:25: error: request for member 'HasInput' in '* ctx', which is of non-class type 'int'
[14:39:28]	PADDLE_ENFORCE(ctx->HasInput("Label"),
[14:39:28]	^
[14:39:28]	/paddle/paddle/platform/enforce.h:207:42: note: in definition of macro 'PADDLE_ENFORCE'
[14:39:28]	::paddle::platform::throw_on_error(__VA_ARGS__); \
[14:39:28]	^
[14:39:28]	/paddle/paddle/operators/auc_op.cc:30:31: error: request for member 'GetInputDim' in '* ctx', which is of non-class type 'int'
[14:39:28]	auto inference_dim = ctx->GetInputDim("Inference");
[14:39:28]	^
[14:39:28]	/paddle/paddle/operators/auc_op.cc:31:27: error: request for member 'GetInputDim' in '* ctx', which is of non-class type 'int'
[14:39:28]	auto label_dim = ctx->GetInputDim("Label");
[14:39:28]	^
[14:39:28]	/paddle/paddle/operators/auc_op.cc:36:10: error: request for member 'SetOutputDim' in '* ctx', which is of non-class type 'int'
[14:39:28]	ctx->SetOutputDim("AUC", {1});
[14:39:28]	^
[14:39:28]	/paddle/paddle/operators/auc_op.cc:37:10: error: request for member 'ShareLoD' in '* ctx', which is of non-class type 'int'
[14:39:28]	ctx->ShareLoD("Inference", /*->*/ "AUC");
[14:39:28]      ^
```

### PR DESCRIPTION
**Pull request by typhoonzero**
Fix #5159

### CODE REVIEW

**Comment by luotao1** [comment]
```
[16:31:20]	The following tests FAILED:
[16:31:20]	167 - test_auc_op (Failed)
[16:31:20]	193 - test_huber_loss_op (Failed)
[16:31:20]	219 - test_lstm_unit_op (Failed)
```

**Comment by typhoonzero** [comment]
@luotao1 I reruned the CI job.

**Comment by typhoonzero** [comment]
@luotao1 I reruned the CI job.

**Comment by Xreki** [comment]
`test_auc_op` also fails on my computer, you need to add the following function to auc_op:
```
 protected:
  // CrossEntropy's data type just determined by "X"
  framework::DataType IndicateDataType(
      const framework::ExecutionContext& ctx) const override {
    return framework::ToDataType(ctx.Input<Tensor>("Inference")->type());
  }
```

**Pull request merged**
