### PR TITLE
enable pyreader use pin memory

### PR DESCRIPTION
**Pull request by typhoonzero**
Can then use batch feeder like:

```python
def batch_feeder(batch_reader, pin_memory=False, img_dtype="float32"):
    # batch((sample, label)) => batch(sample), batch(label)
    def _feeder():
        for batch_data in batch_reader():
            sample_batch = []
            label_batch = []
            for sample, label in batch_data:
                sample_batch.append(sample)
                label_batch.append([label])
            tensor = core.LoDTensor()
            label = core.LoDTensor()
            place = core.CUDAPinnedPlace() if pin_memory else core.CPUPlace()
            tensor.set(np.array(sample_batch, dtype=img_dtype, copy=False), place)
            label.set(np.array(label_batch, dtype="int64", copy=False), place)
            yield [tensor, label]

    return _feeder

pyreader.decorate_tensor_provider(
            reader_fast.batch_feeder(
                paddle.batch(reader, batch_size=args.batch_size),
                pin_memory=True,
                img_dtype=reader_dtype
            )
        )
```

### CODE REVIEW

**Comment by Yancey0623** [comment]
Add an example code as an unit test?

**Review by sneaxiy — COMMENTED** [review]
I am not sure whether it works. Because it seams that double_buffer_reader may only support gpu and cpu place currently.

**Comment by typhoonzero** [comment]
@sneaxiy There's a unit test to ensure this, currently double_buffer_reader use `TensorCopySync` to copy data to GPU, this change add support for `CUDAPinnedPlace` for tensorcopy.

**Review by Yancey0623 — APPROVED** [review]
lgtm

**Pull request merged**
