### PR TITLE
fixed save qat2 model resnet50 and ernie

### PR DESCRIPTION
**Pull request by sfraczek**
Fix for CMakeLists.txt using old variable names and function call.

### CODE REVIEW

**Review by wojtuss — APPROVED** [review]
LGTM

**Review by juncaipeng — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
Hi, @luotao1 could you please help restart the failed CIs ? Thank you!

**Comment by luotao1** [comment]
It's a random unit test error, I have rerun it at first.

**Pull request merged**
