### PR TITLE
[Move Test] Remove fleet

### PR DESCRIPTION
**Pull request by Zheng-Bicheng**
### PR types
Others

### PR changes
Others

### Describe
删除fleet

### CODE REVIEW

**Comment by Zheng-Bicheng** [comment]
@tianshuo78520a @zhiqiu 大佬们帮忙审核下PR

**Review by tianshuo78520a — APPROVED** [review]
LGTM

**Comment by Zheng-Bicheng** [comment]
@luotao1 大佬帮忙合入下哈

**Review by wangzhen38 — APPROVED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
