### PR TITLE
fix assertion failure issue when test_analyzer_bert uses ngraph

### LINKED ISSUE #17147: test_analyzer_bert runs into assertion failure when ngraph is used
**System information**
-PaddlePaddle branch: develop

-CPU: Yes

-GPU: No

-OS Platform: Linux

-Cmake orders:
cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_DSO=ON -DWITH_AMD_GPU=OFF -DWITH_DISTRIBUTE=ON -DWITH_MKL=ON -DWITH_NGRAPH=ON -DWITH_AVX=ON -DWITH_GOLANG=OFF -DWITH_PYTHON=ON  -DWITH_TESTING=ON  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_CONTRIB=ON -DWITH_INFERENCE_API_TEST=ON  -DPY_VERSION=2.7 -DWITH_JEMALLOC=OFF -DWITH_GRPC=ON

**To Reproduce**
run cmd below:
./paddle/fluid/inference/tests/api/test_analyzer_bert --infer_model=./third_party/inference_demo/bert_emb128/model --infer_data=./third_party/inference_demo/bert_emb128/data.txt --gtest_filter=Analyzer_bert.profile --paddle_num_threads=1 --repeat=1 --batch_size=8  --use_ngraph --use_analysis=false

**Describe your current behavior**
program will get assertion failure as shown below

```
I0429 09:59:54.162081 36591 tester_helper.h:327] Thread 0, number of threads 1, run 1 times...
unknown file: Failure
C++ exception with description "While validating node 'Broadcast[Broadcast_1365](Max_1364: float{240}) -> (??)' of type 'Broadcast':
Assertion 'get_input_partial_shape(0).compatible(required_input_shape)' failed at /home/leozhao/Paddle/build/third_party/ngraph/src/extern_ngraph/src/ngraph/op/broadcast.cpp:62:
Broadcast argument shape, specified output shape, and axes are incompatible (argument shape: {240}, output shape: Shape{1, 12, 20, 20}, broadcast axes: AxisSet{1})." thrown in the test body.
[  FAILED  ] Analyzer_bert.compare (177 ms)
[----------] 1 test from Analyzer_bert (177 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (177 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Analyzer_bert.compare
```
**Code to reproduce the issue**

### PR DESCRIPTION
**Pull request by LeoZhao-BJ**
resolve #17147
test=develop

### CODE REVIEW

**Comment by LeoZhao-BJ** [comment]
@baojun-nervana 
Hi baojun, please help to review the patch, I am just trying to run bert using ngraph and find this issue, I guess it should be a typo.

**Comment by luotao1** [comment]
How about add nGraph test in `test_analyzer_bert` to check this PR?

**Comment by LeoZhao-BJ** [comment]
> How about add nGraph test in `test_analyzer_bert` to check this PR?

I am ok. may need baojun's opinion as well. @baojun-nervana

**Review by baojun-nervana — APPROVED** [review]
LGTM. thanks.

**Comment by luotao1** [comment]
@baojun-nervana Please do not merge it yourself. 
> How about add nGraph test in test_analyzer_bert to check this PR?

how do you think about: https://github.com/PaddlePaddle/Paddle/pull/17148#issuecomment-487440888

**Comment by baojun-nervana** [comment]
@luotao1 We are still validating bert model. We may not want to turn it on for bert model now.

**Pull request merged**
