### PR TITLE
fix interpolate mkldnn op error

### PR DESCRIPTION
**Pull request by baoachun**
### PR types
Bug fixes

### PR changes
OPs

### Describe
Fix the problem that the interpolate_v2 mkldnn op reports an error when the scale attribute is empty.

修复interpolate_v2 mkldnn 算子在scale属性为空时报错问题

### CODE REVIEW

**Comment by baoachun** [comment]
@lidanqing-intel  @jakpiase

**Review by jakpiase — APPROVED** [review]
LGTM

**Comment by jakpiase** [comment]
Should this PR have Intel label or not?

**Comment by lidanqing-vv** [comment]
LGTM.

**Review by shangzhizhou — APPROVED** [review]
LGTM

**Pull request merged**
