### PR TITLE
Fix FC + GRU fuse pass

### LINKED ISSUE #14837: The `fc_gru_fuse_pass` breaks accuracy in C-API CRNN-CTC inference.
The `fc_gru_fuse_pass` breaks accuracy when running CRNN-CTC inference using the C-API.

The application
https://github.com/wojtuss/models/tree/wojtuss/capi-ocr-recognition/fluid/PaddleCV/ocr_recognition/capi
runs inference using the CRNN-CTC trained model
https://github.com/wojtuss/models/blob/wojtuss/capi-ocr-recognition/fluid/PaddleCV/ocr_recognition/models/CRNN-CTC_model.tar.gz
 (with weights from Baidu, with EditDistance evaluator added) on the standard dataset.

With the `fc_gru_fuse_pass` disabled in `infer_ocr_recognition.cc:233` the accuracy we get from the app is equal to the accuracy we get using python `eval.py` script: avg distance = 0.09206844, avg seq error = 0.2425.
With the `fc_gru_fuse_pass` enabled, the accuracy gets lost: avg seq error = 1.0000.

The script
https://github.com/wojtuss/models/blob/wojtuss/capi-ocr-recognition/fluid/PaddleCV/ocr_recognition/capi/infer_ocr_with_accuracy.sh
provides an example of how to run the application.

### PR DESCRIPTION
**Pull request by grygielski**
### PR types
Bug fixes

### PR changes
Others

### Describe
This PR fixes FC + GRU fuse pass and enables it in OCR unit test. It should fix https://github.com/PaddlePaddle/Paddle/issues/14837 issue.

### CODE REVIEW

**Comment by luotao1** [comment]
Nice!! Could you explain where is the bug and how do you find it? We are so interested in it.

**Comment by grygielski** [comment]
The main bug for OCR model was not preserving activation functions during fuse. GRU in OCR has following activation attributes:
image
And during pass, these attributes were not forwarded so `fusion_gru` kernel used default ones: sigmoid/tanh.

Another problem was with recalculating bias in a weird way. There was a new variable created during pass and its values were calculated but then, the old bias was linked to `fusion_gru`. I've changed that in a way that Bias variable from GRU is recalculated based on FC bias and then linked to new `fusion_gru` operator.

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
Please cherry-pick into release/1.8

**Pull request merged**
