### PR TITLE
Add coverage tools

### PR DESCRIPTION
**Pull request by chalsliu**
Add coverage data processing tools.

### CODE REVIEW

**Comment by luotao1** [comment]
@kolinwei @kh2se2013 @zhouwei25 Please have a review.

**Review by luotao1 — COMMENTED** [review]
@chalsliu travis-ci代码格式没有过

**Comment by chalsliu** [comment]
for reopen

**Comment by chalsliu** [comment]
reopen

**Review by kolinwei — APPROVED** [review]

**Comment by luotao1** [comment]
@chalsliu 请补充下PR描述

**Pull request merged**
