### PR TITLE
 move contrib/inference to paddle/fluid/inference/api

### LINKED ISSUE #12198: move contrib/inference to paddle/fluid/inference

### PR DESCRIPTION
**Pull request by luotao1**
fix #12198 
1. move `contrib/inference` to `paddle/fluid/inference/api`, and simplify the file name.
- The `contrib` directory only contains `float16`:
```
contrib/
└── float16
    ├── float16_benchmark.md
    ├── float16_inference_demo.py
    ├── float16_transpiler.py
    ├── README.md
    └── run_float16_demo.sh
```
- The `fluid/inference/api` directory likes:
```
fluid/inference/api/
├── api_anakin_engine.cc
├── api_anakin_engine.h
├── api_anakin_engine_tester.cc
├── api.cc
├── api.h
├── api_impl.cc
├── api_impl.h
├── api.map
├── api.sym
├── api_tensorrt_subgraph_engine.cc
├── check_symbol.sh
├── CMakeLists.txt
├── demo_ci
│   ├── CMakeLists.txt
│   ├── README.md
│   ├── run.sh
│   ├── simple_on_word2vec.cc
│   ├── utils.h
│   └── vis_demo.cc
├── high_level_api_cn.md
├── high_level_api.md
├── README.md
├── test_api.cc
├── test_api_impl.cc
└── test_api_tensorrt_subgraph_engine.cc
```
- after `make inference_lib_dist`, the `fluid_install_dir/paddle/fluid/inference` directory likes:
```
paddle/fluid/inference/
├── anakin
│   ├── anakin_release_simple.tar.gz
│   ├── libinference_anakin_api.a
│   └── libinference_anakin_api_shared.so
├── api.h
├── engine.h
├── io.h
├── libpaddle_fluid.a
├── libpaddle_fluid.so
├── libpaddle_inference_api.a
└── libpaddle_inference_api.so
```
**NOTE: api.h is in the same level with io.h**

2. after move, make `demo_ci` pass.

3. fix some format
```
paddle/fluid/inference/api/api_anakin_engine.cc:113:  You don't need a ; after a }  [readability/braces] [4]
paddle/fluid/inference/api/api_anakin_engine.cc:41:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
Done processing paddle/fluid/inference/api/api_anakin_engine.cc
Total errors found: 2
Done processing paddle/fluid/inference/api/api_anakin_engine_tester.cc
paddle/fluid/inference/api/api_impl.cc:108:  You don't need a ; after a }  [readability/braces] [4]
Done processing paddle/fluid/inference/api/api_impl.cc
Total errors found: 1
Done processing paddle/fluid/inference/api/api_impl.h
Done processing paddle/fluid/inference/api/api_tensorrt_subgraph_engine.cc
paddle/fluid/inference/api/test_api.cc:17:  Found C system header after other header. Should be: test_api.h, c system, c++ system, other.  [build/include_order] [4]
paddle/fluid/inference/api/test_api.cc:18:  Found C system header after other header. Should be: test_api.h, c system, c++ system, other.  [build/include_order] [4]
Done processing paddle/fluid/inference/api/test_api.cc
Total errors found: 2
paddle/fluid/inference/api/test_api_impl.cc:18:  <thread> is an unapproved C++11 header.  [build/c++11] [5]
Done processing paddle/fluid/inference/api/test_api_impl.cc
Total errors found: 1
Done processing paddle/fluid/inference/api/test_api_tensorrt_subgraph_engine.cc
```

fixes: #12185

### CODE REVIEW

**Comment by luotao1** [comment]
Combining `libpaddle_inference_api` into `libpaddle_fluid` will be done in next PR.

**Review by Superjomn — COMMENTED** [review]
`paddle_inference_api.h` should not rename to `api.h`, some third-party developers already used that file, and user might copy this file to their project, so with a `paddle_inference_` prefix is better.

And, only one header file `paddle_inference_api.h` is enough, the other `[.h .cc]` are not needed for third-party compile, better to remove them, including the `api.map` and `api.sym`.

The final inference library just needs

- `paddle_inference_api.h`
- `demo_ci` for reference
- related static and dynamic libraries

**Comment by luotao1** [comment]
> `paddle_inference_api.h` should not rename to `api.h`, some third-party developers already used that file, and user might copy this file to their project, so with a `paddle_inference_` prefix is better.

Got it. I will rename it back to `paddle_inference_api.h`.

> And, only one header file `paddle_inference_api.h` is enough, the other `[.h .cc]` are not needed for third-party compile, better to remove them, including the `api.map` and `api.sym`.

Do you mean in the source directory or in the `fluid_install_dir`? What are other `[.h .cc]`, do you mean `paddle/fluid/inference/api/api_anakin_engine.h` etc or `paddle/fluid/platform/*.h` etc? `api.map` and `api.sym` would be removed in next PR when combining `libpaddle_inference_api` into `libpaddle_fluid`.

> The final inference library just needs: `paddle_inference_api.h`, `demo_ci` for reference, related static and dynamic libraries

Do you mean we will polish another inference library? If we still use `libpaddle_fluid`, we should contain all header of fluid for training now. Besides, do we need some thirdparty header such as `glog.h`?

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/12185/commits/c160b8d1d76b2e5c117ab48259cebc4a85acebd0 rename `api.h` back to `paddle_inference_api.h` and put `demo_ci` in `fluid_install_dir`. Now the `fluid_install_dir/paddle/fluid/inference` directory likes:
```
paddle/fluid/inference/
├── anakin
│   ├── anakin_release_simple.tar.gz
│   ├── libinference_anakin_api.a
│   └── libinference_anakin_api_shared.so
├── demo_ci
│   ├── CMakeLists.txt
│   ├── README.md
│   ├── run.sh
│   ├── simple_on_word2vec.cc
│   ├── utils.h
│   └── vis_demo.cc
├── engine.h
├── io.h
├── libpaddle_fluid.a
├── libpaddle_fluid.so
├── libpaddle_inference_api.a
├── libpaddle_inference_api.so
└── paddle_inference_api.h
```
Next PRs will do much more cleaner.

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
