### PR TITLE
[cherry-pick] A fix for oneDNN matmul kernel. Fixes issue #30309 (#30723)

### PR DESCRIPTION
**Pull request by wojtuss**
### PR types
Bug fixes

### PR changes
OPs

### Describe
This is a port of https://github.com/PaddlePaddle/Paddle/pull/30723.

### CODE REVIEW

**Review by luotao1 — APPROVED** [review]

**Comment by lidanqing-vv** [comment]
@wojtuss  Hi, please fix this PR as highest priority. Thank you very much!

**Comment by wojtuss** [comment]
@luotao1 ,
It turns out that the PR https://github.com/PaddlePaddle/Paddle/pull/30723 cannot be cherry-picked to the `release/2.0`. It uses the broadcasting support for `matmul` introduced in the 1.7 version of oneDNN, but the oneDNN version present in the `release/2.0` of Paddle is 1.6.

**Comment by wojtuss** [comment]
@luotao1 ,
It turns out that the PR https://github.com/PaddlePaddle/Paddle/pull/30723 cannot be cherry-picked to the `release/2.0`. It uses the broadcasting support for `matmul` introduced in the 1.7 version of oneDNN, but the oneDNN version present in the `release/2.0` of Paddle is 1.6. I am trying to modify the fix, so the 1.6 version of oneDNN could handle it.

**Comment by wojtuss** [comment]
@luotao1 ,
Please, share your thoughts on how to proceed with the issue. The fix merged already to the `develop` branch is optimal. Modifying it for the `release/2.0` branch so that oneDNN 1.6 could handle is not simple and would be suboptimal. Also, it would require merging the modified fix to the `develop` branch first before merging to `release/2.0` branch.

**Comment by luotao1** [comment]
> Please, share your thoughts on how to proceed with the issue. 

Since this PR solves the accuracy problem. Both two ways are OK, you can choose an easier way you think.

**Comment by wojtuss** [comment]
> Since this PR solves the accuracy problem. Both two ways are OK, you can choose an easier way you think.

@luotao1 ,
Could the fix tailored for release/2.0 be merged directly to the release/2.0 branch? If yes, I would prepare a fix for that branch only.

**Comment by luotao1** [comment]
> Could the fix tailored for release/2.0 be merged directly to the release/2.0 branch? If yes, I would prepare a fix for that branch only.

Yes, you can.

**Comment by wojtuss** [comment]
I am closing this PR. A new one is submitted: https://github.com/PaddlePaddle/Paddle/pull/31066

**Pull request closed without merging**
