### PR TITLE
[OpCompat] add and update `print`, `split` and `sync_batch_norm` in op_compat.yaml

### PR DESCRIPTION
**Pull request by GreatV**
### PR types
Others

### PR changes
Others

### Description

add and update print, split and sync_batch_norm in op_compat.yaml
- #55334

### CODE REVIEW

**Review by zyfncg — APPROVED** [review]

**Review by kangguangli — APPROVED** [review]
LGTM

**Review by heavyrain-lzy — APPROVED** [review]
LGTM

**Review by tianshuo78520a — APPROVED** [review]

**Comment by kangguangli** [comment]
@GreatV 可以rerun下失败的CI，我帮你merge

**Comment by GreatV** [comment]
@kangguangli rerun了

**Pull request merged**
