### PR TITLE
Enable assign operator for a ngraph, test=develop

### PR DESCRIPTION
**Pull request by mozga-intel**
Enable the assign operator for the nGraph bridge. BERT model uses it.

Additionally, the corss_entropy test was updated, due to that CI's test fails.

### CODE REVIEW

**Review by tensor-tang — COMMENTED** [review]
> Additionally, the corss_entropy test was updated, due to that CI's test fails.

Could u give some more details about this ?

**Comment by mozga-intel** [comment]
@tensor-tang The assign operator needs to support different shapes so any changes of xe operator are needed. The previous version of xe operator did not include these changes.

**Comment by tensor-tang** [comment]
> xe operator are needed

did not understand this

> due to that CI's test fails.

Actually I mean what is the test fails you said?

**Comment by mozga-intel** [comment]
@tensor-tang 
1) xe operator are needed - it means that I must have updated the cross_entoropy operator
2) Actually, I mean what is the test fails you said? - cross_entropy_ngraph

**Review by tensor-tang — APPROVED** [review]
LGTM

**Pull request merged**
