### PR TITLE
【Hackathon 6th Fundable Projects 3 No.205】Remove fluid operator lite_engine

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others 

### PR Types

Others 

### Description

Remove fluid operator lite_engine

### CODE REVIEW

**Comment by co63oc** [comment]
合入 https://github.com/PaddlePaddle/Paddle/pull/63501/

**Review by wanghuancoder — APPROVED** [review]
LGTM 这个情 @luotao1 协调LITE的同学帮忙Review一下~

**Review by hong19860320 — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
这个PR是不是和其他的冲突了？Check-Paddle-after-PR-merge 流水线失败了
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/10497468/job/25928535

**Comment by co63oc** [comment]
增加 PR清理 paddle/fluid/inference 中 LITE关联代码
 https://github.com/PaddlePaddle/Paddle/pull/63591

**Pull request merged**
