### PR TITLE
disable TestSoftmaxFP16Op2 in test_softmax_op, test=document_fix test=develop

### PR DESCRIPTION
**Pull request by XieYunshen**
### PR types

 Others
### PR changes

 Others
### Describe

disable TestSoftmaxFP16Op2 in test_softmax_op

### CODE REVIEW

**Review by kolinwei — APPROVED** [review]

**Comment by XieYunshen** [comment]
test_softmax_op中的TestSoftmaxFP16Op2失败，日志如截图所示
image

**Comment by XieYunshen** [comment]
test_softmax_op中的TestSoftmaxFP16Op2失败，日志如下：
 test_softmax_op failed
2020-07-13 13:07:40  .............F.............
2020-07-13 13:07:40 ======================================================================
2020-07-13 13:07:40 FAIL: test_check_output (test_softmax_op.TestSoftmaxFP16Op2)
2020-07-13 13:07:40 ----------------------------------------------------------------------
2020-07-13 13:07:40 Traceback (most recent call last):
2020-07-13 13:07:40   File "/paddle/build/python/paddle/fluid/tests/unittests/test_softmax_op.py", line 194, in test_check_output
2020-07-13 13:07:40     self.check_output_with_place(place, atol=1e-3)
2020-07-13 13:07:40   File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1099, in check_output_with_place
2020-07-13 13:07:40     place, no_check_set=no_check_set, inplace_atol=inplace_atol)
2020-07-13 13:07:40   File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 943, in check_inplace_output_with_place
2020-07-13 13:07:40     place, fwd_res, op_desc, inplace_atol=inplace_atol)
2020-07-13 13:07:40   File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 887, in _check_grad_inplace
2020-07-13 13:07:40     inplace_atol=inplace_atol)
2020-07-13 13:07:40   File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 648, in _compare_expect_and_actual_outputs
2020-07-13 13:07:40     " in class " + self.__class__.__name__ + '\n')
2020-07-13 13:07:40 AssertionError: Output (X@GRAD) has diff at CUDAPlace(0) when using and not using inplace

**Comment by XieYunshen** [comment]
任务链接：http://10.87.145.41:8111/viewLog.html?buildId=373220&buildTypeId=Paddle_PrCiNight

**Comment by XieYunshen** [comment]
任务链接：

**Pull request merged**
