### PR TITLE
[bf16] add bf16 kernel: scale  gather  sum

### PR DESCRIPTION
**Pull request by zhangbo9674**
### PR types
New features

### PR changes
OPs

### Describe
添加 `scale` `gather` `sum` bf16 kernel.

### CODE REVIEW

**Review by ZzSean — DISMISSED** [review]
LGTM for op benchmark

**Review by zhiqiu — DISMISSED** [review]
LGTM

**Review by limin2021 — DISMISSED** [review]
LGTM.

**Review by zhiqiu — APPROVED** [review]
LGTM

**Review by limin2021 — APPROVED** [review]
LGTM.

**Pull request merged**
