### PR TITLE
[ROCM] update fluid operators for rocm (part7), test=develop

### PR DESCRIPTION
**Pull request by qili93**
### PR types

New features 

### PR changes

OPs

### Describe

[ROCM] update fluid operators for rocm (part7)

### CODE REVIEW

**Review by GaoWei8 — DISMISSED** [review]
LGTM for op benchmark ci

**Comment by guoshengCS** [comment]
LGTM for cudnn_lstm related

**Review by GaoWei8 — APPROVED** [review]
LGTM for op benchmark ci

**Review by luotao1 — APPROVED** [review]
LGTM for const_cast

**Pull request merged**
