### PR TITLE
fix cache key for inplaced elementwise ops

### PR DESCRIPTION
**Pull request by wojtuss**
### PR types
Bug fixes

### PR changes
OPs

### Describe
This patch fixes the issue https://github.com/PaddlePaddle/Paddle/issues/29506.

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@juncaipeng Hi, please review

**Comment by lidanqing-intel** [comment]
Hi @wojtuss elementwise_op does not need batch size for the key? I know most elementwise_add will be fused, but maybe some are left not fused, batch_size is not needed for key?

**Comment by wojtuss** [comment]
Please, do not merge this PR until the WIP label is removed.

**Comment by wojtuss** [comment]
The patch is ready.

**Review by jczaja — APPROVED** [review]
LGTM

**Review by juncaipeng — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
Please cherry-pick into release/2.0

**Pull request merged**
