### PR TITLE
Added missing test for shuffle_channel_mkldnn_detect_pass

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Others

### PR changes
Others

### Describe
Added missing test for shuffle_channel_mkldnn_detect_pass

### CODE REVIEW

**Comment by jakpiase** [comment]
@tsocha could you please review this PR?

**Review by tsocha — DISMISSED** [review]

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by jakpiase** [comment]
@baoachun could you please review this PR?

**Comment by baoachun** [comment]
Hi @jakpiase, could you please add python ut like this https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_reshape_transpose_matmul_fuse_pass.py ?

**Review by jczaja — APPROVED** [review]

**Comment by jakpiase** [comment]
@baoachun I have added additional UT as you have requested. Could you please continue your review?

**Review by baoachun — APPROVED** [review]
LGTM

**Pull request merged**
