### PR TITLE
[MKL-DNN] Fix to face model on AVX512 platforms

### PR DESCRIPTION
**Pull request by jczaja**
Changes discussed here are fixing problem #18658 .

### CODE REVIEW

**Comment by jczaja** [comment]
@luotao1 Could you please help on PR_CI_CPU_Py2(Compile) , I have removed PADDLE_ENFORCE and used PADDLE_ENFORCE_NOT_NULL , but paddle_build.sh complains. Please advice how to proceed to have this CI passed

**Comment by luotao1** [comment]
@jczaja The CI rules would be stronger later, now, it monitor `git diff`, but could not distinguish the delete lines or add lines. I will approve it after your PR got approval.

**Comment by jczaja** [comment]
@grygielski Could you please review this PR?

**Review by grygielski — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
### before this PR
```
I0820 20:33:13.381389 35753 analysis_predictor.cc:475] == optimize end ==
I0820 20:33:13.381557 35753 tester_helper.h:332] Thread 0, number of threads 1, run 1 times...
E0820 20:33:13.381688 35753 analysis_predictor.cc:328] feed names from program do not have name: [] from specified input
Exception: /Paddle/paddle/fluid/memory/detail/meta_cache.cc:33 Assertion `desc->check_guards()` failed.
Exception: /Paddle/paddle/fluid/memory/detail/meta_cache.cc:33 Assertion `desc->check_guards()` failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exception encounter.
./run.sh: line 7: 35753 Aborted                 ./test_analyzer_image_classification --gtest_filter=Analyzer_resnet50.compare_mkldnn --paddle_num_threads=1 --repeat=1 --batch_size=1 --infer_model=$model
```
### after this PR
```

I0820 20:29:53.969043 19870 analysis_predictor.cc:475] == optimize end ==
I0820 20:29:53.969202 19870 tester_helper.h:332] Thread 0, number of threads 1, run 1 times...
E0820 20:29:53.969310 19870 analysis_predictor.cc:328] feed names from program do not have name: [] from specified input
I0820 20:29:54.139871 19870 helper.h:322] ====== threads: 1, thread id: 0 ======
I0820 20:29:54.139916 19870 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0820 20:29:54.139925 19870 helper.h:326] ====== batch latency: 170.65ms, number of samples: 1, sample latency: 170.65ms, fps: 5.85996, data type: float ======
F0820 20:29:54.140607 19870 tester_helper.h:119] Check failed: std::abs(pdata_ref[j] - pdata[j]) <= FLAGS_accuracy (0.0278975 vs. 0.001)
*** Check failure stack trace: ***
./run.sh: line 7: 19870 Aborted                 ./test_analyzer_image_classification --gtest_filter=Analyzer_resnet50.compare_mkldnn --paddle_num_threads=1 --repeat=1 --batch_size=1 --infer_model=$model
```
I have accuracy diff on 6148 machine.

**Review by grygielski — DISMISSED** [review]
LGTM

**Comment by LeoZhao-BJ** [comment]
LGTM

**Review by luotao1 — DISMISSED** [review]
LGTM, I test it Ok on 6148 machine

**Review by luotao1 — COMMENTED** [review]
```
[09:23:18][Step 4/5] Label Time Summary:
[09:23:18][Step 4/5] RUN_TYPE=DIST         = 160.53 sec*proc (15 tests)
[09:23:18][Step 4/5] RUN_TYPE=EXCLUSIVE    = 178.79 sec*proc (3 tests)
[09:23:18][Step 4/5] 
[09:23:18][Step 4/5] Total Test time (real) = 612.62 sec
[09:23:18][Step 4/5] 
[09:23:18][Step 4/5] The following tests FAILED:
[09:23:18][Step 4/5] 	495 - test_conv2d_int8_mkldnn_op (Failed)
```
http://ci.paddlepaddle.org/viewLog.html?buildId=150740&buildTypeId=PaddleWindows_PrWindowsCi&tab=buildLog

**Comment by jczaja** [comment]
@luotao1 Thanks for testing it. Changes in fetch op caused a need to change some of our unit tests . I wil update PR as soons as  test_conv2d_int8_mkldnn_op is fixed

**Comment by jczaja** [comment]
I adapted test_conv2d_int8_mkldnn_op.py to fetch op changes. 

@wozna Could you please review mentioned file to make sure it is all fine from your perspective?

@luotao1 Could you please continue reviwing this PR?

**Review by grygielski — APPROVED** [review]
LGTM

**Comment by wozna** [comment]
test_conv2d_int8_mkldnn_op.py LGTM

**Comment by jczaja** [comment]
@luotao1 Do you have any further comments or questions on that PR?

**Comment by luotao1** [comment]
image
Could you not force-push later since we could not see the difference between the before commit and your update commit? Thanks very much!

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 I will limit force pushing in next PRs so you can track review easier.

**Pull request merged**
