### PR TITLE
remove softmax api from fluid

### PR DESCRIPTION
**Pull request by Charles-hit**
### PR types

Others
### PR changes

APIs
### Describe

remove softmax api from fluid.

### CODE REVIEW

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by dingjiaweiww — DISMISSED** [review]

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by momozi1996 — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by dingjiaweiww — DISMISSED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Review by momozi1996 — APPROVED** [review]
LGTM

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Pull request merged**
