### PR TITLE
oneDNN conv2d kernel- optimize memory descriptors.

### PR DESCRIPTION
**Pull request by arogowie-intel**
### PR types
Performance optimization

### PR changes
Others 

### Describe
This PR refactors oneDNN conv2d kernel so that used oneDNN memory descriptors are created only once during first iteration.
This PR aims issue #28555

### CODE REVIEW

**Comment by arogowie-intel** [comment]
@jczaja @lidanqing-intel @wojtuss  Could you please review?

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 Could you please review this PR?

**Review by wojtuss — APPROVED** [review]
LGTM

**Pull request merged**
