### PR TITLE
fix conv2d_grad infer spmd bugs

### PR DESCRIPTION
**Pull request by lxd-cumt**
### PR Category
Auto Parallel

### PR Types
Bug fixes

### Description
fix conv2d_grad infer spmd bugs
Pcard-66975

### CODE REVIEW

**Comment by jeff41404** [comment]
Suggest turning on the gradient verification in the unit test of [semi_auto_parallel_for_conv2d.py](https://github.com/PaddlePaddle/Paddle/blob/develop/test/auto_parallel/semi_auto_parallel_for_conv2d.py#L39) (set `with_backward=True`). If this unit test can pass, it indicates that the accuracy of conv2d gradient is correct after modification

**Review by From00 — DISMISSED** [review]
LGTM

**Comment by lxd-cumt** [comment]
> Suggest turning on the gradient verification in the unit test of [semi_auto_parallel_for_conv2d.py](https://github.com/PaddlePaddle/Paddle/blob/develop/test/auto_parallel/semi_auto_parallel_for_conv2d.py#L39) (set `with_backward=True`). If this unit test can pass, it indicates that the accuracy of conv2d gradient is correct after modification

done

**Review by jeff41404 — APPROVED** [review]
LGTM

**Pull request merged**
