### PR TITLE
Hide globals & redesign tls

### PR DESCRIPTION
**Pull request by pawelpiotrowicz**
@jczaja

### CODE REVIEW

**Comment by jczaja** [comment]
@pawelpiotrowicz To have tests started , you need to put in your commit message "test=develop" string next to other info

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@pawelpiotrowicz  Maybe you need to install pre-commit because integration CI failed. https://pre-commit.com/

**Comment by luotao1** [comment]
[Paddle _ PR_CI_Coverage _ #53760 (19 Mar 20 10_22) _ Diff Coverage — TeamCity.pdf](https://github.com/PaddlePaddle/Paddle/files/4374896/Paddle._.PR_CI_Coverage._.53760.19.Mar.20.10_22._.Diff.Coverage.TeamCity.pdf)
- I will add a unit-test like #18372 first, then this PR could pass the UT-Coverage.
- For windows CI, I rerun it at first.

**Comment by lidanqing-vv** [comment]
@luotao1  Hi, will you add a UT for this PR

**Comment by luotao1** [comment]
Yes, I will add a UT, but I need some time.

**Pull request closed without merging**
