### PR TITLE
[Inference] rewrite elementwise trt layer

### PR DESCRIPTION
**Pull request by zhoutianzi666**
### PR types

Others
### PR changes

Others
### Describe

[Inference] rewrite elementwise trt layer

### CODE REVIEW

**Review by cyj1986 — DISMISSED** [review]
LGTM

**Review by zhangjun — DISMISSED** [review]
LGTM

**Review by chenwhql — DISMISSED** [review]
LGTM for PADDLE_ENFORCE

**Review by cyj1986 — APPROVED** [review]
LGTM

**Pull request merged**
