### PR TITLE
Added flatten and flatten2 BF16/FP32 FWD/BWD kernels

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
Added(currently disabled) flatten and flatten2 BF16/FP32 FWD/BWD kernels

### CODE REVIEW

**Comment by jczaja** [comment]
@tsocha Please review this PR

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jakpiase** [comment]
FYI:
Flatten, reshape and squeeze ops are all disabled and will be re-enabled when memory descriptor will be added to Tensor class. It was my intention to keep them disabled in this PR

**Review by lidanqing-vv — COMMENTED** [review]
- If you commented the mkldnn kernels calling part, how does mkldnn kernels code coverage passed? It looks now the mkldnn UT will always only call native kernels, is it?
- When will be memory descriptor being added into Tensor? What is the cause to add mem descriptor into Tensor?

**Comment by jakpiase** [comment]
Yes, for now only native kernels are called in mkldnn UTs. I will be adding md into tensor at the beginning of Q4, so it is only a temporary solution. We need to add memory descriptor into tensor class, because it is impossible to support all kind of data layouts through the memory format tags.

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Pull request merged**
