### PR TITLE
remove unused AnalysisPredictor::SetMkldnnThreadID()

### LINKED ISSUE #18406: how to run MKLDNN multi-instance
Now we use `AnalysisPredictor::SetMkldnnThreadID()` to run MKLDNN multi-instance in unit-tests:
https://github.com/PaddlePaddle/Paddle/blob/de42fe8fd584cca4a804e6e6f178f14b169d33c3/paddle/fluid/inference/tests/api/tester_helper.h#L415-L425
However, this interface is not in `paddle_analysis_config.h`, how do users run MKLDNN multi-instance?
If we expose to users? What's the interface? How about `config.EnableMKLDNN(int mkldnn_thread_id)`?

### PR DESCRIPTION
**Pull request by luotao1**
- fix #18406 by #17965
- fix warning in https://github.com/PaddlePaddle/Paddle/pull/18112#issuecomment-506129896

### CODE REVIEW

**Comment by luotao1** [comment]
### Result
```
$./paddle/fluid/inference/tests/api/test_analyzer_image_classification --infer_model=third_party/inference_demo/resnet50/model/ --gtest_filter=Analyzer_resnet50.profile_mkldnn --paddle_num_threads=1 --repeat=1 --batch_size=1 --num_threads=8 --disable_mkldnn_fc
Note: Google Test filter = Analyzer_resnet50.profile_mkldnn
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Analyzer_resnet50
[ RUN      ] Analyzer_resnet50.profile_mkldnn
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0702 11:27:01.006177 15515 tester_helper.h:233] feed target 0: {-1, 3, 318, 318}
I0702 11:27:01.010555 15515 tester_helper.h:87] AnalysisConfig {
  NativeConfig {
    PaddlePredictor::Config {
      model_dir:
    }
    use_gpu: 0
    device: 0
    fraction_of_gpu_memory: 0
    specify_input_name: 1
  }
  prog_file: third_party/inference_demo/resnet50/model//model
  param_file: third_party/inference_demo/resnet50/model//params
  enable_ir_optim: 1
  cpu_num_threads: 1
  use_feed_fetch_ops: 1
  use_tensorrt: 0
  use_mkldnn: 1
  use_ngraph: 0
}
I0702 11:27:01.021850 15515 analysis_predictor.cc:403] MKLDNN is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [mkldnn_placement_pass]
--- Running IR pass [infer_clean_graph_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [fc_lstm_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
---  detected 1 subgraphs
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
---  detected 53 subgraphs
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running IR pass [depthwise_conv_mkldnn_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_bias_mkldnn_fuse_pass]
---  detected 53 subgraphs
--- Running IR pass [conv_transpose_bias_mkldnn_fuse_pass]
--- Running IR pass [conv3d_bias_mkldnn_fuse_pass]
--- Running IR pass [conv_elementwise_add_mkldnn_fuse_pass]
---  detected 4 subgraphs
---  detected 12 subgraphs
Fused graph 16
--- Running IR pass [conv_concat_relu_mkldnn_fuse_pass]
--- Running IR pass [conv_relu_mkldnn_fuse_pass]
---  detected 49 subgraphs
--- Running IR pass [conv_brelu_mkldnn_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [ir_graph_to_program_pass]
I0702 11:27:01.542603 15515 analysis_predictor.cc:443] == optimize end ==
I0702 11:27:01.555646 19889 tester_helper.h:332] Thread 1, number of threads 8, run 1 times...
I0702 11:27:01.556151 19890 tester_helper.h:332] Thread 2, number of threads 8, run 1 times...
I0702 11:27:01.556197 19888 tester_helper.h:332] Thread 0, number of threads 8, run 1 times...
I0702 11:27:01.556268 19923 tester_helper.h:332] Thread 4, number of threads 8, run 1 times...
I0702 11:27:01.556403 19927 tester_helper.h:332] Thread 7, number of threads 8, run 1 times...
I0702 11:27:01.556655 19925 tester_helper.h:332] Thread 5, number of threads 8, run 1 times...
I0702 11:27:01.558712 19918 tester_helper.h:332] Thread 3, number of threads 8, run 1 times...
I0702 11:27:01.562502 19926 tester_helper.h:332] Thread 6, number of threads 8, run 1 times...
E0702 11:27:01.562834 19890 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
E0702 11:27:01.563105 19889 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
E0702 11:27:01.563227 19888 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
E0702 11:27:01.563915 19923 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
E0702 11:27:01.564220 19925 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
E0702 11:27:01.565754 19927 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
E0702 11:27:01.570518 19926 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
E0702 11:27:01.570811 19918 analysis_predictor.cc:295] feed names from program do not have name: [] from specified input
I0702 11:27:04.543637 19926 helper.h:322] ====== threads: 8, thread id: 6 ======
I0702 11:27:04.543692 19926 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:04.543701 19926 helper.h:326] ====== batch latency: 2980.31ms, number of samples: 1, sample latency: 2980.31ms, fps: 0.335536, data type: float ======
I0702 11:27:04.721071 19925 helper.h:322] ====== threads: 8, thread id: 5 ======
I0702 11:27:04.721120 19925 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:04.721128 19925 helper.h:326] ====== batch latency: 3164.33ms, number of samples: 1, sample latency: 3164.33ms, fps: 0.316023, data type: float ======
I0702 11:27:04.854277 19890 helper.h:322] ====== threads: 8, thread id: 2 ======
I0702 11:27:04.854326 19890 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:04.854333 19890 helper.h:326] ====== batch latency: 3298.06ms, number of samples: 1, sample latency: 3298.06ms, fps: 0.303209, data type: float ======
I0702 11:27:04.924458 19927 helper.h:322] ====== threads: 8, thread id: 7 ======
I0702 11:27:04.924517 19927 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:04.924525 19927 helper.h:326] ====== batch latency: 3367.21ms, number of samples: 1, sample latency: 3367.21ms, fps: 0.296982, data type: float ======
I0702 11:27:04.978675 19888 helper.h:322] ====== threads: 8, thread id: 0 ======
I0702 11:27:04.978727 19888 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:04.978735 19888 helper.h:326] ====== batch latency: 3421.96ms, number of samples: 1, sample latency: 3421.96ms, fps: 0.29223, data type: float ======
I0702 11:27:05.117595 19918 helper.h:322] ====== threads: 8, thread id: 3 ======
I0702 11:27:05.117645 19918 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:05.117653 19918 helper.h:326] ====== batch latency: 3558.83ms, number of samples: 1, sample latency: 3558.83ms, fps: 0.280991, data type: float ======
I0702 11:27:05.158579 19889 helper.h:322] ====== threads: 8, thread id: 1 ======
I0702 11:27:05.158630 19889 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:05.158638 19889 helper.h:326] ====== batch latency: 3602.79ms, number of samples: 1, sample latency: 3602.79ms, fps: 0.277563, data type: float ======
I0702 11:27:05.212707 19923 helper.h:322] ====== threads: 8, thread id: 4 ======
I0702 11:27:05.212775 19923 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
I0702 11:27:05.212788 19923 helper.h:326] ====== batch latency: 3656.4ms, number of samples: 1, sample latency: 3656.4ms, fps: 0.273493, data type: float ======
[       OK ] Analyzer_resnet50.profile_mkldnn (4493 ms)
[----------] 1 test from Analyzer_resnet50 (4493 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (4493 ms total)
[  PASSED  ] 1 test.
```
NOTE THAT：if `--disable_mkldnn_fc=false`, i.e. append `fc_mkldnn_pass`, there would be segment fault.

**Comment by luotao1** [comment]
@LeoZhao-Intel Please take a review!

**Comment by jianhang-liu** [comment]
LGTM

**Review by ghost — APPROVED** [review]
LGTM

**Comment by LeoZhao-BJ** [comment]
LGTM !

**Pull request merged**
