### PR TITLE
Move paddle/v2/plot/plot.py to paddle/utils

### PR DESCRIPTION
**Pull request by shippingwang**

### CODE REVIEW

**Comment by qingqing01** [comment]
also need PR for develop branch.

**Comment by luotao1** [comment]
This PR is needed for https://github.com/PaddlePaddle/book/pull/625

**Comment by luotao1** [comment]
- v2/plot需要删掉么？
- `python/setup.py.in`需要将`paddle.plot`打包进去，不然whl包安装后，还是无法使用。

**Comment by shippingwang** [comment]
> * v2/plot需要删掉么？
> * `python/setup.py.in`需要将`paddle.plot`打包进去，不然whl包安装后，还是无法使用。

可以不删掉；我放在了paddle.utils下，utils在包里啊

**Comment by luotao1** [comment]
close due to https://github.com/PaddlePaddle/book/pull/625 use `printf` not `plot` in release 1.0

**Pull request closed without merging**
