### PR TITLE
add sample code test under python3 and enabled multi-thread

### PR DESCRIPTION
**Pull request by suoych**
Now the sample code test program could detect the version of your python and run the test under the corresponding environment.  Currently, I let the program run in multi-thread mode.

### CODE REVIEW

**Review by guru4elephant — APPROVED** [review]
you should update your commit information in comment zone. LGTM

**Comment by suoych** [comment]
> you should update your commit information in comment zone. LGTM
OK, I'll remember, thanks.

**Comment by luotao1** [comment]
@suoych 
1. 请在PR描述里补充该PR解决的问题。
2. 之后会考虑利用多个CPU么？现在做的只是2线程加速。

**Comment by suoych** [comment]
> @suoych
> 
> 1. 请在PR描述里补充该PR解决的问题。
> 2. 之后会考虑利用多个CPU么？现在做的只是2线程加速。

会用多个cpu，我还会再改一下的

**Pull request merged**
