### PR TITLE
Rewrite batch norm act fuse pass tester

### PR DESCRIPTION
**Pull request by HulekJakub**
### PR types
Others

### PR changes
 Others

### Describe
Deleted old C++ batch normalization activation mkldnn fuse pass test and updated python one

Currently in PaddlePaddle there are 3 unit-test frameworks - one written in C++ and 2 in Python.
Old fuse pass tests (C++) fuse_pass_tester.cc are checking only if graph has correct number of / type of vertices after fusion. It doesn't check data. So these tests pass even if accuracy drops.
New python framework is superior because it checks both graph fusion and accuracy after fusion.

### CODE REVIEW

**Comment by yeliang2258** [comment]
Hello, please update code to pass the CI first

**Comment by HulekJakub** [comment]
@yeliang2258 CI passed

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM

**Review by jczaja — APPROVED** [review]
LGTM

**Pull request merged**
