### PR TITLE
Add box decoder and assign

### PR DESCRIPTION
**Pull request by jerrywgz**

### CODE REVIEW

**Comment by jerrywgz** [comment]
image
image

**Comment by haowang101779990** [comment]
Thanks, Review of API contents:
1.  Miscellaneous:
27eee18f8a5cb6f1b3d4af4cccc7c68

2.  In the "Returns" part, could you please clarify the relationship between output tensor and output_assign_box? I'm quite confused for a sudden appearance of output_assign_box. Thanks :)

3.
image

**Comment by jerrywgz** [comment]
image
image

**Comment by jerrywgz** [comment]
image
image

**Review by shanyi15 — APPROVED** [review]
format lgtm, please check the examples, thanks!

**Review by panyx0718 — APPROVED** [review]
LG API

**Pull request merged**
