### PR TITLE
Fluid API cleanup - fleet-api-related-changes-and-move

### PR DESCRIPTION
**Pull request by liudongxue01**
### PR types

Others 
### PR changes

APIs 
### Describe

Fluid API cleanup, some minor fixes and refactoring:
- cmake/external/brpc.cmake : add WITH_SNAPPY value in build log
- python/paddle/fluid/executor.py : move _is_optimizer_op() and  split_program_by_device() from FleetUtil to self for decoupling the dependence of FleetUtil.
- remove python/paddle/fluid/incubate/fleet/tests/cluster_train.sh 
- remove python/paddle/fluid/incubate/fleet/tests/ctr_dataset_reader.py
- remove python/paddle/fluid/incubate/fleet/utils/hdfs.py
- remove python/paddle/fluid/incubate/fleet/utils/http_server.py
- python/paddle/incubate/distributed/fleet/base..py: rename to paddle/incubate/distributed/fleet/base.py, delete split_program_by_device()
- python/paddle/fluid/tests/unittests/ps/static_gpubox_trainer.py : remove useless import of  FleetUtil
- python/paddle/fluid/tests/unittests/test_fleet_api_input.py : fix code bug
- python/paddle/fluid/tests/unittests/test_fleet_pyramid_hash.py:  add paddle.enable_static() in main entry on running in standalone mode
- python/paddle/fluid/tests/unittests/collective/fleet/test_fleet_checkpoint.py:  add paddle.enable_static() in main entry on running in standalone mode
- remove paddle/fluid/incubate/fleet/base/mode.py and move the class Mode code to python/paddle/incubate/distributed/fleet/base.py

### CODE REVIEW

**Review by risemeup1 — DISMISSED** [review]
LGTM for setup.py

**Review by zyfncg — DISMISSED** [review]
LGTM for setup.py.in

**Review by luotao1 — COMMENTED** [review]
```
2023-02-20 23:17:21 ['\''paddle.incubate.distributed.utils.io.dist_save.save'\'', '\''paddle.incubate.distributed.utils.io.dist_save.save_for_auto_inference'\''] is not in whl.
```
需要在 `setup.py.in`和`setup.py`中加入新目录`paddle.incubate.distributed.utils.io.dist_save`

**Comment by liudongxue01** [comment]
> 需要在 setup.py.in和setup.py中加入新目录paddle.incubate.distributed.utils.io.dist_save

dist_save不是一个目录，而是dist_save.py（一个文件）。这个不需要写进setup.py吧？

**Review by risemeup1 — APPROVED** [review]
LGTM for setup.py

**Review by raindrops2sea — APPROVED** [review]

**Review by zyfncg — APPROVED** [review]
LGTM for setup.py.in

**Pull request merged**
