### PR TITLE
[cherry-pick 2.5][Zero-Dim] support paddle.sum/mean/loss api output 0D

### PR DESCRIPTION
**Pull request by zhwesky2010**
### PR types

New features
### PR changes

APIs
### Description

cherry-pick以下支持0D的PR：

- https://github.com/PaddlePaddle/Paddle/pull/53182
- https://github.com/PaddlePaddle/Paddle/pull/52832
- https://github.com/PaddlePaddle/Paddle/pull/53186
- https://github.com/PaddlePaddle/Paddle/pull/52739
- https://github.com/PaddlePaddle/Paddle/pull/53382
- https://github.com/PaddlePaddle/Paddle/pull/53454
- https://github.com/PaddlePaddle/Paddle/pull/53473

### CODE REVIEW

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by From00 — APPROVED** [review]
LGTM for use `mutable_data`

**Review by hong19860320 — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by cyber-pioneer — APPROVED** [review]
LGTM for composite rule

**Pull request merged**
