### PR TITLE
[CleanOps]del unuseful op6

### PR DESCRIPTION
**Pull request by wanghuancoder**
### PR types

Others 
### PR changes

Others 
### Description

未有暴露的api
Pcard-74613

### CODE REVIEW

**Review by XieYunshen — DISMISSED** [review]

**Review by Aurelius84 — COMMENTED** [review]
python/paddle/nn/functional/loss.py 里有 sigmoid_focal_loss API

**Comment by Aurelius84** [comment]
> python/paddle/nn/functional/loss.py 里有 sigmoid_focal_loss API

API 里是组合实现的，故这里也可以删除

**Review by Aurelius84 — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Review by Aurelius84 — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
