### PR TITLE
Enhance key generation for Pool INT8 test

### PR DESCRIPTION
**Pull request by xiaolil1**
Enhance key generation for INT8 test.

### CODE REVIEW

**Comment by xiaolil1** [comment]
@luotao1 @tensor-tang @Superjomn   Please help to review this PR, thanks!

**Review by wojtuss — APPROVED** [review]
LGTM

**Comment by wojtuss** [comment]
@xiaolil1, as only the `paddle/fluid/operators/pool_mkldnn_op.cc` is finally modified (via commit f34e779), please clean the PR from all the other commits, as they can cause confusion.

**Comment by hshen14** [comment]
Thanks @wojtuss for your review and reminder.

**Pull request merged**
