### PR TITLE
add NVIDIAN into AUTHORS

### PR DESCRIPTION
**Pull request by jeng1220**
### PR types
Others

### PR changes
Docs

### Describe
Add contributors from NVIDIA into AUTHORS.md

### CODE REVIEW

**Comment by jeng1220** [comment]
@shangzhizhou ,
Please help to merge this PR

**Review by shangzhizhou — APPROVED** [review]
LGTM

**Comment by jeng1220** [comment]
@shangzhizhou,
Looks like CI is malfunction, but we can ignore it, right?

**Comment by shangzhizhou** [comment]
> @shangzhizhou,
> Looks like CI is malfunction, but we can ignore it, right?

这个不能忽略，我已经发起了重试，如果还失败我会请相关同学看下。

**Pull request merged**
