### PR TITLE
[hybrid] fused_feedforward op support tensor model parallel

### PR DESCRIPTION
**Pull request by wangxicoding**
### PR types

New features
### PR changes

OPs
### Describe

fused_feedforward op support tensor model parallel.
First column parallel linear, then row parallel linear, then we will got partial out, we can use allreduce to get final output.
image

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM for `set_tests_properties(test_static_model_parallel_fused_feedforward PROPERTIES TIMEOUT 120)`

**Review by FeixLiu — APPROVED** [review]
LGTM

**Review by zkh2016 — APPROVED** [review]
LGTM

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
