### PR TITLE
[Inference]Improve Performance in TensorRT Engine Instruction

### PR DESCRIPTION
**Pull request by YuanRisheng**
### PR Category

Performance Optimization

### PR Types

Bug fixes

### Description

card-71500
本PR修复TensorRTEngineInstruction中无效循环太多导致性能降低的问题

### CODE REVIEW

**Review by liym27 — APPROVED** [review]
Approve for PR-CI-Auto-Parallel

**Review by zhangting2020 — APPROVED** [review]
LGTM for PR-CI-Distribute-stable

**Review by vivienfanghuagood — APPROVED** [review]
LGTM

**Review by zhangbo9674 — APPROVED** [review]
LGTM

**Pull request merged**
