### PR TITLE
fix error sample code in static.nn.loss.nce

### PR DESCRIPTION
**Pull request by RedContritio**
### PR types

Bug fixes

### PR changes

Docs 

### Description

Fix error in `static.nn.loss.nce` sample code.

### CODE REVIEW

**Comment by RedContritio** [comment]
@LiuShuangQiao @leiqing1  辛苦 approve 一下

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
@RedContritio 辛苦 cherry-pick 到 release/2.5 分支

**Comment by RedContritio** [comment]
> @RedContritio 辛苦 cherry-pick 到 release/2.5 分支

了解，已 PR 

- #53630

**Pull request merged**
