### PR TITLE
SGD BF16 functional test.

### PR DESCRIPTION
**Pull request by arogowie-intel**
### PR types
Others

### PR changes
 Others

### Describe
This PR adds functional test for SGD BF16 op which checks it's correctness on small dummy model.

### CODE REVIEW

**Comment by arogowie-intel** [comment]
@lidanqing-intel Could you help with this approval: (PR-CI-CPU-Py2 failure reason)
```
2021-08-05 20:12:57 paddle.mean
2021-08-05 20:12:57 paddle.Tensor.mean
2021-08-05 20:12:57 You must have one RD (zhiqiu (Recommend) or phlrain) approval for the api change for the opreator-related api without 'core.ops'.
2021-08-05 20:12:57 For more details, please click [https://github.com/PaddlePaddle/Paddle/wiki/paddle_api_development_manual.md]
```
I had to modify those files to be able to run this test. Basically just added support for `uint16_t`.

**Review by jczaja — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Review by arlesniak — APPROVED** [review]
LGTM

**Comment by arogowie-intel** [comment]
@lidanqing-intel Could you please help getting approval from those people:
```
You must have one RD (zhiqiu (Recommend) or phlrain) approval for the api change for the opreator-related api without 'core.ops'
```

**Review by zhiqiu — APPROVED** [review]
LGTM for core.ops

**Comment by arogowie-intel** [comment]
@jczaja This PR is now ready to merge :)

**Pull request merged**
