### PR TITLE
fix type(x)=paddle.VarBase to paddle.Tensor

### PR DESCRIPTION
**Pull request by zhiboniu**
### PR types

Bug fixes
### PR changes

OPs
### Describe

fix type(x)=paddle.VarBase to paddle.Tensor

### CODE REVIEW

**Review by willthefrog — CHANGES_REQUESTED** [review]
maybe add some tests, cover cases with different import path

**Comment by zhiboniu** [comment]
> maybe add some tests, cover cases with different import path
done.
add unittest test_Tensor_type.py

**Review by willthefrog — APPROVED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
