### PR TITLE
[Prim] fix batch_norm custom_vjp dtype

### PR DESCRIPTION
**Pull request by cyber-pioneer**
### PR types
Bug fixes

### PR changes
Others

### Describe
Pcard-66969
Fix batch_norm custom_vjp dtype in amp mode and NHWC case.

### CODE REVIEW

**Review by JiabinYang — COMMENTED** [review]
Add Pcard

**Comment by cyber-pioneer** [comment]
> Add Pcard

done

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by xiaoguoguo626807 — DISMISSED** [review]
LGTM

**Review by xiaoguoguo626807 — APPROVED** [review]

**Pull request merged**
