### PR TITLE
[ProcessGroup] Support new apis in ProcessGroupNCCL

### PR DESCRIPTION
**Pull request by haohongxiang**
### PR types

New features
### PR changes

APIs
### Describe

[ProcessGroup] Support new apis in ProcessGroupNCCL
[docs_cn] [PR-4969](https://github.com/PaddlePaddle/docs/pull/4969) / [Preview Link](http://preview-pr-4969.paddle-docs-preview.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html)

### CODE REVIEW

**Review by ForFishes — APPROVED** [review]
LGTM

**Review by jeff41404 — APPROVED** [review]
the name and parameter of API design meet the Paddle specification requirements, so approve.

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM for 
`
  set_tests_properties(test_collective_alltoall_single PROPERTIES TIMEOUT 60)
  set_tests_properties(test_collective_batch_isend_irecv PROPERTIES TIMEOUT 100)
  set_tests_properties(test_collective_reduce_scatter PROPERTIES TIMEOUT 100)
`

**Review by dingjiaweiww — APPROVED** [review]

**Pull request merged**
