### PR TITLE
remove the extend_optimizer_with_weight_decay function

### PR DESCRIPTION
**Pull request by longranger2**
### PR types
Others

### PR changes
APIs

### Description
remove the extend_optimizer_with_weight_decay function

### CODE REVIEW

**Comment by longranger2** [comment]
@zoooo0820 辛苦review下～

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM
单测删除

**Review by jeff41404 — APPROVED** [review]

**Review by sunzhongkai588 — APPROVED** [review]
LGTM for docs

**Review by risemeup1 — APPROVED** [review]
LGTM

**Review by YuanRisheng — APPROVED** [review]

**Pull request merged**
