### PR TITLE
make paddle.to_tensor() copy if data is tensor

### PR DESCRIPTION
**Pull request by zhiqiu**
### PR types

Bug fixes
### PR changes

APIs
### Describe

- make paddle.to_tensor() copy if data is varbase, so the computation graph is splited from which of data.
- make the  stop_gradient of input(data) not changed

### CODE REVIEW

**Review by zhwesky2010 — DISMISSED** [review]
LGTM，as_tensor会尽量做一些不拷贝的操作，目前没有应用场景，因此无需将其特性合并到to_tensor中，to_tensor始终保持拷贝

**Review by zhwesky2010 — COMMENTED** [review]
中文文档需改下

**Review by TCChenlong — APPROVED** [review]
LGTM
需要同步修改中文文档：

**Review by jzhang533 — APPROVED** [review]
lgtm

**Pull request merged**
