### PR TITLE
Move ngraph files into operators/ngraph

### PR DESCRIPTION
**Pull request by baojun-nervana**
This PR is to move ngraph files from /framework to operators/ngraph. This is part of effort to split the PR https://github.com/PaddlePaddle/Paddle/pull/14948

* ngraph_bridge.* was moved into operators/ngraph
* ngraph_operator.* was moved as well
   - NgraphEngine was taken out of ngraph_operator.* as separate file. (This is needed by PR #14948)

### CODE REVIEW

**Comment by baojun-nervana** [comment]
The const_cast seems to be in the removed file. Any way to avoid the CI flagging?

**Comment by baojun-nervana** [comment]
@luotao1 The const_cast CI fail seems to be a false alarm. Can this PR be merged? The git diff caught the const_cast in the deleted file (framework/ngraph_operator.cc).

**Comment by baojun-nervana** [comment]
@panyx0718 It needs your approval on the const_cast. The const_cast seems to be a false alarm as it is from the old file removed in this PR. This PR is just about move ngraph files to operators/ngraph directory. It is an effort to split PR #14948 into smaller ones to facilitate the review process.

**Review by panyx0718 — DISMISSED** [review]
approve for const_cast deletion. I don't see added new const_cast

**Comment by luotao1** [comment]
why do you temporarily add file to pass CI test=develop in https://github.com/PaddlePaddle/Paddle/pull/15146/commits/02963a8cc07d0fe0b84390042150c366dd6122e8?

**Comment by baojun-nervana** [comment]
> why do you temporarily add file to pass CI test=develop in [02963a8](https://github.com/PaddlePaddle/Paddle/commit/02963a8cc07d0fe0b84390042150c366dd6122e8)?

@luotao1 It is is to avoid CI fail due to const-cast. Pan Xin's approval was dismissed after resolving conflict and rebasing to develop. I can follow up a PR to remove the unwanted file.

**Pull request closed without merging**
