### PR TITLE
Logical compare

### LINKED ISSUE #15815: [Operator] Add less_equal, greater_than, greater_equal, not_equal op
test=develop
Like those compare function in numpy.

### PR DESCRIPTION
**Pull request by zhoukunsheng**
test=develop
compare_op kernel for greater_than, greater_equal, less_equal, not_equal already existed in paddlepaddle,
this commit adds python api only.
resolve #15815

### CODE REVIEW

**Comment by zhoukunsheng** [comment]
image
image
image
image

**Comment by shanyi15** [comment]
could we delete ` **ignored` in the parameter line?

**Comment by zhoukunsheng** [comment]
> could we delete ` **ignored` in the parameter line?

thanks, good point.


image
image

**Comment by zhoukunsheng** [comment]
image

**Review by shanyi15 — DISMISSED** [review]
LG comments, thanks

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by shanyi15 — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]

**Pull request merged**
