### PR TITLE
Fix the global_step & continuous applying error in EMA

### PR DESCRIPTION
**Pull request by kuke**
Fix two problems:
1) The global step should count independently, instead of dependent on learning rate scheduler;
2) The result is not correct when applying EMA continuously.

### CODE REVIEW

**Comment by LielinJiang** [comment]
tried in image classification task, everything looks good.

**Review by LielinJiang — DISMISSED** [review]

**Review by Boyan-Liu — DISMISSED** [review]
LGTM

**Review by wanghaoshuang — DISMISSED** [review]

**Review by wanghaoshuang — APPROVED** [review]
LGTM

**Review by Boyan-Liu — APPROVED** [review]

**Review by swtkiwi — APPROVED** [review]
LGTM

**Pull request merged**
