### PR TITLE
Enable less_than ngraph operator

### PR DESCRIPTION
**Pull request by pawelpiotrowicz**
This PR is to enable less_than op for ngraph engine, it is needed for BERT model

### CODE REVIEW

**Comment by luotao1** [comment]
Please add unit-test for this op.

**Review by mozga-intel — APPROVED** [review]
LGTM

**Review by baojun-nervana — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
@pawelpiotrowicz @mozga-intel @baojun-nervana please improve and perfect the description of all the PRs. https://github.com/PaddlePaddle/Paddle/pull/17642#issue-282048405 "test=develop" is not a good description.

**Comment by baojun-nervana** [comment]
> @pawelpiotrowicz @mozga-intel @baojun-nervana please improve and perfect the description of all the PRs. [#17642 (comment)](https://github.com/PaddlePaddle/Paddle/pull/17642#issue-282048405) "test=develop" is not a good description.

Does the above description look good?

**Comment by luotao1** [comment]
Thanks @baojun-nervana, please improve and perfect the description of other ngraph PRs.

**Pull request merged**
