### PR TITLE
 [cherry-pick 2.2]fix data parallel when VOCAB var in program 

### PR DESCRIPTION
**Pull request by Steffy-zxf**
### PR types

Bug fixes

### PR changes

APIs

### Describe

fix data parallel when VOCAB var in program

### CODE REVIEW

**Review by XieYunshen — DISMISSED** [review]
LGTM  for `set_tests_properties(test_faster_tokenizer_op PROPERTIES LABELS "RUN_TYPE=EXCLUSIVE")`

**Review by wawltor — DISMISSED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Review by wawltor — APPROVED** [review]
LGTM

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Pull request merged**
