### PR TITLE
[CustomDevice] add comm context support

### PR DESCRIPTION
**Pull request by ronny1996**
### PR types

Others
### PR changes

Others
### Description

add comm context support

NPU 上 API 验证通过
image

### CODE REVIEW

**Review by qili93 — APPROVED** [review]
LGTM

**Review by hitywt — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Comment by jimmy-evo** [comment]
@ronny1996 
I got error:

https://github.com/PaddlePaddle/Paddle/blame/develop/paddle/phi/core/distributed/comm_context_manager.cc#L115

```
paddle/phi/core/distributed/comm_context_manager.cc:115:3: error: ‘VLOG’ was not declared in this scope
  115 |   VLOG(3) << "init xccl rank: " << rank << ", nranks: " << size
      |   ^~~~
```

**Pull request merged**
