### PR TITLE
set with_mpi default False.

### PR DESCRIPTION
**Pull request by wuhuachaocoding**
### PR types

Others
### PR changes

Others
### Describe

this PR mainly gives the WITH_MPI option for users to determine ON/OFF, default OFF. only when users set WITH_MPI ON and WITH_DISTRIBUTED ON, and there is mpi supported lib in your system, the  mpi functions can be supported!

### CODE REVIEW

**Review by XieYunshen — DISMISSED** [review]
LGTM
`test_mpi_comm`单测删除

**Review by XieYunshen — APPROVED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by ForFishes — APPROVED** [review]
LGTM

**Pull request merged**
