### PR TITLE
Rewrite mkldnn fc rnn fuse pass tester

### PR DESCRIPTION
**Pull request by HulekJakub**
### PR types
Others

### PR changes
Others

### Describe
Deleted old C++ conv activation mkldnn fuse pass test and updated python one

Currently in PaddlePaddle there are 3 unit-test frameworks - one written in C++ and 2 in Python.
Old fuse pass tests (C++) fuse_pass_tester.cc are checking only if graph has correct number of / type of vertices after fusion. It doesn't check data. So these tests pass even if accuracy drops.
New python framework is superior because it checks both graph fusion and accuracy after fusion.

This change rewrites joint test for onednn fc-gru and fc-lstm pass and separates it.
It also fixes issue with fc_lstm_fuse_pass, when lstm has peepholes (bias wasn't properly merged).

### CODE REVIEW

**Review by Silv3S — APPROVED** [review]

**Comment by HulekJakub** [comment]
@xiegegege please approve "Performance of model ResNet50_pure_fp16_bs64 has been increased from 920.046 to 974.004,(974.004-920.046)/920.046 equals 0.0586,which is greater than threshold 0.05,please contact xiege01 or heya02 to modify the standard value"
@XieYunshen please approve changes in tests

**Review by XieYunshen — APPROVED** [review]
LGTM for test rewrite

**Review by qingqing01 — APPROVED** [review]
LGTM

**Review by jczaja — APPROVED** [review]
LGTM

**Pull request merged**
