### PR TITLE
Remved redundant defintions of likely/unlikely

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Performance optimization

### PR changes
OPs

### Describe
Removing redundant definitions of likely and unlikely and some more usages

### CODE REVIEW

**Review by sfraczek — APPROVED** [review]
LGTM

**Review by jakpiase — APPROVED** [review]
LGTM, very nice refactoring. It's good to see that some concepts of branch prediction can be used in production environment!

**Comment by jczaja** [comment]
@Aganlengzi  Please review

**Comment by jczaja** [comment]
@baoachun Could you please help with review?

**Review by baoachun — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Pull request merged**
