### PR TITLE
[ROCM] update fluid conv and pool op for rocm (part4), test=develop

### PR DESCRIPTION
**Pull request by qili93**
### PR types

New features

### PR changes

OPs

### Describe

[ROCM] update fluid conv and pool op for rocm (part4)

### CODE REVIEW

**Review by luotao1 — DISMISSED** [review]
LGTM for const_cast

**Review by GaoWei8 — DISMISSED** [review]
LGTM for op benchmark ci

**Review by zhangting2020 — APPROVED** [review]
LGTM

**Review by GaoWei8 — APPROVED** [review]
LGTM for op benchmark ci

**Review by luotao1 — APPROVED** [review]

**Review by raindrops2sea — APPROVED** [review]

**Pull request merged**
