### PR TITLE
Optimize INT8 DeQuantize Op with primitive reuse.

### PR DESCRIPTION
**Pull request by xiaolil1**
Add primitive reuse for INT8 DeQuantize Op to improve the performance of ResNet-50 and MobileNet-V1, especially for INT8 latency with ~10% at topology level.

test=develop

### CODE REVIEW

**Comment by xiaolil1** [comment]
@kbinias @sfraczek @wojtuss Please help to review this PR, thanks!

**Review by sfraczek — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
> especially for INT8 latency with ~10% at topology level

Is 10% speedup by this PR, or including other PRs, such as #15883 @xiaolil1

**Comment by hshen14** [comment]
> > especially for INT8 latency with ~10% at topology level
> 
> Is 10% speedup by this PR, or including other PRs, such as #15883 @xiaolil1

@luotao1 The ratio depends on model, ~10% comes from those two PRs on ResNet-50, more speedup on MobileNet-V1.

**Pull request merged**
