### PR TITLE
Remove the NGraph engine from PDPD repository

### PR DESCRIPTION
**Pull request by mozga-intel**
1. Each operator was removed from the operator's directory
2. Each test was removed from the unittest directory
3. The parallel executor support was removed from the PDPD
4. The CMake file was removed from the PDPD
5. The NG flags were removed from the repository
test=develop

### CODE REVIEW

**Review by luotao1 — APPROVED** [review]

**Comment by lidanqing-vv** [comment]
@wojtuss Please help review this PR
@luotao1 We discussed, we want to do internal review first and then will let you know so that you can merge. 
We plan to merge it into 2.0

**Review by luotao1 — CHANGES_REQUESTED** [review]
This Request Changes is only for rerun PR-CI-Coverage. After PR-CI-Coverage pass, I will approve it.

**Review by wojtuss — COMMENTED** [review]
A few places left where nGraph is mentioned:
`CMakeLists.txt`: option `WITH_NGRAPH`
`paddle/fluid/inference/api/demo_ci/CMakeLists.txt`: `${NGRAPH_LIB}`
`python/paddle/fluid/tests/unittests/test_eager_deletion_delete_vars.py`: `FLAGS_use_ngraph`

**Comment by lidanqing-vv** [comment]
@luotao Could you please rerun the failed Coverage CI? Thank you !

**Review by wojtuss — DISMISSED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@wojtuss I think this one need to "Unlock converstaion" too, Please help to start it. Thanks.

**Comment by mozga-intel** [comment]
@luotao1 Could you please help: 
* PR_CI_CPU_Py2 (Compile) — TeamCity build failed
`0. You must have Dianhai approval for change 20+ files or add than 1000+ lines of content.`

**Comment by luotao1** [comment]
Got it. I will invite @raindrops2sea to review it.

**Comment by luotao1** [comment]
@mozga-intel Sorry for my quick approval on this PR at first, and PR-CI-Coverage (see https://xly.bce.baidu.com/paddlepaddle/paddle/ipipe/#/detail/715203/job/1034090) directly passes.
```

[2020-04-06 16:16:00]  current pr 23350 got approvals: TRUE
[2020-04-06 16:16:00]  ===================================
[2020-04-06 16:16:00]  
[2020-04-06 16:16:00]   current pr 23350 has got approvals. So, Pass CI directly!
[2020-04-06 16:16:00]  
[2020-04-06 16:16:00]  ===================================
```
We could not fix this approval bug ASAP, could you create a new PR again? Thanks very much!

**Comment by mozga-intel** [comment]
@luotao1 Thanks!

**Pull request closed without merging**
