### PR TITLE
Add oneDNN fusion_gru kernel

### PR DESCRIPTION
**Pull request by grygielski**
### PR types
New features

### PR changes
OPs

### Describe
This PR adds oneDNN fp32 GRU kernel. It also fixes the fc+gru pass.

### CODE REVIEW

**Comment by grygielski** [comment]
@luotao1 Could you advice me on failing PR-CI-Coverage? It seems to look for CUDA kernel of `fusion_gru` but I've only registered MKLDNN version of CPU kernel.

**Comment by grygielski** [comment]
@luotao1 I've tested this PR on CAPI model prepared by @lidanqing-intel (https://github.com/PaddlePaddle/Paddle/pull/25534) and received significant performance boost. For native PP GRU kernel, model runs with 2660.65 FPS and for oneDNN fusion_gru, introduced by this PR, the performance increase to 4770.75 FPS. We have also tested bfloat16 performance of this model on CPX machine and received 5803.67 FPS. We have some ideas that could speed this model even further but we need this PR to be merged. I'm having some problems with CIs, could you look at logs and ask appropriate people for help (there are some CUDA-related errors)?

**Comment by luotao1** [comment]
> It also fixes the fc+gru pass.

Could you fix the fc+gru pass in a separate PR, since you can cherry-pick into release/1.8, and we will release 1.8.4 later.

If you fix the fc+gru pass, #14837 could be closed? And could you verify it in a unit-test, i.e, remove line60 in `analyzer_vis_tester.cc`
https://github.com/PaddlePaddle/Paddle/blob/b4b169467ba27d04e6d4bd5c6bc3f7abbba04c65/paddle/fluid/inference/tests/api/analyzer_vis_tester.cc#L53-L61

**Comment by grygielski** [comment]
@luotao1 I've done that in https://github.com/PaddlePaddle/Paddle/pull/25687

**Comment by grygielski** [comment]
@luotao1 I'm still getting the same error about fusion_gru CUDA kernel not being registered. It seems to be a bug with pybind (and cmake/operators.cmake file), can someone help with that?

**Comment by luotao1** [comment]
> I'm still getting the same error about fusion_gru CUDA kernel not being registered

@donproc Could you help see it?

**Comment by donproc** [comment]
> @luotao1 I'm still getting the same error about fusion_gru CUDA kernel not being registered. It seems to be a bug with pybind (and cmake/operators.cmake file), can someone help with that?

@grygielski 

Would you please try to add `"fusion_gru_op"` to operators.cmake as following

```
    # Define operators that don't need pybind here.

    foreach(manual_pybind_op "compare_reduce_op" "compare_op" "logical_op" "nccl_op"
"tensor_array_read_write_op" "tensorrt_engine_op" "conv_fusion_op"
"fusion_transpose_flatten_concat_op" "fusion_conv_inception_op"
"sync_batch_norm_op" "dgc_op" "fused_fc_elementwise_layernorm_op"
"multihead_matmul_op" "fusion_group_op" "fused_bn_activation_op" "fused_embedding_eltwise_layernorm_op" "fusion_gru_op")
        if ("${TARGET}" STREQUAL "${manual_pybind_op}")
            set(pybind_flag 1)
        endif()
    endforeach()
```

We can pass the compiling but I'm not clear about the side effects now

**Comment by grygielski** [comment]
@donproc It seems that it doesn't work well

**Comment by donproc** [comment]
> @donproc It seems that it doesn't work well

@grygielski May you show more details? Can you pass the compiling? Side effects?

**Comment by grygielski** [comment]
@donproc 
fusion_gru UTs fail with:
` ValueError: Operator "fusion_gru" has not been registered. `
model UTs with fusion_gru fails with:
` Error: Operator fusion_gru has not been registered [Hint: op_info_ptr should not be null.] at (/paddle/paddle/fluid/framework/op_info.h:140) `

But it passes compiling

**Comment by donproc** [comment]
@grygielski 

This fused Op applys only in oneDNN, seems no cuda implementation; But the default bind requires cpu and cuda implementation, so we need bind this op manually.

Would you please try to add xxx to fused/CMakeLists.txt as following

```
register_operators(EXCLUDES
    fused_bn_activation_op
    conv_fusion_op
    fusion_transpose_flatten_concat_op
    fusion_conv_inception_op
    fused_fc_elementwise_layernorm_op
    multihead_matmul_op
    fused_embedding_eltwise_layernorm_op
    fusion_group_op
    fusion_gru_op) # exclude this op bind
```

and 

```
if (WITH_MKLDNN)
    # fusion_gru_op
    op_library(fusion_gru_op)
    file(APPEND ${pybind_file} "USE_CPU_ONLY_OP(fusion_gru);\n")
endif(WITH_MKLDNN)
```
Seems ugly, we may revise lately.

I can pass the compiling and can bind op, but the unittest failed.  Would you please check again?

**Comment by grygielski** [comment]
@donproc  I'll try that but keep in mind that `fusion_gru` not only has oneDNN kernel but also plain CPU kernel so it should be included also if PP is being built without MKLDNN.

**Comment by donproc** [comment]
> @donproc I'll try that but keep in mind that `fusion_gru` not only has oneDNN kernel but also plain CPU kernel so it should be included also if PP is being built without MKLDNN.

Yes,  we should keep the cpu plain kernel

1/2 Test #442: test_fusion_gru_op ...............   Passed    3.60 sec

**Comment by donproc** [comment]
> @donproc I'll try that but keep in mind that `fusion_gru` not only has oneDNN kernel but also plain CPU kernel so it should be included also if PP is being built without MKLDNN.

I just understood what you said, yes , cpu should be enabled defalut.

```

# fusion_gru_op
op_library(fusion_gru_op)
file(APPEND ${pybind_file} "USE_CPU_ONLY_OP(fusion_gru);\n")

```

**Comment by grygielski** [comment]
It seems everything works now, thanks a lot @donproc :)

**Review by wojtuss — APPROVED** [review]
LGTM

**Pull request merged**
