### PR TITLE
Add bf16 support for fused matmul

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Performance optimization

### PR changes
OPs

### Describe
- we observed performance regression with fused ops, because they were not appended into bf16-supported list,
- add `fused_matmul` to list of bf16 supported ops, 
- remove extra attributes from matmul fuse pass compats to fix warnings.

### CODE REVIEW

**Comment by onecatcn** [comment]
@weishengying Please take care of this PR.

**Comment by Silv3S** [comment]
@PaulinaGacek, @HulekJakub could you review, please?

**Review by jczaja — APPROVED** [review]
LGTM

**Review by paulinagacek — APPROVED** [review]
LGTM!

**Review by HulekJakub — APPROVED** [review]
LGTM

**Comment by Silv3S** [comment]
@jczaja please merge

**Pull request merged**
