### PR TITLE
add sharding-0.6

### PR DESCRIPTION
**Pull request by mapingshuo**
### PR types

New features
### PR changes

APIs
### Describe

**Introduction**
`Sharding` is a distributed strategy for saving memory. 

It is well known that there are two kinds of tensors that consume the device memory when running the neural network: 
- feature maps
- parameters

`Sharding` aims to reduce the memory of `parameters`, so that models with hundreds of billion parameters can be trained on 32 GB memory devices.

`Sharding` strategy split the `parameters` to `N` parts, where `N` stands for the device count. Each device only holds 1 part of the parameters in its memory. When a device needs a parameter that it does not hold, the parameter will be `broadcasted` from the source device.

**Usage**

code

```
import numpy as np
import paddle.distributed.fleet as fleet
import os
import paddle

paddle.enable_static()

fleet.init(is_collective=True)

def gen_data():
    return {"x": np.random.random(size=(32, 32)).astype('float32'),
            "y": np.random.randint(2, size=(32, 1)).astype('int64')}

def mlp(input_x, input_y, hid_dim=128, label_dim=2):
    fc_1 = paddle.static.nn.fc(x=input_x, size=hid_dim)
    fc_2 = paddle.static.nn.fc(x=fc_1, size=hid_dim)
    fc_3 = paddle.static.nn.fc(x=fc_2, size=hid_dim)
    fc_4 = paddle.static.nn.fc(x=fc_3, size=hid_dim)
    fc_5 = paddle.static.nn.fc(x=fc_4, size=hid_dim)
    fc_6 = paddle.static.nn.fc(x=fc_5, size=hid_dim)
    fc_7 = paddle.static.nn.fc(x=fc_6, size=hid_dim)
    prediction = paddle.static.nn.fc(x=[fc_7], size=label_dim, activation='softmax')
    cost = paddle.nn.functional.cross_entropy(input=prediction, label=input_y)
    sum_cost = paddle.mean(cost)
    return sum_cost, fc_1, prediction

input_x = paddle.static.data(name="x", shape=[-1, 32], dtype='float32')
input_y = paddle.static.data(name="y", shape=[-1, 1], dtype='int64')
cost, fc_1, pred = mlp(input_x, input_y)


dist_strategy = fleet.DistributedStrategy()
dist_strategy.sharding=True
dist_strategy.sharding_configs = {"fuse_broadcast_MB": 32}
optimizer = paddle.optimizer.Adam(learning_rate=0.01)
optimizer = fleet.distributed_optimizer(optimizer, dist_strategy)
optimizer.minimize(cost)

place = paddle.CUDAPlace(int(os.environ.get('FLAGS_selected_gpus', 0)))
exe = paddle.static.Executor(place)
exe.run(paddle.static.default_startup_program())
step = 10

with open("main_program.txt", 'w') as f:
    f.write(str(paddle.static.default_main_program()))

for i in range(step):
    cost_val = exe.run(feed=gen_data(),
                       program=paddle.static.default_main_program(),
                       fetch_list=[cost.name])
    print("step=%d cost=%f" % (i, cost_val[0]))
```

start command:

```
fleetrun demo.py
```

expected results:

```
W1021 16:51:45.704849   780 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 9.0
W1021 16:51:45.710430   780 device_context.cc:346] device: 0, cuDNN Version: 7.6.
step=0 cost=0.724302
step=1 cost=15.639750
step=2 cost=4.064980
step=3 cost=34.000000
step=4 cost=35.827511
step=5 cost=10.651733
step=6 cost=3.921406
step=7 cost=3.576933
step=8 cost=5.932743
step=9 cost=0.876115
```

**Reference**

1. Rajbhandari, Samyam, et al. "Zero: Memory optimization towards training a trillion parameter models." arXiv preprint arXiv:1910.02054 (2019).

### CODE REVIEW

**Review by zhwesky2010 — DISMISSED** [review]
LGTM for gradient_clip namescope

**Review by wangxicoding — DISMISSED** [review]
LGTM with DGCOptimizer

**Review by guru4elephant — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]
LGTM for framework.py

**Comment by raindrops2sea** [comment]
demo code可统一使用2.0 API.

**Review by raindrops2sea — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
