### PR TITLE
[cherry-pick] Remove gpu_cpu_reshape2_matmul_fuse_pass in EnableMkldnn

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types

Others
### PR changes

Others
### Describe

Fix resnet50 performance drop issue

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@wozna @yeliang2258 Please review this cherry-pick PR.

**Comment by lidanqing-vv** [comment]
With this PR, performance results as follows. @yeliang2258 @jiangjiajun 

Resnet50 FP32
```
KMP_BLOCKTIME=1 KMP_AFFINITY=granularity=fine,compact,1,0 GLOG_logtostderr=1 numactl -c 0 -m 0 ./build/sample_tester --infer_model=resnet50_fp32/model/ --infer_data=val_1000.bin     --batch_size=1     --num_threads=1     --iterations=0     --with_accuracy_layer=true    --use_analysis=true
```
```
I0622 08:32:15.652083 411584 sample_tester.cc:162] Model: resnet50_fp32/model/
I0622 08:32:15.652092 411584 sample_tester.cc:163] ====== num of threads: 1 ======
I0622 08:32:15.652096 411584 sample_tester.cc:164] ====== batch size: 1, iterations: 1000
I0622 08:32:15.652096 411584 sample_tester.cc:165] ====== batch latency: 50.0012ms, number of samples: 1000
I0622 08:32:15.652109 411584 sample_tester.cc:167] , sample latency: 50.0012ms, fps: 19.9995 ======
I0622 08:32:15.652285 411584 sample_tester.cc:309] Top1 accuracy: 0.7670
I0622 08:32:15.652299 411584 sample_tester.cc:311] Top5 accuracy: 0.9370
```

Resnet50 INT8
```
KMP_BLOCKTIME=1 KMP_AFFINITY=granularity=fine,compact,1,0 GLOG_logtostderr=1 ./build/sample_tester --infer_model=INT8     --infer_data=val_1000.bin     --batch_size=1     --num_threads=1     --iterations=0     --with_accuracy_layer=false    --use_analysis=true
```
```
I0622 08:33:34.907552 411585 sample_tester.cc:162] Model: INT8
I0622 08:33:34.907559 411585 sample_tester.cc:163] ====== num of threads: 1 ======
I0622 08:33:34.907562 411585 sample_tester.cc:164] ====== batch size: 1, iterations: 1000
I0622 08:33:34.907563 411585 sample_tester.cc:165] ====== batch latency: 13.4044ms, number of samples: 1000
I0622 08:33:34.907577 411585 sample_tester.cc:167] , sample latency: 13.4044ms, fps: 74.6022 ======
I0622 08:33:34.960709 411585 sample_tester.cc:309] Top1 accuracy: 0.7550
I0622 08:33:34.960731 411585 sample_tester.cc:311] Top5 accuracy: 0.9420
```

**Review by wozna — DISMISSED** [review]
I can confirm that this PR should not influence on performance for any other model running with EnableMkldnn only for this Resnet50 int8 model.
LGTM

**Review by jiangjiajun — DISMISSED** [review]
LGTM

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Pull request merged**
