### PR TITLE
Remove constraint that last dimension is forced to be 1 by adding lookup_table_v2

### PR DESCRIPTION
**Pull request by Aurelius84**
1. add `fluid.embedding` api.
2. move  `fluid.input.one_hot` into `fluid.one_hot`.
3.  zh doc PR：https://github.com/PaddlePaddle/FluidDoc/pull/1184

**before：**
+ the  last dimension of `input`  shape is  forced to be 1, such as shape `[batch_size, seq_len, 1]`, then the output shape of  `embedding` will be `[batch_size, seq_len, emb_size]`.
```python
import paddle.fluid as fluid

x = fluid.layers.data(name="x", shape=[1], dtype="int64")
emb = fluid.layers.embedding(input=x, size=[128, 100])

place = fluid.CPUPlace()
x_data = np.random.randint(0, 127,  [2, 20, 1]).astype("int64")
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
ret = exe.run(feed={ 'x': x_data}, 
              fetch_list=[emb], return_numpy=False)

# output shape: [2, 20, 100]
```

**after：**
+ **We remove constraint that last dimension is forced to be 1**   by add new api `fluid.embedding`.
+ The output shape will append `size[1]` at the back of `input` shape
```python
import paddle.fluid as fluid

x = fluid.layers.data(name="x", shape=[1], dtype="int64")
emb = fluid.embedding(input=x, size=[128, 100])    # new api

place = fluid.CPUPlace()
x_data = np.random.randint(0, 127,  [2, 20, 1]).astype("int64")
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
ret = exe.run(feed={ 'x': x_data}, 
              fetch_list=[emb], return_numpy=False)

# output shape: [2, 20, 1, 100]   
```

### CODE REVIEW

**Review by lanxianghit — DISMISSED** [review]
LGTM

**Review by phlrain — DISMISSED** [review]
LGTM

**Review by phlrain — APPROVED** [review]

**Review by luotao1 — APPROVED** [review]
LGTM for __init__.py

**Review by lanxianghit — APPROVED** [review]

**Review by heavengate — APPROVED** [review]
LG API

**Pull request merged**
