### PR TITLE
Changed hardcoded format to any in convolution and bumped MKL-DNN version to 0.17rc

### PR DESCRIPTION
**Pull request by kbinias**
This changes give huge performance boost on MobileNet-v1

### CODE REVIEW

**Comment by luotao1** [comment]
```
[11:34:19][Step 1/1] /paddle/build/third_party/mkldnn/src/extern_mkldnn/src/cpu/jit_uni_reorder_utils.cpp: In function ‘void mkldnn::impl::cpu::tr::prb_simplify(mkldnn::impl::cpu::tr::prb_t&)’:
[11:34:19][Step 1/1] /paddle/build/third_party/mkldnn/src/extern_mkldnn/src/cpu/jit_uni_reorder_utils.cpp:302:44: error: array subscript is above array bounds [-Werror=array-bounds]
[11:34:19][Step 1/1]                  p.nodes[j - 1] = p.nodes[j];
[11:34:19][Step 1/1]                                             ^
[11:34:19][Step 1/1] cc1plus: all warnings being treated as errors
[11:34:19][Step 1/1] make[5]: *** [src/CMakeFiles/mkldnn.dir/cpu/jit_uni_reorder_utils.cpp.o] Error 1
[11:34:19][Step 1/1] make[5]: *** Waiting for unfinished jobs....
```
http://ci.paddlepaddle.org/viewLog.html?buildId=27468&buildTypeId=Paddle_PrCiPython35&tab=buildLog&_focus=3066

**Review by mozga-intel — APPROVED** [review]
LGTM!

**Comment by luotao1** [comment]
@kbinias 
> This changes give huge performance boost on MobileNet-v1

How much performance boost after this PR for MobileNet-v1?

**Comment by kbinias** [comment]
On CPU 6148 optimized version is faster ~27 times (1 socket, 1 instance, batch 128), above 2 times (1 instance, 1 thread, batch 1). These are unofficial results, tested on my developer machine. I am waiting for final results from our validation team.

**Pull request merged**
