### PR TITLE
add MM_DNN inference test

### PR DESCRIPTION
**Pull request by luotao1**
add MM_DNN inference analyzer test

### CODE REVIEW

**Comment by yihuaxu** [comment]
When configured "test_all_data" as "true", it will show the below issue.

**Command:**
./paddle/fluid/inference/tests/api/test_analyzer_mm_dnn  --infer_model=third_party/inference_demo/mm_dnn/model --infer_data=third_party/inference_demo/mm_dnn/data.txt --gtest_filter=Analyzer_MM_DNN.profile --batch_size=1 --repeat=1  --test_all_data=true --num_threads=1 --profile

**Log:**
Note: Google Test filter = Analyzer_MM_DNN.profile
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Analyzer_MM_DNN
[ RUN      ] Analyzer_MM_DNN.profile
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1222 02:42:23.844923 205746 analyzer_mm_dnn_tester.cc:111] number of samples: 10000
*** Error in `./paddle/fluid/inference/tests/api/test_analyzer_mm_dnn': free(): invalid next size (fast): 0x000000000636aeb0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81499)[0x7efc9cc35499]
./paddle/fluid/inference/tests/api/test_analyzer_mm_dnn(_ZN6paddle9PaddleBuf4FreeEv+0x130)[0x3464d52]
./paddle/fluid/inference/tests/api/test_analyzer_mm_dnn(_ZN6paddle9PaddleBufD1Ev+0x18)[0x3421928]
./paddle/fluid/inference/tests/api/test_analyzer_mm_dnn(_ZN6paddle12PaddleTensorD2Ev+0x2c)[0x3421d96]
./paddle/fluid/inference/tests/api/test_analyzer_mm_dnn(_ZN6paddle9inference13PrepareInputsEPSt6vectorINS_12PaddleTensorESaIS2_EEPNS0_10DataRecordEi+0x40b)[0x341c430]
<~snip~>

**Comment by yihuaxu** [comment]
It seems that it crashed too when the batch size be not as 1

**Comment by luotao1** [comment]
@yihuaxu Thanks for your report, I fix it in https://github.com/PaddlePaddle/Paddle/pull/14998/commits/91408e3122de7d578ff69a3fa401e34297c21248.

**Review by tensor-tang — APPROVED** [review]
LGTM
data部分每个模型都有点重复，后期可以整理下。

**Comment by luotao1** [comment]
> data部分每个模型都有点重复，后期可以整理下

好的，后期看下如何简化。

**Pull request merged**
