### PR TITLE
【Hackathon 6th Fundable Projects 3 No.312-313、315】Remove fluid operator retinanet_detection_output etc

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others

### PR Types

Others

### Description

Remove fluid operator retinanet_detection_output etc
retinanet_detection_output
retinanet_target_assign
rpn_target_assign

### CODE REVIEW

**Comment by co63oc** [comment]
合入 https://github.com/PaddlePaddle/Paddle/pull/63501

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Comment by luotao1** [comment]
CheckPRTemplate 请补充完

**Comment by co63oc** [comment]
CheckPRTemplate 已修改

**Pull request merged**
