### PR TITLE
[CINN] check shape_or_data

### PR DESCRIPTION
**Pull request by crazyxiaoxi**
### PR Category
CINN

### PR Types
Bug fixes

### Description
Pcard-67164
修改shape_or_data的问题

### CODE REVIEW

**Review by gongshaotian — APPROVED** [review]
LGTM

**Comment by gongshaotian** [comment]
multiary有检查吗

**Comment by gongshaotian** [comment]
PR Category 改为CINN，PR Types改为 bug 修复

**Comment by crazyxiaoxi** [comment]
> multiary有检查吗

有在另一个pr

**Review by Hongqing-work — APPROVED** [review]

**Pull request merged**
