### PR TITLE
【Hackathon No.117】add parameter value for thresholded_relu

### PR DESCRIPTION
**Pull request by jinyouzhi**
### PR types

New features

### PR changes

APIs

### Description

add thresholded_relu to improve the use of ease
#57262

### CODE REVIEW

**Review by zhwesky2010 — COMMENTED** [review]
LGTM

**Comment by zhwesky2010** [comment]
@jinyouzhi coverage CI没过

**Comment by luotao1** [comment]
需要提交对应的中文文档

**Comment by jinyouzhi** [comment]
> @jinyouzhi coverage CI没过

感谢大佬评审，有关 CPU 的代码Coverage能够覆盖到吗？不太确定这里怎么修改，是要增加测试用例来覆盖吗？
image

**Comment by luotao1** [comment]
CPU 的代码Coverage能够覆盖到，是要增加测试用例来覆盖

**Pull request closed without merging**
