### PR TITLE
[Not for Merge]Internal Resnet50 benchmark test

### PR DESCRIPTION
**Pull request by bingyanghuang**
This is our internal branch ResNet50 optimization integration , you can use this branch to reproduce the latest MKLDNN ResNet50 performance. This PR is only for temporary test, not for merge.

Here is my benchmark.
Test Platform: Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
Environment Config: OMP_NUM_THREADS=1, unset KMP_AFFINITY, Enable Turbo boost
Command line: `./paddle/fluid/inference/tests/api/test_analyzer_image_classification --use_fake_data --infer_model=third_party/inference_demo/resnet50/model --iterations=100 --height=318 --width=318 --skip_batch_num=5 --batch_size=`
Test with MKL: `export FLAGS_use_mkldnn=False`
Test with MKLDNN: `export FLAGS_use_mkldnn=True`
Input image size: 318x318
image

### CODE REVIEW

**Comment by bingyanghuang** [comment]
@luotao1  This can reproduce our ResNet50 MKLDNN best performance.

**Comment by luotao1** [comment]
close due to all related PRs are merged

**Comment by luotao1** [comment]
close due to all related PRs are merged

**Comment by luotao1** [comment]
close due to all related PRs are merged

**Comment by luotao1** [comment]
close due to all related PRs are merged

**Comment by luotao1** [comment]
close due to all related PRs are merged

**Pull request closed without merging**
