### PR TITLE
clear fluid apis: fix apis in fleet and passes

### PR DESCRIPTION
**Pull request by isky-cd**
### PR types

Others
### PR changes

APIs
### Describe

fix apis in fleet and passes

### CODE REVIEW

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Comment by sneaxiy** [comment]
PR-CI-APPROVAL因修改了launch.py，但不影响launch相关的接口，请 @raindrops2sea review。
PR-CI-Static-Check因black工具修改了API的示例文档，请 @jzhang533 review。

**Review by jzhang533 — APPROVED** [review]
LGTM for docs change

**Review by raindrops2sea — APPROVED** [review]
LGTM

**Pull request merged**
