### PR TITLE
Support Tensor input with padding for warpctc op

### PR DESCRIPTION
**Pull request by vincentXiyu**
[1] As described in the title, warpctc_op.h and warpctc_op.cc are modified to support tensor inputs with padding.
[2] test_warpctc_op.py are modified to add unittests for warpctc op with tensor inputs.
[3] nn.py are modified to support tensor inputs with padding.

### CODE REVIEW

**Comment by vincentXiyu** [comment]
屏幕快照 2019-08-13 下午5 28 55

**Comment by vincentXiyu** [comment]
屏幕快照 2019-08-13 下午5 29 03

**Review by wanghaoshuang — DISMISSED** [review]

**Review by heavengate — DISMISSED** [review]
Please add pr comments

**Comment by vincentXiyu** [comment]
Modifying code examples for warpctc op in nn.py

**Comment by vincentXiyu** [comment]
modifying API.spec for warpctc op

**Review by heavengate — APPROVED** [review]

**Review by wanghaoshuang — APPROVED** [review]

**Pull request merged**
