### PR TITLE
add mkldnn int8 pass [step3]

### PR DESCRIPTION
**Pull request by baoachun**
### PR types
New features

### PR changes
Others

### Describe
新增 mkldnn int8 推理配置，https://github.com/PaddlePaddle/Paddle/pull/38643 的拆分

### CODE REVIEW

**Comment by baoachun** [comment]
split for https://github.com/PaddlePaddle/Paddle/pull/38643

@lidanqing-intel

**Review by XieYunshen — APPROVED** [review]
LGTM for 
`set_tests_properties(test_analyzer_quant2_mobilenetv1_mkldnn PROPERTIES TIMEOUT 120)
    set_tests_properties(test_analyzer_quant2_resnet50_channelwise_mkldnn PROPERTIES TIMEOUT 120)
`

**Review by wozna — APPROVED** [review]
LGTM

**Review by leiqing1 — APPROVED** [review]

**Review by leiqing1 — APPROVED** [review]

**Review by leiqing1 — APPROVED** [review]

**Review by leiqing1 — APPROVED** [review]

**Review by leiqing1 — APPROVED** [review]

**Review by Ligoml — APPROVED** [review]

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
