### PR TITLE
Disable test_dist_save_load

### LINKED ISSUE #14221: Disable test_dist_save_load

### PR DESCRIPTION
**Pull request by chengduoZH**
fix https://github.com/PaddlePaddle/Paddle/issues/14221

### CODE REVIEW

**Review by sneaxiy — APPROVED** [review]
cool

**Comment by panyx0718** [comment]
make sure there is a issue open for this

**Comment by chengduoZH** [comment]
This issue #14221 has been assigned to @seiriosPlus.

**Comment by panyx0718** [comment]
Thanks! In the future we can open icafe issues so that PM can track them.

**Pull request merged**
