### PR TITLE
[cherry-pick] Add unsigned int8 propagation

### PR DESCRIPTION
**Pull request by wozna**
### PR types

New features
### PR changes

Others 
### Describe

Cherry-pick from https://github.com/PaddlePaddle/Paddle/pull/46378

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Comment by yeliang2258** [comment]
@wozna  It seems that this PR is a duplicate of my PR：https://github.com/PaddlePaddle/Paddle/pull/47156

**Comment by wozna** [comment]
Duplicated with https://github.com/PaddlePaddle/Paddle/pull/47156

**Pull request closed without merging**
