### PR TITLE
Fix for gaussian random kernel

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Bug fixes

### PR changes
OPs

### Describe
Fix for gaussian random oneDNN kernel. Needed for md in tensor refactoring due to the limit of maximum 19 files changed in single PR.

### CODE REVIEW

**Comment by Silv3S** [comment]
LGTM

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@piotrekobi please review

**Review by piotrekobi — APPROVED** [review]
LGTM

**Comment by jakpiase** [comment]
@baoachun please review this PR

**Review by baoachun — APPROVED** [review]
LGTM

**Pull request merged**
