### PR TITLE
Avoid the string as the key of map to improve the jit performance

### LINKED ISSUE #21266: [CPU预测]chinese_ner预测性能下降
- 标题：[CPU预测]chinese_ner预测性能下降40%
- 版本、环境信息：
    1）PaddlePaddle版本：eec9c9cbe7e8
    2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz，使用MKL，未使用MKLDNN
    3）GPU：无
    4）系统环境：Ubuntu1604
    5）docker镜像：hub.baidubce.com/paddlepaddle/paddle:latest-dev 
-预测信息
    1）C++预测：eec9c9cbe7e8
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：自行编译

```shell
cmake .. \
  -DWITH_FLUID_ONLY=ON \
  -DWITH_SWIG_PY=OFF \
  -DWITH_PYTHON=ON \
  -DWITH_MKL=ON \
  -DWITH_GPU=ON \
  -DWITH_MKLDNN=OFF \
  -DON_INFER=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_INFERENCE_API_TEST=ON \
  -DWITH_TESTING=ON \                                                                                                             
  -DINFERENCE_DEMO_INSTALL_DIR=/root/.cache/inference_demo
```
- 复现信息：如为报错，请给出复现环境、复现步骤

直接执行`python chinese_ner_ce.py`即可得到速度指标
[codes.zip](https://github.com/PaddlePaddle/Paddle/files/3868946/codes.zip)

模型可以线下提供

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

continuous evaluation从该commit开始，速度下降较多
以前的预测速度：0.175 ms/record 左右
当前的预测速度：0.234 ms/record 左右

image

### PR DESCRIPTION
**Pull request by yihuaxu**
As the description of [Issue#21266](https://github.com/PaddlePaddle/Paddle/issues/21266), it shows that the performance of Chinese_NER will be degressive after fixed some TLS section issue. To avoid the string as the key can be helpful the performance.

resolve #21266

CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
Command：
```
   I. ./paddle/fluid/inference/tests/api/test_analyzer_ner --infer_model=third_party/inference_demo/chinese_ner/model --infer_data=third_party/inference_demo/chinese_ner/data.txt --gtest_filter=Analyzer_Chinese_ner.profile --batch_size=1 --repeat=2000 --num_threads=1 --test_all_data=true
   II. python chinese_ner_ce.py (changed repeat_times as 1000000 in chinese_ner_ce.py)
```
Tables:

I. Use Command I

Command   I |   |  
-- | -- | --
Mode | Latency(ms) | Percentage
Original | 0.0731486 | 0.00%
Fix TLS issue | 0.085967 | -17.52%
Improve   performance(unordered_map) | 0.0773406 | -5.73%
Improve   performance(map) | 0.0754822 | -3.19%

2. Use Command II with repeat_times=1000

Command   II |   |  
-- | -- | --
Mode | Latency(ms) | Percentage
Original | 0.09608269 | 0.00%
Fix TLS issue | 0.12087822 | -25.81%
Improve   performance(unordered_map) | 0.105142593 | -9.43%
Improve   performance(map) | 0.1039505 | -8.19%

3. Use Command II with repeat_times=1000000

Command   II |   |  
-- | -- | --
Mode | Latency(ms) | Percentage
Original | 0.10085106 | 0.00%
Fix TLS issue | 0.12207031 | -21.04%
Improve   performance(unordered_map) | 0.10585785 | -4.96%
Improve   performance(map) | 0.105142593 | -4.26%

### CODE REVIEW

**Comment by luotao1** [comment]
@LeoZhao-Intel @jianhang-liu Could you help review this PR, and do you have any suggestions about still ~5% down?

**Comment by LeoZhao-BJ** [comment]
LGTM

**Comment by luotao1** [comment]
@yihuaxu Please don't delete the benchmark data using `unordered_map`, then we can see the speedup from `unordered_map` to `map`.

**Comment by yihuaxu** [comment]
> @yihuaxu Please don't delete the benchmark data using `unordered_map`, then we can see the speedup from `unordered_map` to `map`

I have already added it.

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
