### PR TITLE
Fix the bug in sequence_scatter unitest

### PR DESCRIPTION
**Pull request by xyzhou-puck**
The computation of expected scores are not right in the previous uni test, but the op itself is fine. So I correct the unitest file.

### CODE REVIEW

**Comment by zhupengyang** [comment]
把[待修复名单](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/white_list/check_shape_white_list.py)里面的sequence_scatter也一起删掉吧

**Comment by xyzhou-puck** [comment]
> 把[待修复名单](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/white_list/check_shape_white_list.py)里面的sequence_scatter也一起删掉吧

done

**Comment by luotao1** [comment]
@xyzhou-puck @zhupengyang  多人修复check_shape_white_list.py，会引起冲突，要不 @zhupengyang 最后统一修改吧。

**Comment by zhupengyang** [comment]
> @xyzhou-puck @zhupengyang 多人修复check_shape_white_list.py，会引起冲突，要不 @zhupengyang 最后统一修改吧。

可以

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
