### PR TITLE
[PHI] Migrate elementwise_(add/mul) kernels

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Others

### PR changes
Others

### Describe
- migrate FWD elementwise kernels,
- remove fluid elementwise code.

### CODE REVIEW

**Comment by Silv3S** [comment]
There is problem with `elementwise_add int` kernel migrated to PHI, causing _test_analyzer_ernie_int8_ to drop accuracy and fail. _test_analyzer_ernie_int8_ has number of iterations set in _tester_helper.h_. If it's set to 1, same code is executed for both fluid and PHI version of this kernel. Unfortunately, if more iterations are executed, PHI kernel is producing incorrect values because attributes needed for calculations (`Scale_x`, `Scale_y` and `Scale_out`) are lost after first iteration.

That's because `ClearDnnAttrs` from https://github.com/PaddlePaddle/Paddle/pull/48364 is called. But without calling this method, problem is not fixed - last values which were set for each attribute in first iteration are saved and propagated to the end of this test.

Example for  `Scale_x` (`Scale_y` and `Scale_out` have same behavior)
| Iteration | `Scale_X` (nr)   | Fluid| PHI (with `ClearDnnAttrs`) | PHI (without `ClearDnnAttrs`) |
| --------- | ---------    | ---------    | -------------------               | ---------                          |
| 1         | 1            | 30.6755      | 30.6755                           | 30.6755                            |
| 1         | 2            | 31.5858      | 31.5858                           | 31.5858                            |
| 1         | ...          | ...          | ...                               | ...                                |
| 1         | 25           | 8.46045      | 8.46045                           | 8.46045                            |
| 1         | 26           | 27.6632      | 27.6632                           | 27.6632                            |
| 2         | 1            | 30.6755      | 1.0 (default, no attr found)      | 27.6632                            |
| 2         | 2            | 31.5858      | 1.0 (default, no attr found)      | 27.6632                            |
| 2         | ...          | ...          | ...     | ...                                |
| 2         | 25           | 8.46045      | 1.0 (default, no attr found)      | 27.6632                            |
| 2         | 26           | 27.6632      | 1.0 (default, no attr found)      | 27.6632                            |

Could you please help solve this issue? @YuanRisheng, @chenwhql

**Comment by YuanRisheng** [comment]
@Silv3S You can try delete `Scale_x`, `Scale_y` and `Scale_out` as shown in the picture. This code is in op_compat.yaml. If that doesn't work, maybe my logic is wrong and I will recur this issue on my machine and debug it. Thank you.
image

**Comment by Silv3S** [comment]
@YuanRisheng thank you for reply. Removing these attributes in _op_compat.yaml_ didn't change anything. Scales are still removed after first iteration.

**Comment by YuanRisheng** [comment]
I have fixed this problem, you can try again. Thank you

**Comment by YuanRisheng** [comment]
> @YuanRisheng thank you for reply. Removing these attributes in _op_compat.yaml_ didn't change anything. Scales are still removed after first iteration.

I have fixed this problem, you can try again. Thank you

**Comment by Silv3S** [comment]
@YuanRisheng thank you for solving this issue. I checked tests locally and everything works as expected now

**Comment by Silv3S** [comment]
@luotao1 could you please approve modifying `unity_build_rule.cmake`?

**Review by luotao1 — APPROVED** [review]
LGTM for unity_build_rule.cmake

**Review by YuanRisheng — APPROVED** [review]

**Pull request merged**
