### PR TITLE
Support CUDA Graph for partial graph in dygraph mode

### PR DESCRIPTION
**Pull request by sneaxiy**
### PR types
New features

### PR changes
APIs

### Describe
Support CUDA Graph for partial graph in dygraph mode.

### CODE REVIEW

**Review by FeixLiu — APPROVED** [review]
LGTM

**Review by zhiqiu — APPROVED** [review]
LGTM for allocator

**Review by chenwhql — APPROVED** [review]
LGTM for PADDLE_ENFORCE

**Review by Shixiaowei02 — APPROVED** [review]
The operator modification involved in this PR is limited to the dynamic mode.

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
