### PR TITLE
【fluid clean】remove fluid.dygraph.rnn.lstmcell and fluid.dygraph.rnn.grucell

### PR DESCRIPTION
**Pull request by lugimzzz**
### PR types
Others

### PR changes
 APIs 

### Describe
remove：
- fluid.dygraph.rnn.lstmcell
- fluid.dygraph.rnn.grucell

### CODE REVIEW

**Review by zhwesky2010 — DISMISSED** [review]
LGTM for del parallel_UT_rule.py

**Review by FrostML — APPROVED** [review]

**Review by zhwesky2010 — APPROVED** [review]
LGTM for change parallel_UT

**Review by momozi1996 — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by qingqing01 — APPROVED** [review]

**Pull request merged**
