### PR TITLE
Fix That conditional_block_op Doesn't Have InferShape

### PR DESCRIPTION
**Pull request by zhhsplendid**
The conditional_block_op doesn't have InferShape, which can cause an error in distributed PaddlePaddle reported from QA. The error log is:

image

As the log showed, conditional_block_op doesn't have InferShape. I added it and verified it can run now.

### CODE REVIEW

**Comment by luotao1** [comment]
Please paste the detail of errors.

**Comment by zhhsplendid** [comment]
> Please paste the detail of errors.

Done

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Review by lanxianghit — APPROVED** [review]
LGTM

**Pull request merged**
