### PR TITLE
make inference_anakin_test SERIAL

### LINKED ISSUE #12501: CI: inference_anakin_test error!
```
[09:12:38]	        Start  99: inference_anakin_test
[09:12:38]	 93/380 Test  #99: inference_anakin_test ...........................***Exception: Numerical  0.10 sec
[09:12:38]
```

http://ci.paddlepaddle.org/viewLog.html?buildId=3296&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tree&filter=all

### PR DESCRIPTION
**Pull request by luotao1**
fix #12501

### CODE REVIEW

**Comment by luotao1** [comment]
NEXT PRs:
- use Paddle's xybak third-party
- remove a lot of warning when compiling anakin source code
- support only-cpu environment for anakin
- add demo-ci for anakin

**Review by Superjomn — COMMENTED** [review]
LGTM

Does the manylinux release workflow need some change?

**Review by Superjomn — APPROVED** [review]
LGTM

Does the manylinux release workflow need some change?

**Comment by luotao1** [comment]
@Superjomn I will run a manylinux ci job at first.

**Pull request merged**
