### PR TITLE
fix infer_from_dataset and train_from_dataset

### PR DESCRIPTION
**Pull request by guru4elephant**

### CODE REVIEW

**Comment by guru4elephant** [comment]
image
image

**Comment by guru4elephant** [comment]
> _No description provided._

Fix API Example of Executor.train_from_dataset() and Executor.infer_from_dataset()

**Review by shanyi15 — DISMISSED** [review]
LGTM

**Comment by guru4elephant** [comment]
also, this pr fix the DataFeed read problem that multiple dimension tensor can be read and shape -1 can be inducted through real-time reading elem.

**Review by shanyi15 — APPROVED** [review]

**Review by chengduoZH — APPROVED** [review]

**Pull request merged**
