### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
### PR types
Others

### PR changes
Docs

### Describe
Updating Readme

### CODE REVIEW

**Comment by ghost** [comment]
PTAL @Superjomn @jczaja

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jzhang533** [comment]
Hi, @Ethanzjp 
Some CI has passed after I edited PR description and rebuilt CI.
But we still needs you to sign  [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=33704) , so we can make this PR ready to merge.

**Comment by Ethanzjp** [comment]
> Hi, @Ethanzjp
> Some CI has passed after I edited PR description and rebuilt CI.
> But we still needs you to sign [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=33704) , so we can make this PR ready to merge.
OK， LGTM

**Comment by ghost** [comment]
> Hi, @Ethanzjp
> Some CI has passed after I edited PR description and rebuilt CI.
> But we still needs you to sign [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=33704) , so we can make this PR ready to merge.

misoperation！Could you reopen and merge a pull request?  @jzhang533

**Comment by jzhang533** [comment]
Closed PR could not be reopened.
You'll need to create a new Pull Request from your local repo.

**Pull request closed without merging**
