### PR TITLE
oneDNN BatchNorm + Act fusion pass.

### PR DESCRIPTION
**Pull request by arogowie-intel**
### PR types
 New features 

### PR changes
Others

### Describe
This PR adds oneDNN pass for BatchNorm + Act function fusion. Currently only ReLU is supported as activation function. 

Performance improvement is around 2.8% - benchmarked on pvanet_ocr model using Xeon 6148 machine. Run with 40 threads.

| model | avg running time (s) | relative speedup |
| :---- | :---: | ---: |
| base fp32 | 0,473066 | 1x |
| optimized fp32 | 0,150530 | 3,143x |
| optimized fp32 & bn+act | 0,146477 | 1,028x |

### CODE REVIEW

**Comment by arogowie-intel** [comment]
@jczaja @wozna @wojtuss Please take a look and review.

**Comment by lidanqing-intel** [comment]
@arogowie-intel  It seems you did not add test=develop in the commit message?

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by arogowie-intel** [comment]
@luotao1 Could you please help. I see following error occur, although it is not related to my changes:
**PR-CI-Windows-OPENBLAS**: Line 5993: `2020-10-22 02:31:29 LINK : fatal error LNK1104: cannot open file 'C:\home\workspace\Paddle\build\paddle\fluid\pybind\Release\op_function_generator.exe' [C:\home\workspace\Paddle\build\paddle\fluid\pybind\op_function_generator.vcxproj]`

Moreover in **PR-CI-Coverage** and **PR-CI-Windows** i get `AssertionError: We only support 'data()' in static graph mode, please call 'paddle.enable_static()' to enter static graph mode.`, although I have called `enable_static()` [here](https://github.com/PaddlePaddle/Paddle/pull/27912/files?file-filters%5B%5D=.py#diff-79494115e39ea81574a84f205f62fa85fde34d4df6f0700f516c28bc6555930fR77)

Finally in PR-CI-Approval I see complaint about the usage of `PADDLE_ENFORCE*` macro in [these lines](https://github.com/PaddlePaddle/Paddle/pull/27912/files?file-filters%5B%5D=.cc&file-filters%5B%5D=.py#diff-3488827ba69a025855f524419332c3a1e5135a00265b1789be44953175a2efccR34-R37). I have specified the error type and provided clear, long description. Maybe this is a problem with formatting? However clang-format has passed.

**Comment by luotao1** [comment]
- PR-CI-Windows-OPENBLAS: you can rerun it, it's a random failure
- PR-CI-Coverage and PR-CI-Windows: Maybe you can refer to other unit-tests like `python/paddle/fluid/contrib/slim/tests/test_graph.py`
```
import paddle
import paddle.fluid as fluid
from paddle.fluid.framework import IrGraph
from paddle.fluid import core

paddle.enable_static()
...
```
- PR-CI-Approval: The check rule is not robust, I will approve it if other CIs all passed.

**Comment by arogowie-intel** [comment]
@luotao1 All CI-checks (except approval) passed. Could you review please?

**Review by wojtuss — APPROVED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
