### PR TITLE
support minus-int idx to LayerList

### PR DESCRIPTION
**Pull request by lyuwenyu**
### PR types

New features
### PR changes

APIs
### Describe

- support minux-idx for LayerList
- `__getitem__`
- ` __setitem__`
- `__del__`

#### Before
- getitem problem
- setitem problem 
> *will get surprising result here*

```
In [80]: mm = nn.LayerList([nn.Conv2D(2, 2, 2, 2), nn.Linear(10, 10)])

In [81]: mm[-1]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-81-0325fd583382> in <module>
----> 1 mm[-1]

~/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py in __getitem__(self, idx)
    218             return self.__class__(list(self._sub_layers.values())[idx])
    219         else:
--> 220             return self._sub_layers[str(idx)]
    221 
    222     def __setitem__(self, idx, sublayer):

KeyError: '-1'

In [82]: mm[-1] = nn.ReLU()

In [83]: mm
Out[83]: 
LayerList(
  (0): Conv2D(2, 2, kernel_size=[2, 2], stride=[2, 2], data_format=NCHW)
  (1): Linear(in_features=10, out_features=10, dtype=float32)
  (-1): ReLU()
)
```

#### After

```
In [74]: mm = LayerList([nn.Conv2D(2, 2, 2, 2), nn.Linear(10, 10), nn.ReLU()])

In [75]: mm[-1]
Out[75]: ReLU()

In [76]: mm[-1] = nn.Sigmoid()

In [77]: mm
Out[77]: 
LayerList(
  (0): Conv2D(2, 2, kernel_size=[2, 2], stride=[2, 2], data_format=NCHW)
  (1): Linear(in_features=10, out_features=10, dtype=float32)
  (2): Sigmoid()
)

In [78]: del mm[-1]

In [79]: mm
Out[79]: 
LayerList(
  (0): Conv2D(2, 2, kernel_size=[2, 2], stride=[2, 2], data_format=NCHW)
  (1): Linear(in_features=10, out_features=10, dtype=float32)
)

```

### CODE REVIEW

**Review by qingqing01 — DISMISSED** [review]
LGTM

**Review by qingqing01 — DISMISSED** [review]
LGTM. @phlrain Please help to look

**Review by heavengate — DISMISSED** [review]

**Review by qingqing01 — APPROVED** [review]

**Review by heavengate — APPROVED** [review]

**Review by saxon-zh — APPROVED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]
lgtm

**Pull request merged**
