### PR TITLE
[Clean Fluid] replace accuracy and auc

### PR DESCRIPTION
**Pull request by sljlp**
### PR types

New features
### PR changes

APIs
### Describe

- Remove fluid.layers.distributions and get_devices
- Replace fluid.metric_op.accuracy/auc with paddle.metric.accuracy/auc

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM 
单测删除

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Review by LiYuRio — APPROVED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by qingqing01 — APPROVED** [review]

**Review by raindrops2sea — APPROVED** [review]

**Pull request merged**
