### PR TITLE
[MLU] add exp and exp_grad kernel

### PR DESCRIPTION
**Pull request by zhaoying9105**
### PR types

New features 
### PR changes

OPs 
### Describe

add exp and exp_grad kernel for MLU

### CODE REVIEW

**Comment by Ivorfeng** [comment]
👍

**Review by ShawnNew — APPROVED** [review]
👍

**Comment by zhaoying9105** [comment]
测试报告：
exp_1
exp_2

**Review by qili93 — APPROVED** [review]
LGTM

**Pull request merged**
