### PR TITLE
[CHERRY-PICK] Fix for matmul_v2 6D x 2D oneDNN

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
Fix for matmul_v2. It is a cherry pick of #36342

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jakpiase** [comment]
@baoachun We need some of your teammates approval, because this branch is protected and our commiters have no write rights to this branch

**Comment by baoachun** [comment]
> @baoachun We need some of your teammates approval, because this branch is protected and our commiters have no write rights to this branch

Got it. Thanks a lot.

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
