### PR TITLE
[Typing][A-37,A-38] Add type annotations for `paddle/optimizer/{adadelta,adagrad}.py`

### PR DESCRIPTION
**Pull request by ooooo-create**
### PR Category

User Experience

### PR Types

Improvements

### Description

类型标注：

- paddle/optimizer/adadelta.py
- paddle/optimizer/adagrad.py

### Related links
 
- https://github.com/PaddlePaddle/Paddle/issues/65008

@SigureMo @megemini

### CODE REVIEW

**Review by SigureMo — DISMISSED** [review]
LGTMeow

**Review by SigureMo — APPROVED** [review]

**Comment by SigureMo** [comment]
doc preview 怎么挂了呢？rerun 过还是挂了

**Comment by ooooo-create** [comment]
> doc preview 怎么挂了呢？rerun 过还是挂了

是格式错误吗
```
************************************************************************************
2024-06-26 11:03:30 Your PR code style check failed.
2024-06-26 11:03:30 Please install pre-commit locally and set up git hook scripts:
2024-06-26 11:03:30 
2024-06-26 11:03:30     pip install pre-commit==2.17.0
2024-06-26 11:03:30     pre-commit install
2024-06-26 11:03:30 
2024-06-26 11:03:30 Then, run pre-commit to check codestyle issues in your PR:
2024-06-26 11:03:30 
2024-06-26 11:03:30     pre-commit run --files
2024-06-26 11:03:30 
2024-06-26 11:03:30 For more information, please refer to our codestyle check guide:
2024-06-26 11:03:30 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/codestyle_check_guide_cn.html
```

**Comment by ooooo-create** [comment]
不是 git 仓库 好像是
```
Checking code style by pre-commit ...
2024-06-26 11:03:30 An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

**Pull request merged**
