### PR TITLE
Add broadcast operators

### PR DESCRIPTION
**Pull request by chengduoZH**
Demo: https://gist.github.com/chengduoZH/1a34d84c0672a46984bd17c16b6d9dd7 
This PR adds broadcast for multi-process. And it could be used in dynamic graph to broadcast parameters.

### CODE REVIEW

**Review by JiabinYang — COMMENTED** [review]
can we have an unit test here?

**Comment by chengduoZH** [comment]
> can we have an unit test here?

There have two unit tests for dynamic graph training by multi-process, i.e. test_parallel_dygraph_mnist.py, test_parallel_dygraph_se_resnext.py

**Comment by luotao1** [comment]
> test_parallel_dygraph_mnist.py, test_parallel_dygraph_se_resnext.py

These tests are model-level, should we add op-level tests?

**Comment by chengduoZH** [comment]
@luotao1 We found that the unit test of ncclBroadcast is random failed, and this is the issue https://github.com/PaddlePaddle/Paddle/issues/9540, I will analysis the reason and add a unit test in next PR.

**Review by JiabinYang — APPROVED** [review]
LGTM

**Pull request merged**
