### PR TITLE
[PIR] Support int/float/double for Operator Override

### PR DESCRIPTION
**Pull request by Aurelius84**
### PR types

Others
### PR changes

APIs
### Description

Pcard-67164

### CODE REVIEW

**Comment by cyber-pioneer** [comment]
How about symbol "+=", "-=", "-x" ?

**Comment by Aurelius84** [comment]
> How about symbol "+=", "-=", "-x" ?

已经作为「开源热身赛」即将放出去

**Comment by 0x45f** [comment]
> > How about symbol "+=", "-=", "-x" ?
> 
> 已经作为「开源热身赛」即将放出去

为什么将类似__add__方法patch的代码放在了C++端呢？之前patch的代码应该都在python端吧，而且后续类似shape、reshape等方法的patch应该也在python端吧

**Review by 0x45f — APPROVED** [review]
LGTM，后续会将patch的逻辑移到python端

**Pull request merged**
