### PR TITLE
Add the ipipe log param prefix

### PR DESCRIPTION
**Pull request by wadefelix**
### PR types
Others

### PR changes
Others

### Describe
CI指标收集方式跟随日志切分系统变更

### CODE REVIEW

**Review by lelelelelez — COMMENTED** [review]
paddle_build.sh中还缺少：`ccache hit rate` 
paddle_build.bat中还缺少：`Windows build cache`,  `clcache hit rate`

**Comment by wadefelix** [comment]
> paddle_build.sh中还缺少：`ccache hit rate`
> paddle_build.bat中还缺少：`Windows build cache`, `clcache hit rate`

**Comment by wadefelix** [comment]
> paddle_build.sh中还缺少：`ccache hit rate`
> paddle_build.bat中还缺少：`Windows build cache`, `clcache hit rate`

done

**Review by lelelelelez — APPROVED** [review]
LGTM

**Review by zhwesky2010 — APPROVED** [review]
LGTM

**Pull request merged**
