### PR TITLE
[Cherry-pick] Collective communication APIs

### PR DESCRIPTION
**Pull request by HermitSun**
### PR types

New features

### PR changes

APIs

### Describe

Cherry-pick from the following PRs, including bf16 dtype support for collective ops, new stream APIs and some bug fixes:
- https://github.com/PaddlePaddle/Paddle/pull/45844
- https://github.com/PaddlePaddle/Paddle/pull/45848
- https://github.com/PaddlePaddle/Paddle/pull/46023
- https://github.com/PaddlePaddle/Paddle/pull/46295
- https://github.com/PaddlePaddle/Paddle/pull/46761
- https://github.com/PaddlePaddle/Paddle/pull/46962

Related docs: https://github.com/PaddlePaddle/docs/pull/5237

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM 单测时间设置

**Review by jzhang533 — COMMENTED** [review]
for testcase, Please use `np.testing.assert_allclose` in future PRs.
see: https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/code_style_improvement_for_unittest.md

**Review by jzhang533 — APPROVED** [review]
not reviewed this PR thoroughly.
given a +1 to help it pass CI check, after offline discussion.

**Review by LiYuRio — APPROVED** [review]
LGTM, this is a set of cherry-pick prs for 2.4, all comments are modified in origin pr of develop branch before cherry-pick here.

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
