### PR TITLE
[Don't merge]:Test most updated NVIDIA docker

### PR DESCRIPTION
**Pull request by tonyyang-svail**
Update base nvidia docker from `nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04` to `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`.

This is necessary if we need to take full advantage of Volta.

### CODE REVIEW

**Comment by Yancey1989** [comment]
CI build failed with logs
```bash
nvidia-docker | 2017/11/29 10:51:38 Error: unsupported CUDA version: driver 8.0 < image 9.0.176
```

Since https://github.com/NVIDIA/nvidia-docker/issues/497, we need to upgrade the Nvidia Driver to 384.81 or later on the host which the teamCity deployed.

**Comment by tonyyang-svail** [comment]
@Yancey1989 Yesterday, I have manually updated the driver version of 172.19.32.166. It successfully compiled (with tons of Eigen warnings), but failed on one of the tests. You can find the logs here. (https://paddleci.ngrok.io/viewLog.html?tab=buildLog&buildTypeId=Paddle_PrCi&buildId=19791)

**Comment by Yancey1989** [comment]
Another problem, `cmake` detect the invalid `CUDA_VERSION`
```bash
-- Paddle version is 0.10.0
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61
```

**Comment by tonyyang-svail** [comment]
@Yancey1989 Could you be more specific on this? I can't reproduce it on my machine.

**Comment by Yancey1989** [comment]
Hi @tonyyang-svail , I saw @wanghaoshuang Fixed the failed unit test, could you update the code to the latest and rerun the test?

**Comment by luotao1** [comment]
Close due to this PR is a temporary test.

**Pull request closed without merging**
