### PR TITLE
cherry-pick: add kron op (#24105)

### PR DESCRIPTION
**Pull request by iclementine**
1. add kron op;
2. add kron in fluid.layers.tensor;
3. add kron in paddle.complex.tensor.math.

### CODE REVIEW

**Review by kuke — APPROVED** [review]
LGTM

**Review by zhangting2020 — APPROVED** [review]
LGTM

**Review by zhhsplendid — APPROVED** [review]
approve for ShareDataWith

**Review by swtkiwi — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]

**Pull request merged**
