### PR TITLE
Polish documentation

### PR DESCRIPTION
**Pull request by reyoung**
* [row_conv](http://ali.reyoung.me:40080/api_reference/layers.html#row-conv)
* [uniform_random](http://ali.reyoung.me:40080/api_reference/layers.html#uniform-random)
* [layer_norm](http://ali.reyoung.me:40080/api_reference/layers.html#layer-norm)
* [create_parameter](http://ali.reyoung.me:40080/api_reference/layers.html#create-parameter)
* [hard_shrink](http://ali.reyoung.me:40080/api_reference/layers.html#hard-shrink)
* [ssd_loss](http://ali.reyoung.me:40080/api_reference/layers.html#ssd-loss)
* [multiplex](http://ali.reyoung.me:40080/api_reference/layers.html#multiplex)
* [less_than](http://ali.reyoung.me:40080/api_reference/layers.html#less-than)
* [open_recordio_file](http://ali.reyoung.me:40080/api_reference/layers.html#open-recordio-file)
* [cumsum](http://ali.reyoung.me:40080/api_reference/layers.html#cumsum)
* [DynamicRNN](http://ali.reyoung.me:40080/api_reference/layers.html#dynamicrnn)
* [shrink_memory](http://ali.reyoung.me:40080/api_reference/layers.html#shrink-memory)
* [double_buffer](http://ali.reyoung.me:40080/api_reference/layers.html#double-buffer)
* [thresholded_relu](http://ali.reyoung.me:40080/api_reference/layers.html#thresholded-relu)
* [bipartite_match](http://ali.reyoung.me:40080/api_reference/layers.html#bipartite-match)

### CODE REVIEW

**Comment by reyoung** [comment]
@skylarch Please review the polishment of APIs.

**Review by skylarch — CHANGES_REQUESTED** [review]
@reyoung 

	1. API Definition：
	2. Function Description
		a. Function Description：
			i. 缺少标题：layer_norm, create_parameter, multiplex, open_recordio_file, cumsum
			ii. 标题除介词外首字母大写，无句号，加粗：row_conv, uniform_random, hard_shrink, ssd_loss, less_than
		○ Formula：(如果有API没有formula，可不做修改）row_conv的生成有点问题, ssd_loss, open_recordio_file
		○ Symbols' Descriptions if necessary：
		○ References if necessary：
	• Args Description：生成的是中文，改为英文
		○ [Arg’s Name]：
		○ [(Data Type, Default Value)]：缺default：row_conv, layer_norm, create_parameter,  open_recordio_file
		○ [Description]：
	• Returns：生成的是中文，改为英文; open_recordio_file’返回类型‘可标在‘返回’里
		○ [Name][Shape]：cumsum不需首字母大写
		○ Tuple逐个介绍各参数：
	• Raises
		○ [Exception Type][Condition]：
	• Note分条列出：
	• Examples：

**Comment by skylarch** [comment]
@reyoung 
comment已根据最新标准更新，可以开始做修改。

		a. Function Description标题：
			i. 缺少：cumsum
			ii. 多余：less_than 
		○ Formula：(如果有API没有formula，可不做修改）multiplex "For i-th row of the output tensor"后的公式生成错误

**Comment by reyoung** [comment]
@skylarch  Done and add more documentation ^v^

**Comment by skylarch** [comment]
DynamicRNN:
例子的格式和其他API例子不统一
lod_tensor最好用超链接
screen shot 2018-06-15 at 11 34 56 am

shrink_memory
如果有相关文档，DynamicRNN的implementation可用超链接
screen shot 2018-06-15 at 11 38 36 am


cumsum:
缺标题

**Review by skylarch — APPROVED** [review]

**Pull request merged**
