### PR TITLE
fleet backend supports npu hccl

### PR DESCRIPTION
**Pull request by Aganlengzi**
### PR types
Others

### PR changes
Others

### Describe
NPU has supported HCCL backend in https://github.com/PaddlePaddle/Paddle/pull/36285
On NPU device, launch fails because backend is set to 'unknown', this PR supports hccl selection. 
```
python3 -m paddle.distributed.fleet.launch --run_mode=collective tools/train.py -c ppcls/configs/ImageNet/ResNet/ResNet50_vd.yaml -o Arch.pretrained=False -o Global.device=npu
```
before:
image
after:
image

add `--backend=hccl` also works fine.

### CODE REVIEW

**Review by qili93 — APPROVED** [review]
LGTM

**Comment by ronny1996** [comment]
LGTM

**Review by ronny1996 — APPROVED** [review]

**Comment by Aganlengzi** [comment]
PR https://github.com/PaddlePaddle/Paddle/pull/37613 includes the function.

**Pull request closed without merging**
