### PR TITLE
[Cherry-Pick][Dy2St]Get grad names when call append backward to fix high order gradient(#53250)

### PR DESCRIPTION
**Pull request by Aurelius84**
### PR types

Bug fixes
### PR changes

APIs
### Description

PCard-66972
[Dy2St]Get grad names when call append backward to fix high order gradient(#53250)

前置PR：https://github.com/PaddlePaddle/Paddle/pull/53494

### CODE REVIEW

**Review by 0x45f — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by Xreki — APPROVED** [review]
LGTM for max_relative_error

**Review by qingqing01 — APPROVED** [review]

**Review by wanghuancoder — COMMENTED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Pull request merged**
