### PR TITLE
add increment op to ngraph engine

### PR DESCRIPTION
**Pull request by sfvaroglu**
This PR adds increment op to the Intel nGraph engine.

### CODE REVIEW

**Comment by luotao1** [comment]
Please add detail description.

**Comment by mozga-intel** [comment]
@luotao1, @tensor-tang Can you please merge or continue the review and comment this pull-request?

**Comment by baojun-nervana** [comment]
@tensor-tang @luotao1 Can you look at this PR?

**Review by tensor-tang — APPROVED** [review]
LGTM

**Pull request merged**
