### PR TITLE
Add loss conversion from uint16 to float in ProgressBar class

### PR DESCRIPTION
**Pull request by ghost**
### PR types
Others
### PR changes
Others

### Describe
Enables correct printing of loss by the ProgressBar class when the datatype of loss is uint16.

### CODE REVIEW

**Review by arlesniak — DISMISSED** [review]
LGTM

**Review by jakpiase — DISMISSED** [review]
LGTM

**Review by arlesniak — APPROVED** [review]
LGTM

**Review by jczaja — APPROVED** [review]
LGTM

**Review by jakpiase — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@Aganlengzi

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
