### PR TITLE
[Unify Tensors PR #5] framework::Tensor inherits from DenseTensor,test=allcases

### PR DESCRIPTION
**Pull request by jim19930609**
### PR types
New features

### PR changes
Others

### Describe
Previous works on constructing new tensor library "pten" introduced another Tensor type namely "DenseTensor", which temporarily co-exists with framework::Tensor and LoDTensor. In this series of PRs, we attempt to replace legacy "framework::Tensor and LoDTensor" by the newly implemented "DenseTensor", so as to facilitate the progress of "pten" joining original framework.

In this PR, we moved nearly all the members and interfaces from framework::Tensor to pten::DenseTensor, and then asked framework::Tensor to inherit from pten::DenseTensor. Note that interfaces (Split, Chunk, Slice, ...) with "framework::Tensor" as return will remain on framework::Tensor for now. 

After this patch, all the original access to framework::Tensor interfaces will be re-routed
 to accessing the corresponding interfaces on pten::DenseTensor, whereas framework::Tensor will become a simple wrapper that almost holds nothing.

image

### CODE REVIEW

**Review by chenwhql — APPROVED** [review]
LGTM

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by Shixiaowei02 — APPROVED** [review]

**Comment by raindrops2sea** [comment]
> ### Describe
Please describe the reasons behind the change more clearly.

**Comment by raindrops2sea** [comment]
> ### Describe
Please describe the reason behind the change more clearly.

**Review by raindrops2sea — APPROVED** [review]

**Review by zhiqiu — APPROVED** [review]
LGTM

**Pull request merged**
