### PR TITLE
[oneDNN] Port to release/2.0 of Making ThreadID info in caching key optional (#29272)

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Performance optimization

### PR changes
Others

### Describe
This is a backport from developer to release/2.0 of PR https://github.com/PaddlePaddle/Paddle/pull/29272

This PR is fixing performance regression (10% on inference of mobilenet_v1 int8 , C-API) that was introduced in:
https://github.com/PaddlePaddle/Paddle/pull/28758 (Fix to #28459).

### CODE REVIEW

**Review by wojtuss — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
@jczaja @lidanqing-intel Since merging to release/2.0 is very strict, could you update more performance details in the PR description? I remember that dygraph training on mobilenet-v1 /v2 will be faster 10% using this PR?

**Comment by jczaja** [comment]
@luotao1 I have updated description of this PR (last two lines) with a reason why this PR is needed in 2.0

**Comment by luotao1** [comment]
Please solve the conflict

**Comment by jczaja** [comment]
@arlesniak I have resolved conflict with your changes. Could you please take a look ?

**Review by arlesniak — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 I have resolved conflict. Please start your review

**Review by luotao1 — APPROVED** [review]

**Comment by jczaja** [comment]
@luotao1 Do you need any more information on that PR ?

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
