### PR TITLE
[MLU] set_value performance optimizing

### PR DESCRIPTION
**Pull request by fuyou765**
### PR types
 Performance optimization 

### PR changes
 OPs

### Describe
Performance optimization for set_value

### CODE REVIEW

**Review by ShawnNew — CHANGES_REQUESTED** [review]
加一下瓶颈case的测例

**Comment by Ivorfeng** [comment]
👍 ,顺便贴下测试报告

**Comment by fuyou765** [comment]
operation time test report:
image

**Comment by fuyou765** [comment]
operation time test report:
image

**Review by ronny1996 — APPROVED** [review]
LGTM

**Review by qili93 — APPROVED** [review]
LGTM

**Pull request merged**
