### PR TITLE
[XPU] use np.testing.assert_allclose instead of assertTrue(np.allclose(...)), test=kunlun

### PR DESCRIPTION
**Pull request by ronny1996**
### PR types

Others
### PR changes

Others
### Describe

 use np.testing.assert_allclose instead of assertTrue(np.allclose(...))
https://github.com/PaddlePaddle/Paddle/issues/44641

### CODE REVIEW

**Review by qili93 — DISMISSED** [review]
LGTM

**Review by XiaociZhang — CHANGES_REQUESTED** [review]
test_assign_value_op_xpu.py，test_matmul_op_xpu.py，test_fleet_exe_dist_model_run_xpu.py这几个麻烦也一起改掉吧

**Review by qili93 — APPROVED** [review]
LGTM

**Review by XiaociZhang — APPROVED** [review]
lgtm

**Pull request merged**
