### PR TITLE
remove isfinite and has_nan from fluid

### PR DESCRIPTION
**Pull request by ccrrong**
### PR types

Others

### PR changes

APIs

### Describe

To clean the code in paddle.fluid, the useless codes should be removed and code still be used should move to a new position.

For function paddle.fluid.layers.tensor.has_nan and paddle.fluid.layers.tensor.isfinite, since it is not used in version 2.x, should be removed.

### CODE REVIEW

**Review by heavengate — DISMISSED** [review]

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by jzhang533 — DISMISSED** [review]
LGTM for cleaning codes in `python/paddle/fluid/layers/tensor.py`
not reviewed changes to unitests

**Review by heavengate — APPROVED** [review]

**Review by jzhang533 — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
