### PR TITLE
enable check_dygraph for mkldnn activation tests

### PR DESCRIPTION
**Pull request by sfraczek**
### PR types
New features

### PR changes
Others

### Describe
Enable tests in dygraph mode for mkldnn activation ops. Override of `test_check_output` and `test_check_grad` is no longer needed.
It depends on other dygraph pull requests.

### CODE REVIEW

**Review by wojtuss — DISMISSED** [review]

**Comment by lidanqing-vv** [comment]
@luotao1  Could you please help download PR_Windows_CI_OPENBLAS (Paddle Windows)  now the old method does not work. Thanks a lot

**Comment by luotao1** [comment]
[Paddle_Windows_PR_Windows_CI_OPENBLAS_6706.log](https://github.com/PaddlePaddle/Paddle/files/5033795/Paddle_Windows_PR_Windows_CI_OPENBLAS_6706.log)
It seems random fail, I rerun it.

**Comment by grygielski** [comment]
@luotao1 What about now, is it random fail again?

**Comment by luotao1** [comment]
I rerun again, the random build error of this windows machine is high than others.

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
