### PR TITLE
add linspace op

### LINKED ISSUE #16431: [Operator] add linspace op
test=develop
linspace generates evenly spaced numbers in an interval, like the np.linspace.

### PR DESCRIPTION
**Pull request by zhoukunsheng**
resolve #16431

### CODE REVIEW

**Comment by zhoukunsheng** [comment]
image

**Comment by shanyi15** [comment]
image

**Comment by zhoukunsheng** [comment]
image
thanks for pointing out.

**Review by XiaoguangHu01 — APPROVED** [review]

**Review by shanyi15 — APPROVED** [review]
LG comments

**Pull request merged**
