### PR TITLE
Put_along_axis (based on PR #37921 by Xu Huang)

### PR DESCRIPTION
**Pull request by zhhsplendid**
### PR types

New features
### PR changes

APIs
### Describe

Paddle new APIs: put_along_axis.

Xu Huang is on holiday so we created this PR to work on it. It is based on his PR: https://github.com/PaddlePaddle/Paddle/pull/37921

API screenshot:
image

3a2a59b76efe2fd7e6f2ec3ff76c5995

image

### CODE REVIEW

**Review by iclementine — DISMISSED** [review]
LGTM for new changes~

**Review by dingjiaweiww — DISMISSED** [review]

**Review by iclementine — APPROVED** [review]
LGTM

**Review by Ligoml — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]

**Review by chenwhql — APPROVED** [review]
LGTM for PADDLE_ENFORCE

**Pull request merged**
