### PR TITLE
Revert "Add bfloat16 data type"

### PR DESCRIPTION
**Pull request by luotao1**
### PR types
Others

### PR changes
 Others

### Describe
Reverts PaddlePaddle/Paddle#25402

[Liunx_nightbuild_python36_474.log](https://github.com/PaddlePaddle/Paddle/files/5166931/Liunx_nightbuild_python36_474.log)
图片
Maybe it is related with GCC version. The GCC version in log is 4.8.5

### CODE REVIEW

**Comment by luotao1** [comment]
@wozna @lidanqing-intel Please fix the compile error in gcc4.8.5

**Comment by luotao1** [comment]
```
保存 “block.txt” [83/83])

2020-09-03 15:39:14 ****************

2020-09-03 15:39:14 0. The error message you wrote in PADDLE_ENFORCE{_**} or PADDLE_THROW does not meet our error message writing specification. Possible errors include 1. the error message is empty / 2. the error message is too short / 3. the error type is not specified. Please read the specification [ https://github.com/PaddlePaddle/Paddle/wiki/Paddle-Error-Message-Writing-Specification ], then refine the error message. If it is a mismatch, please request chenwhql (Recommend), luotao1 or lanxianghit review and approve.

2020-09-03 15:39:14 The PADDLE_ENFORCE{_**} or PADDLE_THROW entries that do not meet the specification are as follows:

2020-09-03 15:39:14 PADDLE_THROW("Unknown data type");
```

**Review by chenwhql — APPROVED** [review]
LGTM to PADDLE_ENFORCE

**Comment by luotao1** [comment]
@wozna @lidanqing-intel fixed PR in https://github.com/PaddlePaddle/Paddle/pull/26985 by @iclementine

**Comment by luotao1** [comment]
@wozna @lidanqing-intel fixed PR in https://github.com/PaddlePaddle/Paddle/pull/26985 by @iclementine

**Comment by luotao1** [comment]
@wozna @lidanqing-intel fixed PR in https://github.com/PaddlePaddle/Paddle/pull/26985 by @iclementine

**Pull request closed without merging**
