### PR TITLE
rename qat into quant in filenames only

### PR DESCRIPTION
**Pull request by wojtuss**
### PR types
Others

### PR changes
Others

### Describe
This patch changes `qat` into `quant` in filenames, with necessary updates only.
Updates in the contents of the files will come in another PR (see https://github.com/PaddlePaddle/Paddle/pull/24948).

### CODE REVIEW

**Review by luotao1 — APPROVED** [review]

**Comment by lidanqing-vv** [comment]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
Hi, @luotao1  The PR-CI-Coverage failed because deleted tests. Please approve then it should pass. Other CIs are also about approvals

```
2020-06-24 21:57:49 current pr 25194 got approvals: FALSE
2020-06-24 21:57:49 ************************************
2020-06-24 21:57:49 It is forbidden to disable or delete the unit-test.
2020-06-24 21:57:49 
2020-06-24 21:57:49 If you must delete it temporarily, please add it to[https://github.com/PaddlePaddle/Paddle/wiki/Temporarily-disabled-Unit-Test].
2020-06-24 21:57:49 Then you must have one RD (kolinwei(recommended) or zhouwei25) approval for the deletion of unit-test. 
2020-06-24 21:57:49 
2020-06-24 21:57:49 If you have any problems about deleting unit-test, please read the specification [https://github.com/PaddlePaddle/Paddle/wiki/Deleting-unit-test-is-forbidden]. 
2020-06-24 21:57:49 
2020-06-24 21:57:49 Following unit-tests are deleted in this PR: 
2020-06-24 21:57:49  -  test_qat2_int8_mkldnn_pass 
```

**Review by arlesniak — APPROVED** [review]
LGTM

**Review by kolinwei — APPROVED** [review]

**Comment by luotao1** [comment]
```
[12:00:48][Step 1/1] ****************
[12:00:48][Step 1/1] 0. You must have Dianhai approval for change 20+ files or add than 1000+ lines of content.
[12:00:48][Step 1/1] 
[12:00:48][Step 1/1] There are 1 approved errors.
[12:00:48][Step 1/1] ****************
```

**Review by raindrops2sea — APPROVED** [review]
LGTM

**Pull request merged**
