### PR TITLE
Fix for oneDNN layernorm for begin_norm_axis != last_dim

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Bug fixes

### PR changes
OPs

### Describe
Fix for oneDNN layernorm for begin_norm_axis != last_dim

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@piotrekobi please help with review

**Review by piotrekobi — APPROVED** [review]
LGTM but can you explain why @OpTestTool.skip_if_not_cpu_bf16() is required?

**Comment by jakpiase** [comment]
@piotrekobi because this test calls native kernel inside bf16 test file and native kernel doesn't have a kernel for this datatype

**Pull request merged**
