### PR TITLE
[KP] Activation op registration for XPU2. part 1/2

### PR DESCRIPTION
**Pull request by AshburnLee**
### PR types

New features
### PR changes

OPs
## Function
Add 26/48 activation op registration for the support of XPU2. Part 2 will be added in the next PR.

## Result
8 existing tested OPs and the executing device:

截屏2022-03-01 18 27 05
截屏2022-03-01 18 27 52
截屏2022-03-01 18 28 13
截屏2022-03-01 18 28 32
截屏2022-03-01 18 28 53
截屏2022-03-01 18 29 17
截屏2022-03-01 18 29 37
截屏2022-03-01 18 33 20
截屏2022-03-01 18 30 19

- The keyword 'using XPU KP kernel' indicates that this op is running on XPU with KP library, which is expected. 
- Only float is supported on XPU by now
- Export XPU_KPWHITE_LIST before running unittest: `export XPU_KPWHITE_LIST=leaky_relu,sigmoid,relu,exp,log,reciprocal,softplus,hard_swish`

### CODE REVIEW

**Review by Liu-xiandong — COMMENTED** [review]
因为现在还没有CI，所以需要麻烦一下，把本地相关单测的结果也贴一下，然后需要保证OP的kernel用的是KP的kernel

**Comment by AshburnLee** [comment]
> 因为现在还没有CI，所以需要麻烦一下，把本地相关单测的结果也贴一下，然后需要保证OP的kernel用的是KP的kernel

Done，见PR描述

**Review by Liu-xiandong — APPROVED** [review]
LGTM

**Review by AnnaTrainingG — APPROVED** [review]
LGTM

**Review by xingfeng01 — APPROVED** [review]

**Pull request merged**
