### PR TITLE
更改 cross_entropy2 和 grad 名字与其它OP一致

### PR DESCRIPTION
**Pull request by louisfeng**
主要更改名字和其它OP一致，比如`transpose2`:
https://github.com/PaddlePaddle/Paddle/blob/20f18930ae463f4eba1f8c0b682fb7db5ddbce33/paddle/fluid/operators/transpose_op.cc#L287-L289

这样所有OP的grad都有`_grad`作为后缀。

### CODE REVIEW

**Comment by baojun-nervana** [comment]
@louisfeng Please add "test=develop" to commit to enable CI and please sign the CLA

**Comment by louisfeng** [comment]
> @louisfeng Please add "test=develop" to commit to enable CI and please sign the CLA

Thanks, I have added "test=develop" to commit message and signed the CLA.

**Comment by louisfeng** [comment]
I have ran locally to make sure the grad op is tested in `test_cross_entropy2_op.py` and it did run the renamed grad op and passed the test. So I think the failure of the coverage test is a false positive (i.e. test coverage already exists). Could the PaddlePaddle team please take a look? Thanks.

**Comment by louisfeng** [comment]
I have added debug messages in the renamed C++ code path and ran the python unit test and these messages are printed out, so they should have coverage. Please verify the CI coverage is collecting the right data. I will close this PR for now. @baojun-nervana will make a new submission once the tests are fixed. Thanks!

**Pull request closed without merging**
