### PR TITLE
Enable int8v2 and qat resnet101 vgg16, vgg19 UT on 6148

### PR DESCRIPTION
**Pull request by lidanqing-intel**
Check the vgg16, vgg19 time out problems in 6148 machines
related to #21700

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@luotao1 Can you please run this on 6148？ For vgg16 and vgg19 time out problems. Thanks

**Comment by lidanqing-vv** [comment]
Hi @tianshuo78520a  Could you please take this PR and run it on 6148 and send me link? (I will rerun if any problems). It's for vgg16 and vgg19 time out issues. Thank you a lot.

**Comment by luotao1** [comment]
@lidanqing-intel You can rerun it yourself.

**Comment by lidanqing-vv** [comment]
> @lidanqing-intel You can rerun it yourself.

I reopened #21802 and change code and rerun there.

**Comment by lidanqing-vv** [comment]
After enabling resnet101, vgg16, vgg19. All **int8v2 and qat tests passed** on 6148. Log is http://ci.paddlepaddle.org/viewLog.html?buildId=264853&buildTypeId=Paddle_PaddleManylinux_PrCiManylinuxCoverageCpu&tab=buildLog

**Comment by lidanqing-vv** [comment]
close until new CI is applied

**Pull request closed without merging**
