### PR TITLE
use mkl to accelerate gelu_grad

### PR DESCRIPTION
**Pull request by LeoZhao-BJ**
Native gelu_grad use EIGEN to do calculation, but it doesn't utilize vector acceleration. 
This PR uses MKL Vector to accelerate like it does in gelu.

Remaining issue is there is variable allocation/de-allocation for each iteration which is used to store intermediate values, any good idea to avoid this allocation?

test=develop

### CODE REVIEW

**Comment by LeoZhao-BJ** [comment]
@yihuaxu @jczaja @kbinias  for code review

**Comment by LeoZhao-BJ** [comment]
one of my question, in my case, I need a variable to store intermediate value, any good ways to avoid malloc/free each time?

**Comment by yihuaxu** [comment]
@LeoZhao-Intel Could you use "dout_data" to replace the "second" variable? it can avoid the memory assignment.

**Comment by LeoZhao-BJ** [comment]
dout_data and dx_data are all used. x and out are inputs and const type, can't be reused.
seems allocation is unavoidable.

**Comment by yihuaxu** [comment]
> dout_data and dx_data are all used. x and out are inputs and const type, can't be reused.
> seems allocation is unavoidable.

LGTM

**Comment by luotao1** [comment]
Do you have some performance result on this PR?

**Comment by bingyanghuang** [comment]
> Do you have some performance result on this PR?

@LeoZhao-Intel Please follow up this PR and respond to Luo Tao's question.

**Comment by LeoZhao-Intel** [comment]
fast_executor=true, transpose2 mkldnn elewise omp | fast_executor=true,   transpose2 mkldnn
-- | --
Event | Calls | Total | Top20 | Event | Calls | Total
gelu_grad | 96 | 58089 | 268526 | gelu_grad | 96 | 56339.7
transpose2_grad | 384 | 46381.9 |   | transpose2_grad | 384 | 45611.1
mul_grad | 592 | 45916 |   | mul_grad | 592 | 41446.5
layer_norm_grad | 200 | 25143.9 |   | layer_norm_grad | 200 | 24892.1
mul | 592 | 20430 |   | mul | 592 | 20912.1
softmax | 96 | 19871.1 |   | softmax | 96 | 19889.1
dropout | 304 | 8775.08 |   | elementwise_mul | 4456 | 8899.34
adam | 1608 | 7278.33 |   | dropout | 304 | 8669.88
elementwise_mul | 4456 | 6930.35 |   | elementwise_add | 896 | 8453.09
elementwise_add_grad | 896 | 5226.22 |   | adam | 1608 | 5497.32
dropout_grad | 304 | 4504.75 |   | elementwise_add_grad | 896 | 4397.26
matmul_grad | 192 | 4006.71 |   | dropout_grad | 304 | 4135.48
elementwise_add | 896 | 3337.11 |   | gelu | 96 | 2799.44
gelu | 96 | 2748.73 |   | matmul_grad | 192 | 2703.9
softmax_grad | 96 | 1795.23 |   | softmax_grad | 96 | 1537.75
square | 1608 | 1583.15 |   | square | 1608 | 1453.53
elementwise_sub | 616 | 1534.09 |   | matmul | 200 | 1220.11
sum | 200 | 1324.52 |   | sum | 200 | 1190.66
all_reduce | 201 | 1266.84 |   | elementwise_sub | 616 | 1163.99
matmul | 200 | 1250.54 |   | all_reduce | 201 | 1007.34
scale | 3416 | 1132.47 |   | scale | 3416 | 982.401
read | 16 | 934.341 |   | layer_norm | 200 | 868.062
layer_norm | 200 | 894.538 |   | transpose2 | 384 | 786.135
transpose2 | 384 | 827.397 |   | read | 16 | 660.435
assign | 624 | 689.219 |   | assign | 624 | 494.967
reduce_sum | 1608 | 343.413 |   | reduce_sum | 1608 | 332.633
lookup_table | 24 | 288.083 |   | lookup_table_grad | 24 | 297.52
lookup_table_grad | 24 | 260.544 |   | lookup_table | 24 | 209.624
stack | 8 | 144.586 |   | stack | 8 | 113.059
slice_grad | 8 | 99.0269 |   | slice_grad | 8 | 96.9251
ScopeBufferedSSAGraphExecutorAfterRun | 1 | 46.3514 |   | InitLocalExeScopes | 1 | 41.0214
fill_constant | 2256 | 15.4515 |   | DropLocalExeScopes | 1 | 37.1164
reshape2 | 384 | 10.3673 |   | fill_constant | 2256 | 13.9807
reshape2_grad | 384 | 9.28134 |   | reshape2 | 384 | 10.1149
conditional_block | 16 | 4.57082 |   | reshape2_grad | 384 | 8.41595
create_double_buffer_reader | 8 | 1.45153 |   | conditional_block | 16 | 4.13208
cast | 8 | 1.03662 |   | create_double_buffer_reader | 8 | 1.26062
less_than | 8 | 0.737802 |   | top_k | 8 | 1.20751
slice | 8 | 0.716099 |   | slice | 8 | 0.716362
top_k | 8 | 0.477763 |   | cast | 8 | 0.699655
logical_not | 8 | 0.383455 |   | logical_not | 8 | 0.598125
tanh | 8 | 0.356445 |   | less_than | 8 | 0.496436
softmax_with_cross_entropy | 8 | 0.356423 |   | softmax_with_cross_entropy | 8 | 0.389723
increment | 8 | 0.34313 |   | accuracy | 8 | 0.380143
tanh_grad | 8 | 0.300447 |   | tanh | 8 | 0.331222
accuracy | 8 | 0.272335 |   | tanh_grad | 8 | 0.303412
elementwise_div | 16 | 0.245474 |   | mean_grad | 8 | 0.292719
softmax_with_cross_entropy_grad | 8 | 0.243141 |   | softmax_with_cross_entropy_grad | 8 | 0.258632
mean_grad | 8 | 0.155677 |   | elementwise_div | 16 | 0.21832
Fetch | 4 | 0.139138 |   | Fetch | 4 | 0.199696
mean | 8 | 0.115508 |   | increment | 8 | 0.184105
elementwise_max | 8 | 0.097277 |   | sqrt | 8 | 0.109106
sqrt | 8 | 0.084719 |   | elementwise_max | 8 | 0.102416
Scale LossGrad | 8 | 0.023023 |   | mean | 8 | 0.092469
  |   |   |   | FastThreadedSSAGraphExecutorPrepare | 1 | 0.088074
  |   |   |   | Scale LossGrad | 8 | 0.021247

**Comment by LeoZhao-Intel** [comment]
fast_executor=true, transpose2 mkldnn |  
-- | --
Event | Calls | Total | Top20
gelu_grad | 96 | 56339.7 | 263202.1
transpose2_grad | 384 | 45611.1 |  
mul_grad | 592 | 41446.5 |  
layer_norm_grad | 200 | 24892.1 |  
mul | 592 | 20912.1 |  
softmax | 96 | 19889.1 |  
elementwise_mul | 4456 | 8899.34 |  
dropout | 304 | 8669.88 |  
elementwise_add | 896 | 8453.09 |  
adam | 1608 | 5497.32 |  
elementwise_add_grad | 896 | 4397.26 |  
dropout_grad | 304 | 4135.48 |  
gelu | 96 | 2799.44 |  
matmul_grad | 192 | 2703.9 |  
softmax_grad | 96 | 1537.75 |  
square | 1608 | 1453.53 |  
matmul | 200 | 1220.11 |  
sum | 200 | 1190.66 |  
elementwise_sub | 616 | 1163.99 |  
all_reduce | 201 | 1007.34 |  
scale | 3416 | 982.401 |  
layer_norm | 200 | 868.062 |  
transpose2 | 384 | 786.135 |  
read | 16 | 660.435 |  
assign | 624 | 494.967 |  
reduce_sum | 1608 | 332.633 |  
lookup_table_grad | 24 | 297.52 |  
lookup_table | 24 | 209.624 |  
stack | 8 | 113.059 |  
slice_grad | 8 | 96.9251 |  
InitLocalExeScopes | 1 | 41.0214 |  
DropLocalExeScopes | 1 | 37.1164 |  
fill_constant | 2256 | 13.9807 |  
reshape2 | 384 | 10.1149 |  
reshape2_grad | 384 | 8.41595 |  
conditional_block | 16 | 4.13208 |  
create_double_buffer_reader | 8 | 1.26062 |  
top_k | 8 | 1.20751 |  
slice | 8 | 0.716362 |  
cast | 8 | 0.699655 |  
logical_not | 8 | 0.598125 |  
less_than | 8 | 0.496436 |  
softmax_with_cross_entropy | 8 | 0.389723 |  
accuracy | 8 | 0.380143 |  
tanh | 8 | 0.331222 |  
tanh_grad | 8 | 0.303412 |  
mean_grad | 8 | 0.292719 |  
softmax_with_cross_entropy_grad | 8 | 0.258632 |  
elementwise_div | 16 | 0.21832 |  
Fetch | 4 | 0.199696 |  
increment | 8 | 0.184105 |  
sqrt | 8 | 0.109106 |  
elementwise_max | 8 | 0.102416 |  
mean | 8 | 0.092469 |  
FastThreadedSSAGraphExecutorPrepare | 1 | 0.088074 |  
Scale LossGrad | 8 | 0.021247 |

**Comment by LeoZhao-BJ** [comment]
This was original data without change

Event | Calls | Total
-- | -- | --
gelu_grad | 96 | 56339.7
transpose2_grad | 384 | 45611.1
mul_grad | 592 | 41446.5
layer_norm_grad | 200 | 24892.1
mul | 592 | 20912.1
softmax | 96 | 19889.1
elementwise_mul | 4456 | 8899.34
dropout | 304 | 8669.88
elementwise_add | 896 | 8453.09
adam | 1608 | 5497.32
elementwise_add_grad | 896 | 4397.26
dropout_grad | 304 | 4135.48
gelu | 96 | 2799.44
matmul_grad | 192 | 2703.9
softmax_grad | 96 | 1537.75
square | 1608 | 1453.53
matmul | 200 | 1220.11
sum | 200 | 1190.66
elementwise_sub | 616 | 1163.99
all_reduce | 201 | 1007.34
scale | 3416 | 982.401
layer_norm | 200 | 868.062
transpose2 | 384 | 786.135
read | 16 | 660.435
assign | 624 | 494.967

**Comment by LeoZhao-BJ** [comment]
This is with change.


Event | Calls | Total
-- | -- | --
transpose2 | 384 | 46111
transpose2_grad | 384 | 45106.4
mul_grad | 592 | 40239
layer_norm_grad | 200 | 24350.4
mul | 592 | 20972.1
softmax | 96 | 19772.8
dropout | 304 | 8569.8
elementwise_mul | 4456 | 8277.59
elementwise_add | 896 | 7995.87
gelu_grad | 96 | 6005.49
adam | 1608 | 5002.08
elementwise_add_grad | 896 | 3975.05
dropout_grad | 304 | 3648.05
gelu | 96 | 2655.21
matmul_grad | 192 | 1973.03
square | 1608 | 1704.53
matmul | 200 | 1183.66
elementwise_sub | 616 | 1149.01
sum | 200 | 1117.15
softmax_grad | 96 | 1035.54
all_reduce | 201 | 1032.19
read | 16 | 931.969
scale | 3416 | 889.044
layer_norm | 200 | 821.345
reduce_sum | 1608 | 805.203

**Comment by LeoZhao-BJ** [comment]
56339.7 vs. 6005.49, 9x speedup!

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
