### PR TITLE
Refactor cpu_quantize_pass_tester

### PR DESCRIPTION
**Pull request by wozna**
### PR types

Others 
### PR changes

Others 
### Describe

This PR refactors `cpu_quantize_pass_tester.cc`.  A lot of code was repeated in this test, so I merge MainTest into one. Also added generic test for immutable ops like reshape, transpose, or slice.

### CODE REVIEW

**Review by sfraczek — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@Aganlengzi Could you please merge this PR? It is just a test refactoring PR.

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
