### PR TITLE
FTRL with sparse update, test=develop

### PR DESCRIPTION
**Pull request by leesusu**
solve #21957

### CODE REVIEW

**Review by iclementine — DISMISSED** [review]
LGTM!

**Comment by leesusu** [comment]
@wilhelmzh 劳烦跟进下🤦‍♂️

**Comment by leesusu** [comment]
@seiriosPlus @iclementine 这个解了下冲突，帮忙再review下～

**Review by seiriosPlus — APPROVED** [review]
LGTM

**Pull request merged**
