### PR TITLE
Disable CPU Reduce mode

### LINKED ISSUE #12252: The current implementation of multi-threads(CPU)'s Reduce mode is problematic.
Currently, ParallelExecutor supports CPU multi-threads which has two modes, AllReduce and Reduce. 

In AllReduce mode, all the parameter(trainable and no-trainable) are copied into different scopes, those scopes are held by multi-threads separately. During the training, if we can ensure that all the parameters' gradient value are the same, the training process can be considered no problem.  

In Reduce mode, all the parameter(trainable and no-trainable) are shared between those scopes and different threads optimize part of all the parameters. It seems that this mode is no problem and this mode is faster, but if we think more about this mode,  it is problematic. In some operator, for example BatchNorm, its inputs include `X`, `Scale`, `Bias`, `Mean`, `Variance`. `Scale`, `Bias`, `Mean` and `Variance` are the parameter, but `Scale` and `Bias` are trainable, `Mean` and `Variance` are no-trainable, `Mean` and `Variance` are only used to calculate the mean and var of the current batch, and **they should not be shared between scopes**.

The root of the problem is we should not share all the parameter between scopes simply.

After discussing with @jacquesqiao, we think `Parameter` should have another tag to indicate whether this `Parameter` should be shared.

### PR DESCRIPTION
**Pull request by chengduoZH**
fix https://github.com/PaddlePaddle/Paddle/issues/12252

### CODE REVIEW

**Comment by jacquesqiao** [comment]
I think we also need to disable user interface to use reduce mode

**Comment by jacquesqiao** [comment]
不过这个可以先merge了

**Review by jacquesqiao — APPROVED** [review]
LGTM!

**Comment by chengduoZH** [comment]
We should not disable CPU Reduce mode

**Pull request closed without merging**
