### PR TITLE
reduce CI time of high_level_api tests

### PR DESCRIPTION
**Pull request by luotao1**
Discussed with @tianshuo78520a and @junjun315, we decide to put high_level_api tests in Nightly Jobs.
This PR:
- The first commit renames all the high_level_api tests to `test_xxx_new_api.py`,  in order to calculate total high_level_api tests' elapsed time on CI.
- The second commit will add a compiler option `WITH_HIGH_LEVEL_API_TEST`. [WIP]

### CODE REVIEW

**Comment by luotao1** [comment]
All the new_api tests cost 1100 second = 18 minutes. @tianshuo78520a @junjun315 
```
grep "new_api" ~/Downloads/Paddle_PR_CI_39729.log | grep "sec" |sort -k 11 -r
[20:50:43] :	 [Step 1/1] 576/624 Test #607: test_image_classification_vgg_new_api ...............   Passed  306.40 sec
[20:48:15] :	 [Step 1/1] 567/624 Test #605: test_understand_sentiment_stacked_lstm_new_api ......   Passed  164.70 sec
[20:49:29] :	 [Step 1/1] 571/624 Test #609: test_image_classification_resnet_new_api ............   Passed  152.07 sec
[20:48:04] :	 [Step 1/1] 566/624 Test #606: test_understand_sentiment_conv_new_api ..............   Passed  148.22 sec
[20:50:27] :	 [Step 1/1] 574/624 Test #611: test_recognize_digits_conv_new_api ..................   Passed  131.35 sec
[20:46:39] :	 [Step 1/1] 564/624 Test #602: test_word2vec_new_api ...............................   Passed   98.01 sec
[20:48:59] :	 [Step 1/1] 568/624 Test #610: test_recognize_digits_mlp_new_api ...................   Passed   54.99 sec
[20:45:36] :	 [Step 1/1] 562/624 Test #601: test_machine_translation_new_api ....................   Passed   38.34 sec
[20:46:57] :	 [Step 1/1] 565/624 Test #608: test_label_semantic_roles_new_api ...................   Passed   17.61 sec
[20:45:36] :	 [Step 1/1] 563/624 Test #603: test_recommender_system_new_api .....................   Passed   14.69 sec
[20:45:30] :	 [Step 1/1] 561/624 Test #604: test_fit_a_line_new_api .............................   Passed    5.61 sec
```

**Comment by luotao1** [comment]
```
[21:16:54][Step 1/1] 624/624 Test #552: test_image_classification_resnet ....................***Failed    1.86 sec
[21:16:54][Step 1/1] Traceback (most recent call last):
[21:16:54][Step 1/1]   File "/paddle/tools/test_runner.py", line 53, in <module>
[21:16:54][Step 1/1]     main()
[21:16:54][Step 1/1]   File "/paddle/tools/test_runner.py", line 37, in main
[21:16:54][Step 1/1]     module = importlib.import_module(module_name)
[21:16:54][Step 1/1]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[21:16:54][Step 1/1]     __import__(name)
[21:16:54][Step 1/1] ImportError: No module named test_image_classification_resnet
```
http://ci.paddlepaddle.org/viewLog.html?buildId=82024&buildTypeId=Paddle_PrCi&tab=buildLog&branch_Paddle=pull%2F16625

https://github.com/PaddlePaddle/Paddle/pull/16738/commits/7d0ed2a423bb506a6bc655f44e4333226b1a6ab4 remove non-existent test_image_classification_resnet, since there is no `test_image_classification_resnet.py` in https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/fluid/tests/unittests

**Comment by luotao1** [comment]
- Before:
```
[21:16:54][Step 1/1] Total Test time (real) = 3362.81 sec
```
- After:
```
[13:25:39]Total Test time (real) = 3010.22 sec
```

**Review by junjun315 — APPROVED** [review]
LGTM, Good job!

**Pull request merged**
