### PR TITLE
Update DNNL version to 1.3

### PR DESCRIPTION
**Pull request by grygielski**
Update DNNL version to 1.3

### CODE REVIEW

**Comment by grygielski** [comment]
@luotao1 Can you rerun PR-CI-Py35 ?

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
Hi, @jczaja @ddokupil  I heard last time there is accuracy drop after merging 1.3, it was resolved now?

**Comment by ddokupil** [comment]
it's FP32: avg accuracy: 0.797590 vs FP32: avg accuracy: 0.797992. Other than that I have noticed 0,7% performance regression on Ernie but also some minor performance improvements in some of other models.

**Comment by grygielski** [comment]
I can't reproduce accuracy difference on my developer machine

**Comment by ddokupil** [comment]
Never mind, I was using wrong model.
For both dnnl1.2 and 1.3 I got
2020-03-30 14:38:57,013-INFO: FP32: avg accuracy: 0.802008
2020-03-30 14:38:57,013-INFO: INT8: avg accuracy: 0.793574

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
