### PR TITLE
Add possibility to test native config in Mkldnn tests

### PR DESCRIPTION
**Pull request by wozna**
### PR types

Others 
### PR changes

Others 
### Describe

This PR adds the possibility to test native config in the Mkldnn test.

### CODE REVIEW

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM.
This provide option for API UT mkldnn ON/OFF tests.

**Comment by wozna** [comment]
@baoachun Could you please review it?

**Review by baoachun — APPROVED** [review]
LGTM

**Pull request merged**
