### PR TITLE
reaplce fill_constant_batch_size_like 

### PR DESCRIPTION
**Pull request by Difers**
### PR types

Others 
### PR changes

APIs 
### Description

repaclefill_constant_batch_size_like in fluid with 2.0 version

### CODE REVIEW

**Review by zoooo0820 — COMMENTED** [review]
辛苦也删除`python/paddle/fluid/layers/tensor.py`这个文件

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM
单测删除

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by sunzhongkai588 — APPROVED** [review]
LGTM, no docs changes

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
