### PR TITLE
[MLU]add sync stream ops and broadcast pytest

### PR DESCRIPTION
**Pull request by kangna-qi**
### PR types
New features

### PR changes
OPs

### Describe
add c_sync_calc_stream_op kernel and  c_sync_comm_stream_op kernel for mlu.
add broadcast_op pytest.

### CODE REVIEW

**Comment by kangna-qi** [comment]
测试命令：
`python test_collective_broadcast.py`
训练日志：

**Review by qili93 — DISMISSED** [review]
LGTM

**Review by qili93 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM for `set_tests_properties(test_collective_broadcast PROPERTIES TIMEOUT 120)`

**Review by Aurelius84 — APPROVED** [review]
LGTM

**Pull request merged**
