### PR TITLE
[Cleanup][B-11]Replace to_variable

### PR DESCRIPTION
**Pull request by co63oc**
### PR types

Others
### PR changes

Others
### Description

https://github.com/PaddlePaddle/Paddle/issues/61385

### CODE REVIEW

**Review by SigureMo — COMMENTED** [review]
需要解决下冲突

**Comment by co63oc** [comment]
已修改

**Review by SigureMo — APPROVED** [review]
LGTMeow

**Review by SigureMo — APPROVED** [review]
LGTMeow

**Pull request merged**
