### PR TITLE
[XPU] Add element_mul_add_fuse_pass & elementwise_madd_xpu kernel

### PR DESCRIPTION
**Pull request by MuShangCC**
### PR types
Performance optimization

### PR changes
OPs

### Description
Add element_mul_add_fuse_pass & elementwise_madd_xpu kernel to improve performance

### CODE REVIEW

**Review by hong19860320 — DISMISSED** [review]
LGTM

**Review by hong19860320 — DISMISSED** [review]
LGTM

**Review by hong19860320 — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]
LGTM for new Fuse kernel

**Review by leiqing1 — APPROVED** [review]

**Pull request merged**
