### PR TITLE
Export paddle_proto symbols

### PR DESCRIPTION
**Pull request by tsocha**
### PR types
Others

### PR changes
Others

### Describe
Since PaddlePaddle hiden most of the symbols from library I lost an ability to open and read/manipulate PaddlePaddle models.
This PR restore this feature.

It fix the linker error:
```
[ 95%] Linking CXX executable ../pp-runner
/usr/bin/ld: libpp-runner-lib.a(test_configuration.cpp.o): in function `PaddlePaddleRunner::ModelHandler::~ModelHandler()':
<HOME>/pp-runner/src/test_configuration/model_handler.hpp:15: undefined reference to `paddle::framework::proto::ProgramDesc::~ProgramDesc()'
/usr/bin/ld: libpp-runner-lib.a(model_handler.cpp.o): in function `PaddlePaddleRunner::ModelHandler::ModelHandler(std::filesystem::__cxx11::path)':
<HOME>/pp-runner/src/test_configuration/model_handler.cpp:11: undefined reference to `paddle::framework::proto::ProgramDesc::ProgramDesc()'
/usr/bin/ld: <HOME>/pp-runner/src/test_configuration/model_handler.cpp:11: undefined reference to `paddle::framework::proto::ProgramDesc::~ProgramDesc()'
/usr/bin/ld: libpp-runner-lib.a(model_handler.cpp.o): in function `paddle::framework::proto::VarType_TensorDesc::internal_default_instance()':
<HOME>/paddle/build/paddle_inference_install_dir/paddle/include/internal/framework.pb.h:4788: undefined reference to `paddle::framework::proto::VarType_TensorDesc_default_instance_'
/usr/bin/ld: libpp-runner-lib.a(model_handler.cpp.o): in function `paddle::framework::proto::VarType_LoDTensorDesc::internal_default_instance()':
<HOME>/paddle/build/paddle_inference_install_dir/paddle/include/internal/framework.pb.h:4864: undefined reference to `paddle::framework::proto::VarType_LoDTensorDesc_default_instance_'
/usr/bin/ld: libpp-runner-lib.a(model_handler.cpp.o): in function `paddle::framework::proto::VarType::internal_default_instance()':
<HOME>/paddle/build/paddle_inference_install_dir/paddle/include/internal/framework.pb.h:5498: undefined reference to `paddle::framework::proto::VarType_default_instance_'
collect2: error: ld returned 1 exit status

```

### CODE REVIEW

**Review by jiweibo — APPROVED** [review]
Exposed too many symbols in the past, we may try to hide symbols other than API in the future, but this currently looks like a tough job.

**Comment by tsocha** [comment]
> Exposed too many symbols in the past, we may try to hide symbols other than API in the future, but this currently looks like a tough job.

Another solution proposal: export paddle_proto.so library to install directory. This way users could manipulate paddle models and paddle_inference.so will be clean from proto symbols.

**Comment by tsocha** [comment]
@jiweibo Do you have any idea why these CI checks are failing for this PR?
obraz

**Comment by jiweibo** [comment]
> @jiweibo Do you have any idea why these CI checks are failing for this PR? obraz

I will rerun all the ci task.

**Comment by luotao1** [comment]
@tsocha 

### You're Invited: Claim Your Custom PaddlePaddle Contributor Badge!
Baidu Open Source Office is looking for those of you who have quietly contributed to PaddlePaddle. We’ve prepared a special token of appreciation just for you—a custom commemorative badge engraved with your name.

image


Over the years, every step forward PaddlePaddle has taken has been made possible by your code, your passion, and your youth. Maybe you once submitted a line of code late at night, maybe you kindly answered a question in the community, or maybe it’s been a while since you last contributed…
But we’ve never forgotten you.

This time, we’re not just looking to reconnect with your code—we want to relive those years we burned brightly together.
Come join us—let’s once again—“reclaim our youth”!

If you’d like to take part, please send your **name, phone number, and a brief self-recommendation** to:
📧 [ext_paddle_oss@baidu.com](https://mailto:ext_paddle_oss@baidu.com/)
⏰ Deadline: **September 10th, 10:00 AM**
📌 Feel free to write your self-recommendation in your own style～
💡 No committee referral or repository write access is required—every past contributor is warmly welcome to join!

**Pull request merged**
