### PR TITLE
【api 2.0】 reduce_all-->all reduce_any-->any

### PR DESCRIPTION
**Pull request by liuhuiCNN**
### PR types
Function optimization

### PR changes
APIs

### Describe
merge #28134 and  #28098  to this one PR
(1) reduce_all-->all
(2) reduce_any-->any
(3) update doc in reduce_all and reduce_any

### CODE REVIEW

**Review by jzhang533 — DISMISSED** [review]
lgtm

**Review by XiaoguangHu01 — DISMISSED** [review]
lgtm

**Review by jzhang533 — APPROVED** [review]
lgtm

**Comment by liuhuiCNN** [comment]
# move to #28215

**Pull request closed without merging**
