### PR TITLE
[tests] move `paddle/fluid/framework/*_test*` -> `test/cpp/fluid/framework/`

### PR DESCRIPTION
**Pull request by gouzil**
### PR types

Others
### PR changes

Others
### Description

迁移相关单测:

`paddle/fluid/framework/*_test*` -> `test/cpp/fluid/framework/`

### CODE REVIEW

**Comment by gouzil** [comment]
@risemeup1

**Comment by risemeup1** [comment]
> @risemeup1

这个windows编译挂了

**Review by risemeup1 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by zyfncg — APPROVED** [review]

**Pull request merged**
