### PR TITLE
Add output defs for fused_matmul kernel

### PR DESCRIPTION
**Pull request by jinyouzhi**
### PR types

Others

### PR changes

Others

### Describe

Task 25 in #51292 

There are no native implement fused matmul op but oneDNN, so just remove it from need-regisiter list then move InferShape in fluid to phi.

### CODE REVIEW

**Comment by jinyouzhi** [comment]
@From00 Could you have a review?

**Comment by From00** [comment]
> @From00 Could you have a review?

Some CI checks were not successful. You should pass all CI checks before require review.

**Comment by jinyouzhi** [comment]
@From00 麻烦review一下

**Comment by From00** [comment]
> @From00 麻烦review一下

这个OP是需要迁移infershape，并在infershape中推导dtype的哈

**Comment by jinyouzhi** [comment]
@From00 加上了，麻烦看一下有没有问题

**Review by From00 — APPROVED** [review]
LGTM

**Pull request merged**
