### PR TITLE
Matmuls with activation and elementwise_add fuses

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Performance optimization

### PR changes
OPs

### Describe
- add matmul and matmul_v2 + elementwise_add fuse passes,
- matmul + elementwise_add + activation patterns will also be fused as one matmul,
- extend matmul + activation fuse pass to work with matmul_v2,
- add unit test for each new fuse pass.

### CODE REVIEW

**Comment by Silv3S** [comment]
@jczaja, @jakpiase please review

**Review by lidanqing-vv — DISMISSED** [review]
LGTM

**Review by jczaja — DISMISSED** [review]
LGTM

**Review by jakpiase — DISMISSED** [review]
LGTM

**Review by jczaja — APPROVED** [review]

**Comment by Silv3S** [comment]
@jiangjiajun please review

**Pull request merged**
