### PR TITLE
Fix some typos in paddle/.

### PR DESCRIPTION
**Pull request by Yulv-git**
### PR types

Bug fixes

### PR changes

Docs

### Describe

Fix some typos in paddle/

### CODE REVIEW

**Comment by Yulv-git** [comment]
> ## 🕵️ CI failures summary
> 🔍 PR: #42408 Commit ID: [4e68eb4](https://github.com/PaddlePaddle/Paddle/commit/4e68eb4573cbfe74bd2db4c312dff44552527eb1) contains failed CI.
> 
> 🔹 Failed: [PR-CI-APPROVAL](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527448/stage/9206860/0?jump=latestJob)
> 
> Unknown Failed
> ```
> Unknown Failed
> ```
> 
> 🔹 Failed: [PR-CI-Static-Check](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527752/stage/9207379/0?jump=latestJob)
> 
> Unknown Failed
> ```
> Unknown Failed
> ```
> 
> 🔹 Failed: [PR-CI-OP-benchmark](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527998/stage/9207801/0?jump=latestJob)
> 
> Unknown Failed
> ```
> Unknown Failed
> ```
> 
> 🔹 Failed: [PR-CI-Coverage](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527749/stage/9207376/0?jump=latestJob)
> 
> Unknown Failed
> ```
> Unknown Failed
> ```

Excuse me, I'm not quite sure how to improve them to get through some failed checks.

**Comment by TCChenlong** [comment]
> > ## 🕵️ CI failures summary
> > 🔍 PR: #42408 Commit ID: [4e68eb4](https://github.com/PaddlePaddle/Paddle/commit/4e68eb4573cbfe74bd2db4c312dff44552527eb1) contains failed CI.
> > 🔹 Failed: [PR-CI-APPROVAL](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527448/stage/9206860/0?jump=latestJob)
> > Unknown Failed
> > ```
> > Unknown Failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 🔹 Failed: [PR-CI-Static-Check](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527752/stage/9207379/0?jump=latestJob)
> > Unknown Failed
> > ```
> > Unknown Failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 🔹 Failed: [PR-CI-OP-benchmark](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527998/stage/9207801/0?jump=latestJob)
> > Unknown Failed
> > ```
> > Unknown Failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 🔹 Failed: [PR-CI-Coverage](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527749/stage/9207376/0?jump=latestJob)
> > Unknown Failed
> > ```
> > Unknown Failed
> > ```
> 
> Excuse me, I'm not quite sure how to improve them to get through some failed checks.

hello，please merge #42408 and #42409 and we will solve these problems together~
Thanks!

**Comment by luotao1** [comment]
可以提供下发现typos的自动化脚本么，并放到tools目录下

**Comment by Yulv-git** [comment]
> 

Hello, I am out on business now. I'll deal with it when it's convenient, thanks!

**Comment by Yulv-git** [comment]
> 可以提供下发现typos的自动化脚本么，并放到tools目录下

我前段时间写了个脚本，详见项目[Search-for-Typos](https://github.com/Yulv-git/Search-for-Typos) 。该脚本可能比较简陋

**Comment by Yulv-git** [comment]
> > > ## 🕵️ CI failures summary
> > > 🔍 PR: #42408 Commit ID: [4e68eb4](https://github.com/PaddlePaddle/Paddle/commit/4e68eb4573cbfe74bd2db4c312dff44552527eb1) contains failed CI.
> > > 🔹 Failed: [PR-CI-APPROVAL](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527448/stage/9206860/0?jump=latestJob)
> > > Unknown Failed
> > > ```
> > > Unknown Failed
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 🔹 Failed: [PR-CI-Static-Check](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527752/stage/9207379/0?jump=latestJob)
> > > Unknown Failed
> > > ```
> > > Unknown Failed
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 🔹 Failed: [PR-CI-OP-benchmark](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527998/stage/9207801/0?jump=latestJob)
> > > Unknown Failed
> > > ```
> > > Unknown Failed
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 🔹 Failed: [PR-CI-Coverage](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/5527749/stage/9207376/0?jump=latestJob)
> > > Unknown Failed
> > > ```
> > > Unknown Failed
> > > ```
> > 
> > 
> > Excuse me, I'm not quite sure how to improve them to get through some failed checks.
> 
> hello，please merge #42408 and #42409 and we will solve these problems together~ Thanks!

Hi! I have `cherry-pick` the commit from #42409 to #42408.

**Review by TCChenlong — DISMISSED** [review]
LGTM~

**Review by luotao1 — DISMISSED** [review]

**Comment by TCChenlong** [comment]
Hi，please fix `code format error` of **PR-CI-Static-Check** according to the diff information.
image

**Comment by Yulv-git** [comment]
> Hi，please fix `code format error` of **PR-CI-Static-Check** according to the diff information. image

Sorry, I don't understand what should be changed. I looked at the two files mentioned in the picture, I only modified the typos, and it seems that the code format has not been changed.

**Comment by TCChenlong** [comment]
> > Hi，please fix `code format error` of **PR-CI-Static-Check** according to the diff information. image
> 
> Sorry, I don't understand what should be changed. I looked at the two files mentioned in the picture, I only modified the typos, and it seems that the code format has not been changed.

You can use pre-commit to check code fo

> > Hi，please fix `code format error` of **PR-CI-Static-Check** according to the diff information. image
> 
> Sorry, I don't understand what should be changed. I looked at the two files mentioned in the picture, I only modified the typos, and it seems that the code format has not been changed.

This could be a problem due to spaces. You can use pre-commit to check code format, or revert the modification of these two files.

**Comment by TCChenlong** [comment]
`paddle/fluid/operators/mlu/mlu_baseop.h` & `paddle/phi/kernels/funcs/pooling.cu` have the same problem.

**Review by luotao1 — APPROVED** [review]

**Review by TCChenlong — CHANGES_REQUESTED** [review]
LGTM~

**Review by TCChenlong — APPROVED** [review]

**Review by raindrops2sea — APPROVED** [review]
LGTM

**Pull request merged**
