### PR TITLE
copy found_inf to cpu in advance to improve performance

### PR DESCRIPTION
**Pull request by zhiqiu**
### PR types

Performance optimization
### PR changes

Others
### Describe

Since found_inf needs to be on cpu in adam op, we copy it in advance to avoid multiple time copies.

### CODE REVIEW

**Review by pangyoki — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]
LGTM for PADDLE_ENFORCE

**Review by zhhsplendid — APPROVED** [review]
LGTM for ShareDataWith, but discussed that name like "x_" can be changed because it usually looks like class private data member name. We will change in the future PR.

**Review by phlrain — APPROVED** [review]

**Comment by zhiqiu** [comment]
> LGTM for ShareDataWith, but discussed that name like "x_" can be changed because it usually looks like class private data member name. We will change in the future PR.

Refined in https://github.com/PaddlePaddle/Paddle/pull/34330, thanks.

**Pull request merged**
