### PR TITLE
[Fluid Clean] remove paddle.fluid.layers.nn.reduce_all,reduce_any

### PR DESCRIPTION
**Pull request by heyanru01**
### PR types

Others
### PR changes

APIs
### Describe

remove paddle.fluid.layers.nn.reduce_all, paddle.fluid.layers.nn.reduce_any

### CODE REVIEW

**Comment by yingshengBD** [comment]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]
LGTM for API removing

**Review by hong19860320 — APPROVED** [review]
LGTM

**Pull request merged**
