### PR TITLE
remove paddle.fluid.contrib.layers.BasicLSTMUnit、basic_lstm、BasicGRUUnit、basic_gru

### PR DESCRIPTION
**Pull request by zhengqiwen1997**
### PR types

Others
### PR changes

APIs
### Describe

To clean the code in paddle.fluid, the useless codes should be removed and code still be used should move to a new position.

For function paddle.fluid.contrib.layers.BasicLSTMUnit, paddle.fluid.contrib.layers.basic_lstm, paddle.fluid.contrib.layers.BasicGRUUnit and paddle.fluid.contrib.layers.basic_gru, since it is not used in version 2.x, should be removed.

For unittest code where this function is used, if it is aimed to test the old API, it can be removed directly. Otherwise, the paddle.fluid.contrib.layers.BasicLSTMUnit should be replaced with paddle.nn.LSTMCell, the paddle.fluid.contrib.layers.basic_lstm should be replaced with paddle.nn.LSTM, the paddle.fluid.contrib.layers.BasicGRUUnit should be replaced with paddle.nn.GRUCell and the paddle.fluid.contrib.layers.basic_gru should be replaced with paddle.nn.GRU.

### CODE REVIEW

**Review by zhwesky2010 — APPROVED** [review]
LGTM for rm UT_rule.py

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Pull request merged**
