### PR TITLE
fix APIs, to_variable、NCE、PRelu、softmax、rankloss, test=develop

### PR DESCRIPTION
**Pull request by JepsonWong**
fix APIs, to_variable、NCE、PRelu、softmax、softmax_with_cross_entropy、rankloss.

### CODE REVIEW

**Comment by JepsonWong** [comment]
softmax_with
softmax
to_variable
rank_loss
PRelu
NCE

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by hutuxian — DISMISSED** [review]

**Review by kuke — DISMISSED** [review]

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by frankwhzhang — APPROVED** [review]

**Review by hutuxian — APPROVED** [review]

**Pull request merged**
