### PR TITLE
fix 4 apis test=develop

### PR DESCRIPTION
**Pull request by yaoxuefeng6**
### PR types

Others
### PR changes
 APIs

### Describe
 modify 4 apis

### CODE REVIEW

**Review by jzhang533 — DISMISSED** [review]
lgtm (resolved conflict)

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by jzhang533 — COMMENTED** [review]
lgtm (resolved conflict)

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]
lgtm

**Pull request merged**
