### PR TITLE
【code format check upgrade】 step2：yapf

### PR DESCRIPTION
**Pull request by betterpig**
### PR types

Others
### PR changes

Others
### Describe

use yapf of 0.32.0 to format all python file.
some points:

- change the repo of yapf to [google/yapf ](https://github.com/google/yapf), since there is no need to use [mirrors-yapf](https://github.com/PaddlePaddle/mirrors-yapf), which cant set version easily unless update the repo first. And the two of them have nothing different except that.
- exclude two unittests file of "dygraph to static" for they rely on writing and reading file, and format will break them
Pasted Graphic
M4 IBISE ARerE Ltrar HOIM CNFSIAIBPIBe Vveorce cod
- temporarily dissable using git to find out diff python files in check_diff_file_for_coverage, for the diff_py_files is too many that cause the shell script cant execute successfully.
Pasted Graphic 8

### CODE REVIEW

**Comment by luotao1** [comment]
paddle_build.sh是因为修改的文件太多，所以先做修改，等PR merge后再revert么？

**Comment by luotao1** [comment]
static-check也卡住了，paddle_build.sh对git diff的修改，不仅要修改coverage流水线相关的，还需要修改static-check流水线相关的。也可以先豁免等这个PR merge后，revert paddle_build.sh的修改

**Comment by betterpig** [comment]
> paddle_build.sh是因为修改的文件太多，所以先做修改，等PR merge后再revert么？

> static-check也卡住了，paddle_build.sh对git diff的修改，不仅要修改coverage流水线相关的，还需要修改static-check流水线相关的。也可以先豁免等这个PR merge后，revert paddle_build.sh的修改

我觉得可以先merge了，yapf的合入不会对static_check造成影响。等合入后，我再提个PR改回来。就是改了检查python文件覆盖率的功能，先合入再马上改回来，影响很小。

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
