### PR TITLE
[xdoctest] reformat example code with google style in No.86-90

### PR DESCRIPTION
**Pull request by enkilee**
### PR types

Others
### PR changes

Others
### Description

- ./python/paddle/nn/layer/norm.py
- ./python/paddle/nn/layer/pooling.py
- ./python/paddle/nn/layer/rnn.py
- ./python/paddle/nn/layer/transformer.py
- ./python/paddle/nn/layer/vision.py

预览：

en: http://preview-paddle-pr-55812.paddle-docs-preview.paddlepaddle.org.cn/documentation/docs/en/api/paddle/abs_en.html
zh: http://preview-paddle-pr-55812.paddle-docs-preview.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/abs_cn.html

关联 PR：
https://github.com/PaddlePaddle/Paddle/issues/55629
https://github.com/PaddlePaddle/Paddle/pull/55295

@sunzhongkai588 @SigureMo @megemini

### CODE REVIEW

**Comment by luotao1** [comment]
e9ca2fb7b689bab4915f8e06ee379f05

CI 没过

**Comment by SigureMo** [comment]
需要看一下 CI 失败的 case

**Comment by enkilee** [comment]
已改

**Review by SigureMo — APPROVED** [review]
LGTMeow~

**Pull request merged**
