### PR TITLE
【PIR API adaptor No.218、223】Migrate PairwiseDistance / take_along_axis into pir

### PR DESCRIPTION
**Pull request by DrRyanHuang**
### PR types

Others

### PR changes

APIs

### Description

PIR API 推全升级
将 paddle.nn.PairwiseDistance / take_along_axis 迁移升级至 pir，并更新单测
- https://github.com/PaddlePaddle/Paddle/issues/58067

`PairwiseDistance` 全部通过
`take_along_axis` 全部通过

### CODE REVIEW

**Comment by DrRyanHuang** [comment]
目前还有这几个问题，似乎需要修改单测代码，为pir mode适配

```
ERROR: test_check_grad (test_take_along_axis_op.TestCase1)
TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type

ERROR: test_check_output (test_take_along_axis_op.TestCase1)
TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type

ERROR: test_api_static (test_take_along_axis_op.TestTakeAlongAxisAPI)
TypeError: Cannot interpret '<DataType.INT64: 9>' as a data type

ERROR: test_api_static (test_take_along_axis_op.TestTakeAlongAxisAPICase1)
TypeError: Cannot interpret '<DataType.INT64: 9>' as a data type

ERROR: test_check_grad (test_take_along_axis_op.TestTakeAlongAxisOp)
TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type

ERROR: test_check_output (test_take_along_axis_op.TestTakeAlongAxisOp)
TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type
```

**Comment by MarioLulab** [comment]
> 目前还有这几个问题，似乎需要修改单测代码，为pir mode适配
> 
> ```
> ERROR: test_check_grad (test_take_along_axis_op.TestCase1)
> TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type
> 
> ERROR: test_check_output (test_take_along_axis_op.TestCase1)
> TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type
> 
> ERROR: test_api_static (test_take_along_axis_op.TestTakeAlongAxisAPI)
> TypeError: Cannot interpret '<DataType.INT64: 9>' as a data type
> 
> ERROR: test_api_static (test_take_along_axis_op.TestTakeAlongAxisAPICase1)
> TypeError: Cannot interpret '<DataType.INT64: 9>' as a data type
> 
> ERROR: test_check_grad (test_take_along_axis_op.TestTakeAlongAxisOp)
> TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type
> 
> ERROR: test_check_output (test_take_along_axis_op.TestTakeAlongAxisOp)
> TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type
> ```

请问有更为完整的报错栈吗？

**Comment by DrRyanHuang** [comment]
```
2023-11-05 22:35:26 ======================================================================
2023-11-05 22:35:26 ERROR: test_check_output (test_take_along_axis_op.TestTakeAlongAxisOp)
2023-11-05 22:35:26 ----------------------------------------------------------------------
2023-11-05 22:35:26 Traceback (most recent call last):
2023-11-05 22:35:26   File "/workspace/Paddle/build/test/legacy_test/test_take_along_axis_op.py", line 47, in test_check_output
2023-11-05 22:35:26     self.check_output(check_cinn=self.check_cinn, check_pir=True)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 2676, in check_output
2023-11-05 22:35:26     res = self.check_output_with_place(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 2550, in check_output_with_place
2023-11-05 22:35:26     new_ir_checker.check()
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 2151, in check
2023-11-05 22:35:26     self.calculate_output()
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 2337, in calculate_output
2023-11-05 22:35:26     new_ir_outs = self.op_test._calc_new_ir_output(place)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 1346, in _calc_new_ir_output
2023-11-05 22:35:26     ret_tuple = self.python_api(*args)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 4908, in take_along_axis
2023-11-05 22:35:26     indices = paddle.broadcast_to(indices, broadcast_shape)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 3588, in broadcast_to
2023-11-05 22:35:26     out = helper.create_variable_for_type_inference(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/layer_helper_base.py", line 468, in create_variable_for_type_inference
2023-11-05 22:35:26     return self.main_program.current_block().create_var(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 4174, in create_var
2023-11-05 22:35:26     var = Variable(block=self, *args, **kwargs)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1447, in __init__
2023-11-05 22:35:26     dtype = convert_np_dtype_to_dtype_(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1149, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     return pir.core.convert_np_dtype_to_dtype_(np_dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/pir/core.py", line 75, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     dtype = np.dtype(np_dtype)
2023-11-05 22:35:26 TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type
```

```
2023-11-05 22:35:26 ======================================================================
2023-11-05 22:35:26 ERROR: test_check_grad (test_take_along_axis_op.TestTakeAlongAxisOp)
2023-11-05 22:35:26 ----------------------------------------------------------------------
2023-11-05 22:35:26 Traceback (most recent call last):
2023-11-05 22:35:26   File "/workspace/Paddle/build/test/legacy_test/test_take_along_axis_op.py", line 50, in test_check_grad
2023-11-05 22:35:26     self.check_grad(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 2880, in check_grad
2023-11-05 22:35:26     self.check_grad_with_place(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 3137, in check_grad_with_place
2023-11-05 22:35:26     new_ir_grad = self._get_ir_gradient(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/op_test.py", line 3597, in _get_ir_gradient
2023-11-05 22:35:26     ret_tuple = self.python_api(*args)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 4908, in take_along_axis
2023-11-05 22:35:26     indices = paddle.broadcast_to(indices, broadcast_shape)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 3588, in broadcast_to
2023-11-05 22:35:26     out = helper.create_variable_for_type_inference(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/layer_helper_base.py", line 468, in create_variable_for_type_inference
2023-11-05 22:35:26     return self.main_program.current_block().create_var(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 4174, in create_var
2023-11-05 22:35:26     var = Variable(block=self, *args, **kwargs)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1447, in __init__
2023-11-05 22:35:26     dtype = convert_np_dtype_to_dtype_(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1149, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     return pir.core.convert_np_dtype_to_dtype_(np_dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/pir/core.py", line 75, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     dtype = np.dtype(np_dtype)
2023-11-05 22:35:26 TypeError: Cannot interpret '<DataType.INT32: 7>' as a data type
```

```
2023-11-05 22:35:26 ======================================================================
2023-11-05 22:35:26 ERROR: test_api_static (test_take_along_axis_op.TestTakeAlongAxisAPICase1)
2023-11-05 22:35:26 ----------------------------------------------------------------------
2023-11-05 22:35:26 Traceback (most recent call last):
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/pir_utils.py", line 119, in impl
2023-11-05 22:35:26     func(*args, **kwargs)
2023-11-05 22:35:26   File "/workspace/Paddle/build/test/legacy_test/test_take_along_axis_op.py", line 160, in test_api_static
2023-11-05 22:35:26     out = paddle.take_along_axis(x, index, self.axis)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 4908, in take_along_axis
2023-11-05 22:35:26     indices = paddle.broadcast_to(indices, broadcast_shape)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 3588, in broadcast_to
2023-11-05 22:35:26     out = helper.create_variable_for_type_inference(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/layer_helper_base.py", line 468, in create_variable_for_type_inference
2023-11-05 22:35:26     return self.main_program.current_block().create_var(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 4174, in create_var
2023-11-05 22:35:26     var = Variable(block=self, *args, **kwargs)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1447, in __init__
2023-11-05 22:35:26     dtype = convert_np_dtype_to_dtype_(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1149, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     return pir.core.convert_np_dtype_to_dtype_(np_dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/pir/core.py", line 75, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     dtype = np.dtype(np_dtype)
2023-11-05 22:35:26 TypeError: Cannot interpret '<DataType.INT64: 9>' as a data type
```

```
2023-11-05 22:35:26 ======================================================================
2023-11-05 22:35:26 ERROR: test_api_static (test_take_along_axis_op.TestTakeAlongAxisAPI)
2023-11-05 22:35:26 ----------------------------------------------------------------------
2023-11-05 22:35:26 Traceback (most recent call last):
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/pir_utils.py", line 119, in impl
2023-11-05 22:35:26     func(*args, **kwargs)
2023-11-05 22:35:26   File "/workspace/Paddle/build/test/legacy_test/test_take_along_axis_op.py", line 160, in test_api_static
2023-11-05 22:35:26     out = paddle.take_along_axis(x, index, self.axis)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 4908, in take_along_axis
2023-11-05 22:35:26     indices = paddle.broadcast_to(indices, broadcast_shape)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/tensor/manipulation.py", line 3588, in broadcast_to
2023-11-05 22:35:26     out = helper.create_variable_for_type_inference(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/layer_helper_base.py", line 468, in create_variable_for_type_inference
2023-11-05 22:35:26     return self.main_program.current_block().create_var(
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 4174, in create_var
2023-11-05 22:35:26     var = Variable(block=self, *args, **kwargs)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1447, in __init__
2023-11-05 22:35:26     dtype = convert_np_dtype_to_dtype_(dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/base/framework.py", line 1149, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     return pir.core.convert_np_dtype_to_dtype_(np_dtype)
2023-11-05 22:35:26   File "/workspace/Paddle/build/python/paddle/pir/core.py", line 75, in convert_np_dtype_to_dtype_
2023-11-05 22:35:26     dtype = np.dtype(np_dtype)
2023-11-05 22:35:26 TypeError: Cannot interpret '<DataType.INT64: 9>' as a data type
```

**Comment by YuanRisheng** [comment]
take_along_axis这个api使用到了其他python api，所以需要递归把它调用到的api全部适配pir

**Review by MarioLulab — APPROVED** [review]
LGTM

btw, 29 号题目是 paddle.broadcast_tensors，这个 pr 应该并没有涉及？麻烦修改一下 pr 标题吧~
image

**Review by YuanRisheng — APPROVED** [review]

**Pull request merged**
