### PR TITLE
[Zero-Dim] Support p_norm/reduce_sum_p output 0D

### PR DESCRIPTION
**Pull request by zhwesky2010**
### PR types

New features
### PR changes

APIs
### Description

Pcard-66984

支持以下OP输出0D：
```
1. reduce_sum_p
2. p_norm
```

### CODE REVIEW

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by JZ-LIANG — DISMISSED** [review]
LGTM for dist reduce_sum_p

**Review by zhaoyinglia — DISMISSED** [review]
LGTM for dist_p_norm

**Review by jeff41404 — APPROVED** [review]
LGTM

**Pull request merged**
