### PR TITLE
Profile code refine

### PR DESCRIPTION
**Pull request by wangchaochaohu**
整个PR 都在移动代码(出了一处修改)

定义
image
声明
image

两者不一致 不改动会有编译错误

也改动PADDLE_ENFORCE

移动代码的理由如下
1:重构了 profiler.cc 添加profiler_helper.h,在Profiler.cc 中只保留了profiler.h 中声明的函数
2将struct 和enum声明放在了profiler.h文件中
3.调整了部分函数顺序，是的大功能相近的函数在顺序上看起来更自然

### CODE REVIEW

**Comment by luotao1** [comment]
建议5个功能都拆成单独的PR，便于评审

**Comment by wangchaochaohu** [comment]
> 建议5个功能都拆成单独的PR，便于评审

已按照要求修改

**Review by luotao1 — COMMENTED** [review]
LGTM

**Comment by Xreki** [comment]
解决一下PADDLE_ENFORCE问题，[log链接](http://10.87.145.41:8111/viewLog.html?buildId=291095&tab=buildLog&buildTypeId=YYTest_PrCiCpuPy2&logTab=tail)：

```
[11:13:07]	[Step 1/1] + assert_api_spec_approvals
[11:13:07]	[Step 1/1] + /bin/bash /paddle/tools/check_api_approvals.sh
[11:13:07]	[Step 1/1]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[11:13:07]	[Step 1/1]                                  Dload  Upload   Total   Spent    Left  Speed
[11:13:07]	[Step 1/1] 
[11:13:08]	[Step 1/1]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:13:09]	[Step 1/1]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:13:09]	[Step 1/1] 100     5  100     5    0     0      2      0  0:00:02  0:00:01  0:00:01     2
[11:13:09]	[Step 1/1] 100     5  100     5    0     0      2      0  0:00:02  0:00:01  0:00:01     2
[11:13:12]	[Step 1/1] ****************
[11:13:12]	[Step 1/1] 0. PADDLE_ENFORCE is not recommended. Please use PADDLE_ENFORCE_EQ/NE/GT/GE/LT/LE or PADDLE_ENFORCE_NOT_NULL or PADDLE_ENFORCE_CUDA_SUCCESS instead, see [ https://github.com/PaddlePaddle/Paddle/wiki/PADDLE_ENFORCE-Rewriting-Specification ] for details.
[11:13:12]	[Step 1/1] You must have one RD (chenwhql (Recommend) , luotao1 (Recommend) or lanxianghit) approval for the usage (either add or delete) of PADDLE_ENFORCE.
[11:13:12]	[Step 1/1] PADDLE_ENFORCE(cudaDeviceSynchronize());
[11:13:12]	[Step 1/1] 1. The error message you wrote in PADDLE_ENFORCE{_**} or PADDLE_THROW does not meet our error message writing specification. Possible errors include 1. the error message is empty / 2. the error message is too short / 3. the error type is not specified. Please read the specification [ https://github.com/PaddlePaddle/Paddle/wiki/Paddle-Error-Message-Writing-Specification ], then refine the error message. If it is a mismatch, please specify chenwhql (Recommend), luotao1 or lanxianghit review and approve.
[11:13:12]	[Step 1/1] The PADDLE_ENFORCE{_**} or PADDLE_THROW entries that do not meet the specification are as follows:
[11:13:12]	[Step 1/1] PADDLE_ENFORCE(cudaDeviceSynchronize());
[11:13:12]	[Step 1/1] 
[11:13:12]	[Step 1/1] There are 2 approved errors.
[11:13:12]	[Step 1/1] ****************
[11:13:19]	[Step 1/1] Process exited with code 1
[11:13:19]	[Step 1/1] Process exited with code 1 (Step: Build and test (Command Line))
[11:13:19]	[Step 1/1] Step Build and test (Command Line) failed
```

**Comment by wangchaochaohu** [comment]
> 解决一下PADDLE_ENFORCE问题，[log链接](http://10.87.145.41:8111/viewLog.html?buildId=291095&tab=buildLog&buildTypeId=YYTest_PrCiCpuPy2&logTab=tail)：
> 
> ```
> [11:13:07]	[Step 1/1] + assert_api_spec_approvals
> [11:13:07]	[Step 1/1] + /bin/bash /paddle/tools/check_api_approvals.sh
> [11:13:07]	[Step 1/1]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> [11:13:07]	[Step 1/1]                                  Dload  Upload   Total   Spent    Left  Speed
> [11:13:07]	[Step 1/1] 
> [11:13:08]	[Step 1/1]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> [11:13:09]	[Step 1/1]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> [11:13:09]	[Step 1/1] 100     5  100     5    0     0      2      0  0:00:02  0:00:01  0:00:01     2
> [11:13:09]	[Step 1/1] 100     5  100     5    0     0      2      0  0:00:02  0:00:01  0:00:01     2
> [11:13:12]	[Step 1/1] ****************
> [11:13:12]	[Step 1/1] 0. PADDLE_ENFORCE is not recommended. Please use PADDLE_ENFORCE_EQ/NE/GT/GE/LT/LE or PADDLE_ENFORCE_NOT_NULL or PADDLE_ENFORCE_CUDA_SUCCESS instead, see [ https://github.com/PaddlePaddle/Paddle/wiki/PADDLE_ENFORCE-Rewriting-Specification ] for details.
> [11:13:12]	[Step 1/1] You must have one RD (chenwhql (Recommend) , luotao1 (Recommend) or lanxianghit) approval for the usage (either add or delete) of PADDLE_ENFORCE.
> [11:13:12]	[Step 1/1] PADDLE_ENFORCE(cudaDeviceSynchronize());
> [11:13:12]	[Step 1/1] 1. The error message you wrote in PADDLE_ENFORCE{_**} or PADDLE_THROW does not meet our error message writing specification. Possible errors include 1. the error message is empty / 2. the error message is too short / 3. the error type is not specified. Please read the specification [ https://github.com/PaddlePaddle/Paddle/wiki/Paddle-Error-Message-Writing-Specification ], then refine the error message. If it is a mismatch, please specify chenwhql (Recommend), luotao1 or lanxianghit review and approve.
> [11:13:12]	[Step 1/1] The PADDLE_ENFORCE{_**} or PADDLE_THROW entries that do not meet the specification are as follows:
> [11:13:12]	[Step 1/1] PADDLE_ENFORCE(cudaDeviceSynchronize());
> [11:13:12]	[Step 1/1] 
> [11:13:12]	[Step 1/1] There are 2 approved errors.
> [11:13:12]	[Step 1/1] ****************
> [11:13:19]	[Step 1/1] Process exited with code 1
> [11:13:19]	[Step 1/1] Process exited with code 1 (Step: Build and test (Command Line))
> [11:13:19]	[Step 1/1] Step Build and test (Command Line) failed
> ```

已解决

**Review by zhangting2020 — APPROVED** [review]

**Pull request merged**
