### PR TITLE
fix code example

### PR DESCRIPTION
**Pull request by baiyfbupt**
### PR types

Others
### PR changes

Docs
### Describe

Fix code examples.
中文文档PR： https://github.com/PaddlePaddle/FluidDoc/pull/2887

### CODE REVIEW

**Comment by baiyfbupt** [comment]
image
image

**Comment by baiyfbupt** [comment]
image
image

**Comment by baiyfbupt** [comment]
image
image

**Comment by baiyfbupt** [comment]
image
image

**Review by TCChenlong — DISMISSED** [review]
LGTM

**Review by zhiqiu — APPROVED** [review]

**Review by TCChenlong — APPROVED** [review]
LGTM

**Pull request merged**
