### PR TITLE
Enable FC int8

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Performance optimization

### PR changes
Others

### Describe
It does enable mkldnn FC functionality be default for int8 classification workloads (internal tests)

### CODE REVIEW

**Review by wozna — APPROVED** [review]
LGTM

**Review by jakpiase — COMMENTED** [review]
Ars you sure that fc+act pass will work correctly for int8?

**Comment by wozna** [comment]
> Ars you sure that fc+act pass will work correctly for int8?

Yes, it is the same as convolution, because data is multiplied by output_scale and then all activations are applied.

**Review by jakpiase — APPROVED** [review]
LGTM. Thank you very much @wozna for explanation

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Pull request merged**
