### PR TITLE
Second fix to  #34554 

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Bug fixes

### PR changes
Others

### Describe
Clearing of caching mechanism

### CODE REVIEW

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@OliverLPH Hi, this is last fix, Could you please verify on Baidu 6271? And does these fix PRs need to be cherry-picked to release/2.2 ?

**Comment by OliverLPH** [comment]
@lidanqing-intel could you please merge it into develop first.
later this week I will verify the latest develop Paddle. If it works fine, then cherry-pick to release/2.2 ?

**Comment by jczaja** [comment]
@OliverLPH I discovered some problems (crashes) in issue #34554 with this PR merged. So it is not yet solved. I'm still investigating. If you have any observations please write them in #34554 as it was helpful for me some easier reproductions you have described.

**Comment by qili93** [comment]
Hi @lidanqing-intel,

This PR broken Paddle compile on ARM due to missing header file of "x86intrin.h" in aarch64 environment. 

Please kindly help to revert this PR and fix, thanks!

f6397938193206bc73c70b7df9cc1257

**Comment by lidanqing-vv** [comment]
@qili93 Hi, revert PR Revert #36426 is merged just now, could you please verify latest develop again if compiling on ARM works? Sorry for inconvenience. Thanks !

**Pull request merged**
