### PR TITLE
[Eager] Optimize Grad by prune useless branch

### PR DESCRIPTION
**Pull request by JiabinYang**
### PR types

Others
### PR changes

Others
### Describe

This PR optimize grad performance by remove additional subgraph

### CODE REVIEW

**Review by veyron95 — APPROVED** [review]
LGTM

**Review by ZzSean — APPROVED** [review]
LGTM for CI-OP-Benchmark

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by chenwhql — COMMENTED** [review]
需要看下kunlun的编译失败问题

**Review by chenwhql — APPROVED** [review]

**Comment by JiabinYang** [comment]
> 需要看下kunlun的编译失败问题

Will be fixed in https://github.com/PaddlePaddle/Paddle/pull/48621

**Review by QingshuChen — APPROVED** [review]

**Pull request merged**
