### PR TITLE
add keep_kids flag for executor

### PR DESCRIPTION
**Pull request by jacquesqiao**

### CODE REVIEW

**Review by reyoung — CHANGES_REQUESTED** [review]
The kids should not be kept.

* If users add a `FetchOp`, the device context will be synchronized. Every operator should be completed after Run.
* If users do not add a `FetchOp`, we should wait for the device context instead of keeping children scope. (We may add code to sync device for this situation.)

**Comment by emailweixu** [comment]
@reyoung In while_op.cc, the the step scopes created in the scope passed to executor.run needs to be kept so that they can be accessed by while_grad_op. If kids are dropped, how to achieve this?
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/while_op.cc#L63

**Comment by reyoung** [comment]
In control operators, the `create_local_scopes` will be false. So the executor in WhileOp will not destroy any scopes. The scope will be destroyed after the whole program has been executed.

**Comment by reyoung** [comment]
In the original design of Executor, if `create_local_scopes=False`, the local scopes will not be destroyed. 

https://github.com/PaddlePaddle/Paddle/blob/6332b827ab3f9fb8bd285f69e7409cbaae1b4f6b/paddle/framework/executor.cc#L130-L132

However, it seems the `create_vars` flag change this behaviour on our develop branch.

https://github.com/PaddlePaddle/Paddle/blob/3f8d9b0a119b64a25ff277bee3716da4e15b3311/paddle/fluid/framework/executor.cc#L347-L352

**Comment by emailweixu** [comment]
This needs to be fixed. Otherwise nested while_op does not work. What should be the right way to fix it?

**Review by reyoung — APPROVED** [review]
Merge this HotFix first. I will write a issue to record this problem

**Comment by reyoung** [comment]
The problem is recorded in this issue #11597

**Pull request merged**
