### PR TITLE
Update the api for the compare_ops

### PR DESCRIPTION
**Pull request by wawltor**
### PR types
 Others 

### PR changes
 APIs

### Describe
Fix the compare ops for api 2.0，add dygraph sample

### CODE REVIEW

**Review by TCChenlong — APPROVED** [review]
LGTM

**Review by FlyingQianMM — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by zhiqiu — APPROVED** [review]
LGTM, please upgrade the dygraph branch for op-related API in next PR.

**Pull request merged**
