### PR TITLE
[oneDNN] Fix to inplace pass 

### PR DESCRIPTION
**Pull request by jczaja**
This PR is reenabling inplace pass of oneDNN. It restores the performance of Transformer test (#24373 ).

### CODE REVIEW

**Review by grygielski — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@GaoWei8  @luotao1  This PR fix the slow transformer model performance. Could we merge it in 2.0?

**Review by luotao1 — APPROVED** [review]

**Comment by luotao1** [comment]
@jczaja @lidanqing-intel Could you cherry-pick into release/1.8, we will release version1.8.3 recently.

**Comment by lidanqing-intel** [comment]
This PR need to be cherry-picked to release/1.8. 3rd July will be code-freeze date of 1.8.3

**Pull request merged**
