### PR TITLE
replace the PolynomialDecay、NoamDecay、LinearLrWarmup、ReduceLROnPlateau in fluid with 2.0 version

### PR DESCRIPTION
**Pull request by longranger2**
### PR types
Others

### PR changes
APIs

### Description
- [x] remove the ReduceLROnPlateau in python/paddle/fluid/dygraph/learning_rate_scheduler.py and use ReduceOnPlateau in python/paddle/optimizer/lr.py to replace it.
- [x] remove the PolynomialDecay in python/paddle/fluid/dygraph/learning_rate_scheduler.py and use PolynomialDecay in python/paddle/optimizer/lr.py to replace it.
- [x] remove the LinearLrWarmup in python/paddle/fluid/dygraph/learning_rate_scheduler.py and use LinearLrWarmup in python/paddle/optimizer/lr.py to replace it.
- [x] remove the NoamDecay in python/paddle/fluid/dygraph/learning_rate_scheduler.py and use NoamDecay in python/paddle/optimizer/lr.py to replace it.

### CODE REVIEW

**Comment by longranger2** [comment]
NoamDecay对应的单测发生精度错误：
test_imperative_optimizer.py文件中的TestImperativeOptimizerNoamDecay类中的test_sgd函数报了错误
Mismatched elements: 1 / 1 (100%)
1033: Max absolute difference: 0.00056028
1033: Max relative difference: 0.00131846
1033: x: array(0.424392, dtype=float32)
1033: y: array([0.424952], dtype=float32

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Review by jeff41404 — DISMISSED** [review]
LGTM

**Review by sunzhongkai588 — DISMISSED** [review]
no doc'c changes. LGTM

**Review by sunzhongkai588 — DISMISSED** [review]
no doc'c changes. LGTM

**Review by jeff41404 — DISMISSED** [review]

**Review by leiqing1 — APPROVED** [review]
English docs will be automatically deleted, while Chinese docs should be handled uniformly by framework students @sunzhongkai588

**Review by jeff41404 — APPROVED** [review]

**Pull request merged**
