### PR TITLE
[CodeStyle][task 30] enable ruff C411 rule in python/paddle/base

### PR DESCRIPTION
**Pull request by longranger2**
### PR types
Others

### PR changes
Others

### Description
enable ruff C411 rule in python/paddle/base

- https://github.com/PaddlePaddle/Paddle/issues/57367

### CODE REVIEW

**Comment by gouzil** [comment]
还有残留呀，注意现在的ruff版本为`ruff 0.0.289`
```bash
ruff check .
python/paddle/base/backward.py:763:5: C411 [*] Unnecessary `list` call (remove the outer call to `list()`)
Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

**Comment by longranger2** [comment]
@gouzil done

**Comment by gouzil** [comment]
LGTM，@SigureMo

**Review by SigureMo — APPROVED** [review]
LGTMeow 🐾

**Pull request merged**
