### PR TITLE
Added mul BF16/FP32 FWD/BWD oneDNN kernel

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
Added mul BF16/FP32 FWD/BWD oneDNN kernel for enabling bf16 training

### CODE REVIEW

**Review by pawelpiotrowicz — DISMISSED** [review]
LGTM

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jakpiase** [comment]
Hi @Aganlengzi, it is an op needed for BF16 training, could you please review and merge(CI-APPROVAL is failing due to deleting mul_mkldnn_op.cc from unity_build. I have removed it because there were some build errors caused by the presence of mul_mkldnn_op.cc in that file, and it deleting it was the easiest way to fix that.

**Comment by Aganlengzi** [comment]
> Hi @Aganlengzi, it is an op needed for BF16 training, could you please review and merge(CI-APPROVAL is failing due to deleting mul_mkldnn_op.cc from unity_build. I have removed it because there were some build errors caused by the presence of mul_mkldnn_op.cc in that file, and it deleting it was the easiest way to fix that.

@Avin0323 hi, Plz help check deleting mul_mkldnn_op.cc from unity_build_rule.cmake.

**Review by Avin0323 — APPROVED** [review]
LGTM for unity_build_rule.cmake

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
