### PR TITLE
[Clean Fluid]Remove py_reader/double_buffer/create_py_reader_by_data/load from fluid.layer.io

### PR DESCRIPTION
**Pull request by sljlp**
### PR types

New features
### PR changes

APIs
### Describe

Remove py_reader/double_buffer/create_py_reader_by_data/load/read_file from fluid.layer.io

### CODE REVIEW

**Review by XieYunshen — DISMISSED** [review]
LGTM
单测删除

**Review by XieYunshen — APPROVED** [review]

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Review by jzhang533 — APPROVED** [review]
LGTM for API removing

**Review by LiYuRio — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]

**Pull request merged**
