### PR TITLE
Add log when EnableMKLDN() and EnableMemoryOptim() are both set

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types
Others

### PR changes
Others

### Describe
When `config.EnableMKLDNN()` and `config.EnableMemoryOptim()` are both set ON, "memory_optimize_pass" will not be added, also notify users to use `config.SetMkldnnCacheCapacity(xx)` when mkldnn enabled.

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@baoachun I checeked yesterday, when use_mkldnn_ is on, setting enable_memory_optim will not work, I added a log here, what do you think?

**Comment by lidanqing-vv** [comment]
@wozna Could you please review this ? We can discuss about it too.

**Review by jakpiase — DISMISSED** [review]
LGTM

**Review by wozna — DISMISSED** [review]
LGTM

**Review by jczaja — DISMISSED** [review]
LGTM

**Pull request closed without merging**
