### PR TITLE
[PHI decoupling] remove "paddle/fluid/operators/amp/fp16_type_traits.h" in phi

### PR DESCRIPTION
**Pull request by huangjiyi**
### PR types

Others

### PR changes

Others

### Describe

remove "paddle/fluid/operators/amp/fp16_type_traits.h" in phi

- #47615 

changes:
- replace `#include "paddle/fluid/operators/amp/fp16_type_traits.h"` by `#include "paddle/phi/common/amp_type_traits.h"` and replace `paddle::operators::details::MPTypeTrait` by `phi::dtype::MPTypeTrait` in relevant files.

### CODE REVIEW

**Comment by huangjiyi** [comment]
@ZzSean，帮忙看一下 OP-benchmark 的问题

**Comment by huangjiyi** [comment]
@luotao1 , @YuanRisheng

**Comment by luotao1** [comment]
@YuanRisheng 除了 Op-benchmark 外，其余 CI 都已经过了，可以先进行 review

**Review by YuanRisheng — DISMISSED** [review]

**Comment by huangjiyi** [comment]
Conflict resolved.

**Comment by huangjiyi** [comment]
@YuanRisheng ，麻烦再 review 一下

**Comment by huangjiyi** [comment]
@ZzSean , 帮忙看下 OP-benchmark 的问题

**Review by YuanRisheng — APPROVED** [review]

**Review by ZzSean — APPROVED** [review]
LGTM for CI-OP-Benchmark

**Pull request merged**
