### PR TITLE
【complex op】No.18 add complex support for silu

### PR DESCRIPTION
**Pull request by BeingGod**
### PR types

Others

### PR changes

APIs

### Description

add support complex for `silu`
https://github.com/PaddlePaddle/Paddle/issues/56145

### CODE REVIEW

**Comment by BeingGod** [comment]
PTAL @GGBond8488 @ScottWong98

**Review by ScottWong98 — APPROVED** [review]
LGTM

**Review by GGBond8488 — APPROVED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]

**Comment by luotao1** [comment]
@BeingGod 请对应修改下中文文档

**Comment by luotao1** [comment]
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/9105149/job/23785843
61d6a1142857925463164164afe5ee5d
编译有冲突，需要revert或者修复一下。和下面的代码冲突了，提了一样的内容
5590a435af0d5c014c55933de9368a07

**Pull request merged**
