### PR TITLE
Compile cblas library as static

### LINKED ISSUE #6309: docker image paddlepaddle/paddle does not work
```bash
➜  ~ docker pull paddlepaddle/paddle
Using default tag: latest
latest: Pulling from paddlepaddle/paddle
Digest: sha256:85d238e657416ecfb728f29e80e33848eeff199d6c3b9da881af3aa80aeeeb3c
Status: Image is up to date for paddlepaddle/paddle:latest
➜  ~ docker run -v `pwd`:/data paddlepaddle/paddle python /data/test_recognize_digits_conv.py                
Traceback (most recent call last):
  File "/data/test_recognize_digits_conv.py", line 4, in <module>
    import paddle.v2.fluid as fluid
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/__init__.py", line 2, in <module>
    import framework
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/framework.py", line 4, in <module>
    from . import core
ImportError: libcblas.so: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by Yancey1989**
Fixed #6309

### CODE REVIEW

**Comment by tensor-tang** [comment]
hi, @Yancey1989 

MKLML do not have static lib yet, maybe you can not directly change it.

**Comment by Xreki** [comment]
@tensor-tang I think it is OK. The `cblas` library is not the mklml itself, but a wrapper library to link `mklml` or `openblas`. The source code is a `dummy` file. It is used to record the dependency. And the CI passed too.

**Comment by tensor-tang** [comment]
I do not think CI can test this case, like the #6309 is not tested.

Have you ever try locally after this change?

**Comment by tensor-tang** [comment]
> The source code is a dummy file. It is used to record the dependency

If it is really what you said just recording the dependency, then why changing this to static can help the issue #6309 since MKLML do not have static.

And I found this code is change from from this:
https://github.com/PaddlePaddle/Paddle/commit/2be3d32711c150d9d6cdb94124a6ecaa3c7ac0fe#diff-382e124cc9d4782c4a25018bc3fff9a8L76 on purpose #3461

**Comment by Yancey1989** [comment]
Hi @tensor-tang 

> Have you ever tried locally after this change?

Yes, it passed the test.

> I think the way to solve the issue is to link the mklml.so with cblas.so, not directly change it to static.

the cblas library is just a wrapper, and built from `dummy.c`, and it's easier to depend on OpenBlas or MKL, like:
`cc_library(xxx SRCS xxx.c DEPS cblas)`

and the cblas will depend MKL if `WITH_MKL=ON`
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/openblas.cmake#L128

**Comment by Yancey1989** [comment]
> And I found this code is change from this:
2be3d32#diff-382e124cc9d4782c4a25018bc3fff9a8L76 on purpose #3461

I saw this PR make the cblas as a dynamic library. Sorry I'm not sure why cblas must be a .so, just because mkl is a .so ( or other reason)?

**Comment by tensor-tang** [comment]
I have tried locally.

The mkl.so is contained in the so, so the cblas.a would not bother now.

**Pull request merged**
