### PR TITLE
Added a Python interface to Context::set_debug_level in XDNN for setting the XPUAPI_DEBUG level.

### PR DESCRIPTION
**Pull request by ZibinGuo**
### PR Category
Others

### PR Types
New features

### Description
Added a Python interface to Context::set_debug_level in XDNN for setting the XPUAPI_DEBUG level.

### CODE REVIEW

**Comment by ZibinGuo** [comment]
您的邮件已收到，我将尽快回信。谢谢您！Your email has been received and I will reply as soon as possible. Thank you！

**Review by tizhou86 — APPROVED** [review]
LGTM

**Review by RuohengMa — APPROVED** [review]
LGTM

**Comment by houj04** [comment]
有对应的`get_debug_level`功能不，如果有的话其实可以写个单测，证明刷进去的能被正确读出来。

**Review by ZibinGuo — COMMENTED** [review]
有api库有get_debug_level的功能，后期可以加进去

**Review by houj04 — APPROVED** [review]

**Pull request merged**
