### PR TITLE
[RM FLUID] rm parameter_server

### PR DESCRIPTION
**Pull request by wangzhen38**
### PR types
Others

### PR changes
Others

### Describe
删除parameter_server目录（所依赖文件已替换为新接口）

- python/paddle/fluid/incubate/fleet/parameter_server

### CODE REVIEW

**Review by risemeup1 — DISMISSED** [review]
LGTM for setup.py

**Review by zyfncg — DISMISSED** [review]
LGTM for setup.py.in

**Review by zyfncg — APPROVED** [review]
LGTM for setup.py.in

**Review by risemeup1 — APPROVED** [review]
LGTM

**Review by sunzhongkai588 — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]

**Review by sneaxiy — APPROVED** [review]

**Pull request merged**
