### PR TITLE
[Test Mv]mv dataset test

### PR DESCRIPTION
**Pull request by KimBioInfoStudio**
### PR types

Others
### PR changes

Others
### Describe

https://github.com/PaddlePaddle/Paddle/issues/51853 48

### CODE REVIEW

**Comment by KimBioInfoStudio** [comment]
assume we should also modify test/dataset/CMakeLists.txt, but have no idea on it, could anyone help on it? BTW, test/custom_kernel/CMakeLists.txt also need fix @luotao1  @Zheng-Bicheng

**Comment by Zheng-Bicheng** [comment]
Hey, is there anything wrong with `test/custom_kernel/CMakeLists.txt`？

**Comment by KimBioInfoStudio** [comment]
> Hey, is there anything wrong with `test/custom_kernel/CMakeLists.txt`？

https://github.com/PaddlePaddle/Paddle/blob/develop/test/custom_kernel/CMakeLists.txt#L10

**Comment by tianshuo78520a** [comment]
LGTM

**Review by zhiqiu — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
hi, @KimBioInfoStudio 
- 非常感谢你对飞桨框架的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨框架做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~

**Pull request merged**
