### PR TITLE
Fix isnan compiling error

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types
Bug fixes

### PR changes
Others

### Describe
Fix compiling error when CUDA is OFF.

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@arlesniak @wozna Hi, Please review, this PR fix the compiling error.

**Comment by lidanqing-vv** [comment]
Hi, @lijiaqi0612 PR https://github.com/PaddlePaddle/Paddle/pull/37826 caused compiling error with CUDA OFF. This PR fix the compiling error. Could you please review if this is OK ?

**Review by arlesniak — DISMISSED** [review]
LGTM

**Review by baoachun — DISMISSED** [review]
LGTM

**Review by jakpiase — APPROVED** [review]
LGTM

**Pull request closed without merging**
