### PR TITLE
Polish elementwise max min pow document to add more examples.

### PR DESCRIPTION
**Pull request by gongweibao**
1. Change elementwise to Add virtual function such as AddOpOutput AddInputX， so a developer can add additional comments.
2. Change elementwise python functions to run with the rules.

### CODE REVIEW

**Comment by gongweibao** [comment]
image

**Comment by gongweibao** [comment]
image

**Comment by gongweibao** [comment]
image

**Comment by gongweibao** [comment]
image

**Comment by gongweibao** [comment]
image

**Review by guru4elephant — APPROVED** [review]
LGTM. for case 2, I think a figure with some explanation will be better.

**Review by hutuxian — APPROVED** [review]

**Review by gavin1332 — APPROVED** [review]

**Review by kuke — APPROVED** [review]
LGTM

**Pull request merged**
