### PR TITLE
cherry-pick fix dataset py3; fixlogger; add timeout of gloo; modify datanorm op

### PR DESCRIPTION
**Pull request by Thunderbrook**
### PR types
Bug fixes

### PR changes
Others 

### Describe
cherry-pick fix dataset py3 [#25012](https://github.com/PaddlePaddle/Paddle/pull/25012)
cherry-pick fixlogger https://github.com/PaddlePaddle/Paddle/pull/24682
cherry-pick add timeout of gloo https://github.com/PaddlePaddle/Paddle/pull/23436
cherry-pick modify datanorm op https://github.com/PaddlePaddle/Paddle/pull/23030

### CODE REVIEW

**Review by fuyinno4 — APPROVED** [review]

**Review by zhiqiu — APPROVED** [review]
LGTM for `unused_var_check.cc`

**Review by swtkiwi — APPROVED** [review]
LGTM

**Review by raindrops2sea — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
