### PR TITLE
Set expected place in child thread for dataloader to avoid costing cuda memory on other card

### PR DESCRIPTION
**Pull request by zhiqiu**
### PR types

Bug fixes
### PR changes

Others
### Describe

Set expected place in child thread for dataloader to avoid costing cuda memory on other card

`cudaSetDevice()` is valid inside host thread, so the child thread in dataloader may have the default device id (0) if not set explicitly, which may cost about 500MB memory on card 0.

It is worse when doing multi-card training in dygraph, since each process will cost about 500MB memory on card 0.

### CODE REVIEW

**Review by chenwhql — APPROVED** [review]
LGTM

**Review by heavengate — APPROVED** [review]
LGTM for multi-process DataLoader

**Review by Xreki — APPROVED** [review]
LGTM for the change of framework.py

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
