### PR TITLE
clean the `layer_function_generator.py`

### LINKED ISSUE #63734: templatedoc 机制清理
## 背景

框架现存部分 API 文档使用了 `@templatedoc` 装饰器来通过提取 OP 定义中的参数描述来自动生成 docstring，比如 `row_conv`：

https://github.com/PaddlePaddle/Paddle/blob/08c0424a595199d7bc25fb7b6c138e8e31a7f4b2/python/paddle/static/nn/common.py#L3337-L3383

很明显，它通过其模板部分（如 `${comment}`、`${x_type}`、`${x_comment}` 等）是通过 OpMaker 中的参数描述来填充的：

https://github.com/PaddlePaddle/Paddle/blob/08c0424a595199d7bc25fb7b6c138e8e31a7f4b2/paddle/fluid/operators/row_conv_op.cc#L77-L135

可以猜测，当初的设计是为了避免重复书写参数描述，但是这样一方面会导致文档编写不直观，另一方面 IDE 无法通过静态分析获取完整的 docstring，开发体验较差。而 OpMaker 在未来是会被清理的，因此我们需要将这部分文档迁移到 docstring 中。

另外，因为一些 fluid 等的历史原因，我们框架内也存在了两份 `layer_function_generator.py`（`templatedoc` 的定义文件），因此我们希望尽可能清理掉无用的函数 / 文件，保持框架代码的整洁

## 目标

-  清理无用 `templatedoc` 装饰器的使用，将 OP 定义中的参数描述添加到现有的 docstring 中（不必清理 OpMaker 中的，只需要 copy 到 docstirng 即可），清理后框架不再存在 `templatedoc` 装饰器的使用
-  清理掉 `templatedoc` 函数定义，清理 `layer_function_generator.py`（`python/paddle/base/layers/layer_function_generator.py` 和 `python/paddle/tensor/layer_function_generator.py`）无用函数
-  清理 `layer_function_generator.py` 其余函数（如 `add_sample_code`，看是否能完全清理掉，此为进取项）

> [!TIP]
>
> PR 应拆尽拆，尽可能每个 PR 只做一件事情～

## 收益

-  确保框架内代码整洁性，无冗余代码
-  确保 OpMaker 清理后不会导致 API 文档的破坏和丢失
-  提升开发体验，IDE 可以通过静态分析获取完整的 docstring

### PR DESCRIPTION
**Pull request by ooooo-create**
### PR Category

Others 

### PR Types

Others 

### Description

#63734 part4
clean the `layer_function_generator.py` to decouple op_proto with docstring
@SigureMo 

closes #63734

### CODE REVIEW

**Comment by SigureMo** [comment]
```
2024-04-25 01:38:52 ************************************
2024-04-25 01:38:52 It is forbidden to disable or delete the unit-test.
2024-04-25 01:38:52 
2024-04-25 01:38:52 If you must delete it temporarily, please add it to[https://github.com/PaddlePaddle/Paddle/wiki/Temporarily-disabled-Unit-Test].
2024-04-25 01:38:52 Then you must have one RD (kolinwei(recommended), chalsliu, XieYunshen or zhouwei25) approval for the deletion of unit-test. 
2024-04-25 01:38:52 
2024-04-25 01:38:52 If you have any problems about deleting unit-test, please read the specification [https://github.com/PaddlePaddle/Paddle/wiki/Deleting-unit-test-is-forbidden]. 
2024-04-25 01:38:52 
2024-04-25 01:38:52 Following unit-tests are deleted in this PR: 
```

好像是误检，merge 下 develop 重试下吧

**Comment by ooooo-create** [comment]
> ```
> 2024-04-25 01:38:52 ************************************
> 2024-04-25 01:38:52 It is forbidden to disable or delete the unit-test.
> 2024-04-25 01:38:52 
> 2024-04-25 01:38:52 If you must delete it temporarily, please add it to[https://github.com/PaddlePaddle/Paddle/wiki/Temporarily-disabled-Unit-Test].
> 2024-04-25 01:38:52 Then you must have one RD (kolinwei(recommended), chalsliu, XieYunshen or zhouwei25) approval for the deletion of unit-test. 
> 2024-04-25 01:38:52 
> 2024-04-25 01:38:52 If you have any problems about deleting unit-test, please read the specification [https://github.com/PaddlePaddle/Paddle/wiki/Deleting-unit-test-is-forbidden]. 
> 2024-04-25 01:38:52 
> 2024-04-25 01:38:52 Following unit-tests are deleted in this PR: 
> ```
> 
> 好像是误检，merge 下 develop 重试下吧

现在还是会这样，是删了`globals()['_elementwise_div'] = generate_layer_fn('elementwise_div')`的原因嘛

**Comment by SigureMo** [comment]
> 现在还是会这样，是删了 `globals()['_elementwise_div'] = generate_layer_fn('elementwise_div')` 的原因嘛

看起来和这个 PR 没关系，其他 PR 也有这个问题

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by SigureMo — APPROVED** [review]
LGTMeow

**Pull request merged**
