### PR TITLE
add inference_transpiler doc to develop branch

### PR DESCRIPTION
**Pull request by luotao1**
related #11981 
http://www.paddlepaddle.org/docs/0.14.0/api/fluid/en/transpiler.html#permalink-2-inferencetranspiler

### CODE REVIEW

**Comment by luotao1** [comment]
```
[06:42:34]	API Difference is: 
[06:42:34]	+ paddle.fluid.InferenceTranspiler.__init__ 
```
https://paddleci.ngrok.io/viewLog.html?buildId=1027&buildTypeId=Paddle_PrCi&tab=buildLog&_focus=7887

**Comment by luotao1** [comment]
@reyoung Could you help update the API.spec
https://github.com/PaddlePaddle/Paddle/blob/4ed0b62476031f668d3797c664731b11b0055344/paddle/scripts/paddle_build.sh#L321-L322

**Comment by reyoung** [comment]
This PR must be merged first https://github.com/PaddlePaddle/FluidAPISpec/pull/2

**Review by shanyi15 — APPROVED** [review]
LGTM

**Pull request merged**
