### PR TITLE
[mv fleet] mv fleet to distributed

### PR DESCRIPTION
**Pull request by wangzhen38**
### PR types
Others

### PR changes
Others
### Describe
将python/paddle/incubate/fleet/parameter_server目录下的文件整合（移动到）到python/paddle/incubate/distributed/parameter_server目录下

### CODE REVIEW

**Review by danleifeng — APPROVED** [review]

**Review by zhangbo9674 — APPROVED** [review]
Approve for setup

**Review by zyfncg — APPROVED** [review]
LGTM for setup.py.in

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by aoyulong — APPROVED** [review]
LGTM

**Pull request merged**
