### PR TITLE
[PHI decoupling] remove "gpu_primitives.h" in fluid

### PR DESCRIPTION
**Pull request by GreatV**
### PR types
Others

### PR changes
Others

### Describe
Remove `"gpu_primitives.h"` in `fluid` namespace.
- #48015
- #47615

### CODE REVIEW

**Review by YuanRisheng — DISMISSED** [review]

**Comment by luotao1** [comment]
请解决下冲突

**Comment by GreatV** [comment]
@YuanRisheng @luotao1 @XiaoguangHu01 @ZzSean 麻烦再次 review

**Review by YuanRisheng — APPROVED** [review]

**Review by ZzSean — APPROVED** [review]
LGTM for CI-OP-Benchmark

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
