### PR TITLE
Revert to run distributed unittest serially

### PR DESCRIPTION
**Pull request by wangxicoding**
Time1: Run distributed tests parallelly. https://github.com/PaddlePaddle/Paddle/pull/21751
Time2: Some bugs. Revert them. https://github.com/PaddlePaddle/Paddle/pull/21856
Time3: Fix test_dist_mnist log problem. https://github.com/PaddlePaddle/Paddle/pull/21874

But there seem to be other bugs that haven't been resolved. Revert them again until we resolve it.

### CODE REVIEW

**Comment by luotao1** [comment]
> But there seem to be other bugs that haven't been resolved

What's the other bugs?

**Comment by wangxicoding** [comment]
> > But there seem to be other bugs that haven't been resolved
> 
> What's the other bugs?

test_dist_mnist_hallreduce、test_dist_mnist_multi_comm may failed。。

**Comment by luotao1** [comment]
> test_dist_mnist_hallreduce、test_dist_mnist_multi_comm may failed

Please paste the detailed error message.

**Comment by wangxicoding** [comment]
> > test_dist_mnist_hallreduce、test_dist_mnist_multi_comm may failed
> 
> Please paste the detail error message

test_dist_mnist_multi_comm
http://ci.paddlepaddle.org/viewLog.html?buildId=252923&buildTypeId=Paddle_PrCiNight

test_dist_mnist_hallreduce
http://ci.paddlepaddle.org/viewLog.html?buildId=253915&buildTypeId=Paddle_PrCiPython35Night

Look like RPC timeout.
image

**Pull request merged**
