### PR TITLE
[oneDNN]elementwise_add and elementwise_mul int8 support

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
 New features 
### PR changes
Ops 
### Describe
This PR introduced unified implementation of oneDNN elementwise ops. elementwise_add & elementwise_mul int8 oneDNN kernels were added.  it is build on PR #24812 , but some fix to unit tests were added.

### CODE REVIEW

**Comment by jczaja** [comment]
@luotao1 I have overtaken work on #24812 . This PR contains #24812 and small fix in oneDNN integration to fix UT. To pass CI (PR_CI_CPU_Py2) it is needed to have approve from engineers of your team. Could you please approve that one?   

The second favour to ask is that I cannot see logs of PR_Windows_CI (I can see PR_CI_CPU_Py2). Could you please show the error of Windows CI builds?

**Comment by luotao1** [comment]
> To pass CI (PR_CI_CPU_Py2) it is needed to have approve from engineers of your team. Could you please approve that one?

It's hard to understand why the document of tensor API changes. @lelelelelez Could you help see it?

> The second favour to ask is that I cannot see logs of PR_Windows_CI (I can see PR_CI_CPU_Py2). Could you please show the error of Windows CI builds?

Windows machine has some problem, and it may not upload the CI log. I have rerun the windows
CI. @lelelelelez Please take a look about it.

**Review by wojtuss — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 Could you please provide log (or part of it) for PR_Windows_CI (or just restart if random failure) ?

**Comment by luotao1** [comment]
I rerun it.

**Comment by jczaja** [comment]
@luotao1 Thanks for reruning windows CI. So currently the only errors are due to lack of approval. Can you advice what can I do to have this PR approved?

**Review by arlesniak — COMMENTED** [review]
LGTM

**Comment by luotao1** [comment]
@jczaja 

> So currently the only errors are due to lack of approval.

   > It's hard to understand why the document of tensor API changes.

We will see how to fix it at first.

**Comment by lelelelelez** [comment]
@jczaja  @luotao1 
> It's hard to understand why the document of tensor API changes.

The reason is that this PR `AddAttr` in `elementwise_op.h`, but these attributes and comments should not be shown to users. Thus, you should add these attributes in `skip_attrs_set`  In `python/paddle/tensor/math.py` and `python/paddle/fluid/layers/nn.py `
Please refer to https://github.com/PaddlePaddle/Paddle/pull/25019/commits/549d02cb1ba6c66b277a6e7accafbfdab8b0154f 
In addition, you can re-edit your PR description to retrigger  CheckPRTemplate CI.

**Comment by jczaja** [comment]
@lelelelelez Thanks for pointing a solution to problem. Still there are approvals needed to two other issues. could you advice on those as well ?

**Comment by jczaja** [comment]
@luotao1 Could you please help / rerun Windows CI build?

**Comment by lidanqing-vv** [comment]
@luotao1  Could you please help rerun Windows_CI? This PR is important because other models speed -up is relying on this PR. Thanks!

**Review by wojtuss — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 , @lelelelelez Please continue with your reviews

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
```

[13:34:23][Step 1/1] 0. Developers are not allowed to set the check_dygraph field directly, which is set to True by default. If you need to change the check_dygraph field, you must have one RD (phlrain (Recommend) or lanxianghit) review and approve. 
[13:34:23][Step 1/1] The code that do not meet the specification are as follows:
[13:34:23][Step 1/1]  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_add_mkldnn_op.py : 
[13:34:23][Step 1/1] +        self.check_output(check_dygraph=(self.use_mkldnn == False))
[13:34:23][Step 1/1] +            check_dygraph=(self.use_mkldnn == False), atol=int_atol) 
[13:34:23][Step 1/1]  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py : 
[13:34:23][Step 1/1] +        self.check_output(check_dygraph=(self.use_mkldnn == False))
[13:34:23][Step 1/1] +            check_dygraph=(self.use_mkldnn == False), atol=int_atol) 
```
@phlrain Please have a review!

**Review by arlesniak — APPROVED** [review]
LGTM

**Review by phlrain — APPROVED** [review]
LGTM for dygraph = False

**Comment by jczaja** [comment]
@phlrain thanks very much for approving this PR

@luotao1 could you please restart PR_CI_CPU_Py2 ?

**Comment by luotao1** [comment]
> could you please restart PR_CI_CPU_Py2 ?

I rerun it several times, but all fail by network problems. I will rerun it again after the network connect.

**Pull request merged**
