### PR TITLE
[CodeStyle][task 27] Enable Ruff B009 rule in `python/paddle/base`

### PR DESCRIPTION
**Pull request by linzeyang**
### PR types
Bug fixes

### PR changes
Others

### Description
This PR comes after the idea in https://github.com/PaddlePaddle/Paddle/issues/57367.

The purpose is to activate Ruff's B009 check.

Ruff version: 0.0.290

What I've done:

Uncomment "B009", line in pyproject.toml
Take advantage of Ruff to identify and automatically fix relevant violations.
Make sure no B009 violation is found after the fix.
Make sure all local pre-commit hooks pass/skip

@gouzil

### CODE REVIEW

**Comment by gouzil** [comment]
LGTM，@SigureMo

**Review by SigureMo — DISMISSED** [review]
LGTMeow 🐾

**Comment by luotao1** [comment]
需要解决下冲突

**Comment by linzeyang** [comment]
> 需要解决下冲突

冲突已解决 😸

**Review by SigureMo — APPROVED** [review]
> Ruff version: 0.0.290

才发现用的是高版本，注意之后版本需要和我们的 `.pre-commit-config.yaml` 完全对应，否则不确定是否会漏掉 / 多检测出来什么问题

LGTMeow 🐾

**Pull request merged**
