### PR TITLE
RPC Call & Result

### PR DESCRIPTION
**Pull request by sljlp**
### PR types

New features
### PR changes

OPs
### Describe

Adding RPC Call and result OP
cherry pick https://github.com/PaddlePaddle/Paddle/pull/50220

### CODE REVIEW

**Review by phlrain — APPROVED** [review]
该pr是从基于2.4分支 开发的op，cherry-pick到develop中，暂时先放在fluid下，后续随通信库统一迁移

**Review by Aurelius84 — APPROVED** [review]
LGTM for data registration

**Review by XieYunshen — APPROVED** [review]
LGTM for `set_tests_properties(test_rpc_call_result PROPERTIES TIMEOUT "120")`

**Review by LiYuRio — APPROVED** [review]
LGTM

**Review by raindrops2sea — APPROVED** [review]

**Pull request closed without merging**
