### PR TITLE
Replace paddle::platform::DeviceContextPool in test/cpp

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others 

### PR Types

Others 

### Description

Replace paddle::platform::DeviceContextPool to phi::DeviceContextPool in test/cpp

### CODE REVIEW

**Review by wanghuancoder — DISMISSED** [review]
LGTM

**Comment by co63oc** [comment]
@luotao1 CI已完成

**Comment by luotao1** [comment]
冲突了

**Comment by co63oc** [comment]
合入 https://github.com/PaddlePaddle/Paddle/pull/65864

**Pull request closed without merging**
