### PR TITLE
Hidden paddle.fluid.layers.detection_map.

### PR DESCRIPTION
**Pull request by qingqing01**
-  In some sense, there is compatibility impact. 
- Remove this API since uers can use fluid.metrics.DetectionMAP to calculate mAP of cur-batch and accum-batch.

### CODE REVIEW

**Review by heavengate — DISMISSED** [review]
LGTM

**Review by luotao1 — DISMISSED** [review]
LGTM for api.spec

**Review by heavengate — APPROVED** [review]

**Comment by qingqing01** [comment]
```
[04:38:22]
++ python /paddle/tools/check_pr_approval.py 2 50069408 46782768 30176695 6836917 7845005
[04:38:22]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[04:38:22]
                                 Dload  Upload   Total   Spent    Left  Speed
[04:38:22]
[04:38:23]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[04:38:24]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[04:38:24]
  2  5418    2   142    0     0     86      0  0:01:03  0:00:01  0:01:02    86
[04:38:24]
100  5418  100  5418    0     0   3283      0  0:00:01  0:00:01 --:--:--  3283
[04:38:24]
+ APPROVALS=FALSE
[04:38:24]
+ '[' FALSE == TRUE ']'
[04:38:24]
+ echo 'current pr 18033 got approvals: FALSE'
[04:38:24]
current pr 18033 got approvals: FALSE
[04:38:24]
+ '[' FALSE == FALSE ']'
[04:38:24]
+ '[' paddle/fluid/API.spec == paddle/fluid/API.spec ']'
[04:38:24]
You must have one RD (chengduoZH or XiaoguangHu01 or qingqing01 or luotao1) and one PM (xsrobin) approval for the api change! paddle/fluid/API.spec for the management reason of API interface and API document.
[04:38:24]
+ echo 'You must have one RD (chengduoZH or XiaoguangHu01 or qingqing01 or luotao1) and one PM (xsrobin) approval for the api change! paddle/fluid/API.spec for the management reason of API interface and API document.'
[04:38:24]
+ exit 1
```

@luotao1 please help to review.

**Review by luotao1 — APPROVED** [review]

**Review by xsrobin — APPROVED** [review]
LGTM

**Pull request merged**
