### PR TITLE
Add profiler in tracer

### PR DESCRIPTION
**Pull request by chengduoZH**
The profile result:

b18f7a3485f993df71a39acdd

### CODE REVIEW

**Comment by chengduoZH** [comment]
```
import numpy as np
import paddle
import paddle.fluid as fluid
from paddle.fluid.optimizer import AdamOptimizer
from paddle.fluid.dygraph.nn import Conv2D, Pool2D, FC
from paddle.fluid.dygraph.base import to_variable

import paddle.fluid.profiler as profiler
import contextlib

@contextlib.contextmanager
def profile_context(profile=True):
    if profile:
        with profiler.profiler('All', 'total', '/tmp/profile_file'):
            yield
    else:
        yield


class MNIST(fluid.dygraph.Layer):
    def __init__(self, name_scope):
        super(MNIST, self).__init__(name_scope)

        self.conv1 = Conv2D(self.full_name(), 1, 20, 5, act="relu")
        self.pool1 = Pool2D(self.full_name(), 2, "max", 2)

        self.conv2 = Conv2D(self.full_name(), 20, 50, 5, act="relu")
        self.pool2 = Pool2D(self.full_name(), 2, "max", 2)

        pool_2_shape = 50 * 4 * 4
        hidden_size = 10
        scale = (2.0 / (pool_2_shape**2 * hidden_size))**0.5

        self._fc = FC(self.full_name(),
                      hidden_size,
                      param_attr=fluid.initializer.NormalInitializer(
                          loc=0.0, scale=scale),
                      act="softmax")

    def forward(self, inputs, label=None):
        x = self.conv1(inputs)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.pool2(x)
        x = self._fc(x)
        if label is not None:
            acc = fluid.layers.accuracy(input=x, label=label)
            return x, acc
        else:
            return x


def train_mnist():
    epoch_num = 5
    batch_size = 64
    with fluid.dygraph.guard():
        mnist = MNIST("mnist")
        adam = AdamOptimizer(learning_rate=0.001)
        train_reader = paddle.batch(
            paddle.dataset.mnist.train(), batch_size=batch_size, drop_last=True)

        for epoch in range(epoch_num):
            for batch_id, data in enumerate(train_reader()):
                dy_x_data = np.array([x[0].reshape(1, 28, 28)
                                      for x in data]).astype('float32')
                y_data = np.array(
                    [x[1] for x in data]).astype('int64').reshape(-1, 1)

                enable_profile = batch_id > 10
                with profile_context(batch_id > 10):
                    img = to_variable(dy_x_data)
                    label = to_variable(y_data)
                    label.stop_gradient = True

                    cost, acc = mnist(img, label)
                    loss = fluid.layers.cross_entropy(cost, label)
                    avg_loss = fluid.layers.mean(loss)
                    avg_loss.backward()
                    adam.minimize(avg_loss)
                    mnist.clear_gradients()

                print("Loss at epoch {} step {}: {:}".format(epoch, batch_id,
                                                             avg_loss.numpy()))
                if enable_profile:
                    return


train_mnist()
```

The output is:
```
W0524 05:57:42.187705 125773 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0524 05:57:42.330349 125773 device_context.cc:269] device: 0, cuDNN Version: 7.0.


Loss at epoch 0 step 0: [2.3055472]
Loss at epoch 0 step 1: [2.3346252]
Loss at epoch 0 step 2: [2.3809848]
Loss at epoch 0 step 3: [1.9921563]
Loss at epoch 0 step 4: [1.9680856]
Loss at epoch 0 step 5: [1.8520021]
Loss at epoch 0 step 6: [1.7022424]
Loss at epoch 0 step 7: [1.6207304]
Loss at epoch 0 step 8: [1.4558885]
Loss at epoch 0 step 9: [1.4461592]
Loss at epoch 0 step 10: [1.273119]

------------------------->     Profiling Report     <-------------------------

Place: All
Time unit: ms
Sorted by total time in descending order in the same thread

Event                            Calls       Total       CPU Time (Ratio)        GPU Time (Ratio)        Min.        Max.        Ave.        Ratio.
thread0::Imperative Backward     1           1.82378     0.001024 (0.000561)     1.822761 (0.999439)     1.82378     1.82378     1.82378     0.228815
thread0::conv2d                  2           1.18326     0.429237 (0.362757)     0.754026 (0.637243)     0.48146     0.701803    0.591632    0.148454
thread0::conv2d_grad             2           0.900912    0.419199 (0.465305)     0.481713 (0.534695)     0.318911    0.582001    0.450456    0.11303
thread0::scale                   12          0.497125    0.420194 (0.845248)     0.076931 (0.154752)     0.033504    0.062052    0.0414271   0.0623701
thread0::adam                    6           0.465865    0.350151 (0.751615)     0.115714 (0.248385)     0.06372     0.108002    0.0776442   0.0584482
thread0::elementwise_add         3           0.432276    0.265965 (0.615267)     0.166311 (0.384733)     0.121315    0.170375    0.144092    0.0542341
thread0::merge_grads             13          0.410621    0.315220 (0.767667)     0.095401 (0.232333)     0.01903     0.047403    0.0315862   0.0515172
thread0::pool2d                  2           0.349667    0.167066 (0.477786)     0.182601 (0.522214)     0.162041    0.187626    0.174834    0.0438698
thread0::relu                    2           0.244479    0.119524 (0.488893)     0.124955 (0.511107)     0.111332    0.133147    0.12224     0.0306727
thread0::mul                     1           0.231781    0.022431 (0.096777)     0.209350 (0.903223)     0.231781    0.231781    0.231781    0.0290796
thread0::softmax                 1           0.205684    0.012160 (0.059120)     0.193524 (0.940880)     0.205684    0.205684    0.205684    0.0258055
thread0::elementwise_add_grad    3           0.182473    0.099482 (0.545188)     0.082991 (0.454812)     0.054672    0.067338    0.0608243   0.0228934
thread0::pool2d_grad             2           0.168044    0.079357 (0.472239)     0.088687 (0.527761)     0.080381    0.087663    0.084022    0.0210831
thread0::mul_grad                1           0.162218    0.024576 (0.151500)     0.137642 (0.848500)     0.162218    0.162218    0.162218    0.0203521
thread0::cross_entropy2          1           0.132779    0.003072 (0.023136)     0.129707 (0.976864)     0.132779    0.132779    0.132779    0.0166587
thread0::accuracy                1           0.101663    0.007168 (0.070507)     0.094495 (0.929493)     0.101663    0.101663    0.101663    0.0127548
thread0::mean                    1           0.101316    0.005120 (0.050535)     0.096196 (0.949465)     0.101316    0.101316    0.101316    0.0127113
thread0::relu_grad               2           0.096802    0.041986 (0.433731)     0.054816 (0.566269)     0.047648    0.049154    0.048401    0.0121449
thread0::top_k                   1           0.086314    0.005120 (0.059318)     0.081194 (0.940682)     0.086314    0.086314    0.086314    0.0108291
thread0::softmax_grad            1           0.083744    0.006144 (0.073366)     0.077600 (0.926634)     0.083744    0.083744    0.083744    0.0105067
thread0::cross_entropy_grad2     1           0.065667    0.002048 (0.031188)     0.063619 (0.968812)     0.065667    0.065667    0.065667    0.00823869
thread0::mean_grad               1           0.044084    0.002048 (0.046457)     0.042036 (0.953543)     0.044084    0.044084    0.044084    0.00553085

Loss at epoch 0 step 11: [1.131402]
```

**Review by JiabinYang — COMMENTED** [review]
How about add a test here

**Comment by chengduoZH** [comment]
@JiabinYang Currently, the usage of profiler for static graph and dynamic graph is the same, and there has unit test for profiler now, [test_profiler.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_profiler.py).

**Review by JiabinYang — APPROVED** [review]
LGTM

**Pull request merged**
