### PR TITLE
Move content in the buildtools repo into paddle repo

### PR DESCRIPTION
**Pull request by wangkuiyi**
Fixes https://github.com/PaddlePaddle/buildtools/issues/11

### CODE REVIEW

**Comment by wangkuiyi** [comment]
@typhoonzero Do we really need the `root` subdirectory? According to 

https://github.com/PaddlePaddle/buildtools/blob/6839c22073076f3f5ad7a9f8b9e54c51ba4e82f6/manylinux/Dockerfile-x86_64#L42

it seems that this directory is to add a development environment into the releasing Docker image. But we are not supposed to use these images for development, right?

**Comment by wangkuiyi** [comment]
I didn't change any source code, but a unit test failed during CI:

```
[13:07:38]	276/316 Test #276: test_detection_output_op ....................***Failed 1.63 sec
[13:07:38]	F
[13:07:38]	======================================================================
[13:07:38]	FAIL: test_check_output (__main__.TestUnpoolOp)
[13:07:38]	----------------------------------------------------------------------
[13:07:38]	Traceback (most recent call last):
[13:07:38]	File "test_detection_output_op.py", line 45, in test_check_output
[13:07:38]	self.check_output()
[13:07:38]	File "/paddle/python/paddle/v2/fluid/tests/op_test.py", line 321, in check_output
[13:07:38]	self.check_output_with_place(place, atol)
[13:07:38]	File "/paddle/python/paddle/v2/fluid/tests/op_test.py", line 310, in check_output_with_place
[13:07:38]	"Output (" + out_name + ") has diff at " + str(place))
[13:07:38]	AssertionError: Output (Out) has diff at CUDAPlace(0)
[13:07:38]	
[13:07:38]	----------------------------------------------------------------------
[13:07:38]	Ran 1 test in 0.006s
[13:07:38]	
[13:07:38]	FAILED (failures=1)
```

**Comment by typhoonzero** [comment]
@wangkuiyi 

> it seems that this directory is to add a development environment into the releasing Docker image. But we are not supposed to use these images for development, right?

Yes, `root` directory is not needed any more, we should use Dockerfile under Paddle repo as development environment.

**Comment by typhoonzero** [comment]
Seems style check has error, original python code under `buildtools` repo didn't use pre-commit to check the style.

**Pull request merged**
