### PR TITLE
Add LRUCache for fft plans

### PR DESCRIPTION
**Pull request by iclementine**
### PR types

Performance optimization

### PR changes

Ops

### Describe

Add LRUCache for fft plans on cuda and rocm backends.

### CODE REVIEW

**Review by Xreki — DISMISSED** [review]
LGTM for op benchmark ci

**Review by chenwhql — DISMISSED** [review]
LGTM for PADDLE_ENFORCE

**Review by jeff41404 — APPROVED** [review]
lgtm

**Review by Xreki — APPROVED** [review]
LGTM for op benchmark ci

**Review by chenwhql — APPROVED** [review]

**Pull request merged**
