### PR TITLE
[Dy2St]Remove PE logic in @to_static

### PR DESCRIPTION
**Pull request by Aurelius84**
### PR types

Function optimization
### PR changes

APIs
### Describe

动转静模块旧执行器退场

### CODE REVIEW

**Review by zhangbo9674 — COMMENTED** [review]
动转静切换新旧执行器的FLAG是否需要一并清理：
https://github.com/PaddlePaddle/Paddle/blob/8686a74574a4253b73eb3121690962661724a4a1/python/paddle/fluid/framework.py#L123

**Comment by Aurelius84** [comment]
> 动转静切换新旧执行器的FLAG是否需要一并清理：
> 
> https://github.com/PaddlePaddle/Paddle/blob/8686a74574a4253b73eb3121690962661724a4a1/python/paddle/fluid/framework.py#L123

我会额外再提一个PR清理下

**Review by zhangbo9674 — APPROVED** [review]
LGTM

**Review by pangyoki — APPROVED** [review]
LGTM

**Pull request merged**
