### PR TITLE
 remove paddle.static.sparsity and move out sparsity from fluid

### PR DESCRIPTION
**Pull request by GGBond8488**
### PR types
 Others 

### PR changes
APIs

### Describe
In the current paddle version, there are two paths pointing to the same api (sparsity), one of which is paddle.incubate.asp.sparsity, and the other is paddle.static.sparsity, which is obviously unreasonable, so we carefully After discussion and consideration, it is considered that sparsity is not suitable for regularization at present.

So we removed paddle.static.sparsity,kept paddle.incubate.asp.sparsity.  And moved the real implementation of sparsity to paddle.incubate.asp.sparsity

### CODE REVIEW

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Review by zkh2016 — APPROVED** [review]

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by zyfncg — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
