### PR TITLE
【Hackathon 6th Fundable Projects 3 No.138、139】Remove fluid operator fill_zeros_like

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others

### PR Types

Others

### Description

Remove fluid operator fill_zeros_like fill_zeros_like2

### CODE REVIEW

**Review by wanghuancoder — DISMISSED** [review]
LGTM 请 @luotao1 推动合入

**Review by XieYunshen — DISMISSED** [review]

**Comment by luotao1** [comment]
@co63oc 冲突了

**Comment by co63oc** [comment]
已修改

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Pull request merged**
