### PR TITLE
Clean paddle/fluid/platform/device/xpu/xpu_header.h

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others 

### PR Types

Others 

### Description

Clean paddle/fluid/platform/device/xpu/xpu_header.h

### CODE REVIEW

**Comment by co63oc** [comment]
@ForFishes CI已完成辛苦review下

**Review by wanghuancoder — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
冲突了

**Review by ForFishes — APPROVED** [review]
LGTM

**Pull request merged**
