### PR TITLE
remove legacy profiler

### PR DESCRIPTION
**Pull request by zoooo0820**
### PR types

Others
### PR changes

APIs
### Describe

Pcard-67005

This PR is the following part of https://github.com/PaddlePaddle/Paddle/pull/50133

remove legacy profiler apis, including following apis:
`paddle.fluid.profiler.*`
`paddle.utils.profiler.*`

After this change, users are recommended to use new profiler `paddle.profiler`

### CODE REVIEW

**Review by kangguangli — APPROVED** [review]
LGTM for deletion of `test_parallel_executor_profiler.py`

**Review by XieYunshen — APPROVED** [review]
LGTM
单测删除

**Review by luotao1 — APPROVED** [review]

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by sunzhongkai588 — APPROVED** [review]
LGTM

**Pull request merged**
