### PR TITLE
[CINN] Add IdentityOpCleanPass to the Pass execution process of CINN

### PR DESCRIPTION
**Pull request by gongshaotian**
### PR Category

CINN

### PR Types

Bug fixes

### Description

Pcard-67164
Due to some historical resons, useless full op and scale op are inserted at the end of the Program when export models using Paddle. This issue has been resolved in [PR#67570](https://github.com/PaddlePaddle/Paddle/pull/67570), simply export the model again. This PR is designed to address the above-mentioned issues encountered when open CINN execution in some models that cannot be re exported.

### CODE REVIEW

**Comment by gongshaotian** [comment]
0d02c1166b4607fdae7f713ddee5c179
after | before

**Review by yuanlehome — DISMISSED** [review]

**Review by Hongqing-work — COMMENTED** [review]
这个pass放在ApplyShapeOptimizationPass语义上会不会有点奇怪

**Comment by zyfncg** [comment]
> 这个pass放在ApplyShapeOptimizationPass语义上会不会有点奇怪

语义上确实不太合适

**Comment by gongshaotian** [comment]
> > 这个pass放在ApplyShapeOptimizationPass语义上会不会有点奇怪
> 
> 语义上确实不太合适
已修改

**Review by zyfncg — APPROVED** [review]

**Pull request merged**
