### PR TITLE
Fix unittest dataset error 

### PR DESCRIPTION
**Pull request by gongweibao**
The tests on same dataset can't run parallel since they will change local dataset.

test | dataset
-- | --
test_imperative_resnet | flowers
test_imperative_mnist | mnist
test_imperative_se_resnext | flowers
test_dist_mnist | mnist
test_dist_se_resnext | flowers

### CODE REVIEW

**Review by Yancey0623 — APPROVED** [review]
lgtm, need @luotao1 approving for the cmake changing.

**Comment by Yancey0623** [comment]
Can we refine the dataset so that we can execute theses unit test concurrently.

**Review by luotao1 — APPROVED** [review]

**Comment by luotao1** [comment]
> Can we refine the dataset so that we can execute theses unit test concurrently.

@gongweibao How do you think about it?

**Comment by gongweibao** [comment]
嗯。可以。

**Pull request merged**
