### PR TITLE
Make separate folders for mkldnn codes

### PR DESCRIPTION
**Pull request by kbinias**
Related to #15405

### CODE REVIEW

**Review by luotao1 — COMMENTED** [review]
Do you forget remove `paddle/fluid/operators/conv_mkldnn_op.cc`?

**Comment by kbinias** [comment]
> 
> 
> Do you forget remove `paddle/fluid/operators/conv_mkldnn_op.cc`?

Yes. After git pull this file was duplicated.

**Comment by luotao1** [comment]
@kbinias Could you solve the conflict and fix the unit-test fail in CI?

**Comment by kbinias** [comment]
100% tests passed but I got the following error:
```
[22:08:14] :	 [Step 1/1] You must have panyx0718 approval for the const_cast
[22:08:14]W:	 [Step 1/1] + echo 'You must have panyx0718 approval for the const_cast'
[22:08:14]W:	 [Step 1/1] + exit 1
[22:08:21]W:	 [Step 1/1] Process exited with code 1
[22:08:21]E:	 [Step 1/1] Process exited with code 1
[22:08:21]E:	 [Step 1/1] Step Build and test (Command Line) failed
[22:08:21]i: Stopping performance monitoring process
```
Should I correct it in this PR or maybe we should create new PR for cleaning the code ?

**Comment by luotao1** [comment]
@panyx0718 Could you help approve for `const_cast`, this PR only move the location of related codes.

**Review by luotao1 — APPROVED** [review]

**Review by panyx0718 — APPROVED** [review]

**Pull request merged**
