### PR TITLE
【AutoParallel】Promote fuselinear pass in auto-parallel

### PR DESCRIPTION
**Pull request by heavyrain-lzy**
### PR types

Performance optimization
### PR changes

Others
### Description

Pcard-76459
Add a pass before the `fused_linear` pass to promote the performance. This pass mainly solve the following scenario when enabling the MP or TP parallelism:

- The origin `linear` operator as follows:
```
matmul --> add
```
- After enabling `MP`or `TP`, some `linear` operators may become as follows:
```
matmul --> comm_op --> add
```
The communication operator prohibits the `matmul` and `add` from being fused.

#### experiment
Take the experiment on the GPT-3 with 6.7B parameters using the single host with 8 V100 GPUs:
| strategy                             | tokens/s | speed change |
|--------------------------|----------|--------------|
|  no-FusedLinear               |      2166    |       BaseLine         |
| FusedLinear                      |      2203    |       1.71%      |
|  FusedLinear-Promotion  |     2215     |         2.26%    |

### CODE REVIEW

**Review by zhiqiu — COMMENTED** [review]
Add an unittest

**Comment by heavyrain-lzy** [comment]
> Add an unittest

The unittest 'test_auto_parallel_fused_linear_promotion_pass.py' has been added. But the machine of CI/CE can't run the test, because the 'fused_gemm_epilogue' requires the CUDA11.6 at least. I have run the test by myself:
image

**Review by zhiqiu — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
