### PR TITLE
Fix conv act int8 scale

### PR DESCRIPTION
**Pull request by sfraczek**
### PR types
Bug fixes

### PR changes
OPs

### Describe
Make `Scale_out` scale apply to output after activation if fused with activation. When no activation, pass the scale as usual to output_shift_scale.

For conv we had:
act(Scale_out/scale_in_eltwise*residual + Scale_out/(input_scale*weights_scale) * (a*w+b))
So we had to move Scale_out out of the act.

So we want to have:
Scale_out*act(1/scale_in_eltwise*residual + 1/(data_scale*weights_scale)*(a*w+b))

### CODE REVIEW

**Review by jczaja — DISMISSED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@Aganlengzi Hi, could you please merge this PR? It fix conv int8 +activation accuracy bug issue.

**Review by wozna — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
Related PR https://github.com/PaddlePaddle/Paddle/pull/38023

**Comment by lidanqing-vv** [comment]
@baoachun Please review this PR

**Review by baoachun — APPROVED** [review]
LGTM

**Comment by sfraczek** [comment]
@baoachun hi could you please help merge this PR?

**Pull request merged**
