### PR TITLE
[fluid remove]: remove paddle.fluid.layers.detection_map, paddle.fluid.metrics.DetectionMAP and paddle.fluid.evaluator.DetectionMAP

### PR DESCRIPTION
**Pull request by zhengqiwen1997**
### PR types

Others
### PR changes

APIs
### Describe

To clean the code in paddle.fluid, the useless codes should be removed and code still be used should move to a new position.

For function paddle.fluid.layers.detection_map, paddle.fluid.metrics.DetectionMAP and paddle.fluid.evaluator.DetectionMAP, since it is not used in version 2.x, should be removed.

For unittest code where this function is used, if it is aimed to test the old API, it can be removed directly.

### CODE REVIEW

**Review by zoooo0820 — DISMISSED** [review]
LGTM

**Comment by jeff41404** [comment]
also delete `paddle.fluid.metrics.DetectionMAP` and  `paddle.fluid.evaluator.DetectionMAP`, need to be explained in the title.

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Pull request merged**
