### PR TITLE
[1.1] remove unused code in paddle_inference_api.h

### PR DESCRIPTION
**Pull request by luotao1**
Since `SetIncludeMode` function is not called in any other codes, remove this function to make `paddle_inference_api.h` cleaner.

### CODE REVIEW

**Review by wojtuss — CHANGES_REQUESTED** [review]
Please, do not remove this method. The `SetIncludeMode()` is used by our external application for image classification inference. The app is not in the `Paddle` repository, we moved it to the `models` repository (internally for a moment, we will submit a PR with it) and we still need this method.

**Comment by Superjomn** [comment]
This interface seems useless, just two line of codes.

Without this method, one still can make the old application work by modifying the `IRMode` and `ir_passes` in `AnalysisConfig`.

@wojtuss

**Comment by wojtuss** [comment]
@Superjomn , we can go without it, though imho it is useful and less error-prone, as one does not have to remember about adding the `infer_clean_graph_pass` pass required at the beginning of the list of all fuse passes (the feature, which I could not find any documentation about).

**Comment by luotao1** [comment]
> adding the infer_clean_graph_pass pass required at the beginning of the list of all fuse passes

@wojtuss without `infer_clean_graph_pass` at the beginning of the passes, the `test_analyzer_resnet50` runs successfully. Why should add this pass?

Besides, since `paddle_inference_api.h` is published to users and developers, it should be simplify and cautious. Compared with paddle 1.0 tag, there is diff in these lines.

**Comment by wojtuss** [comment]
@luotao1 , last times, when I skipped the `infer_clean_graph_pass` in our application, the optimization process blew up. I will check that again in a moment on the current `develop`.

**Comment by wojtuss** [comment]
@luotao1 , still , without the `infer_clean_graph_pass` there is a segmentation fault in the`GraphPatternDetector::MarkPDNodesInGraph()` method during `conv_bn_fuse_pass`:
```
#0  0x00007ffff5349a14 in paddle::framework::proto::VarDesc::persistable (this=0x0) at /home/wojtuss/repos/PaddlePaddle/Paddle/build/paddle/fluid/framework/framework.pb.h:4269                                   
#1  0x00007ffff5349a92 in paddle::framework::VarDesc::Persistable (this=0x0) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/framework/var_desc.h:107
#2  0x00007ffff6391d9a in paddle::framework::ir::PDNode::<lambda(paddle::framework::ir::Node*)>::operator()(paddle::framework::ir::Node *) const (__closure=0x1543810, x=0x153a940) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/framework/ir/graph_pattern_detector.cc:377
#3  0x00007ffff63a34a7 in std::_Function_handler<bool(paddle::framework::ir::Node*), paddle::framework::ir::PDNode::assert_is_persistable_var()::<lambda(paddle::framework::ir::Node*)> >::_M_invoke(const std::_An
y_data &, <unknown type in /home/wojtuss/repos/PaddlePaddle/Paddle/build/fluid_install_dir/paddle/fluid/inference/libpaddle_fluid.so, CU 0xc22edc2, DIE 0xc2e3bfc>) (__functor=..., __args#0=<unknown type in /home
/wojtuss/repos/PaddlePaddle/Paddle/build/fluid_install_dir/paddle/fluid/inference/libpaddle_fluid.so, CU 0xc22edc2, DIE 0xc2e3bfc>) at /usr/include/c++/5/functional:1857
#4  0x00007ffff63a8825 in std::function<bool (paddle::framework::ir::Node*)>::operator()(paddle::framework::ir::Node*) const (this=0x1543810, __args#0=0x153a940) at /usr/include/c++/5/functional:2267
#5  0x00007ffff63a6849 in paddle::framework::ir::PDNode::Tell (this=0x14a7480, node=0x153a940) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/framework/ir/graph_pattern_detector.h:60
#6  0x00007ffff638f231 in paddle::framework::ir::GraphPatternDetector::MarkPDNodesInGraph (this=0x7fffffffcd00, graph=...) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/framework/ir/graph_pattern_detec
tor.cc:105
#7  0x00007ffff638eca3 in paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::unordered_map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node
*, std::hash<paddle::framework::ir::PDNode*>, std::equal_to<paddle::framework::ir::PDNode*>, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::frame
work::ir::Graph*)>) (this=0x7fffffffcd00, graph=0x11bd6d0, handler=...) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/framework/ir/graph_pattern_detector.cc:81
#8  0x00007ffff542d608 in paddle::framework::ir::ConvBNFusePass::ApplyImpl (this=0x13d7960, graph=std::unique_ptr<paddle::framework::ir::Graph> containing 0x11bd6d0) at /home/wojtuss/repos/PaddlePaddle/Paddle/pa
ddle/fluid/framework/ir/conv_bn_fuse_pass.cc:218
#9  0x00007ffff63c1c33 in paddle::framework::ir::Pass::Apply (this=0x13d7960, graph=std::unique_ptr<paddle::framework::ir::Graph> containing 0x0) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/framework
/ir/pass.cc:31
#10 0x00007ffff63455ba in paddle::inference::analysis::IRPassManager::Apply (this=0x7fffffffd200, passes=std::vector of length 14, capacity 14 = {...}) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/inf
erence/analysis/ir_pass_manager.cc:52
#11 0x00007ffff62f8186 in paddle::inference::analysis::FluidToIrPass::Run (this=0xc72460, graph=0xbf3750) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/inference/analysis/fluid_to_ir_pass.h:96
#12 0x00007ffff631b525 in paddle::inference::analysis::DfgPassManager::RunAll (this=0xc72ab0) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/inference/analysis/pass_manager.cc:41
#13 0x00007ffff62f6708 in paddle::inference::analysis::Analyzer::Run (this=0x7fffffffd510, argument=0x821950) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/inference/analysis/analyzer.cc:121
#14 0x00007ffff53714e2 in paddle::AnalysisPredictor::OptimizeInferenceProgram (this=0x8218b0) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/inference/api/analysis_predictor.cc:237
#15 0x00007ffff536fd9c in paddle::AnalysisPredictor::Init (this=0x8218b0, parent_scope=std::shared_ptr (empty) 0x0, program=std::shared_ptr (empty) 0x0) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/in
ference/api/analysis_predictor.cc:75
#16 0x00007ffff537229b in paddle::CreatePaddlePredictor<paddle::contrib::AnalysisConfig, (paddle::PaddleEngineKind)2> (config=...) at /home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/inference/api/analysis_p
redictor.cc:278
#17 0x0000000000413255 in paddle::Main () at /home/wojtuss/repos/PaddlePaddle/models/fluid/image_classification/capi/infer_image_classification.cc:296
#18 0x000000000040e593 in main (argc=1, argv=0x7fffffffdf80) at /home/wojtuss/repos/PaddlePaddle/models/fluid/image_classification/capi/infer_image_classification.cc:395
```

**Comment by luotao1** [comment]
@wojtuss 

If `infer_clean_graph_pass` must be at the beginning of the passes for your application, could you auto insert it in the codes like `mkldnn_placement_pass`?

**Comment by wojtuss** [comment]
@luotao1 
The `infer_clean_graph_pass` is also used by `test_analyzer_resnet50` because it is the first default pass in the `kExclude` mode used there.

Then I think removing the `infer_clean_graph_pass` from the `all_ir_passes` vector (in `paddle/fluid/inference/analysis/analyzer.h`) and adding the following lines to `paddle/fluid/inference/analysis/analyzer.cc` could satisfy all needs:
```c++
  102 void Analyzer::Run(Argument* argument) {                                                                                     
  103   std::vector<std::string> passes;                                               
  104 #ifdef PADDLE_WITH_MKLDNN                                                        
  105   if (use_mkldnn_) {                                                             
  106     VLOG(3) << "Adding MKL-DNN placement pass";                                  
  107     passes.push_back("mkldnn_placement_pass");                                   
  108   }                                                                              
  109 #endif                                                                           
+ 110   passes.push_back("infer_clean_graph_pass");                                    
+ 111   passes.push_back("graph_viz_pass");  // add graphviz for debug.                
  112   for (auto& pass : ir_passes_) {                                                
  113     if (!disabled_ir_passes_.count(pass)) {                                      
  114       passes.push_back(pass);                                                    
  115       passes.push_back("graph_viz_pass");  // add graphviz for debug.            
  116     }                                                                            
  117   }                                                                              
  118   passes.push_back("graph_viz_pass");                                            
  119   argument->Set(kFluidToIrPassesAttr, new std::vector<std::string>(passes));     
  120                                                                                  
  121   for (auto& x : data_) {                                                        
  122     PADDLE_ENFORCE(x->Initialize(argument));                                     
  123     x->RunAll();                                                                 
  124     PADDLE_ENFORCE(x->Finalize());                                               
  125   }                                                                              
  126 }
```
What do you think?

**Comment by luotao1** [comment]
I think it is OK, I will update the code.

**Review by wojtuss — APPROVED** [review]

**Comment by wojtuss** [comment]
@luotao1 , thank you!

**Pull request merged**
