### PR TITLE
add autogen code support for auc

### PR DESCRIPTION
**Pull request by gouzil**
### PR types

Others
### PR changes

Others
### Describe

add autogen code support for ``auc``

### 相关issues
 * https://github.com/PaddlePaddle/Paddle/issues/51842

### CODE REVIEW

**Review by heavyrain-lzy — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
请解决下冲突

**Comment by heavyrain-lzy** [comment]
请解决一下代码冲突

**Comment by luotao1** [comment]
close due to the following PR is merged:
- #52437

**Pull request closed without merging**
