### PR TITLE
Added ELU FP32 FWD/BWD oneDNN kernel

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
Added ELU FP32 FWD/BWD oneDNN kernel. Just for completeness of our activation kernels coverage, I will add other missing activations in near future. I have also added missing "use_mkldnn" attribute for hardswish activation

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@Silv3S, @piotrekobiIntel , @zuzg , @tsocha   Please review

**Review by Silv3S — APPROVED** [review]

**Comment by jakpiase** [comment]
@jczaja please merge this PR

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Pull request merged**
