### PR TITLE
Fix performance problem in BF16 models

### PR DESCRIPTION
**Pull request by zyfncg**
### PR types

Bug fixes

### PR changes

Others

### Describe

Fix performance problem in BF16 models: [Issue50032](https://github.com/PaddlePaddle/Paddle/issues/50032)

### CODE REVIEW

**Comment by jczaja** [comment]
@zyfncg We have started testing this PR to check performance impact. We will let you know on results.

**Comment by jczaja** [comment]
@zyfncg I got results of bf16 performance problems and they seems to be fixed , so this PR is good to be merged. More detailed inspection will happen in our CI once this PR is merged considering multiple Runs and historical data etc. For now it is good to be merged

**Review by Silv3S — APPROVED** [review]
LGTM

**Review by jiahy0825 — APPROVED** [review]
LGTM

**Review by heavyrain-lzy — APPROVED** [review]

**Pull request merged**
