### PR TITLE
fused_rotary_position_embedding op support GQA for XPU

### PR DESCRIPTION
**Pull request by zhangyk0314**
### PR Category
Others

### PR Types
New features

### Description
fused_rotary_position_embedding op support GQA for XPU

### CODE REVIEW

**Review by ZibinGuo — APPROVED** [review]
LGTM

**Review by XiaociZhang — COMMENTED** [review]
LGTM

**Comment by ZibinGuo** [comment]
您的邮件已收到，我将尽快回信。谢谢您！Your email has been received and I will reply as soon as possible. Thank you！

**Review by RuohengMa — APPROVED** [review]
LGTM

**Review by houj04 — APPROVED** [review]

**Pull request merged**
