### PR TITLE
[Auto Parallel] Reorganize the fold structure

### PR DESCRIPTION
**Pull request by aoyulong**
### PR types

Others

### PR changes

Others

### Description

Pcard-70448
This pr reorganizes the fold structure of auto parallel.
- `dygraph` folder for files for the dygraph auto parallel
- `static` folder for files for the static auto parallel
- the other files located in the same level as dygraph and static folders are common files shared by the dygraph and static auto parallel

### CODE REVIEW

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by zhiqiu — APPROVED** [review]
LGTM

**Review by zhangbo9674 — APPROVED** [review]
LGTM for setup

**Review by zyfncg — APPROVED** [review]
LGTM for setup.py.in

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
