### PR TITLE
fluid API magration : array_read, array_write

### PR DESCRIPTION
**Pull request by feifei-111**
### PR types

Others
### PR changes

Others
### Describe

Remove fluid API array_read, array_write
They are replaced by paddle.tensor.array_read and paddle.tensor.array_write

### CODE REVIEW

**Review by Aurelius84 — DISMISSED** [review]
LGTM

**Review by Aurelius84 — APPROVED** [review]
LGTM

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Pull request merged**
