### PR TITLE
cherry pick#18761 ,fix warpctc dynamic library not found issue on mac and windows platform

### PR DESCRIPTION
**Pull request by silingtong123**
fix warpctc dynamic library not found issue on mac and windows platform
set paddle lib path in core.py by using site.getsitepackages & similar functions

### CODE REVIEW

**Review by liupluswei — APPROVED** [review]
LGTM

**Comment by liushanshan07** [comment]
求问，这个问题是咋解决的。Failed to find dynamic library: libwarpctc.so ( dlopen: cannot load any more object with static TLS )

**Comment by liupluswei** [comment]
> 求问，这个问题是咋解决的。Failed to find dynamic library: libwarpctc.so ( dlopen: cannot load any more object with static TLS )

请问你是在使用paddle的时候碰到这个问题了吗？

**Comment by liushanshan07** [comment]
> > 求问，这个问题是咋解决的。Failed to find dynamic library: libwarpctc.so ( dlopen: cannot load any more object with static TLS )
> 
> 请问你是在使用paddle的时候碰到这个问题了吗？

是的。去掉MKL编译可以解决这个问题。

**Pull request merged**
