### PR TITLE
support prim & cinn test for layer_norm

### PR DESCRIPTION
**Pull request by veyron95**
### PR types

Others
### PR changes

Others
### Describe

Pcard-66975
support prim & cinn test for layer_norm.

### CODE REVIEW

**Review by xiaoguoguo626807 — DISMISSED** [review]
please record the special rtol in doc

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]

**Review by XieYunshen — APPROVED** [review]
LGTM
`set_tests_properties(test_layer_norm_op PROPERTIES TIMEOUT 200)`

**Review by Charles-hit — APPROVED** [review]
please add fp16 and bfp16 test in next pr.

**Pull request merged**
