### PR TITLE
fix en doc and test=document_fix

### PR DESCRIPTION
**Pull request by xjqbest**
fix en doc and test=document_fix
train_from_dataset and infer_from_datatset

### CODE REVIEW

**Comment by xjqbest** [comment]
image

**Review by frankwhzhang — DISMISSED** [review]

**Review by frankwhzhang — APPROVED** [review]

**Comment by xjqbest** [comment]
image

**Comment by xjqbest** [comment]
image

**Review by 123malin — APPROVED** [review]
LGTM

**Review by wanghaoshuang — APPROVED** [review]

**Pull request merged**
