### PR TITLE
Doc fix and enhancement for lstm_unit python wrapper.

### LINKED ISSUE #7156: Doc fix for lstm_unit

### PR DESCRIPTION
**Pull request by pkuyym**
Resolves #7156

### CODE REVIEW

**Comment by pkuyym** [comment]
@sidgoyal78 
Yes, you are right, implementation of `lstm_unit` mainly refers caffe2, and peephole is not supported.
https://github.com/caffe2/caffe2/blob/master/caffe2/operators/lstm_unit_op.h#L1

**Comment by sidgoyal78** [comment]
Oops, as you might have seen already, i think the build failed.

**Comment by pkuyym** [comment]
An random failure, will restart CI ASAP.

**Comment by sidgoyal78** [comment]
@pkuyym : Actually, it is not random. I think this line needs to be corrected:https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/test_layers.py?utf8=%E2%9C%93#L180

**Comment by pkuyym** [comment]
@sidgoyal78  Sorry, my fault, already fix the unit test.  ~ ~

**Comment by sidgoyal78** [comment]
No worries, I think I should have also thought of that while reviewing. So no problems.

**Pull request merged**
