### PR TITLE
[Cleanup][A-10] clean some VarType for test 

### PR DESCRIPTION
**Pull request by co63oc**
### PR types

Others 
### PR changes

Others 
### Description

https://github.com/PaddlePaddle/Paddle/issues/61385

### CODE REVIEW

**Comment by co63oc** [comment]
image

PR-CI-Coverage 重复执行失败

**Comment by SigureMo** [comment]
覆盖率没过不可 rerun，等年后豁免即可

**Comment by co63oc** [comment]
好的

**Comment by luotao1** [comment]
@SigureMo 覆盖率已豁免，可以接着 review

**Review by SigureMo — APPROVED** [review]
LGTMeow

**Pull request merged**
