### PR TITLE
[Executor] remove run_program branch

### PR DESCRIPTION
**Pull request by kangguangli**
### PR types

Others
### PR changes

Others
### Describe

While API `Executor.run` has multiple internal branch, this PR deletes the branch that invokes `core.Executor` cause we have developed a more powerful executor `StandaloneExecutor`. 
Meanwhile, the flag `FLAGS_USE_STANDALONE_EXECUTOR` also need to be deleted. It's used to decide whether use `StandaloneExecutor` or not.

#### Others
Pcard-67004

### CODE REVIEW

**Review by 2742195759 — DISMISSED** [review]
LGTM

**Review by JZ-LIANG — DISMISSED** [review]
LGTM for auto parallel

**Review by From00 — APPROVED** [review]
LGTM

**Review by zhiqiu — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM

**Pull request merged**
