### PR TITLE
Support int64 for op assign_value

### PR DESCRIPTION
**Pull request by liym27**
Support that value type of op `assign_value`  can be `int64`.

### CODE REVIEW

**Review by zhhsplendid — APPROVED** [review]
Should it also support float64? But considering it is not blocking our dy2stat, I will approve this PR. You can change in this PR or TODO it in the future.

**Review by Aurelius84 — APPROVED** [review]
LGTM. But this PR lacks `double` kernel registration, please fill in the reason [here](http://agroup.baidu.com/paddlepaddle/view/office/2348282)

**Comment by liym27** [comment]
> Should it also support float64? But considering it is not blocking our dy2stat, I will approve this PR. You can change in this PR or TODO it in the future.

Yes, float64/bool should be supported too. There are still some bugs that need to be fixed to support float64/bool, so this PR supports `int64` first to avoid blocking dy2stat. `float64` will be supported next PR.

**Comment by liym27** [comment]
> LGTM. But this PR lacks `double` kernel registration, please fill in the reason [here](http://agroup.baidu.com/paddlepaddle/view/office/2348282)

Thanks. Done

**Review by wawltor — APPROVED** [review]
LGTM

**Pull request merged**
