### PR TITLE
[Fluid Clean]Migrate utils files and delete dygraph_to_static dir

### PR DESCRIPTION
**Pull request by Aurelius84**
### PR types

Others
### PR changes

Others
### Describe

[Fluid Clean]Migrate utils files and delete dygraph_to_static dir

### CODE REVIEW

**Review by 2742195759 — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]

**Review by dingjiaweiww — APPROVED** [review]

**Review by YuanRisheng — APPROVED** [review]

**Review by JiabinYang — APPROVED** [review]
LGTM for _C_ops

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by Ligoml — APPROVED** [review]

**Review by momozi1996 — APPROVED** [review]
LGTM

**Pull request merged**
