### PR TITLE
unify gpu context

### PR DESCRIPTION
**Pull request by zhiqiu**
### PR types

Others
### PR changes

Others
### Describe

remove alias name CUDADeviceContext, use phi::GPUContext directly

### CODE REVIEW

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by JamesLim-sy — DISMISSED** [review]
LGTM for op-benchmark ci

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by JamesLim-sy — APPROVED** [review]
LGTM for op-benchmark ci

**Pull request merged**
