### PR TITLE
improve introduction of bfgs args

### PR DESCRIPTION
**Pull request by betterpig**
### PR types

Others
### PR changes

Others
### Describe

improve introduction of bfgs args

### CODE REVIEW

**Review by dingjiaweiww — DISMISSED** [review]

**Comment by shjNT** [comment]
LGTM

**Review by shjNT — DISMISSED** [review]

**Review by zhwesky2010 — COMMENTED** [review]
1D 用大写

**Comment by betterpig** [comment]
> 

done

**Comment by betterpig** [comment]
> 1D 用大写

done

**Review by zhwesky2010 — APPROVED** [review]

**Review by dingjiaweiww — APPROVED** [review]
LGTM

**Pull request merged**
