### PR TITLE
Fix 2 UT error: test_fuse_resnet_unit and test_imperative_auto_mixed_precision

### PR DESCRIPTION
**Pull request by Wong4j**
### PR types
Bug fixes

### PR changes
Others

### Describe
Error:
1. `test_fuse_resnet_unit` failed on P100. (passed on A100)
2. `test_imperative_auto_mixed_precision` failed on P100. (passed on A100 and V100)

This PR add some conditionals to skip test:
1. For `test_fuse_resnet_unit` UT, some ops such as `cudnn_norm_conv` only support gpu arch >= 7.0.  So this unittest should be skipped if gpu arch is less than 7.0.
2. For `test_imperative_auto_mixed_precision`, bf16 precision was originally introduced in Ampere and not supported in P100 and V100. So bf16 test should be skipped if bf16 is not supported by gpu arch (Pascal, Turing, Volta, etc.).

### CODE REVIEW

**Review by zhangbo9674 — APPROVED** [review]
LGTM

**Review by qili93 — APPROVED** [review]
LGTM

**Comment by qili93** [comment]
hi, @Wong4j 

The CLA failed as some of your commits is committed by user "jaywan".

image

And based on the warning below, CLA not passed as "jaywan" is not an Github user.

image

Please try to commit all these three commmits by one Github user to pass the CLA.

Thanks
Qi

**Comment by Wong4j** [comment]
OK, due to wrong user config, I will close this PR and submit another one

**Pull request closed without merging**
