### PR TITLE
Add cuDNN 9.0

### PR DESCRIPTION
**Pull request by jeng1220**
### PR types
New features

### PR changes
OPs

### Description
This PR adds cuDNN 9.0. The cuDNN 9.0 has significantly improved the performance. For example, FP16 and BF16 fused flash attention engine performance has been significantly improved for NVIDIA GPUs:
- Speed-up of up to 50% over cuDNN 8.9.7 on Hopper GPUs.
- Speed-up of up to 100% over cuDNN 8.9.7 on Ampere GPUs.

See [release-notes#cudnn-9-0-0](https://docs.nvidia.com/deeplearning/cudnn/release-notes.html#cudnn-9-0-0) for details.

The major issues are that:
1. The definition of `CUDNN_VERSION` has been changed to `CUDNN_MAJOR * 10000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL` from `CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL`.
2. Multiple **RNN** API are deprecated. See [cudnn/api#api-changes-900](https://docs.nvidia.com/deeplearning/cudnn/api/overview.html#api-changes-900) for details.

This PR resolves above 2 issues.

### CODE REVIEW

**Comment by jeng1220** [comment]
cc @onecatcn for vis

**Review by risemeup1 — DISMISSED** [review]
LGTM

**Comment by risemeup1** [comment]
> cc @onecatcn for vis

请问下这个PR什么时候能够合入？

**Comment by onecatcn** [comment]
2024-03-07 08:46:39 0. You must have one RD (XiaoguangHu01,chenwhql,zhiqiu,Xreki,luotao1,qili93,Aurelius84) approval for the usage of const_cast.
2024-03-07 08:46:39 1. You must have one RD (jiahy0825, zyfncg, chenwhql, YuanRisheng or heavyrain-lzy) approval for including "gflags/gflags.h" or "glog/logging.h" headerfile in paddle/phi headerfiles( paddle/phi/kernels/gpu/cudnn_lstm_cache.h paddle/phi/kernels/gpu/rnn_functor.h). Recommend including third party headers in phi source files(*.cc) instead of phi headerfiles(*.h). Because if phi headerfiles include third party headers like "gflags.h" or "logging.h", error might occur when outside developers use phi headerfiles directly.
2024-03-07 08:46:39 There are 2 approved errors.

**Comment by jiahy0825** [comment]
Can you remove useless `"gflags/gflags.h"` or `"glog/logging.h"` in the header file, or move these codes to .cc file?

You can see the reason below:

> Recommend including third party headers in phi source files(.cc) instead of phi headerfiles(.h). Because if phi headerfiles include third party headers like "gflags.h" or "logging.h", error might occur when outside developers use phi headerfiles directly.

**Review by jiahy0825 — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]
LGTM for const_cast

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by zyfncg — APPROVED** [review]
LGTM

**Pull request merged**
