### PR TITLE
[Fluid API] Remove `shrink_memory`, `create_array` & `array_length`

### PR DESCRIPTION
**Pull request by HermitSun**
### PR types

Others
### PR changes

APIs
### Describe

Clean legacy fluid APIs, including:
- shrink_memory
- create_array
- array_length

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM for 单测删除

**Review by LiYuRio — APPROVED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]
LGTM for API removing

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
