### PR TITLE
Remove TODOs from code

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
Others

### PR changes
Others

### Describe
Delete Intel TODOs from code and convert them to tasks in internal tracker.

### CODE REVIEW

**Review by tsocha — APPROVED** [review]

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by wozna — APPROVED** [review]
LGTM

**Comment by Silv3S** [comment]
@jczaja please merge

**Review by zyfncg — APPROVED** [review]

**Review by jczaja — APPROVED** [review]
LGTM

**Pull request merged**
