### PR TITLE
Delete BASE_SIZE in elementwise_base.h

### PR DESCRIPTION
**Pull request by AnnaTrainingG**
### PR types

Others
### PR changes

OPs
### Describe

Delete BASE_SIZE in elementwise_base.h

本地性能测试结果如下：
op name | axise | dtype | shape | dev (us) | new (us) |  
-- | -- | -- | -- | -- | -- | --
sum | [1] | float32 | [16, 8, 128] | 1.546 | 1.546 | 1.00
sum backward | [1] | float32 | [16, 8, 128] | 2.783 | 2.83 | 1.02
prod | [1] | float32 | [16, 8, 128] | 1.56 | 1.599 | 1.03
prod backward | [1] | float32 | [16, 8, 128] | 4.496 | 4.491 | 1.00

case 比较小 机器波动影响比较大。

### CODE REVIEW

**Review by YuanRisheng — APPROVED** [review]

**Review by qili93 — APPROVED** [review]
LGTM

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Review by xingfeng01 — APPROVED** [review]

**Review by Xreki — APPROVED** [review]
Good work~

**Review by ZzSean — APPROVED** [review]
LGTM for ci op benchmark

**Pull request merged**
