### PR TITLE
Fix 3 unittest errors

### PR DESCRIPTION
**Pull request by Wong4j**
### PR types
Bug fixes

### PR changes
Others

### Describe
Error in 3 UT:

1. `test_fuse_resnet_unit` failed on P100. (passed on A100)
2. `test_imperative_auto_mixed_precision` failed on P100. (passed on A100 and V100)
3. compute-sanitizer reports memory errors in `test_sparse_attention_op`.

Code changes:

1. For `test_fuse_resnet_unit` UT, some ops such as cudnn_norm_conv only support gpu arch >= 7.0. So this unittest should be skipped if gpu arch is less than 7.0.
2. For `test_imperative_auto_mixed_precision`, bf16 precision was originally introduced in Ampere and not supported in P100 and V100. So bf16 test should be skipped if bf16 is not supported by gpu arch (Pascal, Turing, Volta, etc.).
3. For `test_sparse_attention_op`, `nnz` is incorrect when computing `dsoftmax`, which leads to memory error. Use `compute-sanitizer --target-processes all --tool memcheck ctest -R ^test_sparse_attention_op$ -V to reproduce this bug`.

### CODE REVIEW

**Comment by Wong4j** [comment]
Hi @zhangbo9674 @qili93 , I just reopen my PR with correct github user, and add some extra code changes in `sparse_attention_op.cu`.
@Liu-xiandong Please review changes in `sparse_attention_op`.

**Review by qili93 — APPROVED** [review]
LGTM

**Review by Liu-xiandong — APPROVED** [review]
LGTM

**Review by zhangbo9674 — APPROVED** [review]
LGTM

**Pull request merged**
