### PR TITLE
[Cherry-pick] The Second part of new custom op extension in 2.0.1 

### PR DESCRIPTION
**Pull request by chenwhql**
### PR types

Function optimization
### PR changes

Others
### Describe

[Cherry-pick] The Second part of new custom op extension in 2.0.1

### CODE REVIEW

**Review by zhwesky2010 — APPROVED** [review]
LGTM

**Review by Aurelius84 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Review by phlrain — APPROVED** [review]

**Review by raindrops2sea — APPROVED** [review]

**Review by luotao1 — APPROVED** [review]
LGTM

**Review by swtkiwi — APPROVED** [review]
LGTM at requirements.txt

**Review by lanxianghit — APPROVED** [review]

**Review by kolinwei — APPROVED** [review]

**Pull request merged**
