### PR TITLE
[WIP]add the test case for the UVA

### PR DESCRIPTION
**Pull request by wawltor**
### PR types
New features 

### PR changes
OPs

### Describe
add the test case for the UVA  cuda Error：
```python
import time
import numpy
import paddle

ones = numpy.ones((5000000, 200)).astype("float32")
ones = paddle.to_tensor(ones, place=paddle.CPUPlace())
ones.uva()
data = paddle.gather(ones, paddle.to_tensor([0, 2, 3]))
```

The cuda error message as follows:
image

We use the cuda-memcheck to debug the cuda error, the debug message as follows:
image

### CODE REVIEW

**Comment by jeng1220** [comment]
@wawltor ,
Could you try `CUDA_MEMCHECK_PATCH_MODULE=1` ?
```sh
export CUDA_MEMCHECK_PATCH_MODULE=1
cuda-memcheck python your_code.py
```
Reference:
* https://docs.nvidia.com/cuda/cuda-memcheck/index.html#environment-variables

**Comment by wawltor** [comment]
> @wawltor , Could you try `CUDA_MEMCHECK_PATCH_MODULE=1` ?
> 
> ```shell
> export CUDA_MEMCHECK_PATCH_MODULE=1
> cuda-memcheck python your_code.py
> ```
> 
> Reference:
> 
> * https://docs.nvidia.com/cuda/cuda-memcheck/index.html#environment-variables

I try set `CUDA_MEMCHECK_PATCH_MODULE=1`, but no more messages
image
@jeng1220

**Comment by wawltor** [comment]
> > @wawltor , Could you try `CUDA_MEMCHECK_PATCH_MODULE=1` ?
> > ```shell
> > export CUDA_MEMCHECK_PATCH_MODULE=1
> > cuda-memcheck python your_code.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reference:
> > 
> > * https://docs.nvidia.com/cuda/cuda-memcheck/index.html#environment-variables
> 
> I try set `CUDA_MEMCHECK_PATCH_MODULE=1`, but no more messages image

@jeng1220

**Comment by jeng1220** [comment]
@wawltor ,

Have you tried to print some information where `cudaHostRegister` is called?
For instance:
```c
             printf("DEBUG, %p, %zu\n", data_ptr, need_allocate_size);
             auto result = cudaHostRegister(data_ptr, need_allocate_size,
                                            cudaHostRegisterMapped);
             printf("DEBUG, %s\n", cudaGetErrorString(result));
             assert(result == cudaSuccess);
```

What does it show?

**Comment by jeng1220** [comment]
BTW,  after setting `CUDA_MEMCHECK_PATCH_MODULE=1`, does cuBLAS error still exist?

**Comment by wawltor** [comment]
> @wawltor ,
> 
> Have you tried to print some information where `cudaHostRegister` is called? For instance:
> 
> ```c
>              printf("DEBUG, %p, %zu\n", data_ptr, need_allocate_size);
>              auto result = cudaHostRegister(data_ptr, need_allocate_size,
>                                             cudaHostRegisterMapped);
>              printf("DEBUG, %s\n", cudaGetErrorString(result));
>              assert(result == cudaSuccess);
> ```
> 
> What does it show?

there is no error message for the cudaHostRegister

**Comment by wawltor** [comment]
> BTW, after setting `CUDA_MEMCHECK_PATCH_MODULE=1`, does cuBLAS error still exist?

cuBLAS error still exist

**Pull request closed without merging**
