### PR TITLE
Refactor elementwise op grad classes

### PR DESCRIPTION
**Pull request by piotrekobi**
### PR types
Others

### PR changes
Others

### Describe
Refactors the implementation of elementwise operator grad classes into a single class.

### CODE REVIEW

**Comment by jczaja** [comment]
@tsocha , @Silv3S Please help with review

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by Silv3S** [comment]
LGTM

**Comment by piotrekobi** [comment]
I've tested the changes with Jenkins and they don't seem to have any significant impact on model performance or accuracy.

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Pull request merged**
