### PR TITLE
Add common CreateKey for MKLDNN handlers

### PR DESCRIPTION
**Pull request by grygielski**
This PR is next in series of refactoring, templatizing and preparing code for easier MKLDNN v1.0 update.
It implements common CreateKey() variadic template that accepts any number of parameters and create string key from them.

### CODE REVIEW

**Comment by luotao1** [comment]
Please resolve the conflict!

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by grygielski** [comment]
@luotao1 Could You advice me on PR_CI_python35 failing?

**Comment by luotao1** [comment]
It's random fail. There is some random fail on `test_dist`, we are fixing it now. Thus, you can rerun at first.

**Comment by jczaja** [comment]
@luotao1 Please continue your review

**Pull request merged**
