### PR TITLE
[with_data_parallel][part6] remove with_data_parallel in distributed optimizer

### PR DESCRIPTION
**Pull request by kangguangli**
### PR types

Others
### PR changes

APIs
### Describe

由于旧执行器预计在2.5版本退场，相关接口需要提前下线。本PR旨在去除使用了`with_data_parallel`来插入通信算子的`GraphExecutionOptimizer`，改为通过`RawProgramOptimizer`来插入通信算子。

As the PE is expected to be removed in version 2.5, relevant APIs need to be deleted in advance. This PR is intended to remove `GraphExecutionOptimizer` cause it use `with_data_parallel` to insert comm ops。And we use `RawProgramOptimizer` to replace it.

#### 细则 Details
1. 删除了`GraphExecutionOptimizer`
2. 在其他MetaOptimizer的white_list中去掉了`GraphExecutionOptimizer`
3. 对于`RawProgramOptimizer`, 修改了可以启用的条件，避免和其他MetaOptimizer冲突
5. 修改了`paddle/fluid/framework/distributed_strategy.proto`，将`without_graph_optimization`默认修改为True
6. 修改了`test_fleet_graph_executor`和`test_fleet_graph_execution_meta_optimizer`，让它们在去除`GraphExecutionOptimizer`依然能跑通，之后会单独提PR删除
7. 对于hapi/model.py，在对startup_program剪枝时排除`c_comm_init` Op。

#### Relevate PRs
1. #50664 

#### Others
Pcard-67004

### CODE REVIEW

**Review by JZ-LIANG — APPROVED** [review]
LGTM for using raw optimizer for basic DataParallel functionality.

**Review by zhiqiu — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM for 
`"RUN_TYPE=DIST"`

**Pull request merged**
