### PR TITLE
Use ExternalProject_Add to download and install boost.

### PR DESCRIPTION
**Pull request by qingqing01**
Fix https://github.com/PaddlePaddle/Paddle/issues/7708

It is not time-consuming to download, build and install boost by ExternalProject_Add in CMake when I test on my server.

### CODE REVIEW

**Review by typhoonzero — COMMENTED** [review]
Seems boost building command `./b2 install` is generating too much logs, can you make boost build quiet please?

**Comment by qingqing01** [comment]
@typhoonzero 
- In Fluid, we only depend on the header file, so only add `--with-program_options` in installing step.  Do you think is it ok?  
- For the logs, I'll make boost build quiet. Thanks.

**Comment by typhoonzero** [comment]
> In Fluid, we only depend on the header file, so only add --with-program_options in installing step. Do you think is it ok?

I did some search and it seems that [program_options](http://www.boost.org/doc/libs/1_58_0/doc/html/program_options.html) is only one part of the boost libraries that do argument parsing, for paddle we use `gflags` currently maybe it's not needed? I'm not sure you can have some test, if you are testing with docker, try remove the boost installation inside the docker, and maybe the `Dockerfile` under current repo should also be updated.

The build options of boost: https://theboostcpplibraries.com/introduction-installation
Maybe you are looking for `--build-type`?

**Comment by reyoung** [comment]
Paddle does not use any boost library. It is no need to `build` boost.

Just adding the `include_directories` is enough

**Comment by typhoonzero** [comment]
@reyoung was right, download boost and add to `include_directories` is enough, please ignore my comments.

**Comment by qingqing01** [comment]
@typhoonzero @reyoung Thanks!

**Review by reyoung — DISMISSED** [review]
Excellent!

**Review by typhoonzero — APPROVED** [review]
LGTM!

**Pull request merged**
