### PR TITLE
[Cherry-pick] Add FasterTokenizer Operator

### PR DESCRIPTION
**Pull request by Steffy-zxf**
### PR types

 New features

### PR changes

OPs 

### Describe

 Add Tokenizer related functionalities for Transformer model in order that the process of training and predicting is consistent.

* support the text string as an input Tensor 
* support the "VOCAB"`unordered_map<wstring, int>` as an input Tensor to lookup tokens
* Tokenizer used for BERT. This tokenizer applies an end-to-end, text string to wordpiece tokenization. 
   It first applies basic tokenization, followed by wordpiece tokenization.

### Operators

* The bert_tokenizer operator backends on CPU.
* The FasterBertTokenizer API of python end will be implemented on PaddleNLP in the interim programme.

### Example

* train script:

```python
from paddlenlp.datasets import load_dataset
from paddlenlp.experimental import FastBertForSequenceClassification
import paddle

train_ds, dev_ds = load_dataset("chnsenticorp", splits=["train", "dev"])

model = FastBertForSequenceClassification.from_pretrained(
    'bert-base-chinese',
    num_classes=2)

train_data_loader = paddle.io.DataLoader(
    dataset=train_ds, batch_size=32, shuffle=True)

...
```

* export model script:

```python
import paddle
from paddlenlp.experimental import FastBertForSequenceClassification

model = FastBertForSequenceClassification.from_pretrained(
    'bert-base-chinese', num_classes=2)
state_dict = paddle.load("./model_state.pdparams")
model.set_dict(state_dict)
model.eval()
model.to_static_model("./export")
```

* deploy script:

```python
import os

import paddle

model_dir = "export"
model_file = os.path.join(model_dir, "inference.pdmodel")
params_file = os.path.join(model_dir, "inference.pdiparams")
config = paddle.inference.Config(model_file, params_file)
config.enable_use_gpu(100, 0)
predictor = paddle.inference.create_predictor(config)

input_handle = predictor.get_input_handle(
    predictor.get_input_names()[0])
output_handle = predictor.get_output_handle(
    predictor.get_output_names()[0])

data = [
    '这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般',
    '怀着十分激动的心情放映，可是看着看着发现，在放映完毕后，出现一集米老鼠的动画片',
    '作为老的四星酒店，房间依然很整洁，相当不错。机场接机服务很好，可以在车上办理入住手续，节省时间。',
]

input_handle.copy_from_cpu(data)
predictor.run()
logits = output_handle.copy_to_cpu()

```

### CODE REVIEW

**Review by XiaoguangHu01 — DISMISSED** [review]

**Review by TCChenlong — DISMISSED** [review]

**Review by jiweibo — DISMISSED** [review]
LGTM for paddle copy_from_cpu(list[str])

**Review by zhiqiu — DISMISSED** [review]
LGTM

**Review by Aurelius84 — DISMISSED** [review]
LGTM

**Review by Shixiaowei02 — DISMISSED** [review]

**Review by zhwesky2010 — DISMISSED** [review]

**Review by raindrops2sea — DISMISSED** [review]
LGTM

**Review by chenwhql — DISMISSED** [review]

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Review by wawltor — APPROVED** [review]
LGTM

**Review by Aurelius84 — APPROVED** [review]

**Review by TCChenlong — APPROVED** [review]

**Review by Shixiaowei02 — APPROVED** [review]

**Review by chenwhql — APPROVED** [review]

**Review by zhiqiu — APPROVED** [review]

**Review by zhwesky2010 — APPROVED** [review]

**Pull request merged**
