### PR TITLE
remove the optimizer base and learning rate base

### PR DESCRIPTION
**Pull request by longranger2**
### PR types
Others

### PR changes
APIs

### Description
remove the optimizer base and learning rate base in fluid

### CODE REVIEW

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Review by zoooo0820 — APPROVED** [review]

**Review by jeff41404 — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
请解决下冲突

**Review by sunzhongkai588 — APPROVED** [review]
LGTM

**Review by jeff41404 — APPROVED** [review]

**Pull request merged**
