### PR TITLE
add map_matmul and fc_act_fuse passes to quant2_int8_mkldnn_pass

### PR DESCRIPTION
**Pull request by sfraczek**
### PR types
Performance optimization

### PR changes
Others

### Describe
Fixed mkldnn fc with activation.
Also by adding map_matmul passes, all matmul_v2 ops are converted to either matmul or mul. Afterwards mul+elementiwse_add are fused to fc by fc_fuse_pass. 
Adding those 3 map passes fix a problem of crashing introduced by putting matmul_v2_transpose_reshape_fuse_pass in this file. They improve performance. Those passes together with matmul_v2_transpose_reshape fuse pass change accuracy from acc: 0.5478 to 0.5383, but accuracy before this change was higher than reference obtained from tnewst_quant_model.
I also added fc_act_mkldnn_fuse pass which fuses fc+gelu. It improves performance.
Accuracy written in here: https://github.com/PaddlePaddle/Paddle/issues/36962#issuecomment-989856895

### CODE REVIEW

**Review by lidanqing-vv — DISMISSED** [review]
LGTM.

**Review by wozna — DISMISSED** [review]
LGTM

**Review by lidanqing-vv — DISMISSED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@baoachun @Aganlengzi Could you please merge this PR?

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
