### PR TITLE
Use boost::any other than linb::any

### PR DESCRIPTION
**Pull request by wangkuiyi**
In hope to fix https://github.com/PaddlePaddle/Paddle/issues/3283, but not sure if it works.

### CODE REVIEW

**Comment by wangkuiyi** [comment]
I filed two experiments to fix this problem -- 

1. PR #3284 switches from thelink2012/any to boost::any, and
1. PR #3286 switches to a PaddlePaddle's fork of any with the noexcept bug fixed.

Because thelink2012/any doesn't have versioning tags nor two-branch Git branching model, it seems pretty hacky and less maintained project, I'd prefer to merge PR #3284 if it passes CI and suppress the noexcept warning.

**Comment by wangkuiyi** [comment]
Curious -- TeamCity CI passed, but Android-build on Travis CI failed. Could @Xreki @hedaoyuan please have a look at this?

**Comment by Xreki** [comment]
@wangkuiyi We use [Google's NDK](https://developer.android.com/ndk/downloads/index.html) to build PaddlePaddle for Android devices. It does not include a pre-build boost and we have never built boost for Android manually since the dependency of boost is possible to be removed. To access boost for Android, we may need more work. If it is indispensable, I'll fix it.

**Comment by wangkuiyi** [comment]
Close this PR because we need to do something to allow our Android-build to use boost.

**Pull request closed without merging**
