### PR TITLE
Performance and functional fixes to LRN

### PR DESCRIPTION
**Pull request by jczaja**
This PR is improving performance of LRN and fix a bug in it. It does solve the #14346.

- Inaccuracy of LRN was removed.
- Performance of whole googlenet was improved by **~40%** (SKX 8180)
- Added test_analyzer_googlenet

### CODE REVIEW

**Comment by luotao1** [comment]
Please add an unit-test `test_analyzer_googlenet` in this PR.

**Comment by jczaja** [comment]
@luotao1 This PR fix a bug in LRN , but it is not enough to have test_analyzer_googlenet . So I cannot add it in this PR.

**Review by kbinias — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 I managed to fix another LRN problem so now test_analyzer_googlenet was added. 

@kbinias I update review with new fix and enabling test_analyzer_googlenet. Please review updated part

**Review by kbinias — APPROVED** [review]

**Comment by luotao1** [comment]
Thanks very much!
I test googlenet with batchsize=1 and repeat=100 on 2620 v3.

|  | 1 thread | 4 threads |
| ------ | ------ | ------ |
| MKL |95.72ms | 65.99ms |
| MKLDNN before this PR | 87.79ms | 31.74ms |
| MKLDNN after this PR | 67.58ms | 25.48ms |

**Pull request merged**
