### PR TITLE
cleanup of old TODOs

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Others 

### PR changes
Others 

### Describe
Cleaned up some of older TODOs that are no longer relevant

### CODE REVIEW

**Review by Silv3S — APPROVED** [review]

**Comment by jczaja** [comment]
@luotao1 , @Xreki I have a problem with failing PR-CI-OP-benchmark. I have tried to restart this CI job a few times. Failure seems to be unrelated to my changes. Please help to have it completed.

**Comment by luotao1** [comment]
> @luotao1 , @Xreki I have a problem with failing PR-CI-OP-benchmark. I have tried to restart this CI job a few times. Failure seems to be unrelated to my changes. Please help to have it completed.

Done

**Review by wozna — APPROVED** [review]
LGTM

**Review by vivienfanghuagood — APPROVED** [review]
LGTM

**Pull request closed without merging**
