### PR TITLE
Add setting Scope function for the graph class

### PR DESCRIPTION
**Pull request by wzzju**
* Add setting `Scope` function for the graph class in order to call IR passes by using Python.

### CODE REVIEW

**Review by Superjomn — DISMISSED** [review]
LGTM

**Review by fc500110 — DISMISSED** [review]
LGTM

**Review by luotao1 — DISMISSED** [review]
LGTM for remove const_cast

**Comment by wzzju** [comment]
如上图所示，pr中删除了`const_cast`相关的代码，所以触发了如下的CI：

@luotao1

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
