### PR TITLE
add pixel_shuffle FP16 test and BF16 test

### PR DESCRIPTION
**Pull request by superwinner1**
### PR types

Others
### PR changes

Others
### Describe

add pixel_shuffle FP16 tests

### CODE REVIEW

**Comment by superwinner1** [comment]
@ZzSean 麻烦帮我review一下，十分感谢

**Comment by superwinner1** [comment]
@luotao1 可以帮我review下吗，谢谢

**Comment by superwinner1** [comment]
@Vvsmile 麻烦review~下，谢谢

**Comment by Vvsmile** [comment]
FP16单测添加没有问题，但是BF16的单测和API Check Dtype任务最好一同在这个PR里做了

**Comment by superwinner1** [comment]
@Vvsmile 麻烦再review~下，谢谢

**Comment by luotao1** [comment]
close due to the following PR is merged:
- https://github.com/PaddlePaddle/Paddle/pull/52582

**Pull request closed without merging**
