### PR TITLE
remove unused FLAGS_warpctc_dir

### PR DESCRIPTION
**Pull request by luotao1**
since #3783, `FLAGS_warpctc_dir` could be removed.

### CODE REVIEW

**Review by kuke — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
```
[11:04:48]509/519 Test #487: test_warpctc_op .................................***Failed    2.00 sec
[11:04:48]W0429 19:04:48.507172 1742816704 dynamic_loader.cc:107] Can not find library: libwarpctc.dylib. Please try to add the lib path to LD_LIBRARY_PATH.
[11:04:48]W0429 19:04:48.529270 1742816704 dynamic_loader.cc:107] Can not find library: libwarpctc.dylib. Please try to add the lib path to LD_LIBRARY_PATH.
[11:04:48]W0429 19:04:48.542315 1742816704 dynamic_loader.cc:107] Can not find library: libwarpctc.dylib. Please try to add the lib path to LD_LIBRARY_PATH.
[11:04:48]W0429 19:04:48.555681 1742816704 dynamic_loader.cc:107] Can not find library: libwarpctc.dylib. Please try to add the lib path to LD_LIBRARY_PATH.
[11:04:48]W0429 19:04:48.583214 1742816704 dynamic_loader.cc:107] Can not find library: libwarpctc.dylib. Please try to add the lib path to LD_LIBRARY_PATH.
[11:04:48]W0429 19:04:48.611457 1742816704 dynamic_loader.cc:107] Can not find library: libwarpctc.dylib. Please try to add the lib path to LD_LIBRARY_PATH.
[11:04:48]test_warpctc_op failed
[11:04:48] EEEEEE
[11:04:48]======================================================================
[11:04:48]ERROR: test_check_grad (test_warpctc_op.TestCudnnCTCOp)
[11:04:48]----------------------------------------------------------------------
[11:04:48]Traceback (most recent call last):
```
fails on mac http://ci.paddlepaddle.org/viewLog.html?buildId=91141&tab=buildLog&buildTypeId=PaddleMac_MacPrCiPython35&logTab=tree&filter=all

**Review by shanyi15 — DISMISSED** [review]

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by shanyi15 — APPROVED** [review]

**Comment by wopeizl** [comment]
configure_file(warpctc_lib_path.h.in ${CMAKE_CURRENT_BINARY_DIR}/warpctc_lib_path.h)

warpctc_lib_path.h.in  这里面的路径设置在windows下有问题，导致  #17792 bug

**Pull request merged**
