### PR TITLE
[complex op] No.68 add complex support for expand

### PR DESCRIPTION
**Pull request by BeingGod**
### PR types

Others

### PR changes

APIs

### Description

add complex support for `expand`
https://github.com/PaddlePaddle/Paddle/issues/56145

### CODE REVIEW

**Comment by BeingGod** [comment]
PTAL @GGBond8488

**Review by GGBond8488 — COMMENTED** [review]
'x (Tensor): The input Tensor, its data type is bool, float32, float64, int32 or int64.
shape (list|tuple|Tensor): The result shape after expanding. The data type is int32. If shape is a list or tuple, all its elements '
这里加一下complex64 和complex128

**Comment by BeingGod** [comment]
> 'x (Tensor): The input Tensor, its data type is bool, float32, float64, int32 or int64. shape (list|tuple|Tensor): The result shape after expanding. The data type is int32. If shape is a list or tuple, all its elements ' 这里加一下complex64 和complex128

done

**Comment by luotao1** [comment]
@BeingGod 需要解决一下冲突

**Review by GGBond8488 — APPROVED** [review]
LGTM

**Pull request closed without merging**
