### PR TITLE
Add dataset ptb

### LINKED ISSUE #2022: Add a new dataset ptb to support demos
In models repo, language model task is used to demonstrate how to implement language modes using paddle. As a public dataset, PTB is very suitable for the demo mentioned above.

### PR DESCRIPTION
**Pull request by pkuyym**
fixes #2022

### CODE REVIEW

**Comment by pkuyym** [comment]
@lcy-seso @luotao1

**Comment by wangkuiyi** [comment]
@pkuyym Is this package duplicated with https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/imikolov.py ?

**Comment by pkuyym** [comment]
@wangkuiyi no exactly, language mode requires two types of data which are ngram and sequence, imikolov only provides ngram data.

**Comment by wangkuiyi** [comment]
I see. You added some readers, which read from the same tarball file. Is the right way to doing so to add some readers to the existing module `imikolov`; instead to to create a new module?

**Pull request merged**
