### PR TITLE
[Bug fix] reshape_transpose_matmul_mkldnn_fuse_pass failure

### PR DESCRIPTION
**Pull request by baoachun**
### PR types
Others

### PR changes
Others

### Describe
update ut

### CODE REVIEW

**Comment by baoachun** [comment]
Hi @lidanqing-intel , there is a bug in `reshape_transpose_matmul_mkldnn_fuse_pass`.
图片

    
图片


图片

**Comment by lidanqing-vv** [comment]
@baoachun What is its priority?

**Comment by baoachun** [comment]
@lidanqing-intel   The bug needs to be resolved before the release of 2.3, thanks.

**Comment by baoachun** [comment]
In addition, when the `shape` attribute of `reshape` op contains 0 or -1, the output will be calculated incorrectly. Please refer to the code:https://github.com/PaddlePaddle/Paddle/blob/c52a664e86a53c77a3ee33400edb49de36d81f4e/paddle/fluid/operators/matmul_op.cc#L696

**Comment by sfraczek** [comment]
I cloned this branch but I got this error instead
```
======================================================================
ERROR: test (__main__.TestReshapeTransposeMatmulMkldnnFusePass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_reshape_transpose_matmul_fuse_pass.py", line 125, in test
    quant=False, passes=["reshape_transpose_matmul_mkldnn_fuse_pass"])
  File "/mnt/drive/PaddlePaddle/Paddle/build/python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py", line 365, in run_and_statis
    loop_func()
  File "/mnt/drive/PaddlePaddle/Paddle/build/python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py", line 358, in run_test
    return self.run_test(quant=quant, prog_configs=[prog_config])
  File "/home/sfraczek/anaconda3/envs/paddle-default/lib/python3.7/site-packages/hypothesis/core.py", line 1190, in wrapped_test
    raise the_error_hypothesis_found
  File "/mnt/drive/PaddlePaddle/Paddle/build/python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py", line 358, in run_test
    return self.run_test(quant=quant, prog_configs=[prog_config])
  File "/mnt/drive/PaddlePaddle/Paddle/build/python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py", line 404, in run_test
    model, params = create_fake_model(prog_config)
  File "/mnt/drive/PaddlePaddle/Paddle/build/python/paddle/fluid/tests/unittests/ir/inference/program_config.py", line 303, in create_fake_model
    op_desc.infer_shape(main_block_desc)
RuntimeError: (NotFound) Attribute (head_number) should be in AttributeMap.
  [Hint: Expected found == true, but received found:0 != true:1.] (at /mnt/drive/PaddlePaddle/Paddle/paddle/fluid/framework/attribute.h:232)
  [operator < matmul > error]

----------------------------------------------------------------------
Ran 1 test in 0.044s

FAILED (errors=1)
```

**Comment by sfraczek** [comment]
> In addition, when the `shape` attribute of `reshape` op contains 0 or -1, the output will be calculated incorrectly. Please refer to the code:
> 
> https://github.com/PaddlePaddle/Paddle/blob/c52a664e86a53c77a3ee33400edb49de36d81f4e/paddle/fluid/operators/matmul_op.cc#L696

This part is for matmul+transpose+reshape case

**Comment by baoachun** [comment]
Hi @sfraczek , You can change `matmul` to `matmul_v2` and try again. https://github.com/PaddlePaddle/Paddle/blob/907a55b0c29ed94c872261384b3a910b9732e14e/python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_reshape_transpose_matmul_fuse_pass.py#L86

**Comment by sfraczek** [comment]
If I add heads number=1 or change matmul->matmul_v2 (transpose_X->trans_X) I get this thing:
```
SUCCESS: RUN predictor_config {'use_mkldnn': True, 'use_gpu': False, 'use_trt': False} done
===================Statistical Information===================
Number of Generated Programs: 1
Number of Invalid Programs: 0
Number of Ran Programs: 1
Number of Ignore Tests: 0
Number of successfully ran programs approximately equal to 1
satisfied_programs = ran_programs - num_ignore_tests / num_predictor_kinds
At least 25 programs need to ran successfully, but now only about 1 programs satisfied.
FAIL

======================================================================
FAIL: test (__main__.TestReshapeTransposeMatmulMkldnnFusePass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_reshape_transpose_matmul_fuse_pass.py", line 126, in test
    quant=False, passes=["reshape_transpose_matmul_mkldnn_fuse_pass"])
  File "/mnt/drive/PaddlePaddle/Paddle/build/python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py", line 387, in run_and_statis
    assert False
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.367s

FAILED (failures=1)
```

**Comment by sfraczek** [comment]
So we should comment out this part?
https://github.com/PaddlePaddle/Paddle/blob/c52a664e86a53c77a3ee33400edb49de36d81f4e/paddle/fluid/operators/matmul_op.cc#L359-L379

**Comment by sfraczek** [comment]
So I can't really reproduce the issue.

**Comment by baoachun** [comment]
Hi @sfraczek, maybe you can reproduce this problem with following command:
1. Pull this pr, then build paddle with `-DWITH_TESTING=ON` cmake command
2. Run ut by name: `ctest -R test_mkldnn_reshape_transpose_matmul_fuse_pass$ -V` , then you will get this error
图片

I have tried uncommenting line 359 but it causes a lot of model inference failures on CI

**Comment by sfraczek** [comment]
I do it this way but I don't have this error. I have the error with heads number which I solve by setting it to 1 and when I do that I only see the error that only 1 valid program was created and 0 invalid programs out of required  25 programs.

**Comment by baoachun** [comment]
Are you using the latest develop branch code? I have been able to reproduce the problem. Or did you uncomment line 359?

**Comment by sfraczek** [comment]
With latest develop I see it now thanks.

**Comment by sfraczek** [comment]
I have found a solution but it might slightly impact performance. I will look for optimization and create a PR soon.

**Comment by sfraczek** [comment]
I did testing and found no performance impact of the fix.

**Comment by lidanqing-vv** [comment]
@baoachun Hi the fix has been merged, please update this PR. Thanks

**Review by sfraczek — APPROVED** [review]

**Pull request closed without merging**
