### PR TITLE
Remove dependence of scipy

### PR DESCRIPTION
**Pull request by LielinJiang**
### PR types

Function optimization
### PR changes

Others
### Describe

Remove dependence of scipy.

image

### CODE REVIEW

**Review by kolinwei — DISMISSED** [review]

**Review by swtkiwi — COMMENTED** [review]
LGTM

**Review by swtkiwi — DISMISSED** [review]
LGTM

**Comment by swtkiwi** [comment]
> 报错部分是否可以明确指出，需要用户自行安装scipy包呢？

**Review by phlrain — APPROVED** [review]

**Review by kolinwei — APPROVED** [review]

**Review by swtkiwi — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
