### PR TITLE
Replace platform::errors phi::errors in paddle/fluid/distributed/collective

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others 

### PR Types

Others 

### Description

需要迁移分布式算子到phi，替换  paddle/fluid/distributed/collective 目录部分调用为phi调用
 platform::errors phi::errors
platform::DeviceContextPool phi::DeviceContextPool
platform::is_xxx_place phi::is_xxx_place

### CODE REVIEW

**Comment by luotao1** [comment]
冲突了

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Comment by co63oc** [comment]
@ForFishes @sneaxiy CI已完成需要review下

**Review by ForFishes — APPROVED** [review]
LGTM

**Pull request merged**
