### PR TITLE
optimize the GPU inplementation of stack_op

### PR DESCRIPTION
**Pull request by Xreki**
stack_op's function is the same as concat, except the output's dims. We can call concat functor to optimize it. The current code is implemented by thrust which may generate the calling of  `cudaMalloc`, `cudaFree` and `Wait`. See the timelien of ernie (https://github.com/PaddlePaddle/benchmark/issues/165#issuecomment-521134541):

image

### CODE REVIEW

**Comment by jeng1220** [comment]
@NHZlX ,
looks like this patch can improve ERNIE performance, doesn't? Why did no one review this PR?

**Comment by Xreki** [comment]
@jeng1220 stack op is optimized by https://github.com/PaddlePaddle/Paddle/pull/22142 .

**Comment by jeng1220** [comment]
@Xreki,
So we can close this PR, right?

**Comment by Xreki** [comment]
@jeng1220 Yes, I'll close it.

**Pull request closed without merging**
