### PR TITLE
【fluid api clear】Remove reduce sum

### PR DESCRIPTION
**Pull request by xiaoguoguo626807**
### PR types
 Others 

### PR changes
APIs 

### Describe

remove fluid.layers.reduce_sum ,replaced by paddle.sum

### CODE REVIEW

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by Ligoml — DISMISSED** [review]
LGTM for docs

**Pull request closed without merging**
