### PR TITLE
Add linear learning warmup method in learning rate scheduler.

### PR DESCRIPTION
**Pull request by qingqing01**
This warmup lr can be combinated with other learning rate strategies.
For example:

            decayed_lr = fluid.layers.linear_lr_warmup(
                fluid.layers.piecewise_decay(boundaries, lr_steps),
                warmup_steps, start_lr, end_lr)

### CODE REVIEW

**Comment by qingqing01** [comment]
Doc pre-review:

图片

**Review by shanyi15 — APPROVED** [review]
LG comments

**Review by chengduoZH — APPROVED** [review]
LGTM

**Review by heavengate — APPROVED** [review]
LGTM

**Pull request merged**
