### PR TITLE
support NCCLContextPool singleton for collective op strategy

### PR DESCRIPTION
**Pull request by gavin1332**
some pointer and reference signs is formatted automatically by clang-format

### CODE REVIEW

**Review by gongweibao — COMMENTED** [review]
Where and who will use `NCCLCommGroup`?
This pr is not completed.

**Review by gongweibao — CHANGES_REQUESTED** [review]
Where and who will use NCCLCommGroup?
This pr is not completed.

**Comment by gavin1332** [comment]
> Where and who will use NCCLCommGroup?
> This pr is not completed.

some comments have been added.
NCCLCommGroup is specially useful for hierarchical ring communication, in which, communicators are initialized with different ncclUniqueId, even though with the save world ranks.

**Review by guru4elephant — DISMISSED** [review]
LGTM, you need verify that hierarchical all reduce is valid through NCCLCommGroup

**Pull request closed without merging**
