### PR TITLE
[cherry-pick] release/2.3 elementwise_mul and matmul mkldnn fix

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types
Bug fixes
### PR changes
OPs 

### Describe
elementwise_mul and matmul mkldnn fix

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@jiangjiajun @yeliang2258 Could you please help with the failed CI? I can not see what it is the problem.

**Comment by lidanqing-vv** [comment]
@wozna Please review this PR. Thanks

**Review by wozna — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@yeliang2258 @jiangjiajun @yaomichael The required CI all passed, please review and merge this cherry-pick PR. Thank you!

Another cherry-pick PR is https://github.com/PaddlePaddle/Paddle/pull/43750, still passing CIs, I have committed with pre-commit.

**Review by jiangjiajun — APPROVED** [review]
LGTM

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Pull request merged**
