### PR TITLE
log/Log10/log2/log1p support int32/int64/float16/bfloat16 forward

### PR DESCRIPTION
**Pull request by zh794390558**
### PR types

Function optimization

### PR changes

OPs

### Description

log/Log10/log2/log1p 
*  cpu/gpu support int32/int64/float16/bfloat16

card-71330
doc: https://github.com/PaddlePaddle/docs/pull/5897
test: https://github.com/PaddlePaddle/PaddleTest/pull/2273

### CODE REVIEW

**Review by zhwesky2010 — COMMENTED** [review]
I have no other problem, need to pass CI

**Review by zhwesky2010 — COMMENTED** [review]
GPU kernel支持了吗

**Comment by zh794390558** [comment]
> GPU kernel支持了吗

支持了

**Review by zhwesky2010 — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]
LGTM for dtype register

**Review by dingjiaweiww — APPROVED** [review]

**Review by chenwhql — APPROVED** [review]

**Pull request merged**
