### PR TITLE
[Phi]move reduce_min/any/all kernel

### PR DESCRIPTION
**Pull request by MingMingShangTian**
### PR types

Others
### PR changes

Others
### Describe

Move reduce_min, reduce_any, reduce_all into phi.

### CODE REVIEW

**Review by chenwhql — COMMENTED** [review]
每个kernel实现都很短，是不是合并成reduce_kernel比较好

**Review by chenwhql — APPROVED** [review]
好像reduce max已经合入了，后面建议整合一下

**Review by zyfncg — APPROVED** [review]

**Comment by MingMingShangTian** [comment]
> reduce_kernel

后续合并一下

**Review by YuanRisheng — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
