### PR TITLE
Add Amax and Amin API

### PR DESCRIPTION
**Pull request by luotao1**
### PR types

New features
### PR changes

APIs
### Describe

- amax文档
image

- amin文档
image

- 中文文档：https://github.com/PaddlePaddle/docs/pull/4162

### CODE REVIEW

**Review by jeff41404 — APPROVED** [review]
LGTM

**Review by XieYunshen — COMMENTED** [review]
LGTM 
UT重命名：test_max_min_op -> test_max_min_amax_amin_op

**Review by TCChenlong — APPROVED** [review]
TODO：Add max/min backward

**Review by lanxianghit — APPROVED** [review]

**Review by zhiqiu — APPROVED** [review]
LGTM

**Pull request merged**
