### PR TITLE
expand_as refine 

### PR DESCRIPTION
**Pull request by wangchaochaohu**
same purpose as https://github.com/PaddlePaddle/Paddle/pull/21063

### CODE REVIEW

**Comment by luotao1** [comment]
编译时间能减少多少？编译出来的`libexpand_as_op.a`能减少多少？

**Comment by wangchaochaohu** [comment]
develop
```
time /usr/bin/c++   -DEIGEN_USE_GPU -DLAPACK_FOUND -DPADDLE_CUDA_BINVER=\"90\" -DPADDLE_CUDNN_BINVER=\"7\" -DPADDLE_DISABLE_PROFILER -DPADDLE_USE_DSO -DPADDLE_USE_PTHREAD_BARRIER -DPADDLE_USE_PTHREAD_SPINLOCK -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_WITH_AVX -DPADDLE_WITH_CUDA -DPADDLE_WITH_CUPTI -DPADDLE_WITH_MKLDNN -DPADDLE_WITH_MKLML -DPADDLE_WITH_TENSORRT -DPADDLE_WITH_XBYAK -DXBYAK64 -DXBYAK_NO_OP_NAMES -I/workspace/card_requrement/Paddle/build/third_party/install/mklml/include -I/workspace/card_requrement/Paddle/build/third_party/install/xbyak/include -I/workspace/card_requrement/Paddle/build/third_party/install/xbyak/include/xbyak -I/workspace/card_requrement/Paddle/build/third_party/install/zlib/include -I/workspace/card_requrement/Paddle/build/third_party/install -I/workspace/card_requrement/Paddle/build/third_party/install/gflags/include -I/workspace/card_requrement/Paddle/build/third_party/install/glog/include -I/workspace/card_requrement/Paddle/build/third_party/install/protobuf/include -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/workspace/card_requrement/Paddle/build/third_party/install/mkldnn/include -I/workspace/card_requrement/Paddle/build/third_party/boost/src/extern_boost -I/workspace/card_requrement/Paddle/build/third_party/eigen3/src/extern_eigen3 -I/workspace/card_requrement/Paddle/build/third_party/pybind/src/extern_pybind/include -I/workspace/card_requrement/Paddle/build/third_party/cub/src/extern_cub -I/workspace/card_requrement/Paddle/build/third_party/install/xxhash/include -I/workspace/card_requrement/Paddle/build/third_party/dlpack/src/extern_dlpack/include -I/workspace/card_requrement/Paddle/build/third_party/install/warpctc/include -I/workspace/card_requrement/Paddle/build/third_party/threadpool/src/extern_threadpool -I/usr/local/cuda/extras/CUPTI/include -I/usr/local/cuda/include -I/workspace/card_requrement/Paddle/build -I/workspace/card_requrement/Paddle  -Wno-error=deprecated-declarations -Wno-deprecated-declarations -std=c++11 -m64 -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -Wno-error=maybe-uninitialized -fopenmp -mavx -O3 -DNDEBUG   -o CMakeFiles/expand_as_op.dir/expand_as_op.cc.o -c /workspace/card_requrement/Paddle/paddle/fluid/operators/expand_as_op.cc

real	0m39.166s
user	0m37.434s
sys	0m1.696s
```
this PR

```
time /usr/bin/c++   -DEIGEN_USE_GPU -DLAPACK_FOUND -DPADDLE_CUDA_BINVER=\"90\" -DPADDLE_CUDNN_BINVER=\"7\" -DPADDLE_DISABLE_PROFILER -DPADDLE_USE_DSO -DPADDLE_USE_PTHREAD_BARRIER -DPADDLE_USE_PTHREAD_SPINLOCK -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_WITH_AVX -DPADDLE_WITH_CUDA -DPADDLE_WITH_CUPTI -DPADDLE_WITH_MKLDNN -DPADDLE_WITH_MKLML -DPADDLE_WITH_TENSORRT -DPADDLE_WITH_XBYAK -DXBYAK64 -DXBYAK_NO_OP_NAMES -I/workspace/card_requrement/Paddle/build/third_party/install/mklml/include -I/workspace/card_requrement/Paddle/build/third_party/install/xbyak/include -I/workspace/card_requrement/Paddle/build/third_party/install/xbyak/include/xbyak -I/workspace/card_requrement/Paddle/build/third_party/install/zlib/include -I/workspace/card_requrement/Paddle/build/third_party/install -I/workspace/card_requrement/Paddle/build/third_party/install/gflags/include -I/workspace/card_requrement/Paddle/build/third_party/install/glog/include -I/workspace/card_requrement/Paddle/build/third_party/install/protobuf/include -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/workspace/card_requrement/Paddle/build/third_party/install/mkldnn/include -I/workspace/card_requrement/Paddle/build/third_party/boost/src/extern_boost -I/workspace/card_requrement/Paddle/build/third_party/eigen3/src/extern_eigen3 -I/workspace/card_requrement/Paddle/build/third_party/pybind/src/extern_pybind/include -I/workspace/card_requrement/Paddle/build/third_party/cub/src/extern_cub -I/workspace/card_requrement/Paddle/build/third_party/install/xxhash/include -I/workspace/card_requrement/Paddle/build/third_party/dlpack/src/extern_dlpack/include -I/workspace/card_requrement/Paddle/build/third_party/install/warpctc/include -I/workspace/card_requrement/Paddle/build/third_party/threadpool/src/extern_threadpool -I/usr/local/cuda/extras/CUPTI/include -I/usr/local/cuda/include -I/workspace/card_requrement/Paddle/build -I/workspace/card_requrement/Paddle  -Wno-error=deprecated-declarations -Wno-deprecated-declarations -std=c++11 -m64 -fPIC -fno-omit-frame-pointer -Werror -Wall -Wextra -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-unused-parameter -Wno-unused-function -Wno-error=literal-suffix -Wno-error=sign-compare -Wno-error=unused-local-typedefs -Wno-error=maybe-uninitialized -fopenmp -mavx -O3 -DNDEBUG   -o CMakeFiles/expand_as_op.dir/expand_as_op.cc.o -c /workspace/card_requrement/Paddle/paddle/fluid/operators/expand_as_op.cc

real	0m14.165s
user	0m13.319s
sys	0m0.833s
```
image

**Comment by wangchaochaohu** [comment]
> 编译时间能减少多少？编译出来的`libexpand_as_op.a`能减少多少？

直观上感受减少的时间最少有5到6倍的差距

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Pull request merged**
