### PR TITLE
Reuse OneDNN handler for SGD and SUM for SelectedRows input tensors.

### PR DESCRIPTION
**Pull request by arogowie-intel**
### PR types
Performance optimization

### PR changes
 OPs

### Describe
This PR optimize current implementations for SGD and SUM operators for BF16 data type (mainly) when SelectedRows (sparse) tensors were used by reusing OneDNN handler.

The performance results on word2vec model are as follows on CPX 6348 machine with single thread:

| type | commit    | engine    |   words/sec   |
| :---- | :---: | :---: | :---: |
| bf16 | c56d697  | oneDNN |   18142.32   |
| bf16 | This PR     | oneDNN |   20814.31   |
| fp32 | c56d697  | CPU        |   27680.99   |

This gives ~15% speedup.

From profiling:

| type | commit | sgd total[ms]| sgd % | sum total[ms]| sum % |
| :---- | :---: | :---: | :---: | :---: | :---: |
| fp32 | c56d697  | 117.77       | 2.5   |  395.31      |  8    |
| bf16 | c56d697  | 954.94       | 8.6   | 5151.35      |  47   |
| bf16 | wo cache | 339.28       | 4.6   | 2159.22      |  29   |

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@wzzju Please tak a look at changes in this PR

**Comment by lidanqing-vv** [comment]
@wzzju Hi, please take a look at this PR, use oneDNN sum and SGD

**Comment by jczaja** [comment]
@tsocha Please review this PR

**Review by lidanqing-vv — APPROVED** [review]

**Review by chenwhql — APPROVED** [review]
LGTM for PADDLE_ENFORCE

**Comment by jczaja** [comment]
@chenwhql could you please approve PR-CI-APPROVAL ?

**Review by tsocha — APPROVED** [review]

**Pull request merged**
