### PR TITLE
Mish FP32/BF16 kernel, conv and fc fuse passes

### PR DESCRIPTION
**Pull request by Silv3S**
### PR types
New Features

### PR changes
OPs

### Describe
- Implemented Mish FP32/BF16 activation kernel,
- Added Mish fuse pass for conv and fc operators,
- Added 4 related unit tests.

### CODE REVIEW

**Comment by Silv3S** [comment]
@jakpiase @jczaja please review

**Comment by jakpiase** [comment]
Hi @Silv3S, please fix CI errors before review

**Review by jczaja — APPROVED** [review]
LGTM

**Review by jakpiase — APPROVED** [review]
LGTM, really good job!

**Comment by Silv3S** [comment]
Hello @Aganlengzi, could you review?

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
