### PR TITLE
No fp64 check for mkldnn op test for now, test=develop

### PR DESCRIPTION
**Pull request by juncaipeng**
No fp64 check for mkldnn op test for now, test=develop

### CODE REVIEW

**Review by zhangting2020 — APPROVED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]
LGTM! @bingyanghuang @jczaja @LeoZhao-Intel Do you have a plan to support double type for all mkldnn kernel?

**Comment by jczaja** [comment]
@bingyanghuang Currently DNNL (MKL-DNN) Does not support double data type. Supported data types are:
* int8
* fp32
* bfloat16

So we are not planning update to float64.

**Comment by luotao1** [comment]
Got it. Thus, does Ngraph not support double data type, and have no planning update to float64 in Ngraph as well? @LeoZhao-Intel @baojun-nervana ?

**Comment by baojun-nervana** [comment]
NGraph supports fp64. But NGraph cpu performant kernel relies on MKLDNN, so there is a dependency on mkldnn support.

**Comment by luotao1** [comment]
@baojun-nervana @LeoZhao-Intel Since MKLDNN don't have a plan to update to fp64, and we skip all mkldnn op test in #22363, do you have some idea to skip all ngraph op test in `op_test.py` or using some other ways?

We use `use_mkldnn` attribute in `op_test.py` to judge whether an op is MKLDNN kernel, but since ngraph is integrated like sub-graph, we could not use the same way what we skip all mkldnn op test in #22363.

**Comment by baojun-nervana** [comment]
Is it feasible to use "use_ngraph" flag to disable FP64 tests?

**Comment by luotao1** [comment]
> Is it feasible to use "use_ngraph" flag to disable FP64 tests?

@baojun-nervana Do you have any ideas of this?

**Pull request merged**
