### PR TITLE
Add ParallelExecutor Test for Cond API and Fix PE Checks Shape Bug

### PR DESCRIPTION
**Pull request by zhhsplendid**
Add ParallelExecutor test to prove Cond API Can Work in ParallelExecutor.

Also found a bug in ParallelExecutor and fix it. The bug is that ParallelExecutor splits data evenly on devices, but we didn't divide the number of devices when checking feed data shape in ParallelExecutor

### CODE REVIEW

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Review by sneaxiy — CHANGES_REQUESTED** [review]
Think about lod cases?

**Comment by zhhsplendid** [comment]
> Think about lod cases?

Added

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Pull request merged**
