### PR TITLE
[MKL-DNN] Error throwing for NHWC layout for MKL-DNN ops

### PR DESCRIPTION
**Pull request by jczaja**
This is PR to throw an error when MKL-DNN kernels are to be used but with data_format="NHWC".

### CODE REVIEW

**Review by zhangting2020 — DISMISSED** [review]

**Review by luotao1 — DISMISSED** [review]

**Comment by jczaja** [comment]
@luotao1 PR_CI_CPU_Py2 does fail due to incompatible Error message with the CI guidelines and to have it pass I need your approve or adjust error messages to guidelines. I would like you to consider approving those changes as then I can resume work on implementing NHWC where half of error messages will be deleted anyway and I will adjust those remaining (Grad ops) in next PR.

**Comment by luotao1** [comment]
@chenwhql How do you think about it?

**Review by chenwhql — APPROVED** [review]

**Review by chenwhql — CHANGES_REQUESTED** [review]
now we use new error message writing form, please change PADDLE_ENFORCE to 
```
PADDLE_ENFORCE_NE(data_format, "NHWC",
                      platform::errors::Unimplemented("Conv MKLDNN does not support NHWC data format yet"));
```
about the new specification, you can read https://github.com/PaddlePaddle/Paddle/wiki/Paddle-Error-Message-Writing-Specification-(English-Verison)

**Comment by luotao1** [comment]
@bingyanghuang Could you help see why `test_lrn_mkldnn_op` and `test_pool2d_mkldnn_op` fail in this PR?
```
[16:34:36]	The following tests FAILED:
[16:34:36]		772 - test_lrn_mkldnn_op (Failed)
[16:34:36]	Errors while running CTest
[16:34:45]	96/96 Test #670: test_imperative_ocr_attention_model .........................   Passed   30.05 sec
[16:34:45]	Errors while running CTest
[16:34:45]	
[16:34:45]	99% tests passed, 1 tests failed out of 96
[16:34:45]	
[16:34:45]	Total Test time (real) = 567.57 sec
[16:34:45]	
[16:34:45]	The following tests FAILED:
[16:34:45]		781 - test_pool2d_mkldnn_op (Failed)
```

**Review by luotao1 — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
Please cherry-pick into release/1.6

**Pull request merged**
