### PR TITLE
Add row_conv and hsigmoid into paddle.nn(functional and layer)

### PR DESCRIPTION
**Pull request by iclementine**
1. add row_conv in paddle.nn.functional, RowConv in paddle.nn.layer
2. add hsigmoid in paddle.nn.functional, HSigmoid in paddle.nn.layer
3. fix a bug in `fluid.layers.row_conv`, feature dimension should be -1 instead of 1.

### CODE REVIEW

**Comment by iclementine** [comment]
图片

图片

图片

图片

**Comment by kuke** [comment]
image

 

image







Remember to create another pull request to fix these problems

**Review by kuke — DISMISSED** [review]

**Comment by iclementine** [comment]
> image
> 
> image
> 
> image
> 
> Remember to create another pull request to fix these problems

Okay, I will fix the docstring later in a new pull request.

**Review by kuke — APPROVED** [review]
LGTM

**Comment by iclementine** [comment]
图片

图片

图片

图片

图片

**Pull request merged**
