### PR TITLE
Move dygraph api to root

### PR DESCRIPTION
**Pull request by junjun315**
1. move dygraph.nn.*,dygraph.layer to fluid
2. move unittest import uri

### CODE REVIEW

**Review by panyx0718 — DISMISSED** [review]

**Review by JiabinYang — DISMISSED** [review]
LGTM

**Review by shanyi15 — DISMISSED** [review]
LG comments

**Review by shanyi15 — APPROVED** [review]

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by chengduoZH — APPROVED** [review]
LG API.spec

**Pull request merged**
