### PR TITLE
polish doc for uniform_random and multi_box_head

### LINKED ISSUE #16781: ssd检测头multi_box_head注释有误
- 问题描述：SSD检测头multi_box_head注释部分出现问题，日志/代码关键片段：
Examples:
        .. code-block:: python

          mbox_locs, mbox_confs, box, var = fluid.layers.multi_box_head(
            inputs=[conv1, conv2, conv3, conv4, conv5, conv5],
            image=images,
            num_classes=21,
            min_ratio=20,
            max_ratio=90,
            aspect_ratios=[[2.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]],
            base_size=300,
            offset=0.5,
            flip=True,
            clip=True)
 inputs最后一个参数**conv5**应部分应改为**conv6**

### PR DESCRIPTION
**Pull request by tink2123**
- resolve #16781
- modified the format for uniform_random

### CODE REVIEW

**Comment by tink2123** [comment]
预览效果图：
uniform_random:
image

multi_box_head:
mulit_box_head

**Review by qingqing01 — APPROVED** [review]
LGTM.

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by shanyi15 — APPROVED** [review]
LG comments

**Pull request merged**
