### PR TITLE
fix unittests for eigh op

### PR DESCRIPTION
**Pull request by Zjq9409**
### PR types

Function optimization
### PR changes

OPs
### Describe

1. 在 CUDA 11.6 后 tolerance 修改到 2e-6 之上
2. Complex 单测构建 Hermitian matrix

### CODE REVIEW

**Comment by zlsh80826** [comment]
LGTM

**Comment by JamesLim-sy** [comment]
Will tolerance extension of  eigh OP do harm to the accuracy while trainning model with this OP in CUDA 11.6.

**Comment by zlsh80826** [comment]
@JamesLim-sy 
We tested all of Paddle's unit tests on CUDA 11.6 and there is no failure is caused by increasing this tolerance.

**Comment by JamesLim-sy** [comment]
> @JamesLim-sy We tested all of Paddle's unit tests on CUDA 11.6 and there is no failure is caused by increasing this tolerance.

Roger that.

**Review by JamesLim-sy — APPROVED** [review]
LGTM

**Review by ZzSean — APPROVED** [review]
LGTM，PR里补充下提升tolerance的原因吧

**Pull request merged**
