### PR TITLE
[Docs] Modified the docs of some api for supporting list/tuple args.

### PR DESCRIPTION
**Pull request by xiemoyuan**
### PR types
Others

### PR changes
Docs

### Describe
Modified and completed the docs of some api, which originally supported list/tuple args, when deal with this [iCafe](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-25863/show?source=drawer-header).

### CODE REVIEW

**Review by jzhang533 — APPROVED** [review]
lgtm

**Review by chenwhql — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by raindrops2sea — APPROVED** [review]
LGTM

**Comment by zhiqiu** [comment]
Better add unit tests for the changed APIs to ensure that list/tuple args are supported well.

**Review by zhiqiu — APPROVED** [review]
LGTM，plz add tests in next PR.

**Pull request merged**
