### PR TITLE
This PR improve performance of prior_box op about 1.25x faster on CPU.

### PR DESCRIPTION
**Pull request by guomingz**
* Test Env:SKX 8180 with fake data on 28 threads(bs=1).
* The below table shows the ~25% improvement in prior_box (SSD-MobileNet) which testing data generated by [eval_tp_fake_data.py](https://github.com/PaddlePaddle/Paddle/issues/15618#issuecomment-464613976).

| Type |Event | Calls |   Total     |  Min.    |   Max.      |  Ave.      |  Ratio.|
| ---------------- | ------------------ | ---- | ------- | -------- | -------- | ------------ | -------- |
| w/ optimization  | thread0::prior_box | 6000 | 921.201 | 0.110572 | 0.383402 | **0.153533** | 0.084585 |
| w/o optimization | thread0::prior_box | 6000 | 1151.85 | 0.102276 | 0.426702 | **0.191976** | 0.103337 |

test=develop

### CODE REVIEW

**Comment by luotao1** [comment]
What difference between `w/ optimization` and `w/o optimization`?

**Comment by guomingz** [comment]
> What difference between `w/ optimization` and `w/o optimization`?

Oh, the elapsed time of prior_box op has been decreased with the optimization.

**Comment by guomingz** [comment]
hello @kbinias @lidanqing-intel ,
would you please help review this PR？ Thank you in advance.

**Comment by luotao1** [comment]
> the elapsed time of prior_box op has been decreased with the optimization

I don't understand. What's the meaning of `w` and `w/o`? What's the original performance?

**Comment by guomingz** [comment]
> > the elapsed time of prior_box op has been decreased with the optimization
> 
> I don't understand. What's the meaning of `w` and `w/o`? What's the original performance?
"w/" & "w/o" are the abbreviations.
- w/o == without (equal to original performance)
- w/ == with (equal to optimized performance)

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
