### PR TITLE
Fix reader api doc

### PR DESCRIPTION
**Pull request by sneaxiy**
a4e063de5c48d8790e7caddbcce8eb28
ce6185e158d8ce99bb5913aac378e239
cfb52895f3953ae3b02a697140d13c19

image

### CODE REVIEW

**Comment by shanyi15** [comment]
@haowang101779990  please CHECK

**Comment by haowang101779990** [comment]
Thanks, here is my review,
1. 

图片

**Comment by shanyi15** [comment]
引号这里，另外请check一下是否是英文引号
image

**Comment by shanyi15** [comment]
image
image
image

**Review by shanyi15 — APPROVED** [review]
LGTM

**Review by panyx0718 — APPROVED** [review]

**Pull request merged**
