### PR TITLE
Add isCached() mechanism for BatchNorm and LRN oneDNN operators

### PR DESCRIPTION
**Pull request by grygielski**
PR types: Performance optimization
PR changes: OPs
Describe: PR adds isCached() mechanism for BatchNorm and LRN oneDNN operators

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by grygielski** [comment]
@luotao1 Windows CI seems to be a random fail but I don't know what happened to PR-CI-Coverage, could you help with that?

**Comment by luotao1** [comment]
The reason for PR_CI_Coverage fail is: inference unit tests rely on static libraries, which cause large memory usage in `make -j`. Each inference unit test such as `build/paddle/fluid/inference/tests/api/test_analyzer_xxx` contains 2G. #24743  is fixing this problem. And you can rerun at first.

**Comment by grygielski** [comment]
@luotao1 Thanks, I've already rerun it. Could you do the same to Windows_CI? It looks like it is random fail

**Comment by luotao1** [comment]
I have rerun Windows CI.

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
