### PR TITLE
Update test_imperative_auto_prune.py

### PR DESCRIPTION
**Pull request by idiomaticrefactoring**
refactoring code with var unpack which is more pythonic, concise, readable and efficient; how do think this change which has practical value？

### CODE REVIEW

**Comment by luotao1** [comment]
Sorry too later to notice this PR, Could you pull a new commit and pass the CI again? @idiomaticrefactoring

**Comment by luotao1** [comment]
@phillxnet Could you pull a new commit and pass the CI again? It seems that @idiomaticrefactoring is a bot.

**Comment by enkilee** [comment]
https://github.com/PaddlePaddle/Paddle/pull/49526

**Comment by luotao1** [comment]
close due to #49521 merged

**Pull request closed without merging**
