### PR TITLE
Removed duplicated code

### PR DESCRIPTION
**Pull request by wojtuss**
This also fixes linking to libpaddle_fluid.so built in debug mode. 

test=develop

### CODE REVIEW

**Comment by luotao1** [comment]
> This also fixes linking to libpaddle_fluid.so built in debug mode.

Could paste the error log?

**Comment by wojtuss** [comment]
> Could paste the error log?

Here it is:
```
/home/wojtuss/repos/PaddlePaddle/Paddle/build/fluid_install_dir/paddle/fluid/inference/libpaddle_fluid.so: undefined reference to `paddle::inference::analysis::NodesTSIterator::NodesTSIterator(paddle::inference:
:analysis::NodesTSIterator const&)'                                                                                                                                                                                
/home/wojtuss/repos/PaddlePaddle/Paddle/build/fluid_install_dir/paddle/fluid/inference/libpaddle_fluid.so: undefined reference to `paddle::inference::analysis::NodesTSIterator::NodesTSIterator(std::vector<paddl$
::framework::ir::Node*, std::allocator<paddle::framework::ir::Node*> > const&)'                                                                                                                                    
collect2: error: ld returned 1 exit status                                                                                                                                                                         
CMakeFiles/model_graph_generator.dir/build.make:96: recipe for target 'model_graph_generator' failed                                                                                                               
make[2]: *** [model_graph_generator] Error 1                                                                                                                                                                       
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/model_graph_generator.dir/all' failed                                                                                                                       
make[1]: *** [CMakeFiles/model_graph_generator.dir/all] Error 2                                                                                                                                                    
Makefile:83: recipe for target 'all' failed                                                                                                                                                                        
make: *** [all] Error 2
```
In RELEASE or RelWithDebInfo modes (with -O3 optimizations) the unused symbols were removed from the library and there was no error.

**Comment by luotao1** [comment]
What's your cmake option? Since our CI_Debug builds successfully in http://ci.paddlepaddle.org/viewLog.html?buildId=58530&tab=buildLog&buildTypeId=Paddle_CiDebug&logTab=tree&filter=all

**Comment by wojtuss** [comment]
> What's your cmake option?

PaddlePaddle builds successfully in both Debug and Release modes, but when building our C-API standalone app, it fails to link to PaddlePaddle built in Debug mode.

These are my cmake options for PaddlePaddle:
```
cmake -DWITH_DOC=OFF -DWITH_GPU=OFF -DWITH_DISTRIBUTE=OFF -DWITH_MKLDNN=ON -DWITH_GOLANG=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_TESTING=OFF -DWITH_TIMER=ON -DWITH_PROFILER=ON -DWITH_INFERENCE_API_TEST=OFF -DON_INFER=ON ..
```

**Review by Superjomn — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
Thanks very much! The reason is that our CI does not run in `-DON_INFER=ON -DCMAKE_BUILD_TYPE=DEBUG`.

**Comment by luotao1** [comment]
Could you cherry-pick this PR into release/1.3?

**Comment by wojtuss** [comment]
> Could you cherry-pick this PR into release/1.3?

Sure. Thanks!

**Pull request merged**
