### PR TITLE
[Typing][A-40,A-41,A-42] Add type annotations for some optimizers (adamax, adamw, asgd)

### PR DESCRIPTION
**Pull request by ooooo-create**
### PR Category

User Experience

### PR Types

Improvements

### Description

类型标注：

- paddle/optimizer/adamax.py
- paddle/optimizer/adamw.py
- paddle/optimizer/asgd.py

### Related links
 
- https://github.com/PaddlePaddle/Paddle/issues/65008

@SigureMo @megemini

### CODE REVIEW

**Comment by SigureMo** [comment]
> ```
> 2024-06-18 00:41:53 ++ python type_checking.py
> 2024-06-18 00:41:53 ----------------Check results--------------------
> 2024-06-18 00:41:53 paddle.optimizer.Adamax:1
> 2024-06-18 00:41:53 <string>:11:15: error: Argument "beta1" to "Adamax" has incompatible type "Tensor"; expected "float"  [arg-type]
> 2024-06-18 00:41:53 <string>:12:15: error: Argument "beta2" to "Adamax" has incompatible type "Tensor"; expected "float"  [arg-type]
> 2024-06-18 00:41:53 Found 2 errors in 1 file (checked 1 source file)
> 2024-06-18 00:41:53 
> 2024-06-18 00:41:53 
> 2024-06-18 00:41:53 >>> Mistakes found in type checking!
> 2024-06-18 00:41:53 >>> Please recheck the type annotations. Run `tools/type_checking.py` to check the typing issues:
> 2024-06-18 00:41:53 > python tools/type_checking.py paddle.optimizer.Adamax
> 2024-06-18 00:41:53 ----------------End of the Check--------------------
> ```

adamax 的 beta1、beta2 支持 Tensor？

**Comment by ooooo-create** [comment]
> > ```
> > 2024-06-18 00:41:53 ++ python type_checking.py
> > 2024-06-18 00:41:53 ----------------Check results--------------------
> > 2024-06-18 00:41:53 paddle.optimizer.Adamax:1
> > 2024-06-18 00:41:53 <string>:11:15: error: Argument "beta1" to "Adamax" has incompatible type "Tensor"; expected "float"  [arg-type]
> > 2024-06-18 00:41:53 <string>:12:15: error: Argument "beta2" to "Adamax" has incompatible type "Tensor"; expected "float"  [arg-type]
> > 2024-06-18 00:41:53 Found 2 errors in 1 file (checked 1 source file)
> > 2024-06-18 00:41:53 
> > 2024-06-18 00:41:53 
> > 2024-06-18 00:41:53 >>> Mistakes found in type checking!
> > 2024-06-18 00:41:53 >>> Please recheck the type annotations. Run `tools/type_checking.py` to check the typing issues:
> > 2024-06-18 00:41:53 > python tools/type_checking.py paddle.optimizer.Adamax
> > 2024-06-18 00:41:53 ----------------End of the Check--------------------
> > ```
> 
> adamax 的 beta1、beta2 支持 Tensor？

应该不行叭，看 ops.yml 里面 adamax 定义的写的是 float beta1,adam 写的是 scalar beta1

**Comment by SigureMo** [comment]
> 应该不行叭，看 ops.yml 里面 adamax 定义的写的是 float beta1,adam 写的是 scalar beta1

示例代码不能跑吗？

**Comment by ooooo-create** [comment]
> 示例代码不能跑吗？

可以～，加上 Tensor 了

**Comment by SigureMo** [comment]
> 可以～，加上 Tensor 了

应该不止这一个？看其他 API 也有这么用的

**Comment by ooooo-create** [comment]
> > 可以～，加上 Tensor 了
> 
> 应该不止这一个？看其他 API 也有这么用的

是有一些，有些 docstring 里没有明确写beta1,beta2支持 0d tensor，但是传进去也不报错，adam 里 epsilon 也写可以是 0d tensor，别的地方 docstring 也没明确写支持，但是也可以传😂

**Review by SigureMo — APPROVED** [review]
LGTMeow

**Pull request merged**
