### PR TITLE
Upgrade OneDNN to v3.2

### PR DESCRIPTION
**Pull request by zhanglirong1999**
### PR types
Others

### PR changes
Others

### Description
Upgrade OneDNN V3.2 in Paddle

### CODE REVIEW

**Comment by xinyu-intel** [comment]
It seems oneDNN built fail with VS2017, @zhanglirong1999 can you please double check on that?

**Comment by zhanglirong1999** [comment]
sure，I will check.
________________________________
发件人: Xinyu Chen ***@***.***>
发送时间: Tuesday, September 12, 2023 7:43:00 AM
收件人: PaddlePaddle/Paddle ***@***.***>
抄送: Zhang, Lirong ***@***.***>; Mention ***@***.***>
主题: Re: [PaddlePaddle/Paddle] Upgrade OneDNN to v3.2 (PR #57179)


It seems oneDNN built fail with VS2017, @zhanglirong1999<https://github.com/zhanglirong1999> can you please double check on that?

―

**Comment by xinyu-intel** [comment]
oneDNN has deprecated support for VS2017 and claim the support for [VS2019 and VS2022](https://github.com/oneapi-src/oneDNN/tree/rls-v3.2#validated-configurations) since [Microsoft ended the main stream support on April 12th, 2022](https://learn.microsoft.com/zh-cn/lifecycle/products/visual-studio-2017). We'll try to skip build with mkldnn on MSVC15. @tianshuo78520a

**Review by xinyu-intel — APPROVED** [review]

**Review by vivienfanghuagood — COMMENTED** [review]
Detailed benchmark data on model inference performance should be posted

**Comment by zhanglirong1999** [comment]
@vivienfanghuagood , here's the model performance data compared with OneDNN 3.1.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/zhanglir/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/zhanglir/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/zhanglir/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal><o:p>&nbsp;</o:p></p>



Test   name |   | oneDNN 3.1.1 | oneDNN3.2 | Speedup
-- | -- | -- | -- | --
ernie3.0_fp32_performance | 32 | 47.32 | 47.37 | 0%
ernie3.0_int8_performance | 32 | 113.77 | 112.81 | -1%
GRU_TA_LA_performance_fp32 | 50 | 2105.88 | 2109.28 | 0%
GRU_TA_LA_performance_int8 | 50 | 1911.28 | 1916.47 | 0%
OCR_det_performance | 1 | 4.47 | 9.91 | 122%
pp-runner_vit_ocr_inference_performance | 1 | 11.49 | 12.50 | 9%
TA_B_bert_performance_fp32 | 1 | 143.23 | 143.55 | 0%
TA_I8_IC_googlenet_performance_fp32 | 1 | 33.22 | 33.15 | 0%
TA_I8_IC_googlenet_performance_int8 | 1 | 72.11 | 72.09 | 0%
TA_I8_IC_mobilenetV1_performance_fp32 | 1 | 79.02 | 78.42 | -1%
TA_I8_IC_mobilenetV1_performance_int8 | 1 | 190.61 | 190.21 | 0%
TA_I8_IC_mobilenetV2_performance_fp32 | 1 | 76.60 | 76.27 | 0%
TA_I8_IC_mobilenetV2_performance_int8 | 1 | 151.08 | 151.84 | 1%
TA_I8_IC_mobilenetV3_performance_fp32 | 1 | 67.97 | 68.16 | 0%
TA_I8_IC_mobilenetV3_performance_int8 | 1 | 111.26 | 112.86 | 1%
TA_I8_IC_resnet101_performance_fp32 | 1 | 7.50 | 7.42 | -1%
TA_I8_IC_resnet101_performance_int8 | 1 | 22.70 | 22.44 | -1%
TA_I8_IC_resnet50_performance_fp32 | 1 | 13.69 | 13.60 | -1%
TA_I8_IC_resnet50_performance_int8 | 1 | 43.29 | 43.25 | 0%
TA_I8_IC_vgg16_performance_fp32 | 1 | 4.05 | 4.01 | -1%
TA_I8_IC_vgg16_performance_int8 | 1 | 10.55 | 10.30 | -2%
TA_I8_IC_vgg19_performance_fp32 | 1 | 3.33 | 3.29 | -1%
TA_I8_IC_vgg19_performance_int8 | 1 | 9.09 | 8.93 | -2%
TA_IC_demark_performance | 1 | 9.88 | 9.94 | 1%
TA_IC_feature_performance | 1 | 2.45 | 2.46 | 0%
TA_IC_googlenetV1_performance | 1 | 32.74 | 32.24 | -2%
TA_quant_IC_mobilenetv1_performance | 1 | 173.67 | 173.77 | 0%
TA_quant_IC_mobilenetv2_performance | 1 | 141.35 | 141.04 | 0%
TA_quant_IC_resnet101_performance | 1 | 21.16 | 20.78 | -2%
TA_quant_IC_resnet50_performance | 1 | 43.34 | 42.16 | -3%
TA_quant_IC_vgg16_performance | 1 | 10.83 | 10.86 | 0%
TA_quant_IC_vgg19_performance | 1 | 9.36 | 9.43 | 1%
test_lstm_fp32_performance | 1 | 4002.82 | 4086.93 | 2%
test_lstm_ptq_int8_performance | 1 | 5385.17 | 5391.96 | 0%
VIT_OCR_performance_fp32 | 1 | 35.47 | 35.20 | -1%
placeholder_greater_is_better |   |   |   |  
ERNIE_fp32_20_threads_performance | 1 | 26.76 | 22.93 | 17%
ERNIE_fp32_performance | 1 | 218.35 | 222.96 | -2%
ERNIE_int8_20_threads_performance | 1 | 16.50 | 16.61 | -1%
ERNIE_int8_performance | 1 | 79.49 | 80.49 | -1%
ocrv3_det_fp32_perf | 1 | 35.76 | 36.93 | -3%
ocrv3_rec_fp32_perf | 6 | 22.57 | 21.52 | 5%
PDI_Picodet_m_416_coco_fp32[ms] | 1 | 59.90 | 60.70 | -1%
PDI_ppyolov2_r50vd_dcn_365e_coco[ms] | 1 | 1094.50 | 1100.30 | -1%
picodet_fp32_perf | 1 | 19.60 | 19.60 | 0%
picodet_int8_perf | 1 | 17.80 | 17.60 | 1%
ppyoloe_fp32_perf | 1 | 287.80 | 291.50 | -1%
ppyoloe_int8_perf | 1 | 303.00 | 313.80 | -3%
placeholder_lower_is_better |   |   |   |  




</body>

</html>

**Review by tianshuo78520a — APPROVED** [review]

**Pull request merged**
