### PR TITLE
[CodeStyle][Typos][B-14,B-[17-19]] Fix typos(`Broardcast`,`Bradcast`,`Boardcast`,`buitin`,`buitlin`,`Buitin`,`builded`,`ba`)

### PR DESCRIPTION
**Pull request by rich04lin**
### PR Category

User Experience

### PR Types

Devs

### Description

Fix:
Broardcast
Bradcast
Boardcast
buitin
buitlin
Buitin
builded

Undo：
ba：表示张张量的顺序or缩写buddyallocator

### CODE REVIEW

**Review by SigureMo — DISMISSED** [review]
LGTMeow

**Comment by SigureMo** [comment]
codestyle 又没过，本地没装 pre-commit 吗？

**Comment by rich04lin** [comment]
> codestyle 又没过，本地没安装 pre-commit 吗？

下载了，有时候提交第二次才能成功

**Comment by SigureMo** [comment]
```
2024-12-05 00:57:26 ************************************************************************************
2024-12-05 00:57:26 Your PR code style check failed.
2024-12-05 00:57:26 Please install pre-commit locally and set up git hook scripts:
2024-12-05 00:57:26 
2024-12-05 00:57:26     pip install pre-commit==2.17.0
2024-12-05 00:57:26     pre-commit install
2024-12-05 00:57:26 
2024-12-05 00:57:26 Then, run pre-commit to check codestyle issues in your PR:
2024-12-05 00:57:26 
2024-12-05 00:57:26     pre-commit run --files _typos.toml paddle/fluid/framework/new_executor/standalone_executor.cc paddle/fluid/pir/serialize_deserialize/include/serialize_utils.h paddle/fluid/pybind/manual_static_op_function.h python/paddle/jit/dy2static/partial_program.py python/paddle/tensorrt/export.py python/paddle/tensorrt/util.py test/deprecated/legacy_test/test_eager_run_program_deprecated.py test/deprecated/legacy_test/test_run_program_op_deprecated.py test/legacy_test/test_elementwise_add_op.py test/legacy_test/test_imperative_triple_grad.py test/tensorrt/tensorrt_test_base.py
2024-12-05 00:57:26 
2024-12-05 00:57:26 For more information, please refer to our codestyle check guide:
2024-12-05 00:57:26 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/codestyle_check_guide_cn.html
2024-12-05 00:57:26 ************************************************************************************
```

> 下载了，有时候提交第二次才能成功

下载是什么？按照流程，安装 pre-commit，并在项目根目录初始化 git hook，正常来说不可能出现 codestyle 问题

**Comment by rich04lin** [comment]
> ```
> 2024-12-05 00:57:26 ************************************************************************************
> 2024-12-05 00:57:26 Your PR code style check failed.
> 2024-12-05 00:57:26 Please install pre-commit locally and set up git hook scripts:
> 2024-12-05 00:57:26 
> 2024-12-05 00:57:26     pip install pre-commit==2.17.0
> 2024-12-05 00:57:26     pre-commit install
> 2024-12-05 00:57:26 
> 2024-12-05 00:57:26 Then, run pre-commit to check codestyle issues in your PR:
> 2024-12-05 00:57:26 
> 2024-12-05 00:57:26     pre-commit run --files _typos.toml paddle/fluid/framework/new_executor/standalone_executor.cc paddle/fluid/pir/serialize_deserialize/include/serialize_utils.h paddle/fluid/pybind/manual_static_op_function.h python/paddle/jit/dy2static/partial_program.py python/paddle/tensorrt/export.py python/paddle/tensorrt/util.py test/deprecated/legacy_test/test_eager_run_program_deprecated.py test/deprecated/legacy_test/test_run_program_op_deprecated.py test/legacy_test/test_elementwise_add_op.py test/legacy_test/test_imperative_triple_grad.py test/tensorrt/tensorrt_test_base.py
> 2024-12-05 00:57:26 
> 2024-12-05 00:57:26 For more information, please refer to our codestyle check guide:
> 2024-12-05 00:57:26 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/codestyle_check_guide_cn.html
> 2024-12-05 00:57:26 ************************************************************************************
> ```
> 
> > 下载了，有时候提交第二次才能成功
> 
> 下载是什么？按照流程，安装 pre-commit，并在项目根目录初始化 git hook，正常来说不可能出现 codestyle 问题

安装初始化过的，有时候第一次提交显示codestyle有问题，重新再提交一次就没问题了

**Review by SigureMo — APPROVED** [review]

**Pull request merged**
