### PR TITLE
support quantization of bert

### PR DESCRIPTION
**Pull request by XGZhang11**
### PR types

Bug fixes
### PR changes

Others
### Describe

修复了量化无权重的matmul_v2时，错误地添加量化op的问题

### CODE REVIEW

**Review by qingqing01 — APPROVED** [review]
LGTM

**Review by qingqing01 — COMMENTED** [review]
better to add unit testing.

**Review by wanghaoshuang — APPROVED** [review]
LGTM

**Review by LiuChiachi — APPROVED** [review]
LGTM

**Review by ceci3 — APPROVED** [review]
LGTM

**Pull request merged**
