### PR TITLE
Add affine channel op to speed and save memory for faster-rcnn model.

### PR DESCRIPTION
**Pull request by qingqing01**
Applies a separate affine transformation to each channel of the input. Useful
for replacing spatial batch norm with its equivalent fixed transformation.

Speed and memory usage for faster-rcnn model:

- speed: 

10个iter时间 | 版本1 | 版本2：generate_proposals加速 | 版本3：affine_channel_op加速
-- | -- | -- | --
1 GPU | 10.843s | 8.663s | 6.701s
8 GPU| 13.663s| 11.315s | 10.532s

- max batch size:

max batch size | 版本1 | 版本2：generate_proposals加速 | 版本3：affine_channel_op加速
-- | -- | -- | --
1 GPU | 1 | 1 | 2
8 GPU| 8| 8| 16

### CODE REVIEW

**Review by jerrywgz — COMMENTED** [review]
need API.spec?

**Comment by qingqing01** [comment]
API.spec is added

**Comment by qingqing01** [comment]
API.spec is added

**Review by typhoonzero — APPROVED** [review]
LG API

**Review by jerrywgz — APPROVED** [review]
LGTM

**Review by panyx0718 — APPROVED** [review]
LG API

**Pull request merged**
