### PR TITLE
[Bug fix] Fix for wrong results in segmentation models

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Bug fixes

### PR changes
Others

### Describe
Added dcab format tag support. "Any" format tag was choosing it, but we weren't supporting that and elementwise_add kernel was causing incorrect results in a segmentation model. We really need to add memory descriptor as a field to tensor class to avoid that kind of issues in future. It is a fix for #35307

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@jakpiase @jczaja Could this one be merged?

**Comment by jakpiase** [comment]
@lidanqing-intel yes, please merge it

**Comment by jakpiase** [comment]
@jczaja please merge this PR

**Pull request merged**
