### PR TITLE
[CodeStyle][Ruff][BUAA][A-[21-25]] Fix ruff `Q003` diagnostic for 5 files in `python/paddle/` and `test/`

### PR DESCRIPTION
**Pull request by Marcusryz**
### PR Category

User Experience

### PR Types

Devs

### Description

修复如下文件 Q003 的 Ruff 规则：

- python/paddle/nn/functional/pooling.py

- python/paddle/optimizer/optimizer.py

- test/cinn/test_paddle_model_convertor.py

- test/legacy_test/op.py

- test/legacy_test/test_operator_desc.py

### Related Links
- https://github.com/PaddlePaddle/Paddle/issues/67116

@gouzil @SigureMo

### CODE REVIEW

**Review by SigureMo — APPROVED** [review]
LGTMeow

**Comment by Marcusryz** [comment]
这个 windows 流水线怎么寄了，能帮忙看一下吗 @SigureMo

**Comment by SigureMo** [comment]
https://github.com/PaddlePaddle/Paddle/pull/67540 修了，rerun 就可以了

**Comment by Marcusryz** [comment]
> #67540 修了，rerun 就可以了

收到

**Pull request merged**
