### PR TITLE
[Fluid Clean] remove paddle.fluid.layers.nn.reduce_mean

### PR DESCRIPTION
**Pull request by heyanru01**
### PR types

Others
### PR changes

APIs
### Describe

remove fluid API

### CODE REVIEW

**Comment by yingshengBD** [comment]
LGTM

**Comment by heyanru01** [comment]
paddle.mean有自己的保护单测test_mean_op.py

**Review by jzhang533 — APPROVED** [review]
LGTM for API changes
but want to know why 'python/paddle/fluid/tests/unittests/ir/inference/test_trt_reduce_mean_op.py' is deleted

**Review by XieYunshen — APPROVED** [review]
LGTM
单测删除

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by raindrops2sea — APPROVED** [review]

**Comment by heyanru01** [comment]
> LGTM for API changes but want to know why 'python/paddle/fluid/tests/unittests/ir/inference/test_trt_reduce_mean_op.py' is deleted

this kind of unittest is all for fluid APIs, since reduce_mean is deleted, the unittest can be deleted to ensure the uniformity of these unittests while paddle.mean has reliable unittest itself.

**Review by hong19860320 — APPROVED** [review]
LGTM

**Pull request merged**
