### PR TITLE
Fix UT failure

### PR DESCRIPTION
**Pull request by leo0519**
### PR types

Bug fixes

### PR changes

Others

### Description

Modifications

1. Disable `trt_flash_multihead_matmul_fuse_pass` and `trt_cross_multihead_matmul_fuse_pass` if TRT version >= 8.6.1
2. Remove `test_trt_activation_pass` UT because it is same as [`test_trt_convert_activation` UT](https://github.com/PaddlePaddle/Paddle/blob/develop/test/ir/inference/test_trt_convert_activation.py)
3. Modify the incorrect input dynamic shape in `test_trt_convert_cross_multihead_matmul`
4. Modify the input of `test_trt_convert_multihead_matmul`
5. Fix the random seed of `test_math_op_patch`
6. Change the algorithm of `TestPostTrainingAvgONNXFormatForMobilenetv1TensorRT` in `test_post_training_quantization_mobilenetv1`

### CODE REVIEW

**Comment by leo0519** [comment]
The CI `PR-CI-Build` failed.
```bash
/paddle/paddle/fluid/inference/tensorrt/helper.h:25:10: fatal error: paddle/fluid/framework/framework.pb.h: No such file or directory
```

**Comment by tianshuo78520a** [comment]
> The CI `PR-CI-Build` failed.
> 
> ```shell
> /paddle/paddle/fluid/inference/tensorrt/helper.h:25:10: fatal error: paddle/fluid/framework/framework.pb.h: No such file or directory
> ```

看起来并不是CI的问题

**Comment by leo0519** [comment]
@tianshuo78520a 
PR-CI-Py3's error for third_party openblas
```bash
2023-07-19 08:26:51 /bin/sh: 1: gfortran: not found
2023-07-19 08:26:51 expr: syntax error: unexpected argument ???4???
2023-07-19 08:26:51 /bin/sh: 1: gfortran: not found
2023-07-19 08:26:51 expr: syntax error: unexpected argument ???5???
2023-07-19 08:26:51 /bin/sh: 1: gfortran: not found
2023-07-19 08:26:51 expr: syntax error: unexpected argument ???7???
```

**Comment by tianshuo78520a** [comment]
> @tianshuo78520a PR-CI-Py3's error for third_party openblas
> 
> ```shell
> 2023-07-19 08:26:51 /bin/sh: 1: gfortran: not found
> 2023-07-19 08:26:51 expr: syntax error: unexpected argument ???4???
> 2023-07-19 08:26:51 /bin/sh: 1: gfortran: not found
> 2023-07-19 08:26:51 expr: syntax error: unexpected argument ???5???
> 2023-07-19 08:26:51 /bin/sh: 1: gfortran: not found
> 2023-07-19 08:26:51 expr: syntax error: unexpected argument ???7???
> ```

看起来并不像CI问题，报错原因是更上面
image

**Review by Wangzheee — APPROVED** [review]

**Review by XieYunshen — APPROVED** [review]
LGTM
单测删除

**Pull request merged**
