### PR TITLE
Reduce kernel optimization on GPU

### PR DESCRIPTION
**Pull request by shaojiewang**
### PR types

Performance optimization
### PR changes

OPs
### Describe

For reduce any kernel based on GPU:
1. redesign the memory access pattern
2. re-computation for max threads num on 1 SM
3. redesign the pipeline for 2-stage reduction

On op benchmark, ops improve above 5%:
performance test on V-100 16GB:
op_name | dtype | pd time develop(us) | pd time PR(us) | boost
-- | -- | -- | -- | --
all_0 | bool | 83.4 | 61.9 | 25%
any_0 | bool | 86.2 | 61.9 | 28%
max_0 | float | 181.4 | 170.0 | 6%
mean_0 | float | 185.3 | 169.9 | 8%
mean_1 | float16 | 113.9 | 94.4 | 17%
mean_5 | float16 | 150 | 86.9 | 42%
min_0 | float32 | 180.6|168.2|6%
p_norm_0|float32|124|63|49%
p_norm_1|float32|108.5|74.8|31%
p_norm_2|float32|107.2|62.8|41%
sum_0|float32|182|170|6%
sum_1|float16|110|94|14%
sum_5|float16|150|87|41%

### CODE REVIEW

**Comment by JamesLim-sy** [comment]
CI-OP-Benchmark has been last for almost 18 hours, therefore, this ctest item will be not pased on PR platform. And optimization for reduction needs more tests to completely show the real optimization. Please use [OP-Benchamrk](https://github.com/PaddlePaddle/benchmark/tree/master/api) to completely test accuracy and speed optimization on p_nom, AddGrad, DivGrad etc.

**Comment by shaojiewang** [comment]
> CI-OP-Benchmark has been last for almost 18 hours, therefore, this ctest item will be not pased on PR platform. And optimization for reduction needs more tests to completely show the real optimization. Please use [OP-Benchamrk](https://github.com/PaddlePaddle/benchmark/tree/master/api) to completely test accuracy and speed optimization on p_nom, AddGrad, DivGrad etc.

AddGrad and DivGrad's perfs are not changed. Related perf boost is updated in description. 
CI benchmark has 1 non-passed op(trace 0), but this op is computed by third party lib and is not influenced by this PR. Could you please help to check this one?

**Review by JamesLim-sy — APPROVED** [review]
LGTM, great work~

**Review by AnnaTrainingG — APPROVED** [review]

**Review by ZzSean — APPROVED** [review]
LGTM

**Pull request closed without merging**
