### PR TITLE
Deleted mkldnn_inplace_pass code

### PR DESCRIPTION
**Pull request by HulekJakub**
### PR types
Others 

### PR changes
Others 

### Describe
Clean up code related to mkldnn_inplace_pass

### CODE REVIEW

**Review by tsocha — DISMISSED** [review]

**Review by Silv3S — DISMISSED** [review]
LGTM

**Review by jczaja — DISMISSED** [review]
LGTM

**Review by jakpiase — DISMISSED** [review]
LGTM

**Review by chenwhql — DISMISSED** [review]

**Review by tsocha — DISMISSED** [review]

**Review by Silv3S — DISMISSED** [review]

**Comment by tsocha** [comment]
@zhouwei25 Could you approve this PR?
We have removed a pass and unit tests for it.

**Review by XieYunshen — DISMISSED** [review]
LGTM

**Review by yeliang2258 — DISMISSED** [review]
LGTM

**Review by jczaja — DISMISSED** [review]

**Review by jczaja — DISMISSED** [review]

**Review by jczaja — DISMISSED** [review]

**Review by jczaja — DISMISSED** [review]

**Review by jczaja — DISMISSED** [review]

**Review by tsocha — DISMISSED** [review]

**Review by chenwhql — DISMISSED** [review]

**Review by yeliang2258 — DISMISSED** [review]
LGTM

**Review by zhwesky2010 — DISMISSED** [review]

**Review by Silv3S — APPROVED** [review]

**Review by tsocha — APPROVED** [review]

**Review by zhwesky2010 — APPROVED** [review]

**Pull request merged**
