### PR TITLE
[Inference] save_optimized_model_pass support tensorrt

### PR DESCRIPTION
**Pull request by yuanlehome**
### PR types

New features
### PR changes

Others
### Description

This PR's work:
1. save_optimized_model_pass support tensorrt, cpu/gpu/xpu has been supported and verified in https://github.com/PaddlePaddle/Paddle/pull/53696, https://github.com/PaddlePaddle/Paddle/pull/55551.
2. Uniformly package all non runtime parameters of TenosrRTEngine to ConstructionParams.
3. Support load trt engine in runtime(in tensorrt_engine op run).
4. Remove some unused function and variable in trt related code.
5. Refine some unittest related to trt.
6. Add unittest for function of save_optimized_model_pass(gpu/trt).

How to use:
```cpp
//
// Step 1: first run
//
// other code
config.SetModel(/*model dir*/);
// other code
config.EnableUseGpu(...); // for gpu
config.EnableTensorRtEngine(..., use_static=true, ...). // for tensorrt
// other code
config.SwitchIrOptim(true);
config.SetOptimCacheDir("./optim_cache");
config.EnableSaveOptimModel(true);
// other code
auto predictor = CreatePredictor(config);

// Optimized model will be save to ./optim_cache/_optimized.*

//
// Step 2: second run
//
// other code
config.SetModel(/*optimized model dir*/);
// other code
config.EnableUseGpu(...); // for gpu
config.EnableTensorRtEngine(..., use_static=true, ...). // for tensorrt
// other code
config.SwitchIrOptim(false);
// other code
auto predictor = CreatePredictor(config);
// other code
predictor->Run();
// other code
```

Note:
1. Not support EnableTensorRtEngine(..., use_cuda_graph=true).

### Others
Pcard-71500

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM for `set_tests_properties(test_save_optimized_model_pass PROPERTIES TIMEOUT 300)`

**Review by Aurelius84 — APPROVED** [review]
LGTM for ENFORCE MSG

**Review by zhangjun — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
