### PR TITLE
convert input vars' dtype for range op

### PR DESCRIPTION
**Pull request by mapingshuo**
There was an issue that if the input variables (`start`, `end`, `step`) of the `range` op hold different dtypes, an error occurs: 

```shell
------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/mapingshuo/paddle_release_home/python-distribute/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2459, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/mapingshuo/paddle_release_home/python-distribute/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/mapingshuo/paddle_release_home/python-distribute/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 1202, in range
    outputs={'Out': [out]})
  File "demo.py", line 5, in <module>
    y = fluid.layers.range(0, x[0], 1, 'int64')

----------------------
Error Message Summary:
----------------------
PaddleCheckError: The DataType of range Op's duplicable Variable Start must be consistent. The current variable type is (int64_t), but the previous variable type is (int). at [/home/users/dongdaxiang/Paddle/paddle/fluid/framework/operator.cc:1151]
  [operator < range > error]
```

For details of this error, please see: https://github.com/PaddlePaddle/Paddle/issues/22004

This is because paddle requires the inputs of range op holds vars with the same dtype. I added a cast op to make them consistent.

### CODE REVIEW

**Comment by mapingshuo** [comment]
image

**Comment by mapingshuo** [comment]
image

**Review by swtkiwi — APPROVED** [review]
LGTM

**Review by guru4elephant — APPROVED** [review]
LGTM

**Pull request merged**
