### PR TITLE
Correct C++ QAT pass

### PR DESCRIPTION
**Pull request by wozna**
### PR types

 Bug fixes
### PR changes

Others 
### Describe

I have found that pass `compute_propagate_scales_mkldnn_pass.cc` doesn't work for VGG16 and VGG19 models, because it was trying to get access to unallocated memory. 
I fixed that and I added a test for vgg16. 

Moreover, I removed `fp32_cfg.EnableMKLDNN()` because it is already set here https://github.com/wozna/Paddle/blob/678f2bf329eefa8053d1bd27a56a8130bfbe3c52/paddle/fluid/inference/tests/api/analyzer_quant_image_classification_tester.cc#L31

### CODE REVIEW

**Review by lidanqing-vv — DISMISSED** [review]
LGTM

**Review by sfraczek — DISMISSED** [review]
LGTM

**Review by sfraczek — DISMISSED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
https://github.com/PaddlePaddle/Paddle/issues/42972 slow performance is caused by fc quantization, removing fc from quantization list is a work-around to get perf recover. But will this PR finally fix Resnet50 slow performance issue?

**Review by lidanqing-vv — DISMISSED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
Assuming customers always turn on EnableMKLDNN() after saving int8 model, because that is more intuitive. If this PR could not fix fc quantization slow perf issue, maybe we should just comment fc quant for some time. Leaving fc as fp32 is safer. We could think long term fix.
But please check if your PR already fix #42972, thanks

**Review by sfraczek — DISMISSED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@jiangjiajun  Hi, could you please approve this PR ?

**Comment by wozna** [comment]
> Assuming customers always turn on EnableMKLDNN() after saving int8 model, because that is more intuitive. If this PR could not fix fc quantization slow perf issue, maybe we should just comment fc quant for some time. Leaving fc as fp32 is safer. We could think long term fix. But please check if your PR already fix #42972, thanks

This PR is only fixing VGG model like VGG16 and VGG19, so it doesn't fix #42972.

**Comment by wozna** [comment]
Has been fixed in another PR https://github.com/PaddlePaddle/Paddle/pull/43184

**Pull request closed without merging**
