### PR TITLE
remove vars when remove ops

### PR DESCRIPTION
**Pull request by luotao1**
when removing an op, the vars of  this op should be removed at the same time:
- output vars of this op: remove all.
- input vars of this op:  remove the input vars which are not used by other ops.

add a simple unit test to check `RemoveOp` method.

### CODE REVIEW

**Comment by typhoonzero** [comment]
Is there a case that the output of the removed op is used by other op?

**Comment by luotao1** [comment]
If the output of removed op is the input of other ops, then other ops should adjust their inputs. If the output of removed op is the output of other ops, although this case has not been seen now, but these output vars should be remained, how do you think about it ?

**Comment by qingqing01** [comment]
>  Is there a case that the output of the removed op is used by other op?

I think this case in existence. Maybe two ways to remove var:

1. remove vars specified by name ?
2. go through ProgramDesc to check whether some unused vars need to be removed ?

**Comment by typhoonzero** [comment]
If we want to make this a general function, it's quite complex, see https://github.com/PaddlePaddle/Paddle/pull/9080 and https://en.wikipedia.org/wiki/Static_single_assignment_form. We must build a SSA graph before head so that two ops have same outputs ( write to var ) won't affect each other.

For the simple implementation, I think just check if the output is used by other ops and do not remove them should work.

@qingqing01 

> remove vars specified by name ?

For generate inference programdesc, if remove_op can also remove unused vars, it's simpler to transpile a program for inference.

**Comment by luotao1** [comment]
I agree with the simple implementation for generating inference program-desc at first. 
And I adjust the remove rule of variables: for either input or output variable, if it is also an input or output variable of other ops, we should remain it.

**Pull request merged**
