### PR TITLE
disable ut quickly

### PR DESCRIPTION
**Pull request by XieYunshen**
### PR types

Others
### PR changes

Others
### Describe

disable ut quickly;

### CODE REVIEW

**Review by zhwesky2010 — DISMISSED** [review]
LGTM for windows

**Comment by chalsliu** [comment]
建议日志中打印disable了哪些单测

**Review by chalsliu — DISMISSED** [review]
LGTM

**Comment by XieYunshen** [comment]
> 建议日志中打印disable了哪些单测
done
Linux和Mac中会显示
image

**Review by chalsliu — DISMISSED** [review]

**Review by zhwesky2010 — APPROVED** [review]

**Review by chalsliu — APPROVED** [review]

**Pull request merged**
