### PR TITLE
Transfer MultiHeadAttention's matmul to v2 op

### PR DESCRIPTION
**Pull request by FrostML**
### PR types

Others

### PR changes

APIs

### Describe

Transfer MultiHeadAttention to v2 op. 
* matmul -> matmul_v2. 

More performance information can be found according to QA report. 

测试结论：
* 静态图、动态图均无无 5% 以上性能异常下降情况
* 动态图下： 8 卡性能下降最大的 case 为: transformer big bs4096 amp fp16: -3.55%

* 静态图下： 8 卡性能下降最大的 case 为: bert large seqlen512 fp32 bs10: -2.82%

### CODE REVIEW

**Review by jeff41404 — APPROVED** [review]
lgtm

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by guoshengCS — APPROVED** [review]

**Comment by raindrops2sea** [comment]
> ### PR types
> Others
> 
> ### PR changes
> APIs
> 
> ### Describe
> Transfer MultiHeadAttention to v2 op.
> 
> * matmul -> matmul_v2.
> 
> Performance: paddle commit id: [0c0817c](https://github.com/PaddlePaddle/Paddle/commit/0c0817cf1da06e75c88839b6f0827c490b615517) **GPU: V100**
> 
> * API test:
> 
> ```python
> import paddle
> import time
> import numpy as np
> import random
> paddle.seed(2)
> np.random.seed(2)
> random.seed(2)
> place = paddle.set_device("gpu")
> 
> a = paddle.randn([64, 64, 512])
> b = paddle.randn([64, 64, 512])
> 
> for i in range(1000000):
>     if i == 100:
>         start = time.time()
>     # c = paddle.fluid.layers.matmul(a, b, transpose_y=True, alpha=512**-0.5)
>     c = paddle.matmul(a, b, transpose_y=True) * (512**-0.5)
> paddle.fluid.core._cuda_synchronize(place)
> print(time.time() - start)
> ```
> 
> input shape is `[64, 64, 512]`	time
> layers.matmul(x=q, y=k, transpose_y=True, alpha=self.head_dim**-0.5)	59.297
> paddle.matmul(x=q, y=k, transpose_y=True) * (self.head_dim**-0.5)	65.234
> input shape is `[200, 16, 512]`	time
> layers.matmul(x=q, y=k, transpose_y=True, alpha=self.head_dim**-0.5)	24.457
> paddle.matmul(x=q, y=k, transpose_y=True) * (self.head_dim**-0.5)	40.186
> More performance information can be found according to QA report.

Please update the description.

**Comment by raindrops2sea** [comment]
Please update the description.

**Review by raindrops2sea — APPROVED** [review]

**Pull request merged**
