### PR TITLE
Update of oneDNN to 2.5

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Performance optimization

### PR changes
OPs

### Describe
Update of oneDNN from 2.4 to 2.5

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
It seems oneDNN2.5 need linux kernel specific version. Before it is merged, let me test on SPR. Since now we only have SPR installed with linux kernel v5.10

**Comment by jczaja** [comment]
@lidanqing-intel I tested manually on SPR this PR (run LSTM int8 model) and it DID not worked fine e.g. AMX was not present when running on SPR.

**Review by lidanqing-vv — DISMISSED** [review]
LGTM

**Review by jakpiase — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@baoachun I cannot have PR-CI-Build passed successfully despite many attempts(reruns) neither I can understand from logs where the problem is. Please advice how to pass PR-CI-Build

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Pull request merged**
