### PR TITLE
Turnon fc_mkldnn_pass fc_act_mkldnn_fuse_pass by default

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types
Others

### PR changes
Others

### Describe
Turn on fc_mkldnn_pass and fc_act_mkldnn_fuse_pass by default

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@baoachun  QA could follow this https://github.com/PaddlePaddle/continuous_integration/blob/develop/inference/inference_benchmark/cc/Paddle/intel_bash.sh to test models

**Comment by baoachun** [comment]
@lidanqing-intel  我看ci是精度下降挂掉了

**Comment by lidanqing-vv** [comment]
Why this CI failed without any error information?
```
2021-12-29 10:08:58 [INFO] Running on (paddle-clone-1) with agent(v1.2.6) in workspace /home/xly/workspace/f9d40cd7-b693-49ce-8af3-a0d599b3bd31
2021-12-29 10:08:58 + work_dir=/home/work
2021-12-29 10:08:59 + mkdir -p /home/work
2021-12-29 10:08:59 + rm -rf '/home/work/*'
2021-12-29 10:08:59 + cd /home/work
2021-12-29 10:08:59 + set +xe
```

**Comment by lidanqing-vv** [comment]
@baoachun Do you know why this PR-CI-Coverage fail without any log ?

**Comment by baoachun** [comment]
@lidanqing-intel  输入format不符合？
图片

**Comment by lidanqing-vv** [comment]
image
Left is 498dbfa8c55af592b74eaee543a5dace8531f068 + zuzg PR + this PR
Right is 498dbfa8c55af592b74eaee543a5dace8531f068 
Enable fc and fc_act made performance slightly drop, what do you think? Should I still turn it on ?

**Comment by lidanqing-vv** [comment]
[benchmark_mkl_excel_jacek.xlsx](https://github.com/PaddlePaddle/Paddle/files/7876961/benchmark_mkl_excel_jacek.xlsx)
[benchmark_mkl_excel_jacek_danqing_zuzg.xlsx](https://github.com/PaddlePaddle/Paddle/files/7876962/benchmark_mkl_excel_jacek_danqing_zuzg.xlsx)

**Comment by lidanqing-vv** [comment]
Close cause it slow down performance

**Pull request closed without merging**
