### PR TITLE
[Paddle-TRT] Fixes #24964, call cublasGemmStridedBatchedEx when using fp16

### LINKED ISSUE #24964: [Paddle-TRT] FP16 with cublasGemmStridedBatchedEx
-PaddlePaddle version: develop
-GPU: including CUDA/CUDNN version
-OS Platform Ubuntu 16.04

**Describe the feature and the current behavior/state.**
The implementation in [blas_impl.cu.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/blas_impl.cu.h#L430) doesn't use the ``cublasGemmStridedBatchedEx`` when the data type is fp16, even the ``CUDA_VERSION`` is greater than 9010. ``cublasGemmStridedBatchedEx`` has more capability like selecting the algorithm ([reference](https://docs.nvidia.com/cuda/cublas/index.html#cublas-GemmStridedBatchedEx)), it also performs better performance. We should use it when available, i.e., ``CUDA_VERSION >= 9010``.

So the code should be like this:
```
#if CUDA_VERSION >= 9010
  cublasGemmAlgo_t algo = CUBLAS_GEMM_DFALT;
  bool use_tensor_op_math = context_.tensor_core_available();
  if (FLAGS_enable_cublas_tensor_op_math && use_tensor_op_math) {
    algo = CUBLAS_GEMM_DFALT_TENSOR_OP;
  }
  VLOG(5) << "use_tensor_op_math: "
          << (use_tensor_op_math ? "True" : "False");

  auto fp = std::is_same<T, float>::value ? CUDA_R_32F : CUDA_R_16F;

  context_.TensorCoreCublasCallIfAvailable([&](cublasHandle_t handle) {
    PADDLE_ENFORCE_CUDA_SUCCESS(platform::dynload::cublasGemmStridedBatchedEx(
        handle, cuTransB, cuTransA, N, M, K, &alpha, B, fp, ldb,
        strideB, A, fp, lda, strideA, &beta, C, fp, ldc,
        strideC, batchCount, fp, algo));
  });
#else   // CUDA_VERSION < 9010
  context_.CublasCall([&](cublasHandle_t handle) {
    CUBlas<T>::GEMM_STRIDED_BATCH(handle, cuTransB, cuTransA, N, M, K, &alpha,
                                  B, ldb, strideB, A, lda, strideA, &beta, C,
                                  ldc, strideC, batchCount);
  });
#endif  // CUDA_VERSION >= 9010

```

### PR DESCRIPTION
**Pull request by zlsh80826**
### PR types

Function optimization

### PR changes

Others

### Describe

Call `cublasGemmStridedBatchedEx` when using fp16 and the tensor core is available

### CODE REVIEW

**Comment by NHZlX** [comment]
This pr leads to mutihead matul utest failed

**Comment by zhangting2020** [comment]
Before this PR, GEMM_STRIDED_BATCH will be called when dtype is float32. How about calling cublasGemmStridedBatchedEx only when the data type is float16. For example,
```c++
#if CUDA_VERSION >= 9010
  if ((FLAGS_enable_cublas_tensor_op_math && (std::is_same<T, float>::value)) ||
      std::is_same<T, paddle::platform::float16>::value) {
    cublasGemmAlgo_t algo = CUBLAS_GEMM_DFALT;
    bool use_tensor_op_math = context_.tensor_core_available();
    if (use_tensor_op_math) {
      algo = CUBLAS_GEMM_DFALT_TENSOR_OP;
    }
    VLOG(5) << "use_tensor_op_math: "
            << (use_tensor_op_math ? "True" : "False");

    auto fp = std::is_same<T, float>::value ? CUDA_R_32F : CUDA_R_16F;
    context_.TensorCoreCublasCallIfAvailable([&](cublasHandle_t handle) {
      PADDLE_ENFORCE_CUDA_SUCCESS(platform::dynload::cublasGemmStridedBatchedEx(
          handle, cuTransB, cuTransA, N, M, K, &alpha, B, fp, ldb, strideB, A,
          fp, lda, strideA, &beta, C, fp, ldc, strideC, batchCount, fp, algo));
    });
  } else {
#endif  // CUDA_VERSION >= 9010

    context_.CublasCall([&](cublasHandle_t handle) {
      CUBlas<T>::GEMM_STRIDED_BATCH(handle, cuTransB, cuTransA, N, M, K, &alpha,
                                    B, ldb, strideB, A, lda, strideA, &beta, C,
                                    ldc, strideC, batchCount);
    });

#if CUDA_VERSION >= 9010
  }
#endif  // CUDA_VERSION >= 9010
}
```
I have tested that the above modification will not cause the unittest to fail.

**Comment by zlsh80826** [comment]
Hello @zhangting2020,
Our future goal is passing different algorithms when doing the inference. So we want to call `cublasGemmStridedBatchedEx` as much as possible. I think we will not call `cublasGemmStridedBatchedEx` when datatype is fp32 and `FLAGS_enable_cublas_tensor_op_math=0` in your case. However, in this case, we want to call `cublasGemmStridedBatchedEx(..., CUBLAS_GEMM_DFALT_TENSOR_OP, ...)` instead.

**Comment by zhangting2020** [comment]
@zlsh80826 It seems that when the dtype is float32, calling cublasGemmStridedBatchedEx will cause accuracy difference. 
```
2020-07-10 12:46:45 W0710 04:46:41.459350 30683 device_context.cc:268] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.1
2020-07-10 12:46:45 W0710 04:46:41.464474 30683 device_context.cc:276] device: 0, cuDNN Version: 7.6.
2020-07-10 12:46:45 test_fused_multihead_matmul_op failed
2020-07-10 12:46:45  FF
2020-07-10 12:46:45 ======================================================================
2020-07-10 12:46:45 FAIL: test_check_output (test_fused_multihead_matmul_op.TestFusedMultiHeadMatmulOp2)
2020-07-10 12:46:45 ----------------------------------------------------------------------
2020-07-10 12:46:45 Traceback (most recent call last):
2020-07-10 12:46:45   File "/paddle/build/python/paddle/fluid/tests/unittests/test_fused_multihead_matmul_op.py", line 112, in test_check_output
2020-07-10 12:46:45     self.check_output_with_place(place, atol=2e-3)
2020-07-10 12:46:45   File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1056, in check_output_with_place
2020-07-10 12:46:45     str(actual_t) + " in class " + self.__class__.__name__)
2020-07-10 12:46:45 AssertionError: Output (Out) has diff at CUDAPlace(0)
2020-07-10 12:46:45 Expect [[[  5.776616     3.9715116    5.201322   ...   8.596786     5.8878407
2020-07-10 12:46:45      4.0973763 ]
2020-07-10 12:46:45   [  7.8005614    6.308768     8.905681   ...   8.671705     6.89982
2020-07-10 12:46:45      5.8040943 ]
2020-07-10 12:46:45   [-13.1742525  -10.099151   -13.139561   ...  -5.045996    -8.11002
2020-07-10 12:46:45     -8.70053   ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [-13.1742525  -10.099151   -13.139561   ...  -5.045996    -8.11002
2020-07-10 12:46:45     -8.70053   ]
2020-07-10 12:46:45   [  7.802108     8.018037    10.227896   ...   8.983935     6.951409
2020-07-10 12:46:45      6.315857  ]
2020-07-10 12:46:45   [  7.818101     8.106127    10.483855   ...   8.343097     6.85838
2020-07-10 12:46:45      5.2832446 ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[ -8.214077    -6.531863    -8.048469   ...  -5.9264445   -4.9786973
2020-07-10 12:46:45     -5.163481  ]
2020-07-10 12:46:45   [  8.762487     6.4557467    7.4881344  ...   7.795342     9.453417
2020-07-10 12:46:45      9.227907  ]
2020-07-10 12:46:45   [ -8.262811    -6.521938    -8.08897    ... -11.766105    -8.842117
2020-07-10 12:46:45     -9.550448  ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  8.705818     6.6128187    7.163091   ...   5.521026     7.5131273
2020-07-10 12:46:45      9.817219  ]
2020-07-10 12:46:45   [  8.738355     6.5223136    7.5150104  ...   8.1346035    9.741439
2020-07-10 12:46:45      9.1354065 ]
2020-07-10 12:46:45   [  8.74401      8.270022     5.559404   ...   7.405386     8.783498
2020-07-10 12:46:45      8.107179  ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[ -0.6964107    0.39817268  -0.3639686  ...  -6.3362374   -5.5737033
2020-07-10 12:46:45     -6.0001307 ]
2020-07-10 12:46:45   [  1.7404548    1.4094388    1.4225312  ...  -6.7152634   -7.022369
2020-07-10 12:46:45     -7.077012  ]
2020-07-10 12:46:45   [  9.5911875    2.5953467    4.8701067  ...   9.259661     8.169888
2020-07-10 12:46:45     10.095537  ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [ -7.336084    -7.771396    -9.586166   ...  -8.878321    -6.734918
2020-07-10 12:46:45     -7.736672  ]
2020-07-10 12:46:45   [ -6.745624    -6.6974626   -8.12866    ...  -9.6381235   -7.154953
2020-07-10 12:46:45     -8.217078  ]
2020-07-10 12:46:45   [  6.1508255    4.49273      5.5540066  ...   8.703482     8.116027
2020-07-10 12:46:45      9.43808   ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  ...
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[  8.600853     6.6734896    6.5445833  ...   8.165901     8.029342
2020-07-10 12:46:45      8.159456  ]
2020-07-10 12:46:45   [  8.470227     6.2325935    6.1604953  ...   8.160879     8.023905
2020-07-10 12:46:45      8.142258  ]
2020-07-10 12:46:45   [-10.788595   -10.179301   -10.481063   ... -10.802945   -14.784469
2020-07-10 12:46:45    -10.475583  ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  8.604747     6.68009      6.5499144  ...   8.165015     8.03565
2020-07-10 12:46:45      8.169079  ]
2020-07-10 12:46:45   [-10.83294    -10.217027   -10.490349   ... -10.865822   -15.057756
2020-07-10 12:46:45    -10.465141  ]
2020-07-10 12:46:45   [ -6.6157055   -6.561237    -7.6280293  ... -10.493526   -13.600616
2020-07-10 12:46:45    -10.445425  ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[  8.90605      9.085551     8.955194   ...   9.96135     10.409067
2020-07-10 12:46:45      7.8788557 ]
2020-07-10 12:46:45   [ -8.599926   -10.155849   -12.093031   ...  -8.782974    -6.200974
2020-07-10 12:46:45     -8.887322  ]
2020-07-10 12:46:45   [  8.426503     8.759588     8.577809   ...   3.7943182    6.4377933
2020-07-10 12:46:45      4.34755   ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [ -8.599942   -10.155886   -12.0930605  ...  -8.782976    -6.200968
2020-07-10 12:46:45     -8.887324  ]
2020-07-10 12:46:45   [  8.230652     8.658945     8.393938   ...   9.94738     10.405576
2020-07-10 12:46:45      7.870036  ]
2020-07-10 12:46:45   [  8.455787     8.5538435    9.029001   ...   8.844844     9.589812
2020-07-10 12:46:45      6.518222  ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[ -2.9581232   -3.6234586   -4.351145   ...  -7.3564134   -4.6793623
2020-07-10 12:46:45     -6.1434345 ]
2020-07-10 12:46:45   [ -8.084079    -6.002945    -8.35218    ...   2.6217618    3.459871
2020-07-10 12:46:45      1.8275186 ]
2020-07-10 12:46:45   [  7.912509     5.9496336    8.644568   ...   7.014971     7.7406545
2020-07-10 12:46:45      6.6400695 ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  7.80948      6.482283     7.297437   ...   7.130148     8.070193
2020-07-10 12:46:45      6.755789  ]
2020-07-10 12:46:45   [  7.7085843    6.5489       7.260419   ...   6.6698914    6.891833
2020-07-10 12:46:45      6.183354  ]
2020-07-10 12:46:45   [ -8.109389    -5.98236     -8.366132   ...  -6.402679    -7.5874915
2020-07-10 12:46:45     -7.4038444 ]]]
2020-07-10 12:46:45 But Got[[[  5.7764406    3.9713144    5.2009387  ...   8.597683     5.8871093
2020-07-10 12:46:45      4.096999  ]
2020-07-10 12:46:45   [  7.7980194    6.3102627    8.906955   ...   8.669369     6.896156
2020-07-10 12:46:45      5.7993584 ]
2020-07-10 12:46:45   [-13.171875   -10.1015625  -13.140625   ...  -5.046875    -8.109375
2020-07-10 12:46:45     -8.703125  ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [-13.171875   -10.1015625  -13.140625   ...  -5.046875    -8.109375
2020-07-10 12:46:45     -8.703125  ]
2020-07-10 12:46:45   [  7.802036     8.018857    10.225206   ...   8.982766     6.9488616
2020-07-10 12:46:45      6.31399   ]
2020-07-10 12:46:45   [  7.818556     8.107937    10.482648   ...   8.342636     6.8575816
2020-07-10 12:46:45      5.2801905 ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[ -8.217687    -6.530621    -8.045495   ...  -5.9256635   -4.976669
2020-07-10 12:46:45     -5.1651325 ]
2020-07-10 12:46:45   [  8.760054     6.456053     7.4876533  ...   7.7953463    9.454408
2020-07-10 12:46:45      9.229492  ]
2020-07-10 12:46:45   [ -8.266894    -6.520753    -8.086368   ... -11.765665    -8.843775
2020-07-10 12:46:45     -9.54696   ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  8.704506     6.614665     7.1618905  ...   5.519387     7.512497
2020-07-10 12:46:45      9.816418  ]
2020-07-10 12:46:45   [  8.736592     6.5233183    7.5151815  ...   8.135923     9.743076
2020-07-10 12:46:45      9.135021  ]
2020-07-10 12:46:45   [  8.748523     8.273381     5.5612817  ...   7.403362     8.782416
2020-07-10 12:46:45      8.104924  ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[ -0.6992238    0.39617383  -0.3659378  ...  -6.3344      -5.5711913
2020-07-10 12:46:45     -5.9984236 ]
2020-07-10 12:46:45   [  1.7424885    1.4114112    1.4247384  ...  -6.713958    -7.02124
2020-07-10 12:46:45     -7.076179  ]
2020-07-10 12:46:45   [  9.595127     2.5965304    4.8706975  ...   9.257813     8.171876
2020-07-10 12:46:45     10.093751  ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [ -7.334356    -7.7696047   -9.5856695  ...  -8.879744    -6.7331924
2020-07-10 12:46:45     -7.737253  ]
2020-07-10 12:46:45   [ -6.7498636   -6.6997128   -8.134048   ...  -9.637855    -7.151783
2020-07-10 12:46:45     -8.2163515 ]
2020-07-10 12:46:45   [  6.1517844    4.492412     5.554113   ...   8.702999     8.115968
2020-07-10 12:46:45      9.438016  ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  ...
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[  8.595855     6.6716714    6.544054   ...   8.1661825    8.03396
2020-07-10 12:46:45      8.163469  ]
2020-07-10 12:46:45   [  8.466616     6.2291603    6.158403   ...   8.160241     8.027573
2020-07-10 12:46:45      8.1453285 ]
2020-07-10 12:46:45   [-10.790945   -10.180647   -10.484219   ... -10.804547   -14.788273
2020-07-10 12:46:45    -10.479845  ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  8.6015625    6.6796875    6.5507812  ...   8.1640625    8.0390625
2020-07-10 12:46:45      8.171875  ]
2020-07-10 12:46:45   [-10.831809   -10.215091   -10.49012    ... -10.865456   -15.058133
2020-07-10 12:46:45    -10.467831  ]
2020-07-10 12:46:45   [ -6.614438    -6.55947     -7.626449   ... -10.492868   -13.599354
2020-07-10 12:46:45    -10.447964  ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[  8.904865     9.086076     8.954507   ...   9.961533    10.404607
2020-07-10 12:46:45      7.879526  ]
2020-07-10 12:46:45   [ -8.601607   -10.156284   -12.093807   ...  -8.781265    -6.1992393
2020-07-10 12:46:45     -8.890641  ]
2020-07-10 12:46:45   [  8.423895     8.761903     8.576064   ...   3.7955935    6.43977
2020-07-10 12:46:45      4.348063  ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [ -8.6015625  -10.15625    -12.09375    ...  -8.781253    -6.1992226
2020-07-10 12:46:45     -8.890628  ]
2020-07-10 12:46:45   [  8.227198     8.661357     8.3910475  ...   9.947214    10.400812
2020-07-10 12:46:45      7.870427  ]
2020-07-10 12:46:45   [  8.452787     8.554865     9.025612   ...   8.845201     9.584945
2020-07-10 12:46:45      6.518692  ]]
2020-07-10 12:46:45 
2020-07-10 12:46:45  [[ -2.9586418   -3.6230829   -4.351913   ...  -7.3557158   -4.6789207
2020-07-10 12:46:45     -6.1428094 ]
2020-07-10 12:46:45   [ -8.084247    -6.001172    -8.353414   ...   2.620895     3.4578404
2020-07-10 12:46:45      1.825903  ]
2020-07-10 12:46:45   [  7.912005     5.9501696    8.642587   ...   7.012212     7.7381415
2020-07-10 12:46:45      6.6401606 ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  7.809762     6.482481     7.2992983  ...   7.1299777    8.070292
2020-07-10 12:46:45      6.7587857 ]
2020-07-10 12:46:45   [  7.70792      6.5484767    7.261619   ...   6.6695876    6.891098
2020-07-10 12:46:45      6.1848745 ]
2020-07-10 12:46:45   [ -8.109375    -5.9804688   -8.3671875  ...  -6.403287    -7.5863996
2020-07-10 12:46:45     -7.403119  ]]] in class TestFusedMultiHeadMatmulOp2
2020-07-10 12:46:45 
2020-07-10 12:46:45 ======================================================================
2020-07-10 12:46:45 FAIL: test_check_output (test_fused_multihead_matmul_op.TestFusedMultiheadMatmulOp)
2020-07-10 12:46:45 ----------------------------------------------------------------------
2020-07-10 12:46:45 Traceback (most recent call last):
2020-07-10 12:46:45   File "/paddle/build/python/paddle/fluid/tests/unittests/test_fused_multihead_matmul_op.py", line 112, in test_check_output
2020-07-10 12:46:45     self.check_output_with_place(place, atol=2e-3)
2020-07-10 12:46:45   File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1056, in check_output_with_place
2020-07-10 12:46:45     str(actual_t) + " in class " + self.__class__.__name__)
2020-07-10 12:46:45 AssertionError: Output (Out) has diff at CUDAPlace(0)
2020-07-10 12:46:45 Expect [[[  8.95059    15.543324   12.6098175 ...   4.000815   13.59532
2020-07-10 12:46:45     11.329147 ]
2020-07-10 12:46:45   [-10.671515  -10.151385  -13.8746    ... -11.065385  -16.299675
2020-07-10 12:46:45    -10.7878065]
2020-07-10 12:46:45   [  4.9835615   5.405641    5.7174673 ...   4.6468673   9.358703
2020-07-10 12:46:45     13.359614 ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  8.95059    15.543324   12.6098175 ...   4.00167    13.593628
2020-07-10 12:46:45     11.328342 ]
2020-07-10 12:46:45   [-10.671515  -10.151385  -13.8746    ... -11.065385  -16.299675
2020-07-10 12:46:45    -10.7878065]
2020-07-10 12:46:45   [  8.95059    15.543324   12.6098175 ...   4.000815   13.59532
2020-07-10 12:46:45     11.329147 ]]]
2020-07-10 12:46:45 But Got[[[  8.953125   15.546875   12.609375  ...   4.         13.59375
2020-07-10 12:46:45     11.328125 ]
2020-07-10 12:46:45   [-10.671875  -10.1484375 -13.875     ... -11.0625    -16.296875
2020-07-10 12:46:45    -10.7890625]
2020-07-10 12:46:45   [  4.9801455   5.395029    5.702401  ...   4.6455297   9.358577
2020-07-10 12:46:45     13.360432 ]
2020-07-10 12:46:45   ...
2020-07-10 12:46:45   [  8.953125   15.546875   12.609375  ...   4.001551   13.5944805
2020-07-10 12:46:45     11.32933  ]
2020-07-10 12:46:45   [-10.671875  -10.1484375 -13.875     ... -11.0625    -16.296875
2020-07-10 12:46:45    -10.7890625]
2020-07-10 12:46:45   [  8.953125   15.546875   12.609375  ...   4.         13.59375
2020-07-10 12:46:45     11.328125 ]]] in class TestFusedMultiheadMatmulOp
2020-07-10 12:46:45 
2020-07-10 12:46:45 ----------------------------------------------------------------------
2020-07-10 12:46:45 Ran 2 tests in 6.202s
```

I read the [CUDA Toolkit Documentation](https://docs.nvidia.com/cuda/cublas/index.html#cublas-GemmStridedBatchedEx) and noticed the following table
image

Does it mean that the input data dtype(float32) will be converted to float16? It seems that this is the reason for the loss of accuracy. Could you please help check the usage here?

**Comment by zlsh80826** [comment]
@zhangting2020 ,
I think the problem is caused by `TensorCoreCublasCallIfAvailable`, I will see whether we can call `cublasGemmStridedBatchedEx` without it if `cublasGemmStridedBatchedEx=false`.

**Comment by zhangting2020** [comment]
@zlsh80826 You can support FP16 first [as the code above](https://github.com/PaddlePaddle/Paddle/pull/25207#issuecomment-659298769), and then support FP32 in another PR.

**Comment by zhangting2020** [comment]
I recently found some problems when testing the performance of the matmul op. May I ask you some questions?
- The [Tensor Core Requirements](https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc) mentions that  in order to use Tensor Cores, NVIDIA libraries require that matrix dimensions M, N, and K are multiples of 8 (with FP16 data). Is there any way to speed up the computation when the requirements for using Tensor Core are not met?
- I did some experiments. When the input of matmul op is a 3-D or 2-D Tensor and K is not multiples of 8,  the performance of FP16 kernel is not much faster(Ideally, I think it should be 2x) than FP32 kernel. I found that in this case it will call the following function. And I noticed the computeType is  FP32. Should we change the  computeType to FP16 to speed up it? 

https://github.com/PaddlePaddle/Paddle/blob/f8ec5f0fceaeb7452acfe31a19b54c69e3c986a1/paddle/fluid/operators/math/blas_impl.cu.h#L316-L319

Here are experiments. The input shapes are the same in two cases. And it is tested on Tesla V100.
- Case 1: The dtype is float16
```
  x_shape: [16, 36, 1504]
  x_dtype: float16
  y_shape: [1504, 998]
  y_dtype: float16

```

```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   98.53%  171.15ms      1001  170.98us  147.07us  188.45us  volta_fp16_sgemm_fp16_32x128_nn
                    1.06%  1.8448ms      1005  1.8350us  1.6640us  2.2720us  [CUDA memset]
```
- Case 2: The dtype is float32
```
  x_shape: [16, 36, 1504]
  x_dtype: float32
  y_shape: [1504, 998]
  y_dtype: float32
```
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   98.09%  172.07ms      1001  171.90us  155.10us  185.50us  volta_sgemm_32x128_nn
                    1.05%  1.8455ms      1005  1.8360us  1.6640us  2.7840us  [CUDA memset]
```

**Comment by zlsh80826** [comment]
Hello @zhangting2020,

First question,
yes, your data should meet the requirement to enable tensor core before cublas 11. After cublas 11, cublas will use tensor core automatically if tensor core is faster regardless of the requirement.

Second,
If you are testing the performance of GEMM, I recommend this [repo](https://github.com/jeng1220/cuGemmProf) for testing different settings. Then you can observe that `compute type = CUDA_R_16F` can speed up on volta architecture. However, because there is no tensor core on pre-volta architecture, it will be very slow on pre-volta architecture. However, I think you can pull another request to use `compute_type = CUDA_R_16F` if the compute capability is great than volta.

Below is my testing log (the last column is the performance),
```
$ ./cuGemmProf -m 512 -n 512 -k 128 --type 0,2 -l 100 --all_algo -r 20 -w 8 -d 2 | grep DEFAULT
Tesla T4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT, 0.0171011, 3924.24
Tesla T4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT_TENSOR_OP, 0.00722336, 9290.53
Tesla T4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_32F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT, 0.017631, 3806.29
Tesla T4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_32F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT_TENSOR_OP, 0.00760032, 8829.74
$ ./cuGemmProf -m 512 -n 512 -k 128 --type 0,2 -l 100 --all_algo -r 20 -w 8 -d 3 | grep DEFAULT
Tesla P4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT, 1.17914, 56.9134
Tesla P4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT_TENSOR_OP, 0.951426, 70.535
Tesla P4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_32F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT, 0.0252627, 2656.44
Tesla P4, CUBLAS_OP_N, CUBLAS_OP_N, 512, 512, 128, CUDA_R_32F, CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, all meet, all meet, CUBLAS_GEMM_DEFAULT_TENSOR_OP, 0.0249603, 2688.62
```

**Pull request closed without merging**
