### PR TITLE
remove unnecessary attrs copy

### PR DESCRIPTION
**Pull request by lidanqing-intel**
### PR types
Others 

### PR changes
Others

### Describe
Solve issue #28002 performance decrease 5%. Remove unnecessary Attrs copy which caused performance drop.

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@arlesniak  Please review and leave a LGTM
These few lines were added by sylwek before, but later some changes happened and this `mutable_op_attrs` was never used in any other place.
It caused baidu models performance drop 5%, removing it is necessary.

@luotao1  The approval CI failed because I deleted const_cast, after @arlesniak reviewed, you could approve.

**Comment by arlesniak** [comment]
If you look at the PR-CI-Coverage and  PR-CI-Windows error logs removing the lines causes the value of 'use_mkldnn' attribute not to be passed properly to the op.

**Comment by luotao1** [comment]
@lidanqing-intel Please update this PR since #28147 is merged

**Review by luotao1 — APPROVED** [review]

**Comment by luotao1** [comment]
ptb lm sequence FPS:
- develop (https://github.com/PaddlePaddle/Paddle/commit/a1e7fd4a139bd95abc29960ef97e4369af1a1f4c): 25.253 steps/s
- develop+PR: 26.108 steps/s

**Pull request merged**
