### PR TITLE
Fix for expand_v2 op

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Bug fixes

### PR changes
OPs

### Describe
Fix for expand_v2 op mentioned in #34723 for solov2 and ppyolo_mbv3 models

### CODE REVIEW

**Review by lidanqing-vv — COMMENTED** [review]
Hi, @jakpiase  Thanks ! Is this case tested? Maybe add a UT for it?
```
for (size_t i = 0; i < out_new_dims.size(); ++i) {
      out_new_dims[i] = out_new_dims[i] > 0 ? out_new_dims[i] : x_vec_dims[i];
    }
```

**Comment by OliverLPH** [comment]
Thanks @jakpiase.
And could you please enable [test_ppyolo_mbv3(multi_thread4_mkl_bz2)](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/infer_ut/test_ppyolo_mbv3.cc#L104), it will automatically  run in `PR-CI-Inference` task, so that I can know whether it fix  ppyolo_mbv3.

https://github.com/PaddlePaddle/Paddle/blob/b0a1d122c3cdde00284706ff904bdeb48378490e/paddle/fluid/inference/tests/infer_ut/test_ppyolo_mbv3.cc#L104

**Review by jczaja — DISMISSED** [review]

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Review by OliverLPH — APPROVED** [review]
LGTM

**Pull request merged**
