### PR TITLE
Fix bug of sampling_id op

### PR DESCRIPTION
**Pull request by zenghsh3**
sorry!
The code i mentioned in  #12890 is wrong! The correct implementation should be this PR.
Have verified the op in local.

### CODE REVIEW

**Comment by zenghsh3** [comment]
@seiriosPlus @JiayiFeng please help review the code.

**Comment by seiriosPlus** [comment]
can add some unit tests?

**Comment by zenghsh3** [comment]
Have refine origin unittest:
- check output dtype
- check output is in index ids of inputs

**Review by seiriosPlus — APPROVED** [review]
LGTM！

**Pull request merged**
