### PR TITLE
Fix div 0 error of case20: paddle.min

### PR DESCRIPTION
**Pull request by RedContritio**
### PR types

Bug fixes

### PR changes

OPs

### Describe

- #49919
- #49927 

### Solution

- 规定 0 / 0 == 0

### CODE REVIEW

**Review by wanghuancoder — COMMENTED** [review]
为这个case加个单测吧

**Comment by RedContritio** [comment]
> 为这个case加个单测吧

已添加

**Comment by RedContritio** [comment]
@wanghuancoder 待 approve

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by csy0225 — APPROVED** [review]

**Pull request merged**
