### PR TITLE
update how to write docs

### PR DESCRIPTION
**Pull request by tink2123**

### CODE REVIEW

**Review by luotao1 — COMMENTED** [review]
对应的英文文档也可以一并修改了。

**Comment by tink2123** [comment]
好的 后面会开始修改英文版~

**Review by jetfuel — APPROVED** [review]
Things will be different once we start using FluidDoc. Some steps here won't apply anymore. otherwise, LGTM for this version

**Comment by luotao1** [comment]
This PR will be updated in FluidDoc repo. Close it at first.

**Pull request closed without merging**
