### PR TITLE
fix kron_op: when only one input needs gradient, test=develop

### PR DESCRIPTION
**Pull request by iclementine**
fix kron_op: when only one input needs gradient

Kron op wroks like matmul. It has two inputs, X and Y. So we need to check their gradients altogether, and separately.

### CODE REVIEW

**Review by kuke — DISMISSED** [review]
LGTM

**Review by phlrain — DISMISSED** [review]
LGTM for no_grad_set

**Review by Shixiaowei02 — DISMISSED** [review]

**Review by Boyan-Liu — DISMISSED** [review]

**Review by swtkiwi — DISMISSED** [review]
LGTM

**Review by kuke — APPROVED** [review]

**Review by phlrain — APPROVED** [review]
LGTM for no_grad_set

**Pull request merged**
