### PR TITLE
Readme Corrections

### PR DESCRIPTION
**Pull request by Muennighoff**
Changed small grammatical & plural errors in the ReadMe

### CODE REVIEW

**Review by Heeenrrry — APPROVED** [review]
Hi, Muennighoff, many thanks for your contribution! We are pleased to accept the corrections and looking forward to seeing more wonderful feedbacks from you!

**Review by swtkiwi — DISMISSED** [review]
LGTM

**Review by Heeenrrry — CHANGES_REQUESTED** [review]
The CI check of the pull request can't start up unless writing the commit message in this way `git commit -m “Readme Corrections, test = develop, test=document_fix”`. Could you please make the necessary change?

**Comment by Muennighoff** [comment]
> The CI check of the pull request can't start up unless writing the commit message in this way `git commit -m “Readme Corrections, test = develop, test=document_fix”`. Could you please make the necessary change?

Yes sure, sorry for forgetting it  –– How do I change the commit message on the desktop version? Or do I need to download the repo and amend the messages via git commit --amend..?

**Comment by luotao1** [comment]
> amend the messages via git commit --amend

Yes, you can do it.

**Review by Heeenrrry — APPROVED** [review]

**Review by swtkiwi — APPROVED** [review]
LGTM

**Pull request merged**
