### PR TITLE
[cherry-pick] NVIDIA fixes

### PR DESCRIPTION
**Pull request by Aganlengzi**
### PR types
Others

### PR changes
Others

### Describe
Cherry pick the following PRs：
1.Fix several unit tests and increase the unit tests stability https://github.com/PaddlePaddle/Paddle/pull/43670
2.Use fixed random seed https://github.com/PaddlePaddle/Paddle/pull/43659
3.Fix 3 unittest errors https://github.com/PaddlePaddle/Paddle/pull/43532
4.Use all sitepackages path as the library/include path https://github.com/PaddlePaddle/Paddle/pull/42940

### CODE REVIEW

**Review by XieYunshen — DISMISSED** [review]
LGTM for `set_tests_properties(test_gather_op PROPERTIES TIMEOUT 180)`

**Review by qili93 — DISMISSED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM for `set_tests_properties(test_gather_op PROPERTIES TIMEOUT 180)`

**Review by qili93 — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
