### PR TITLE
Replacing set_format with set_mem_desc in FC onednn kernel

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Others 

### PR changes
OPs 

### Describe
This PR replace set_format with set_mem_desc and also reimplemented whole FC kernel not to use caching mechanism (to rely on oneDNN caching mechanism)

### CODE REVIEW

**Review by jakpiase — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@Aganlengzi  Please help to sort out the problem with PR-CI-Coverage. Error message is:
_2022-09-22 21:35:15 cp: error reading '/home/data/cfs/coverage/46372/be8a72d1cb5ba415ac21a2dfc6bd1f71aaf11e71/Paddle.tar.gz': Input/output error_

**Comment by yaomichael** [comment]
@jiangjiajun can you help have a look at the CI coverage error of this PR?

**Review by zhiqiu — APPROVED** [review]
LGTM for ShareDataWith

**Pull request merged**
