### PR TITLE
resolve #16987

### LINKED ISSUE #16987: 建议修改test_conv2d_op.py中一个非测试case的名称
[testcuda](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_conv2d_op.py#L120) 是否可以修改为has_cuda(self)? 这里使用test开头，会被unittest认为是一个test case，尽管这不是。

### PR DESCRIPTION
**Pull request by guomingz**
resolve #16987

Rename the testcuda function to has_cuda, it will elimate the unnecessary testing.
test=develop

### CODE REVIEW

**Comment by guomingz** [comment]
hi @luotao1 ， the pre-ci had been passed, please help to review.

**Comment by luotao1** [comment]
- Before:
http://ci.paddlepaddle.org/viewLog.html?tab=buildLog&buildTypeId=Paddle_PrCi&buildId=87531&_focus=12471#_state=86
```
[07:32:36] 62/145 Test #274: test_conv2d_op ...........................   Passed   28.61 sec
```
- After:
```
253/617 Test #274: test_conv2d_op ......................................   Passed   12.66 sec
```

**Comment by guomingz** [comment]
> 274: test_conv2d_op

yes. any issue on the log?

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
