### PR TITLE
[DO NOT MERGE]Test ngraph cmake 3.5

### PR DESCRIPTION
**Pull request by baojun-nervana**
@luotao1 This PR is to verify it won't cause any issue if ngraph set cmake minimum required to 3.5. It is not intended to merge now. If there is any known issue, I will advice ngraph not to set to 3.5.

### CODE REVIEW

**Comment by baojun-nervana** [comment]
@luotao1 @tensor-tang It passed CI. Is there any other concern on cmake3.5?
	+ '[' 15709 '!=' '' ']'
[23:16:39]	++ curl -H 'Authorization: token 95a329e820eeae12c4c5c8a0b6e3e39654dc01a4' 'https://api.github.com/repos/PaddlePaddle/Paddle/pulls/15709/reviews?per_page=10000'
[23:16:39]	++ python /paddle/tools/check_pr_approval.py 1 2887803
[23:16:39]	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[23:16:39]	                                 Dload  Upload   Total   Spent    Left  Speed
[23:16:39]	
[23:16:40]	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[23:16:40]	  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[23:16:40]	100     5  100     5    0     0      3      0  0:00:01  0:00:01 --:--:--     3
[23:16:40]	+ APPROVALS=FALSE
[23:16:40]	+ echo 'current pr 15709 got approvals: FALSE'
[23:16:40]	+ '[' FALSE == FALSE ']'
[23:16:40]	+ echo 'You must have panyx0718 approval for the api change! cmake/external'
[23:16:40]	+ exit 1
[23:16:48]	Process exited with code 1

**Comment by luotao1** [comment]
Why do you update Ngraph tag?
But not update
https://github.com/PaddlePaddle/Paddle/blob/c47e258ea489a7773eb6a257b969195dec7642a5/CMakeLists.txt#L15
I thought you update `cmake_minimum_required(VERSION 3.5)`, maybe I was wrong?

> [23:16:40]	+ echo 'You must have panyx0718 approval for the api change! cmake/external'

Any change to cmake/external/ should be approved by panyx0718.

**Comment by luotao1** [comment]
Please update the description of this PR. There is nothing in description.

**Review by tensor-tang — COMMENTED** [review]
My concern is that does our online deployment support at least cmake 3.5 @panyx0718 @luotao1 .

Such as our internal env.

**Comment by luotao1** [comment]
http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/Tables.html
image
cmake al least should be 3.4. @tensor-tang 

@JiabinYang Why `MAC_PR_CI` pass but `MAC_PR_CI_python35` fails at
```
[04:05:11]CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
[04:05:11]  CMake 3.5 or higher is required.  You are running version 3.4.3
```
http://ci.paddlepaddle.org/viewLog.html?buildId=58711&buildTypeId=PaddleMac_MacPrCiPython35&tab=buildLog

**Comment by tensor-tang** [comment]
@luotao1 the doc link is just for external use.
As for external, we can resolve the version minimum require anyway.
But as for internal use, for example, if we need compile in icode or bcloud with ngraph, does it need internal env upgrate cmake, is that possible or convenience. 
That is my concern.

**Comment by JiabinYang** [comment]
> http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/Tables.html
> image
> cmake al least should be 3.4. @tensor-tang
> 
> @JiabinYang Why `MAC_PR_CI` pass but `MAC_PR_CI_python35` fails at
> 
> ```
> [04:05:11]CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
> [04:05:11]  CMake 3.5 or higher is required.  You are running version 3.4.3
> ```
> http://ci.paddlepaddle.org/viewLog.html?buildId=58711&buildTypeId=PaddleMac_MacPrCiPython35&tab=buildLog

yes, cmake version on Mac CI machines is 3.4.3, and python35 Mac ci is built by @velconia, could u plz  solve this problem? @velconia

**Comment by luotao1** [comment]
@baojun-nervana please update with `cmake_minimum_required(VERSION 3.4)`.
> But as for internal use, for example, if we need compile in icode or bcloud with ngraph, does it need internal env upgrate cmake, is that possible or convenience.

@tensor-tang if cmake version < 3.4, the external use fails as well.

**Comment by baojun-nervana** [comment]
I will recommend ngraph to set mininum as 3.4 or 3.3

**Pull request closed without merging**
