### PR TITLE
fix ngraph compile issue 

### PR DESCRIPTION
**Pull request by baojun-nervana**
Fix compile issue with gcc 4.8 https://github.com/PaddlePaddle/Paddle/issues/15599

### CODE REVIEW

**Comment by tensor-tang** [comment]
Could you give a little bit explanation why fail before?

**Comment by baojun-nervana** [comment]
the gcc 4.8 was given by an env variables which was received by paddle but not by nGraph. NGraph used the system gcc which is 5.4 and caused a mismatch.

**Comment by tensor-tang** [comment]
Got it, Thanks.

**Review by tensor-tang — APPROVED** [review]
fixed the problem

**Pull request merged**
