### PR TITLE
Fix some english doc api, shenze tools group

### PR DESCRIPTION
**Pull request by wawltor**
test=document_fix
Fix english doc api, invloves the op of greater_equal,greater_than,less_equal,not_equal,
rank,rsqrt,diag,linspace,reduce_all,reduce_any,sign,where,zeros_like,unique_with_counts.

### CODE REVIEW

**Comment by wawltor** [comment]
https://user-images.githubusercontent.com/16698950/66458433-5c446380-eaa5-11e9-9dbd-fa568d297f06.png

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Review by heavengate — DISMISSED** [review]

**Review by nepeplwu — APPROVED** [review]
LGTM

**Review by heavengate — DISMISSED** [review]

**Review by nepeplwu — DISMISSED** [review]

**Review by nepeplwu — APPROVED** [review]

**Review by heavengate — APPROVED** [review]

**Pull request merged**
