### PR TITLE
[Waiting oneDNN v2.4 upgrade] Fix for wrong results in segmentation models

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Bug fixes

### PR changes
Others

### Describe
Added dcab format tag support. "Any" format tag was choosing it, but we weren't supporting that and elementwise_add kernel was causing incorrect results in a segmentation model. We really need to add memory descriptor as a field to tensor class to avoid that kind of issues in future. It is a fix for #35307

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
```
2021-09-18 06:48:10 	1648 - test_quant2_int8_mobilenetv1_mkldnn (Failed)
2021-09-18 06:48:10             	1645 - test_quant2_int8_resnet50_mkldnn (Failed)
2021-09-18 06:48:10 	1647 - test_quant2_int8_resnet50_channelwise_mkldnn (Failed)
2021-09-18 06:48:10 ipipe_log_param_Rerunaaaa_TestCases_Total_Time: 385s
2021-09-18 06:48:10 ipipe_log_param_actualaaaaa_TestCases_Total_Time: 2484s
2021-09-18 06:48:10 ========================================
2021-09-18 06:48:10 There are failed tests, which have been executed re-run,but success rate is less than 50%:
2021-09-18 06:48:10 Summary Failed Tests... 
2021-09-18 06:48:10 ========================================
2021-09-18 06:48:10 The following tests FAILED: 
2021-09-18 06:48:10 	1645 - test_quant2_int8_resnet50_mkldnn (Failed)
2021-09-18 06:48:10 	1646 - test_quant2_int8_resnet50_range_mkldnn (Failed)
2021-09-18 06:48:10 	1647 - test_quant2_int8_resnet50_channelwise_mkldnn (Failed)
2021-09-18 06:48:10 	1648 - test_quant2_int8_mobilenetv1_mkldnn (Failed)
2021-09-18 06:48:10             	1645 - test_quant2_int8_resnet50_mkldnn (Failed)
2021-09-18 06:48:10             	1646 - test_quant2_int8_resnet50_range_mkldnn (Failed)
2021-09-18 06:48:10 + EXCODE=8
```

**Review by arogowie-intel — APPROVED** [review]
Looks good, although I agree with you that general mechanism is faaar away from being perfect.

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@jakpiase  Hi, since last round of CIs, PR-CI-Coverage failed, and 
```
2021-09-18 06:48:10             	1645 - test_quant2_int8_resnet50_mkldnn (Failed)
2021-09-18 06:48:10             	1646 - test_quant2_int8_resnet50_range_mkldnn (Failed)
```
Are you still working on this PR. How are these failed UT?

**Comment by jakpiase** [comment]
closing because there are conflicts and it will be easier to create another PR since it has only 3 lines, but is problematic

**Pull request closed without merging**
