### PR TITLE
[PHI] Migrate elementwise add, sub and mul kernels

### PR DESCRIPTION
**Pull request by piotrekobi**
### PR types

Others
### PR changes

Others
### Describe

Migrates the following oneDNN operator fluid kernels to PHI:
- elementwise_add
- elementwise_sub
- elementwise_mul

### CODE REVIEW

**Comment by piotrekobi** [comment]
@chenwhql I have a few issues with migrating the elementwise kernels:
1.  I'm getting errors related to .cc tests at the end of compilation even though I added PD_DECLARE_KERNEL(...) changes to them
2. The Out tensor is required in some grad kernels. It was previously acquired by `auto* out = ctx.Input<phi::DenseTensor>("Out")`. I tried `auto* out = dev_ctx.GetDnnInput("Out")` but it doesn't work.
3. When I try to register the divide_grad kernel I'm getting compilation errors, starting with:
```
In file included from /home/ppaturej/Paddle/paddle/phi/core/custom_kernel.h:18,
                 from /home/ppaturej/Paddle/paddle/phi/core/kernel_registry.h:24,
                 from /home/ppaturej/Paddle/paddle/phi/kernels/onednn/elementwise_grad_kernel.cc:21:
/home/ppaturej/Paddle/paddle/phi/core/kernel_registry.h:457:55: error: decltype cannot resolve address of overloaded function
   template decltype(meta_kernel_fn<cpp_dtype, context>) \
```
Could you please help me solve these problems?

**Comment by yaomichael** [comment]
@YuanRisheng can you help @piotrekobi out?

**Comment by YuanRisheng** [comment]
> @chenwhql I have a few issues with migrating the elementwise kernels:
> 
> 1. I'm getting errors related to .cc tests at the end of compilation even though I added PD_DECLARE_KERNEL(...) changes to them
> 2. The Out tensor is required in some grad kernels. It was previously acquired by `auto* out = ctx.Input<phi::DenseTensor>("Out")`. I tried `auto* out = dev_ctx.GetDnnInput("Out")` but it doesn't work.
> 3. When I try to register the divide_grad kernel I'm getting compilation errors, starting with:
> 
> ```
> In file included from /home/ppaturej/Paddle/paddle/phi/core/custom_kernel.h:18,
>                  from /home/ppaturej/Paddle/paddle/phi/core/kernel_registry.h:24,
>                  from /home/ppaturej/Paddle/paddle/phi/kernels/onednn/elementwise_grad_kernel.cc:21:
> /home/ppaturej/Paddle/paddle/phi/core/kernel_registry.h:457:55: error: decltype cannot resolve address of overloaded function
>    template decltype(meta_kernel_fn<cpp_dtype, context>) \
> ```
> 
> Could you please help me solve these problems?

For the first point, please provide more detailed error information.

For the second point, the only kernel that uses Out tensor is `DivideGradKernel` and you need separate divide_grad logic from `EltwiseMKLDNNGradKernel` for it. Please see the  function declaration of `DivideGradKernel`  in "elementwise_divide_grad_kernel.h". It has provided Out tensor.

For the third point, It is because the kernel you defined is not equal with the function declaration of `DivideGradKernel`  in "elementwise_divide_grad_kernel.h".
Good luck. @piotrekobi

**Comment by piotrekobi** [comment]
@YuanRisheng Thanks a lot for your help with the elementwise_div_grad registration! The issues were simple to fix.

I'm still getting compilation errors related to .cc tests after adding PD_DECLARE_KERNEL(...) to them.
Here's the error message:
```bash
[ 89%] Linking CXX executable tests/test_mkldnn_caching
/usr/bin/ld: CMakeFiles/test_mkldnn_caching.dir/fluid/operators/mkldnn/test_mkldnn_caching.cc.o: in function `__static_initialization_and_destruction_0(int, int) [clone .constprop.994]':
test_mkldnn_caching.cc:(.text.startup+0x83d): undefined reference to `TouchKernelSymbolFor_elementwise_add_OneDNN_ONEDNN()'
/usr/bin/ld: test_mkldnn_caching.cc:(.text.startup+0x847): undefined reference to `TouchKernelSymbolFor_elementwise_mul_OneDNN_ONEDNN()'
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/CMakeFiles/test_mkldnn_caching.dir/build.make:92: paddle/tests/test_mkldnn_caching] Error 1
make[1]: *** [CMakeFiles/Makefile2:7073: paddle/CMakeFiles/test_mkldnn_caching.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by YuanRisheng** [comment]
> @YuanRisheng Thanks a lot for your help with the elementwise_div_grad registration! The issues were simple to fix.
> 
> I'm still getting compilation errors related to .cc tests after adding PD_DECLARE_KERNEL(...) to them. Here's the error message:
> 
> ```shell
> [ 89%] Linking CXX executable tests/test_mkldnn_caching
> /usr/bin/ld: CMakeFiles/test_mkldnn_caching.dir/fluid/operators/mkldnn/test_mkldnn_caching.cc.o: in function `__static_initialization_and_destruction_0(int, int) [clone .constprop.994]':
> test_mkldnn_caching.cc:(.text.startup+0x83d): undefined reference to `TouchKernelSymbolFor_elementwise_add_OneDNN_ONEDNN()'
> /usr/bin/ld: test_mkldnn_caching.cc:(.text.startup+0x847): undefined reference to `TouchKernelSymbolFor_elementwise_mul_OneDNN_ONEDNN()'
> collect2: error: ld returned 1 exit status
> make[2]: *** [paddle/CMakeFiles/test_mkldnn_caching.dir/build.make:92: paddle/tests/test_mkldnn_caching] Error 1
> make[1]: *** [CMakeFiles/Makefile2:7073: paddle/CMakeFiles/test_mkldnn_caching.dir/all] Error 2
> make: *** [Makefile:141: all] Error 2
> ```

@piotrekobi  Well, I get it. For elementwise_add, the kernel name registered in PHI is add_raw or add. So, you can modify it like this : `PD_DECLARE_KERNEL(add_raw, OneDNN, ONEDNN); `.The same reason is for elementwise_mul

**Comment by piotrekobi** [comment]
@YuanRisheng Thanks! Everything seems to be working now.

**Comment by Silv3S** [comment]
Done in https://github.com/PaddlePaddle/Paddle/pull/48625, https://github.com/PaddlePaddle/Paddle/pull/48611

**Pull request closed without merging**
