### PR TITLE
reserve vector space before loop in top-k

### PR DESCRIPTION
**Pull request by sfraczek**
it makes top-k faster

### CODE REVIEW

**Comment by luotao1** [comment]
please see https://github.com/PaddlePaddle/Paddle/pull/12099#issuecomment-404376243 to pass the ci.

**Comment by luotao1** [comment]
Could you tell us how and why top-k faster after merging this PR?

**Comment by sfraczek** [comment]
### Why is it faster
The top-k operator is faster after merging this because it reserves all required memory before pushing data to vector. Without this reservation, the vector memory is allocated to some default size, then when the size is exceeded a new memory block twice this size has to be allocated and the data has to be copied from old to new block and the old data has to be deleted. This may be happening more than once, depending on the vector's implementation. 

#### Vector memory allocation scheme
It may start at 0 and when pushing first element allocate memory for 1 element and place it. When pushing second variable to vector it may allocate memory of size 2 and copy the first element, destroy old memory and add the second element to new memory. When pushing the third element to vector it may allocate memory block of size 4, copy the two elements, destroy old memory and add the third element and so on.

### How much faster
The top-k operator in training is roughly faster:
batch 128 - 2,13 times
batch 64 - 1,73 times
batch 32 - 1,42 times
**on i9-7980XE processor with 18 threads.**
Top-k is not a bottleneck in **ResNet-50**, so despite this speedup there is no significant impact on overall training performance.

**Comment by luotao1** [comment]
please merge the latest code to pass the ci since there is API diff again.

**Review by luotao1 — APPROVED** [review]
LGTM！

**Pull request merged**
