### PR TITLE
[cherry-pick] Add quant2 int8 lstm model test (#35887)

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types
Bug fixes

### PR changes
Others

### Describe
Fix LSTM quant INT8 accuracy issue, cherry-pick #35887

### CODE REVIEW

**Review by wozna — APPROVED** [review]
LGTM

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
@baoachun  Hi, could you please help merge this cherry-pick PR. This PR is kinda important because this cherry-pick solved the LSTM and some other model accuracy issues.

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
