### PR TITLE
Added support for BF16 datatype for all oneDNN activation kernels

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
Added support for BF16 datatype for all oneDNN activation kernels. Also fixed an issue with oneDNN abs activation not being used

### CODE REVIEW

**Comment by jakpiase** [comment]
@Silv3S please review this PR

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by Silv3S** [comment]
LGTM

**Comment by jakpiase** [comment]
@Aganlengzi could you please review this PR? It is related to both forward and backward activations operations

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
