### PR TITLE
Fix for reshape2 oneDNN op

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Bug fixes

### PR changes
OPs

### Describe
Fix for reshape2 oneDNN op which was causing errors in fcos model mentioned in #34723

### CODE REVIEW

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@piotrekobiIntel  Please review

**Review by lidanqing-vv — DISMISSED** [review]
LGTM

**Comment by ghost** [comment]
I would suggest using a range-based for loop instead of a classic one like this:
for (const auto& tensor : list_new_shape_tensor) 

Thanks to this we do not have to copy the tensor pointer to a new variable, which can slightly improve performance.
It also saves one line of code and makes it clear that we don't really need the index "i" for anything.

Thanks to the fact that we know the size of the vec_new_shape vector,
we can reserve the memory that it needs right after defining it like this:
vec_new_shape.reserve(list_new_shape_tensor.size());

That way there is no time wasted on allocation every iteration.

After using reserve(), it also would be better to use emplace_back() instead of push_back.

Also, I'm not sure if it is necessary to declare the function as inline, as it is not a very small function.
Chances are that the compiler simply ignores the inline keyword.

**Review by jczaja — APPROVED** [review]

**Review by arlesniak — APPROVED** [review]
LGTM

**Pull request merged**
