### PR TITLE
[oneDNN] disabling oneDNN inplace pass

### PR DESCRIPTION
**Pull request by jczaja**
There was an issue reported #24373 (performance drop). It is caused by oneDNN inplace pass.
It is under investigation. If in-place pass is not fixed very soon than this PR disables , so resotores performance on Transformer.

### CODE REVIEW

**Comment by jczaja** [comment]
@luotao1 Could you please show me the logs of PR_CI_CPU_Py2 (compile) run ? If this is 100% random then please reboot if not just logs would be welcomed.

**Comment by luotao1** [comment]
```
[14:00:07][Step 1/1] clang-format version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
[14:00:07][Step 1/1] + commit_files=on
[14:00:07][Step 1/1] ++ git diff --numstat upstream/develop
[14:00:07][Step 1/1] ++ awk '{print $NF}'
[14:00:07][Step 1/1] + for file_name in '`git diff --numstat upstream/$BRANCH |awk '\''{print $NF}'\''`'
[14:00:07][Step 1/1] + pre-commit run --files paddle/fluid/inference/api/paddle_pass_builder.cc
[14:00:08][Step 1/1] CRLF end-lines remover...............................(no files to check)Skipped
[14:00:08][Step 1/1] yapf.................................................(no files to check)Skipped
[14:00:08][Step 1/1] Check for added large files..............................................Passed
[14:00:08][Step 1/1] Check for merge conflicts................................................Passed
[14:00:08][Step 1/1] Check for broken symlinks................................................Passed
[14:00:08][Step 1/1] Detect Private Key...................................(no files to check)Skipped
[14:00:08][Step 1/1] Fix End of Files.....................................(no files to check)Skipped
[14:00:08][Step 1/1] clang-format.............................................................Failed
[14:00:08][Step 1/1] hookid: clang-format-with-version-check
[14:00:08][Step 1/1] 
[14:00:08][Step 1/1] Files were modified by this hook.
[14:00:08][Step 1/1] 
[14:00:08][Step 1/1] cpplint..................................................................Passed
[14:00:08][Step 1/1] pylint...............................................(no files to check)Skipped
[14:00:08][Step 1/1] copyright_checker........................................................Passed
[14:00:08][Step 1/1] + git diff
[14:00:08][Step 1/1] diff --git a/paddle/fluid/inference/api/paddle_pass_builder.cc b/paddle/fluid/inference/api/paddle_pass_builder.cc
[14:00:08][Step 1/1] index c1ea6c3..d5dfcf8 100644
[14:00:08][Step 1/1] --- a/paddle/fluid/inference/api/paddle_pass_builder.cc
[14:00:08][Step 1/1] +++ b/paddle/fluid/inference/api/paddle_pass_builder.cc
[14:00:08][Step 1/1] @@ -201,7 +201,7 @@ void CpuPassStrategy::EnableMKLDNN() {
[14:00:08][Step 1/1] + commit_files=off
[14:00:08][Step 1/1]               // Disabled due to topology-dependent speed-up
[14:00:08][Step 1/1]               // "fc_mkldnn_pass",
[14:00:08][Step 1/1] + '[' off == off ']'
[14:00:08][Step 1/1]               // "mkldnn_inplace_pass",  // This pass should be activated after
[14:00:08][Step 1/1] + echo 'code format error'
[14:00:08][Step 1/1] -                                     // fuses
[14:00:08][Step 1/1] + exit 1
[14:00:08][Step 1/1] +             // fuses
[14:00:08][Step 1/1] + abort
[14:00:08][Step 1/1]           })) {
[14:00:08][Step 1/1] + echo 'Your change doesn'\''t follow PaddlePaddle'\''s code style.'
[14:00:08][Step 1/1]        passes_.push_back(pass);
[14:00:08][Step 1/1] Your change doesn't follow PaddlePaddle's code style.
[14:00:08][Step 1/1]      }
[14:00:08][Step 1/1] + echo 'Please use pre-commit to check what is wrong.'
[14:00:08][Step 1/1] Please use pre-commit to check what is wrong.
[14:00:08][Step 1/1] + exit 1
[14:00:08][Step 1/1] code format error
[14:00:16][Step 1/1] Process exited with code 1
[14:00:16][Step 1/1] Process exited with code 1 (Step: Build and test (Command Line))
[14:00:16][Step 1/1] Step Build and test (Command Line) failed
```
The code format is error.  @tianshuo78520a Could you see the [URL](http://10.87.145.41:8111/viewLog.html?buildId=342004&buildTypeId=YYTest_PrCiCpuPy2&tab=buildLog), the result of report errors seems disordered

**Comment by jczaja** [comment]
@luotao1 Thanks very much!

**Comment by tianshuo78520a** [comment]
> ```
> [14:00:07][Step 1/1] clang-format version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
> [14:00:07][Step 1/1] + commit_files=on
> [14:00:07][Step 1/1] ++ git diff --numstat upstream/develop
> [14:00:07][Step 1/1] ++ awk '{print $NF}'
> [14:00:07][Step 1/1] + for file_name in '`git diff --numstat upstream/$BRANCH |awk '\''{print $NF}'\''`'
> [14:00:07][Step 1/1] + pre-commit run --files paddle/fluid/inference/api/paddle_pass_builder.cc
> [14:00:08][Step 1/1] CRLF end-lines remover...............................(no files to check)Skipped
> [14:00:08][Step 1/1] yapf.................................................(no files to check)Skipped
> [14:00:08][Step 1/1] Check for added large files..............................................Passed
> [14:00:08][Step 1/1] Check for merge conflicts................................................Passed
> [14:00:08][Step 1/1] Check for broken symlinks................................................Passed
> [14:00:08][Step 1/1] Detect Private Key...................................(no files to check)Skipped
> [14:00:08][Step 1/1] Fix End of Files.....................................(no files to check)Skipped
> [14:00:08][Step 1/1] clang-format.............................................................Failed
> [14:00:08][Step 1/1] hookid: clang-format-with-version-check
> [14:00:08][Step 1/1] 
> [14:00:08][Step 1/1] Files were modified by this hook.
> [14:00:08][Step 1/1] 
> [14:00:08][Step 1/1] cpplint..................................................................Passed
> [14:00:08][Step 1/1] pylint...............................................(no files to check)Skipped
> [14:00:08][Step 1/1] copyright_checker........................................................Passed
> [14:00:08][Step 1/1] + git diff
> [14:00:08][Step 1/1] diff --git a/paddle/fluid/inference/api/paddle_pass_builder.cc b/paddle/fluid/inference/api/paddle_pass_builder.cc
> [14:00:08][Step 1/1] index c1ea6c3..d5dfcf8 100644
> [14:00:08][Step 1/1] --- a/paddle/fluid/inference/api/paddle_pass_builder.cc
> [14:00:08][Step 1/1] +++ b/paddle/fluid/inference/api/paddle_pass_builder.cc
> [14:00:08][Step 1/1] @@ -201,7 +201,7 @@ void CpuPassStrategy::EnableMKLDNN() {
> [14:00:08][Step 1/1] + commit_files=off
> [14:00:08][Step 1/1]               // Disabled due to topology-dependent speed-up
> [14:00:08][Step 1/1]               // "fc_mkldnn_pass",
> [14:00:08][Step 1/1] + '[' off == off ']'
> [14:00:08][Step 1/1]               // "mkldnn_inplace_pass",  // This pass should be activated after
> [14:00:08][Step 1/1] + echo 'code format error'
> [14:00:08][Step 1/1] -                                     // fuses
> [14:00:08][Step 1/1] + exit 1
> [14:00:08][Step 1/1] +             // fuses
> [14:00:08][Step 1/1] + abort
> [14:00:08][Step 1/1]           })) {
> [14:00:08][Step 1/1] + echo 'Your change doesn'\''t follow PaddlePaddle'\''s code style.'
> [14:00:08][Step 1/1]        passes_.push_back(pass);
> [14:00:08][Step 1/1] Your change doesn't follow PaddlePaddle's code style.
> [14:00:08][Step 1/1]      }
> [14:00:08][Step 1/1] + echo 'Please use pre-commit to check what is wrong.'
> [14:00:08][Step 1/1] Please use pre-commit to check what is wrong.
> [14:00:08][Step 1/1] + exit 1
> [14:00:08][Step 1/1] code format error
> [14:00:16][Step 1/1] Process exited with code 1
> [14:00:16][Step 1/1] Process exited with code 1 (Step: Build and test (Command Line))
> [14:00:16][Step 1/1] Step Build and test (Command Line) failed
> ```
> 
> The code format is error. @tianshuo78520a Could you see the [URL](http://10.87.145.41:8111/viewLog.html?buildId=342004&buildTypeId=YYTest_PrCiCpuPy2&tab=buildLog), the result of report errors seems disordered

I see this log，This is a problem with Teamcity receiving logs. I mentioned a PR test but the logs are normal. I think this is an accidental problem. [TestURL](http://10.87.145.41:8111/viewLog.html?buildId=342178&buildTypeId=YYTest_PrCiCpuPy2&tab=buildLog&branch_YYTest=pull%2F24411)

**Comment by jczaja** [comment]
@tianshuo78520a I tried to click "TestURL" , so I can see again "Problem loading page". It happens more often for me this kind of error.

**Comment by lidanqing-vv** [comment]
LGTM

**Comment by lidanqing-vv** [comment]
@wojtuss  Can you review this PR?

**Review by wojtuss — COMMENTED** [review]
As a temporary fix: LGTM

**Review by wojtuss — APPROVED** [review]
LGTM as a temporary fix

**Pull request merged**
