### PR TITLE
[Fluid Clean] remove unfold, deformable_roi_pooling, shard_index, hard_swish, mish, uniform_random, unbind

### PR DESCRIPTION
**Pull request by heyanru01**
### PR types

Others
### PR changes

APIs
### Describe

remove unfold, deformable_roi_pooling, shard_index, hard_swish, mish, uniform_random, unbind in paddle.fluid.layers

### CODE REVIEW

**Comment by heyanru01** [comment]
1. delete test_deformable_psroi_pooling.py

    由于fluid APIdeformable_psroi_pooling已删除，没有适合替代的2.0API，故删除对应单测

**Comment by yingshengBD** [comment]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM 单测删除

**Review by jzhang533 — APPROVED** [review]
lgtm

**Review by XiaoguangHu01 — APPROVED** [review]
lgtm

**Review by YuanRisheng — APPROVED** [review]

**Pull request merged**
