### PR TITLE
[bug fix]remove paddle.nn.Sequential to fix dygraph to static error

### PR DESCRIPTION
**Pull request by GGBond8488**
### PR types
Bug fixes

### PR changes
APIs

### Describe
In the previous work of cleaning `Sequential` under fluid, due to the problem of circular dependency, I copied a copy of `Sequential` and put it under paddle.nn, and kept the original `Sequential` under fluid.

In dygraph to static, `paddle.fluid.dygraph.dygraph_to_static.convert_call_func.py` imports `paddle.fluid.dygraph.container.Sequential` under fluid on line 27, and performs type judgment on lines 48 and 131, which will lead to an obscure problem. Use `paddle.nn.Sequential` models will not be able to perform dygraph and static conversions correctly.

So we remove the Sequential under paddle.nn, and will migrate it back after the dygraph to static migration is completed.

### CODE REVIEW

**Review by zoooo0820 — APPROVED** [review]
LGTM

**Comment by PaddlePaddle-Gardener** [comment]
之前因为循环依赖的问题，将Sequential复制一份放到paddle.nn下，保留原有Sequential实现；

**Comment by GGBond8488** [comment]
之前因为循环依赖的问题，将Sequential复制一份实现放到paddle.nn下，保留原有Sequential实现
在paddle.fluid.dygraph.dygraph_to_static.convert_call_func.py引入了fluid下的Sequential
line 27`from paddle.fluid.dygraph.container import Sequential`（由于循环依赖无法替换）
line 48 `PADDLE_NEED_CONVERT_APIS = [Sequential]`
line 131 `if type(func) in PADDLE_NEED_CONVERT_APIS:
        return False`
会导致使用paddle.nn.Sequential的部分模型动转静失败（两个Sequential不是同一个类）

等到动转静完成迁出fluid以后，可将Sequential 从fluid下完全迁移到paddle.nn

**Comment by jeff41404** [comment]
The description should be clear why remove `paddle.nn Sequential`? and what conditions can be met to migrate `Sequential` in fluid to `paddle.nn.Sequential` ?

**Comment by GGBond8488** [comment]
> The description should be clear why remove `paddle.nn Sequential`? and what conditions can be met to migrate `Sequential` in fluid to `paddle.nn.Sequential` ?

added description

**Review by jeff41404 — APPROVED** [review]

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Pull request merged**
