### PR TITLE
Add Shallow clone to ExternalProjects

### LINKED ISSUE #20797: Modify ExternalProject to perform git shallow clone
ExternalProject Add is used to download needed dependencies. Normally git clone downloads whole history of given repo. More recent cmake can perform git clone shallow to checkout only selected revision without whole history. It would be good to investigate such a possibility as it would save some time during building and save disk space when checking out. Problem is that it require recent cmake.

### PR DESCRIPTION
**Pull request by Sand3r-**
Resolves #20797.

### CODE REVIEW

**Review by jczaja — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@Sand3r- This looks great.  Do you know what are roughly the savings (in terms of smaller build directory and time of configuration & building) ?

**Comment by Sand3r-** [comment]
@jczaja I have only measured space savings which amount to ~51MB.
I haven't benchmarked the compile times unfortunately.

**Comment by jczaja** [comment]
@Sand3r- Thanks for info. I guess there will be some time saved on NOT downloading those ~51 MB provided that cmake version is recent enough.

**Comment by luotao1** [comment]
Please use `test=develop` to trigger the CI

**Comment by Sand3r-** [comment]
According to PR_CI_CPU_Py2 (Compile), requires Dianhai approval (due to modification of 20+ files).

**Review by luotao1 — APPROVED** [review]
LGTM

**Review by raindrops2sea — APPROVED** [review]
LGTM

**Pull request merged**
