### PR TITLE
split test_dist_se_resnext.py into 4 testcases

### PR DESCRIPTION
**Pull request by guru4elephant**
test=develop
split test_dist_se_resnext.py into 4 testcases

### CODE REVIEW

**Review by gavin1332 — COMMENTED** [review]
no deletion in this pr?

**Comment by guru4elephant** [comment]
> no deletion in this pr?

base file removed.

**Comment by gavin1332** [comment]
> base file deleted.

Did you forget to commit the deleted base file. Or you deleted in other PRs?

**Comment by guru4elephant** [comment]
> > base file deleted.
> 
> Did you forget to commit the deleted base file. Or you deleted in other PRs?

I mean fixed.

**Review by gavin1332 — DISMISSED** [review]
LGTM

**Review by gavin1332 — APPROVED** [review]

**Pull request merged**
