### PR TITLE
Fix throw exception typo in paddle/nn/functional/loss.py

### PR DESCRIPTION
**Pull request by ucsk**
### PR types

Others

### PR changes

APIs

### Describe

Fix throw exception typo in paddle/nn/functional/loss.py and python/paddle/distributed/fleet/layers/mpu/mp_ops.py

### CODE REVIEW

**Comment by ucsk** [comment]
### PR types

Others

### PR changes

APIs

### Describe

Fix throw exception typo in paddle/nn/functional/loss.py

**Comment by luotao1** [comment]
@ucsk Sorry for too late to review this PR, could you update the PR to pass the CI?
Besides, you can fix another typo in `python/paddle/distributed/fleet/layers/mpu/mp_ops.py`
https://github.com/PaddlePaddle/Paddle/blob/852c8db38cea0baecad9756b01903fa98e992395/python/paddle/distributed/fleet/layers/mpu/mp_ops.py#L393

**Comment by luotao1** [comment]
飞桨快乐开源活动暖冬来袭，为完成任务的贡献者准备了礼品表示感谢！
👇报名链接：https://aistudio.baidu.com/aistudio/activitydetail/1503019026
有兴趣可以参加下～

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
@ucsk 很高兴收到你的贡献，欢迎参与飞桨开源共建～
- [Paddle Framework Contributor Club (PFCC)](https://github.com/PaddlePaddle/community/tree/master/pfcc) 是一个有兴趣、正在、或者已经为 [飞桨开源框架](https://github.com/PaddlePaddle/Paddle/) 做开源贡献的贡献者成立的虚拟组织，详情可见 https://github.com/luotao1
- 可以先加运营同学的企业微信，她会拉你进入交流群：
061a1f6142ba3e7f4aced49ed1f0bbd8

**Pull request merged**
