### PR TITLE
[Security] fix security problem for prune_by_memory_estimation

### PR DESCRIPTION
**Pull request by vn-ncvinh**
### PR types
Others 

### PR changes
Others 

### Description
fix security problem for prune_by_memory_estimation

### CODE REVIEW

**Comment by luotao1** [comment]
Please fix the CodeStyle problem
image

**Review by Caozhou1995 — COMMENTED** [review]
LGTM

**Review by ForFishes — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
@vn-ncvinh Could you cherry-pick to release/2.6?

**Comment by vn-ncvinh** [comment]
> @vn-ncvinh Could you cherry-pick to release/2.6?

Thank you for your instruction. Would you prefer me to handle the cherry-picking myself, or would you like to take care of it?

**Comment by luotao1** [comment]
We prefer you to handle the cherry-picking yourself.

**Pull request merged**
