### PR TITLE
Move QAT API from PaddleSlim to Paddle

### PR DESCRIPTION
**Pull request by leo0519**
### PR types

New features
### PR changes

APIs
### Description

We integrate QAT into distributed optimizer (another PR), and the integration needs QAT API to quantize Paddle program.
Hence, this PR move necessary API from PaddleSlim to Paddle.

Move the QAT API `quant_aware` and `convert` and their corresponding UT from PaddleSlim to Paddle.
1. Copy the files [quanter.py](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/quant/quanter.py) and [test_quant_aware.py](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/tests/test_quant_aware.py) from PaddleSlim to Paddle
2. Update the import path of python library
3. Remove the redundant code (transformer model and quant_post functions)
4. Move the [mobilenet.py](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/models/mobilenet.py) and [static_case.py](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/tests/static_case.py) into UT test_quant_aware
5. Replace eval function in `quanter.py`
6. Make `test_quant_aware.py` can be finished in Paddle CI (increate time limit and reduce batch size and iteration for model testing)
7. Apply new formatter on modified files

### CODE REVIEW

**Review by wanghaoshuang — DISMISSED** [review]
LGTM

**Review by wanghaoshuang — APPROVED** [review]

**Review by ceci3 — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by tianshuo78520a — APPROVED** [review]

**Comment by ceci3** [comment]
下个PR修复：
1. print or std::cout is not recommended for direct use, please use loggin or glog.
2. 单测实际实行时间优化

**Review by XieYunshen — APPROVED** [review]
LGTM for
`  set_tests_properties(test_quant_aware PROPERTIES TIMEOUT 900)
  set_tests_properties(test_quant_post_quant_aware PROPERTIES TIMEOUT 900)
  set_tests_properties(test_quant_aware_user_defined PROPERTIES TIMEOUT 900)
  set_tests_properties(test_quant_aware_config PROPERTIES TIMEOUT 900)`

单测执行时间阈值设置较大，需要优化一下

**Pull request merged**
