### PR TITLE
[CodeStyle][task 16] enable Ruff B010 rule in python/paddle/base

### PR DESCRIPTION
**Pull request by ooooo-create**
### PR types

Others
### PR changes

Others
### Description

auto fix
@gouzil 

- #57367

### CODE REVIEW

**Comment by gouzil** [comment]
LGTM @SigureMo

**Review by SigureMo — DISMISSED** [review]
LGTMeow 🐾

**Comment by luotao1** [comment]
请解决下冲突

**Comment by ooooo-create** [comment]
> 请解决下冲突

Done

**Review by SigureMo — APPROVED** [review]
LGTMeow 🐾

**Pull request merged**
