### PR TITLE
Softmax for Inference is enabled when ON_INFER is set

### PR DESCRIPTION
**Pull request by jczaja**
Rework of #14337 so softmax for inference is enabled when ON_INFER flag is used to build paddle.

### CODE REVIEW

**Comment by jczaja** [comment]
@luotao1 When CI is successful, could you please check your test that made PR #14337 reverted , if it works fine before any merge?

**Comment by luotao1** [comment]
If use `ON_INFER=ON` option, it will not affect the CE(continuous_evaluation) test which made PR #14337 reverted. In CE(continuous_evaluation) test, `ON_INFER=OFF`.

**Review by luotao1 — APPROVED** [review]
LGTM!
Todo in Next PR:
- add back `python/paddle/fluid/tests/unittests/test_softmax_op.py` in #14337 https://github.com/PaddlePaddle/Paddle/pull/14337/files#diff-83947608348e40bf0ba25e28d4d60c36
- change `ifdef ON_INFER` to `ifdef PADDLE_ON_INFERENCE`, like https://github.com/PaddlePaddle/Paddle/pull/14414/files#diff-bb4dff0e76921ba253151a33c5b6d1f4R806

**Comment by jczaja** [comment]
@luotao1 How Can I add back unit test? Previously it was triggerred by is_test? Currently it is via define: ON_INFER. How should I make unit test that runs when ON_INFER is set?

**Pull request merged**
