### PR TITLE
refactoring code with For Else

### PR DESCRIPTION
**Pull request by idiomaticrefactoring**
### PR types
Performance optimization

### PR changes
Others

### Describe

refactoring code with For Else which is more pythonic, concise and efficient; how do you think this change which has practical value？

### CODE REVIEW

**Comment by luotao1** [comment]
Sorry too later to notice this PR, Could you pull a new commit and pass the CI again? @idiomaticrefactoring

**Comment by luotao1** [comment]
@phillxnet Could you pull a new commit and pass the CI again? It seems that @idiomaticrefactoring is a bot.

**Comment by enkilee** [comment]
https://github.com/PaddlePaddle/Paddle/pull/49528

**Comment by luotao1** [comment]
close due to #49521 merged

**Pull request closed without merging**
