### PR TITLE
Added numpy bf16 datatype support via custom pip package

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
Others

### PR changes
Others

### Describe
This PR adds bfloat16 datatype support for numpy via an external package. Sample usage is included in UT. That will shorten the time of loading word2vec BF16 model significantly and will allow us to remove "convert_float_to_uint16" function from UTs.

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
This PR will be merged once Baidu agreed with this PR's liscence etc.

**Comment by jakpiase** [comment]
Additional info:
My PIP package: https://pypi.org/project/paddle-bfloat/
Github source code(changes are on develop2 branch): https://github.com/jakpiase/paddle_bfloat/tree/develop2 

This package is an extension to https://pypi.org/project/bfloat16/ package. My package added python2 and windows compatibility and made it possible to install it with older pip versions. Original(https://pypi.org/project/bfloat16/) package is an extension to Tensorflow's bfloat16 numpy implementation which made it possible to use as a standalone feature. The author have written a note in bfloat16.cc file about his changes in Tensorflow's files(to make it clear that it's still Tensorflow's license, but he did some changes to source code) and so did I. I haven't changed any licensing and it is distributed on Apache2(same as Tensorflow). I had to make a separate pip package because some PaddlePaddle machines have old pip versions and it was not possible for pip to install package directly from github or from local files.

**Comment by lidanqing-vv** [comment]
@Aganlengzi Hi, could you please check this comment? Thanks !

**Comment by lidanqing-vv** [comment]
@Aganlengzi The source numpy bf16 package link is given, please veirfy if it is legal to merge this PR

**Comment by Aganlengzi** [comment]
> @Aganlengzi The source numpy bf16 package link is given, please veirfy if it is legal to merge this PR

@lidanqing-intel I will ask. By the way, this PR is too long time ago for reviewing because the CI status can not be reported.

**Comment by lidanqing-vv** [comment]
@jakpiase Baidu said it is legal to use this package, but this PR is too old to be merged, Please make another PR that has same content and once it pass CIs Baidu will review and merge. Thanks!

**Comment by jakpiase** [comment]
As Danqing has said, there will be another PR made

**Pull request closed without merging**
