### PR TITLE
Update of PHI transpose_grad

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Others

### PR changes
OPs

### Describe
This is adapting transpose_grad PHI to use mem desc in working with Tensors

### CODE REVIEW

**Review by Silv3S — APPROVED** [review]
LGTM

**Comment by yaomichael** [comment]
@YuanRisheng we have a problem restarting PR-CI-Coverage e.g. I got an error "Do not click multiple times". Please help to restart this PR-CI-Coverage. can you help have a look?

**Comment by YuanRisheng** [comment]
> @YuanRisheng we have a problem restarting PR-CI-Coverage e.g. I got an error "Do not click multiple times". Please help to restart this PR-CI-Coverage. can you help have a look?

It seems that CI-Coverage detects low code coverage. You can check it on your machine by running unittest. If the code modified is exercised. I will let my colleague mark it as successful. Thank you.

**Comment by jczaja** [comment]
@YuanRisheng  Thanks for looking to that problem. Yes, Unit test (test_transpose_mkldnn_op) is exercising all lines of code that coverage mechanism marked red. Here is a screen from GDB showing execution stopped at first red line `(x_grad->set_mem_desc(out_grad.mem_desc());)`
coverage-transpose

Please mark it those lines as covered and approve this PR-CI_coverage if possible.

**Review by wozna — APPROVED** [review]
LGTM

**Review by YuanRisheng — APPROVED** [review]

**Pull request merged**
