### PR TITLE
[MLU]add matmul and matmul_v2 op

### PR DESCRIPTION
**Pull request by qipengh**
### PR types

New features
### PR changes

OPs
### Describe

adapt matmul_v2 op and fix data_type of tensor

### CODE REVIEW

**Comment by qipengh** [comment]
pytest测试报告
matmul:
image
image
image

matmul_v2:
image
image
image

**Review by qili93 — DISMISSED** [review]
LGTM

**Review by qili93 — APPROVED** [review]
LGTM

**Review by chenwhql — APPROVED** [review]
LGTM for PADDLE_ENFORCE

**Pull request merged**
