### PR TITLE
Faster implementation of CPU kernel for ROI Align operator

### PR DESCRIPTION
**Pull request by tsocha**
### PR types
Function optimization

### PR changes
OPs

### Describe
About ~20% faster ROI Align implementation in faster_rcnn_r50_fpn_1x_coco model(~2-3% faster model overall).

PR have to be polished.

### CODE REVIEW

**Review by jakpiase — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@pawelpiotrowicz  Please take a look at this PR

**Review by jczaja — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@baoachun , @Aganlengzi Please start your review & merge

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
