### PR TITLE
fix the strong Wolfe conditions for line search for minimize_lbfgs and minimize_bfgs APIs

### LINKED ISSUE #52020: minimize_lbfgs在line_search中Wolfe条件错误
### minimize_lbfgs在line_search中Wolfe条件错误

版本：develop最新版本（2023-03-23）

文件路径：
https://github.com/PaddlePaddle/Paddle/blob/2add31f4c994684ce038931d1eda8a17a17a086d/python/paddle/incubate/optimizer/functional/line_search.py#L316

代码位置：
```python
line 316        pred1 = ~done & (
line 317            (phi_2 > phi_0 + c1 * a2 * derphi_0) | ((phi_2 >= phi_0) & (i > 1))
line 318        )
```

应修改：
```python
line 316        pred1 = ~done & (
line 317            (phi_2 > phi_0 + c1 * a2 * derphi_0) | ((phi_2 >= phi_1) & (i > 1)) # 修改phi_0 为 phi_1
line 318        )
```

其他小错误：minimize_lbfgs中max_line_search_iters参数未传递给line_search函数
文件路径：https://github.com/PaddlePaddle/Paddle/blob/325fdf1d87b512fb679aad12cfcd7cae478711b3/python/paddle/incubate/optimizer/functional/lbfgs.py#L212

代码位置：
```python
line 212        if line_search_fn == 'strong_wolfe':
line 213            alpha, value, g2, ls_func_calls = strong_wolfe(
line 214                f=objective_func,
line 215                xk=xk,
line 216                pk=pk,
line 217                initial_step_length=initial_step_length,
line 218                dtype=dtype,
line 219            )
```

### PR DESCRIPTION
**Pull request by DrownFish19**
### PR types
Bug fixes

### PR changes
APIs

### Description

1. fix the strong Wolfe conditions for line search

The conditions are cited as follows:
```
    Line Search Algorithm:
        repeat
            Compute phi(a2) and derphi(a2).
            1. If phi(a2) > phi(0) + c_1 * a2 * phi'(0) or [phi(a2) >= phi(a1) and i > 1],
                a_star= zoom(a1, a2) and stop;

            2. If |phi'(a2)| <= -c_2 * phi'(0),
                a_star= a2 and stop;

            3. If phi'(a2) >= 0,
                a_star= zoom(a2, a1) and stop;

            a1 = a2
            a2 = min(2 * a2, a2)
            i = i + 1
        end(repeat)
```
However the condition 1 is ```phi_2 >= phi_0``` in current version. I have modify the line 317 as follows,

```python
line 316        pred1 = ~done & (
line 317            (phi_2 > phi_0 + c1 * a2 * derphi_0) | ((phi_2 >= phi_1) & (i > 1)) # 修改phi_0 为 phi_1
line 318        )
```

2. pass the max_line_search_iters parameter into line search method (strong_wolfe)

In current version, the `max_line_search_iters` is the parameter of minimize_lbfgs and minimize_bfgs, however, this parameter are not passed into line search method (strong_wolfe).

fix #52020

### CODE REVIEW

**Review by cxxly — APPROVED** [review]
LGTM with todo:

- test in paddlescience model @cxxly

**Comment by luotao1** [comment]
PR-CE-Framework 流水线失败
```
2023-03-24 05:09:41 test_minimize_lbfgs.py
2023-03-24 05:09:41 test_minimize_bfgs.py
2023-03-24 05:09:41 total bugs: 2
```
请 @cxxly 帮忙看下是否要修改 https://github.com/PaddlePaddle/PaddleTest/blob/develop/framework/api/incubate/test_minimize_lbfgs.py 和 https://github.com/PaddlePaddle/PaddleTest/blob/develop/framework/api/incubate/test_minimize_bfgs.py

**Comment by cxxly** [comment]
PR-CE-Framework失败原因是由于PaddleTest中有bfgs/lbfgs测试用例，麻烦提交PR修复 https://github.com/PaddlePaddle/PaddleTest/blob/develop/framework/api/incubate/test_minimize_lbfgs.py 和 https://github.com/PaddlePaddle/PaddleTest/blob/develop/framework/api/incubate/test_minimize_bfgs.py 中的测试用例，修复方式比较简单，直接更新expected file中的期望数据即可

**Comment by luotao1** [comment]
- https://github.com/PaddlePaddle/PaddleTest/pull/2104

**Comment by lijialin03** [comment]
https://github.com/PaddlePaddle/PaddleTest/blob/develop/framework/api/incubate/test_minimize_lbfgs.py 和 https://github.com/PaddlePaddle/PaddleTest/blob/develop/framework/api/incubate/test_minimize_bfgs.py 中的测试用例数据已经修复，但是现在由于时间过去比较久paddle本身改动较大，ci检查没法通过
麻烦您可以重新git pull --rebase upstream develop再git push -f origin develop提交一下这个pr吗？谢谢 @DrownFish19
另外PRTemplate中的Describe最近改成Description了，也得辛苦一起改掉，感谢

**Comment by luotao1** [comment]
hi, @DrownFish19 
- 非常感谢你对飞桨框架的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨框架做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~

**Pull request merged**
