### PR TITLE
TeamCity: hook up tests in different GPUs

### PR DESCRIPTION
**Pull request by helinwang**

### CODE REVIEW

**Comment by helinwang** [comment]
Not ready for review yet: the `test.sh` need to merge the return code for all background ctest processes.

**Comment by qingqing01** [comment]
The memory usage env setting in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/test.sh#L9 does not work.  So the unit tests failed.

**Comment by helinwang** [comment]
This PR will be on hold, since currently all our CI machines only have 2GPUs (the minimal requirement), the change could only gain advantage when CI machines have numbers GPUs > 2.

**Comment by luotao1** [comment]
Close due to this PR is a temporary test.

**Pull request closed without merging**
