### PR TITLE
Fix document of APIs,  test=develop, test=document_fix

### PR DESCRIPTION
**Pull request by huangjun12**
Fix document of 5 APIs:
1. hard_swish
2. huber_loss
3. linear_lr_warmup
4. lrn
5. roi_pool

### CODE REVIEW

**Comment by huangjun12** [comment]
hard_swish
huber_loss
linear_lr_warmup
lrn
roi_pool

**Comment by huangjun12** [comment]
image

**Comment by huangjun12** [comment]
image

**Review by wanghaoshuang — DISMISSED** [review]

**Review by wanghaoshuang — DISMISSED** [review]

**Comment by heavengate** [comment]
image
确认下这个格式

**Review by heavengate — DISMISSED** [review]

**Review by heavengate — APPROVED** [review]

**Review by wanghaoshuang — APPROVED** [review]

**Pull request merged**
