### PR TITLE
Rewrite scale matmul mkldnn fuse pass tester

### PR DESCRIPTION
**Pull request by HulekJakub**
### PR types
Others

### PR changes
Others

### Describe
Deleted old C++ scale matmul fuse pass test and updated python one

Currently in PaddlePaddle there are 3 unit-test frameworks - one written in C++ and 2 in Python. 
Old fuse pass tests (C++) fuse_pass_tester.cc are checking only if graph has correct number of / type of vertices after fusion. It doesn't check data. So these tests pass even if accuracy drops. 
New python framework is superior because it checks both graph fusion and accuracy after fusion.

### CODE REVIEW

**Review by Silv3S — APPROVED** [review]
LGTM

**Review by Silv3S — APPROVED** [review]

**Review by yeliang2258 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM

**Comment by HulekJakub** [comment]
@kolinwei Please review. Your approval is needed for Coverage check.

**Review by XieYunshen — APPROVED** [review]
LGTM

**Pull request merged**
