### PR TITLE
Add Identity module name in __init__

### PR DESCRIPTION
**Pull request by shiyutang**
### PR types

Bug fixes

### PR changes

OPs

### Describe

Add the module name in all of __init__.py

### CODE REVIEW

**Review by TCChenlong — DISMISSED** [review]
LGTM

**Comment by shiyutang** [comment]
Preview doc http://10.136.157.23:8090/documentation/docs/zh/api/index_cn.html
image

**Review by TCChenlong — DISMISSED** [review]
LGTM

**Review by TCChenlong — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
