### PR TITLE
Re-enable fc_lstm_fuse_pass

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types
Performance optimization

### PR changes
Others

### Describe
Re-enable fc_lstm_fuse_pass for fc_lstm_fuse UT

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@jiweibo  Hi, recently we are closing intel-labeled issues, for issue #33168, I have updated the UT and it seems the UT passed without error. Is this ok ? Or I should test other way?

**Comment by lidanqing-vv** [comment]
ch_ppocr_mobile_v1.1_rec

Test machine: i9

Paddle commit id: cf0d6027f9a2a10cdeb0eb43d863bd409a19ba2c
```
I0618 05:22:57.311427 25606 analysis_predictor.cc:1161] ======= optimize end =======
I0618 05:22:57.313923 25606 naive_executor.cc:104] ---  skip [feed], feed -> image
I0618 05:22:57.314550 25606 naive_executor.cc:104] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
I0618 05:22:57.314558 25606 naive_executor.cc:104] ---  skip [save_infer_model/scale_1.tmp_0], fetch -> fetch
I0618 05:22:57.314570 25606 clas_benchmark.cc:104] run ch_ppocr_mobile_v1.1_rec_infer model
I0618 05:22:57.314585 25606 clas_benchmark.cc:37] batch_size: 1 ,channels: 3    ,height: 32 ,width: 320
I0618 05:22:57.314826 25606 device_context.cc:805] oneDNN v2.6.0
I0618 05:23:01.178411 25606 demo_helper.h:143] ----------------------- Model info ----------------------
I0618 05:23:01.178440 25606 demo_helper.h:144] Model name: ch_ppocr_mobile_v1.1_rec_infer, Model type: static
I0618 05:23:01.178444 25606 demo_helper.h:146] ----------------------- Data info -----------------------
I0618 05:23:01.178447 25606 demo_helper.h:147] Batch size: 1, Num of samples: 500
I0618 05:23:01.178450 25606 demo_helper.h:149] ----------------------- Conf info -----------------------
I0618 05:23:01.178453 25606 demo_helper.h:150] device: cpu, ir_optim: true
I0618 05:23:01.178457 25606 demo_helper.h:152] enable_memory_optim: false
I0618 05:23:01.178463 25606 demo_helper.h:159] enable_mkldnn: true
I0618 05:23:01.178467 25606 demo_helper.h:160] cpu_math_library_num_threads: 1
I0618 05:23:01.178469 25606 demo_helper.h:161] enable_mkldnn_bfloat16: false
I0618 05:23:01.178472 25606 demo_helper.h:163] ----------------------- Perf info -----------------------
I0618 05:23:01.178474 25606 demo_helper.h:164] Average latency(ms): 7.48142, QPS: 133.664
2022-06-18 05:23:02,140 - __main__ - WARNING - <class 'subprocess.CalledProcessError'>
```

Paddle commit id + fc_lstm

```
I0618 06:34:22.493718  7550 analysis_predictor.cc:1161] ======= optimize end =======
I0618 06:34:22.496223  7550 naive_executor.cc:104] ---  skip [feed], feed -> image
I0618 06:34:22.496829  7550 naive_executor.cc:104] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
I0618 06:34:22.496836  7550 naive_executor.cc:104] ---  skip [save_infer_model/scale_1.tmp_0], fetch -> fetch
I0618 06:34:22.496850  7550 clas_benchmark.cc:104] run ch_ppocr_mobile_v1.1_rec_infer model
I0618 06:34:22.496867  7550 clas_benchmark.cc:37] batch_size: 1 ,channels: 3    ,height: 32 ,width: 320
I0618 06:34:22.497108  7550 device_context.cc:805] oneDNN v2.6.0
I0618 06:34:26.201647  7550 demo_helper.h:143] ----------------------- Model info ----------------------
I0618 06:34:26.201680  7550 demo_helper.h:144] Model name: ch_ppocr_mobile_v1.1_rec_infer, Model type: static
I0618 06:34:26.201684  7550 demo_helper.h:146] ----------------------- Data info -----------------------
I0618 06:34:26.201687  7550 demo_helper.h:147] Batch size: 1, Num of samples: 500
I0618 06:34:26.201690  7550 demo_helper.h:149] ----------------------- Conf info -----------------------
I0618 06:34:26.201694  7550 demo_helper.h:150] device: cpu, ir_optim: true
I0618 06:34:26.201696  7550 demo_helper.h:152] enable_memory_optim: false
I0618 06:34:26.201704  7550 demo_helper.h:159] enable_mkldnn: true
I0618 06:34:26.201705  7550 demo_helper.h:160] cpu_math_library_num_threads: 1
I0618 06:34:26.201709  7550 demo_helper.h:161] enable_mkldnn_bfloat16: false
I0618 06:34:26.201711  7550 demo_helper.h:163] ----------------------- Perf info -----------------------
I0618 06:34:26.201714  7550 demo_helper.h:164] Average latency(ms): 7.1346, QPS: 140.162
2022-06-18 06:34:27,316 - __main__ - WARNING - <class 'subprocess.CalledProcessError'>
```

**Comment by jczaja** [comment]
@lidanqing-intel Hi, what is the status of this work?

**Comment by lidanqing-vv** [comment]
@jczaja Hi, it passed all CIs last time but now it is out of date. 
Now I actually planned to move `fc_lstm_fuse_pass` into first of mkldnn passes and then verify in CIs that it will not cause any mkldnn models crash, what do you think?
I just think maybe adding it into CPU Passes will be not safe.

**Comment by lidanqing-vv** [comment]
@jczaja  I will update this PR and restart CIs.

**Pull request closed without merging**
