### PR TITLE
Fix dst memory allocation in elementwise_add (#21059)

### PR DESCRIPTION
**Pull request by wojtuss**
This is a cherry-pick of the fix: https://github.com/PaddlePaddle/Paddle/pull/21059

test=release/1.6

### CODE REVIEW

**Review by luotao1 — APPROVED** [review]
LGTM! Thanks very much!

**Review by luotao1 — CHANGES_REQUESTED** [review]
It seems mis-add ` paddle/fluid/train/imdb_demo/CMakeLists.txt` and `python/paddle/fluid/tests/unittests/seresnext_net.py`

**Comment by bingyanghuang** [comment]
We can close this PR since PR #21153 is rightly created.

**Comment by luotao1** [comment]
close due to #21153

**Pull request closed without merging**
