### PR TITLE
Added shuffle_channel BF16/FP32 FWD oneDNN kernel

### PR DESCRIPTION
**Pull request by jakpiase**
### PR types
New features

### PR changes
OPs

### Describe
Added shuffle_channel BF16/FP32 FWD oneDNN kernel. This kernel is made by merging `reshape2` + `transpose2` + `reshape2` operators into `shuffle_channel` operator by `shuffle_channel_detect_pass`. It is designed to speedup picodet and shufflenet models.

<b>Picodet FP32: ~11% speed up</b>
<b>ShufflenetV2 FP32: ~22% speed up</b>

Picodet with shuffle_channel:
image

Picodet without shuffle_channel:
image

ShufflenetV2 with shuffle_channel:
image

ShufflenetV2 without shuffle_channel:
image

### CODE REVIEW

**Comment by baoachun** [comment]
Hi @jakpiase, there is a bug in the pass `shuffle_channel_detect_pass`, so the original plan is to delete it. Maybe you need to move the file to the mkldnn directory and fix its bug to ensure the correct operation of the new operator. In addition, when an operator is a fusion operator, such as `shuffle_channel`, it may be necessary to add two single tests, one is a pass single test, and the other is a single operator single test.

**Comment by jakpiase** [comment]
Hi @baoachun, could you please give some more details about that bug in `shuffle_channel_detect_pass`?

**Comment by baoachun** [comment]
Hi @jakpiase, you can check the modification of this pr: https://github.com/PaddlePaddle/Paddle/pull/39242. I learned yesterday that no new bugs have been found for the time being. However, this pass has many restrictions and can be verified against oneDNN based on the new single test framework.

**Comment by jakpiase** [comment]
Hi @baoachun, so should I create another pass(`shuffle_channel_mkldnn_detect_pass`) or can I use `shuffle_channel_detect_pass`? Is it fixed after this PR that you have mentioned?

**Comment by baoachun** [comment]
Hi @jakpiase, I think you need to move the file to the mkldnn directory, and rename it with `shuffle_channel_mkldnn_detect_pass`.

**Comment by jakpiase** [comment]
@baoachun I have moved shuffle channel pass into `shuffle_channel_mkldnn_detect_pass` as you have requested

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by jakpiase** [comment]
@baoachun could you please review this PR?

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
We can add ShuffleNetV2 in our CI too later.

**Comment by baoachun** [comment]
Hi @jakpiase well done! Maybe you also need to add a single test for the pass, not just a single test for a single operator.

**Comment by lidanqing-vv** [comment]
@baoachun  Can we add pass test in next PR. Casue this PR has passed all CIs.
And pass test may will require approval and will delay long time to merge

**Comment by lidanqing-vv** [comment]
Hi, @jakpiase I've talked with achun. Please submit pass test in next PR and relate to this PR.
Cause CIs are not so easily to pass all now, so achun agreed to just merge this and make pass test in next PR.

**Pull request merged**
