### PR TITLE
Fix incorrect parameter replacing of PIR constant_folding_pass caused by stack op

### PR DESCRIPTION
**Pull request by lszxb**
### PR Category

Performance Optimization

### PR Types

Improvements

### Description

Currently, the PIR constant_folding_pass will decide the constant in PIR program to be a `builtin.constant`, which is on CPU, or a `builtin.parameter`, which is on GPU. In some situation, this will produce incorrect results, causing a constant being placed on GPU, which leads to unnecessary D2H synchronization.

The following code
```python
out = paddle.full([mask.shape[0], 1], 1)
```
will translate to the following PIR:
```
    (%7) = "pd_op.full" () {dtype:(pd_op.DataType)int32,persistable:[false],place:(pd_op.Place)Place(cpu),shape:(pd_op.IntArray)[],stop_gradient:[false],value:(Float)1} : () -> builtin.tensor<i32>
    (%8) = "pd_op.full" () {dtype:(pd_op.DataType)float32,place:(pd_op.Place)Place(cpu),shape:(pd_op.IntArray)[1],stop_gradient:[true],value:(Double)1} : () -> builtin.tensor<1xf32>
    (%9) = "builtin.combine" (%6, %7) {} : (builtin.tensor<i32>, builtin.tensor<i32>) -> vec[builtin.tensor<i32>,builtin.tensor<i32>]
    (%10) = "pd_op.stack" (%9) {axis:(Int32)0,stop_gradient:[true]} : (vec[builtin.tensor<i32>,builtin.tensor<i32>]) -> builtin.tensor<2xi32>
    (%11) = "pd_op.full_with_tensor" (%8, %10) {dtype:(pd_op.DataType)int64,persistable:[false],stop_gradient:[false]} : (builtin.tensor<1xf32>, builtin.tensor<2xi32>) -> builtin.tensor<-1x1xi64>
```
The first constant "1" (%7) as a part of the shape will become a `builtin.parameter` in the current version. This PR fixes this problem.

### CODE REVIEW

**Comment by yuanlehome** [comment]
Hi同学，merge一下develop再提个commit吧

**Comment by lszxb** [comment]
好的，merge了

**Comment by yuanlehome** [comment]
> Details

PR-CI-Codestyle-Check有问题，执行一下 pre-commit run --files paddle/fluid/pir/transforms/general/constant_folding_pass.cc

**Comment by yuanlehome** [comment]
https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=68152 点进去这个链接签署一下

**Comment by lszxb** [comment]
好的，签署了

**Review by yuanlehome — APPROVED** [review]

**Comment by luotao1** [comment]
hi, @lszxb 
- 非常感谢你对飞桨的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~

**Pull request merged**
