### PR TITLE
Upgrade oneDNN version to 2.6

### PR DESCRIPTION
**Pull request by piotrekobi**
### PR types

Performance optimization
### PR changes

Others
### Describe

Updates the version of oneDNN to 2.6-rc.

### CODE REVIEW

**Comment by piotrekobi** [comment]
@Aganlengzi the Windows CI has been failing for this PR for quite a long time. The fail is caused by stream_safe_cuda_alloc_test, which seems to be detecting a potential memory leak on CUDA. I have no idea why this could be caused by a oneDNN update, and I have no way to reproduce it locally. Can you please look into this?

**Comment by Aganlengzi** [comment]
> @Aganlengzi the Windows CI has been failing for this PR for quite a long time. The fail is caused by stream_safe_cuda_alloc_test, which seems to be detecting a potential memory leak on CUDA. I have no idea why this could be caused by a oneDNN update, and I have no way to reproduce it locally. Can you please look into this?

@piotrekobi hi, I will try re-run again and follow up.

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Comment by piotrekobi** [comment]
This branch is not ready to be merged yet. One of our internal models (test_am_vocoder) is encountering an error with oneDNN 2.6 and I'm investigating the issue.

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Comment by piotrekobi** [comment]
https://github.com/PaddlePaddle/Paddle/pull/42657 (newer oneDNN 2.6 SHA) will be merged instead

**Pull request closed without merging**
