### PR TITLE
Split test_calibration test to two tests

### PR DESCRIPTION
**Pull request by chuanqi129**
For reducing unite test "test_calibration" executor time, split "test_calibration" to "test_calibration_resnet50" and "test_calibration_mobilenetv1" two test. Please @luotao1 help to review it.

### CODE REVIEW

**Comment by luotao1** [comment]
Do you test on the local machine? You should update `CMakelists.txt` at the same time.

**Comment by chuanqi129** [comment]
[11:46:52]	569/618 Test #610: test_calibration_mobilenetv1 ........................   Passed   55.21 sec
[11:47:15]	571/618 Test #611: test_calibration_resnet50 ...........................   Passed   75.95 sec

But failed at "test_dist_se_resnext ", I have re-run the test.

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
[11:46:52]569/618 Test #610: test_calibration_mobilenetv1 ........................   Passed   55.21 sec
[11:47:15]571/618 Test #611: test_calibration_resnet50 ...........................   Passed   75.95 sec

**Pull request merged**
