### PR TITLE
Add table design doc

### PR DESCRIPTION
**Pull request by jacquesqiao**
fix: https://github.com/PaddlePaddle/Paddle/issues/9183
related issue: https://github.com/PaddlePaddle/Paddle/pull/9068

### CODE REVIEW

**Comment by typhoonzero** [comment]
I don't think we need this type of variable:

1. One tensor distributed on multiple servers could do the same thing. Because the size of the table can be determined before training, distribute this tensor by dim0 and lookup the id by calculating the index boundaries of the servers.
1. If it's for an outside server, we'll only need to merge the keys to a `SelectedRows` variable.

**Comment by jacquesqiao** [comment]
The main problem is that in large scale embedding, the feature_id(int64_t) is discrete in a very big range, it's hard to represent it by Tensor or SelectedRows, for both of them use a dense tensor that the  shape of memory should be decided before run.

**Comment by typhoonzero** [comment]
@jacquesqiao I see, I figure it out now, thank you very much I'll look into the design.

**Comment by typhoonzero** [comment]
I've talked to @jacquesqiao today that we can use `SelectedRows` as the sparse weight table directly and decide which server should an id be put on by ` id % server_count`.

**Comment by jacquesqiao** [comment]
yes, SelectedRows can support the need for the distributed lookup table. It's structure is 
```cpp
struct {
  Vector<int64_t> rows_;
  std::unique_ptr<Tensor> value_{nullptr};
  int64_t height_;
}
```
`rows_` can be used to store the ids with the same `shard_id`
`value_` store a dense matrix, user can get the value of a id using id's offset in the `rows_`.

**Pull request closed without merging**
