### PR TITLE
[oneDNN][cherry-pick] Fix to #33282 , added support of X input broadcasting to one…

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Bug fixes

### PR changes
OPs

### Describe
This is a backport of fix to #33282.

### CODE REVIEW

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM. Thanks !

**Review by jakpiase — APPROVED** [review]

**Review by gentelyang — APPROVED** [review]

**Comment by jczaja** [comment]
@wzzju , @juncaipeng  Please merge (it is a cherry-pick from develop).

**Review by juncaipeng — APPROVED** [review]
LGTM

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
