### PR TITLE
fix Variable's gradient api in framework.py, test=develop

### PR DESCRIPTION
**Pull request by JepsonWong**
fix Variable's gradient api in framework.py.

en_doc for PR #21078 .

cn_doc: https://github.com/PaddlePaddle/FluidDoc/pull/1625

### CODE REVIEW

**Comment by JepsonWong** [comment]
image

**Review by Boyan-Liu — DISMISSED** [review]
LGTM

**Review by luotao1 — DISMISSED** [review]
LGTM

**Review by Boyan-Liu — APPROVED** [review]
LGTM

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Pull request merged**
