### PR TITLE
[oneDNN][INT8][FP32] INT8/FP32 elementwise_mul and INT8 elementwise_add

### PR DESCRIPTION
**Pull request by Sand3r-**
PR types: New features

PR changes: OPs 

Describe:
1. PR introduces oneDNN forward kernels for:
- INT8 elementwise_add
- INT8 elementwise_mul
- FP32 elementwise_mul

2. It also fixes 2 bugs:
* When using ShareBufferWith (inplace operators), the type wasn't assigned to the tensor to which the buffer was shared with. This resulted in hard to detect memory crashes when attempting to test inplace elementwise int8 operators (size was allocated in ints, while fetch_op required size allocated for floats).
* OpTester has can now succesfully output uint8 results to the console. Previously arrays of uint8 data were treated as encoded byte strings instead of arrays of numbers.

3. At the same time, the following has been removed:
- An old elementwise_mul kernel that was crafted for a special case in ResNeXt-50. This special case (and many others) should now be fully covered inside of the new kernel
- It's unit tests

PRs to be merged before this one:

#24853
#24854
#24855

### CODE REVIEW

**Comment by Sand3r-** [comment]
* MAC_PR_CI_python35 (Paddle Mac) -> Fails due to missing approval for removal of UT. UT test_elementwise_mul_op_correct_dims was removed because its no longer relevant (old elementwise_mul kernel was removed).
* PR_CI_CPU_Py2 (Compile)  -> Fails due to missing approvals for:
1. Change in API - I don't know which one is meant here, maybe addition of int8 attributes to elementwise_op?
2. Change in tensor.h (fixed bug with ShareBufferWith)
3. Setting dygraph field to false in int8 UTs, just the way it is in original elementwise_mul test, otherwise the oneDNN tests fail with dygraph
4. Usage of skip_check_grad_ci for int8 inference-only ops.
* PR_Windows_CI (Paddle Windows)
```
[14:33:59]W:	 [Step 7/8] CMake Error at cmake/inference_lib.cmake:217 (add_dependencies):
[14:33:59]W:	 [Step 7/8]   The dependency target "cuda_error_proto" of target "fluid_lib_dist" does
[14:33:59]W:	 [Step 7/8]   not exist.
[14:33:59]W:	 [Step 7/8] Call Stack (most recent call first):
[14:33:59]W:	 [Step 7/8]   CMakeLists.txt:211 (include)
```
No idea what happened, didn't touch anything there.
* PR-CI-Coverage:
```
[2020-04-03 21:24:05]  [  3%] Building CXX object paddle/fluid/framework/io/CMakeFiles/shell.dir/shell.cc.o
[2020-04-03 21:24:05]  [  3%] Linking CXX static library libfs.a
[2020-04-03 21:24:05]  In file included from /paddle/paddle/fluid/platform/enforce.h:41:0,
[2020-04-03 21:24:05]                   from /paddle/paddle/fluid/framework/io/shell.cc:16:
[2020-04-03 21:24:05]  /paddle/paddle/fluid/platform/errors.h:23:50: fatal error: paddle/fluid/platform/error_codes.pb.h: No such file or directory
[2020-04-03 21:24:05]  #include "paddle/fluid/platform/error_codes.pb.h"
[2020-04-03 21:24:05]                                                    ^
[2020-04-03 21:24:05]  compilation terminated.
```
Again, no idea what went wrong there, didn't touch the file.

@luotao1 do you know if there are any ongoing fixes for PR-CI-Coverage and PR_Windows_CI (Paddle Windows)?

@jczaja @wojtuss you can start the review, as no tests currently fail, CIs only fail because of missing approvals, or random PR-unrelated compilation failures.

**Comment by luotao1** [comment]
> PR-CI-Coverage and PR_Windows_CI fails

fixed by #24800, just rerun it, and I have already rerun Windows. 

> Change in API - I don't know which one is meant here, maybe the addition of int8 attributes to elementwise_op?

It seems not the addition of int8 attributes, I have rerun it at first.

**Review by jczaja — COMMENTED** [review]
LGTM

**Review by wojtuss — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
Could you split this PR into several ones? The reason is:
-  There are too many approvals in this PR.
- Change in API - I don't know which one is meant here, maybe addition of int8 attributes to elementwise_op?
  - After rerun, it still has the Change in API. If you can split the PR into smaller ones, it may be easier for us to find the reason.

**Comment by Sand3r-** [comment]
@luotao1 
> Could you split this PR into several ones? The reason is:
> 
> * There are too many approvals in this PR.
> * Change in API - I don't know which one is meant here, maybe addition of int8 attributes to elementwise_op?
>   
>   * After rerun, it still has the Change in API. If you can split the PR into smaller ones, it may be easier for us to find the reason.

Following files are strictly connected to one another and concern addition of elementwise_kernels:
```
 paddle/fluid/operators/elementwise/CMakeLists.txt 
 paddle/fluid/operators/elementwise/elementwise_mul_op.h 
 paddle/fluid/operators/elementwise/elementwise_op.h 
 paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc 
 paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
 paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
 paddle/fluid/operators/elementwise/test_elementwise_mul_op_dim.cc
 paddle/fluid/platform/mkldnn_reuse.h
 python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_add_mkldnn_op.py 
 python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py 
```
This is a bugfix required for int8 tests to pass
```
 python/paddle/fluid/tests/unittests/op_test.py
```
This is a bugfix required for int8 inplace tests to pass
```
 paddle/fluid/framework/tensor.h 
```

Do you want me to split this into 3 such PRs?

**Comment by luotao1** [comment]
It's better to split this into 3 such PRs. Besides, how about remove `test_elementwise_mul_op_dim.cc` in a separate PR, which is easy for QA review?

**Comment by Sand3r-** [comment]
@luotao1 
> It's better to split this into 3 such PRs. Besides, how about remove `test_elementwise_mul_op_dim.cc` in a separate PR, which is easy for QA review?
Alright, will do.

**Comment by Sand3r-** [comment]
@luotao1 Done:
https://github.com/PaddlePaddle/Paddle/pull/24853
https://github.com/PaddlePaddle/Paddle/pull/24854
And the current one.

Btw. removing `test_elementwise_mul_op_dim.cc` separately might cause PR_CI_Coverage to fail. Are you sure we should move it to separate PR? Also: Maintaining so many PRs is going to be quite of a hassle.

**Comment by luotao1** [comment]
> removing test_elementwise_mul_op_dim.cc separately might cause PR_CI_Coverage to fail. 

The fail reason for `PR_CI_Coverage` is an approval. Is any other fail reason?

> Are you sure we should move it to separate PR?

Yes, it's better to move it to separate PR, which is easy for QA review. And your current PR is much more clearer.

> Maintaining so many PRs is going to be quite of a hassle.

I see the other two PRs, which are quick to be merged. But if they are in one PR, the approval may take some time.

**Comment by Sand3r-** [comment]
> Yes, it's better to move it to separate PR, which is easy for QA review. And your current PR is much more clearer.

Alright, I moved it to #24855

> I see the other two PRs, which are quick to be merged. But if they are in one PR, the approval may take some time.

That's assuming no random CI failures 😉

**Comment by jczaja** [comment]
Work on this functionality is continued in PR #24984. Closing

**Pull request closed without merging**
