### PR TITLE
[OneDNN] Conv op refactor.

### PR DESCRIPTION
**Pull request by arogowie-intel**
### PR types
Others

### PR changes
Others

### Describe
This PR refactors OneDNN convolution (FWD) operator kernel. The aim was to unify implementation across supported data types (fp32/bf16/int8).

### CODE REVIEW

**Comment by arogowie-intel** [comment]
The CI errors are due to failures to clone eigen repository.

**Review by jczaja — APPROVED** [review]
LGTM

**Review by jakpiase — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
Hi, this PR caused #35778 failed on test_conv3d_mkldnn_op. so I revert it first, please make a new PR later.

**Comment by jakpiase** [comment]
Hi, @lidanqing-intel I have fixed this error in #36284 which is already merged

**Pull request merged**
