### PR TITLE
[CI] CI for Distributed

### PR DESCRIPTION
**Pull request by sljlp**
### PR types

Others
### PR changes

Others
### Describe

CI for Distributed multinode-mode

### CODE REVIEW

**Review by wanghuancoder — DISMISSED** [review]
LGTM for WITH_MULTINODE_TESTING

**Review by XieYunshen — DISMISSED** [review]
LGTM

**Review by XieYunshen — DISMISSED** [review]
LGTM for `"RUN_TYPE=EXCLUSIVE"`

**Review by wanghuancoder — DISMISSED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Pull request merged**
