### PR TITLE
Add mkldnn bfloat16 option to C-API

### PR DESCRIPTION
**Pull request by wozna**
### PR types

New features
### PR changes

APIs
### Describe

This PR presents: 
- bfloat16 enablement in C-API

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Review by jczaja — APPROVED** [review]

**Comment by luotao1** [comment]
@Superjomn Please help review the C-API bfloat16 interface.

**Review by Superjomn — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
@wozna @lidanqing-intel This PR is reverted in #26854, the reason is that the unit-test failed. There is some error in our CI system, which does not report this error.
```

2020-08-28 03:30:40 ========================================
2020-08-28 03:30:40 There are failed tests, which have been successful after re-run:
2020-08-28 03:30:40 ========================================
2020-08-28 03:30:40 The following tests have been re-ran:
2020-08-28 03:30:40 
2020-08-28 03:30:40             	220 - test_analyzer_capi_gpu (Child aborted)
2020-08-28 03:30:40             	273 - test_activation_op (Failed)
```
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/1599837/job/2282345

**Pull request merged**
