### PR TITLE
【Infer Symbolic Shape No.105】Add full_ implementation 

### PR DESCRIPTION
**Pull request by enkilee**
### PR Category

CINN

### PR Types

New features

### Description

- https://github.com/PaddlePaddle/Paddle/issues/66444
full_

### CODE REVIEW

**Review by gongshaotian — APPROVED** [review]
LGTM

**Comment by gongshaotian** [comment]
rerun了windows和windows-inference 测试

**Comment by gongshaotian** [comment]
麻烦处理下冲突

**Comment by enkilee** [comment]
收到

**Review by zyfncg — APPROVED** [review]

**Review by Hongqing-work — APPROVED** [review]

**Pull request merged**
