### PR TITLE
[oneDNN] candidate fix to #34554

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Bug fixes

### PR changes
OPs

### Describe
This is another fix to have issue #34554 resolved.

### CODE REVIEW

**Review by jakpiase — DISMISSED** [review]
LGTM

**Review by lidanqing-vv — DISMISSED** [review]
LGTM

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
Can you please change the title so that the title could be collected directly by github cli for release note without any changes. Thanks

LGTM.

**Pull request merged**
