### PR TITLE
Replace platform::CPUPlace phi::CPUPlace in fluid/operators

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others 

### PR Types

Others 

### Description

 in fluid/operators
Replace platform::CPUPlace phi::CPUPlace
framework::DDim phi::DDim
Replace is_xxx_place in fluid/operators

### CODE REVIEW

**Comment by co63oc** [comment]
合入https://github.com/PaddlePaddle/Paddle/pull/63843

**Comment by luotao1** [comment]
需要解决冲突

**Review by wanghuancoder — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
@co63oc 需要解决冲突

**Comment by luotao1** [comment]
冲突了

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
