### PR TITLE
mv test 58/59

### PR DESCRIPTION
**Pull request by KimBioInfoStudio**
### PR types

Others 
### PR changes

Others 
### Describe

Others

### CODE REVIEW

**Comment by tianshuo78520a** [comment]
麻烦修改下这个文件引用路径
image

**Comment by KimBioInfoStudio** [comment]
> 麻烦修改下这个文件引用路径 image

it's too ugly to incude this file from test dir, @tianshuo78520a  @zhiqiu

**Comment by tianshuo78520a** [comment]
> 

This is indeed a problem，You can try to optimize。

**Comment by KimBioInfoStudio** [comment]
> > 
> 
> This is indeed a problem，You can try to optimize。

will focus on the original problem, i think this task is a subtask when we mv test base to wheel, need a detailed plan and rfc

**Comment by tianshuo78520a** [comment]
PR：#52987 已经完成迁移，close该PR

**Pull request closed without merging**
