### PR TITLE
[cherry pick] Fix issue #33021 setCacheCapacity could not limit memory consumption

### PR DESCRIPTION
**Pull request by lidanqing-vv**
### PR types
Bug fixes

### PR changes
Others

### Describe
[cherry pick] Fix issue #33021 setCacheCapacity could not limit memory consumption

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@jczaja  Hi please review and approve it. Tomorrow is 2.1.1 branch day they want to merge it today.

**Review by jczaja — APPROVED** [review]
LGTM

**Review by juncaipeng — APPROVED** [review]
LGTM

**Review by Superjomn — APPROVED** [review]
LGTM

**Pull request merged**
