### PR TITLE
Integrate QAT into distributed optimizer

### PR DESCRIPTION
**Pull request by leo0519**
### PR types

New features

### PR changes

APIs

### Description

1. Make onnx QAT API support AMP program
      In AMP program, the filter of conv2d OP is temporary variable because AMP will cast weight first. This PR marks those 
      nodes of cast weights and treats them as persistable weight.
2. Integrate QAT into distributed optimizer
      Add QAT strategy into distributed optimizer
3. Use `logging.info` to show message and reduce the time limit in unittests

### CODE REVIEW

**Review by ceci3 — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]
LGTM for ` 
set_tests_properties(test_quant_aware PROPERTIES TIMEOUT 200)
  set_tests_properties(test_quant_post_quant_aware PROPERTIES TIMEOUT 200)
  set_tests_properties(test_quant_aware_user_defined PROPERTIES TIMEOUT 200)
  set_tests_properties(test_quant_aware_config PROPERTIES TIMEOUT 200)
  set_tests_properties(test_quant_amp PROPERTIES TIMEOUT 200)`

**Review by jzhang533 — APPROVED** [review]
LGTM for API change

**Comment by leo0519** [comment]
This PR needs CI approval:
```
2023-07-04 12:36:35 Please find RD for approval first, and then find TPM for approval.
2023-07-04 12:36:35 0. You must have one RD (XiaoguangHu01, jeff41404, lanxianghit or qingqing01) approval for API change.
2023-07-04 12:36:35  and one TPM approval for API change: 
2023-07-04 12:36:35  jzhang533/ZhangJun, sunzhongkai588/SunZhongKai, dingjiaweiww/DingJiaWei, Ligoml/LiMengLiu for general APIs.
2023-07-04 12:36:35  liuTINA0907/LiuShuangQiao for distributed related APIs.
2023-07-04 12:36:35  leiqing1/LeiQing for inference related APIs.
2023-07-04 12:36:35 
2023-07-04 12:36:35 There are 1 approved errors.
```

**Comment by jeff41404** [comment]
Because the `qat_init` method has been added to a public class API `paddle.distributed.fleet.Fleet`, so [documentation]( https://github.com/PaddlePaddle/docs/blob/develop/docs/api/paddle/distributed/fleet/Fleet_cn.rst) is also needed to add `qat_init`.

**Comment by leo0519** [comment]
Hi @jeff41404 , can I submit another PR to modify the document?

**Comment by jeff41404** [comment]
> Hi @jeff41404 , can I submit another PR to modify the document?

Because  [documentation](https://github.com/PaddlePaddle/docs/blob/develop/docs/api/paddle/distributed/fleet/Fleet_cn.rst) is in another repo, you can write a another PR, but you need to attach that PR link here

**Comment by leo0519** [comment]
Hi @jeff41404 , I submit a [PR](https://github.com/PaddlePaddle/docs/pull/6013) to modify the document. Could you help review and merge the PR?

**Review by qingqing01 — APPROVED** [review]

**Pull request merged**
