### PR TITLE
trt reduce_mean supported

### PR DESCRIPTION
**Pull request by b3602sss**
### PR types
New features

### PR changes
OPs 

### Describe
增加reduce_mean支持，修改reduce op支持静态shape.

### CODE REVIEW

**Review by XieYunshen — DISMISSED** [review]
LGTM for set_tests_properties(test_trt_reduce_mean_op PROPERTIES TIMEOUT 60)

**Review by cryoco — DISMISSED** [review]
LGTM

**Review by shangzhizhou — COMMENTED** [review]
完善测试case，比如
1、非动态shape
2、动态shape不在batch维度（第0维）的情况
3、fp16
4、开启序列化

**Review by shangzhizhou — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Pull request merged**
