### PR TITLE
Decouple weights and bias from fc primitive in MKLDNN cache

### PR DESCRIPTION
**Pull request by wojtuss**
### PR types
Function optimization

### PR changes
OPs

### Describe
This patch decouples weights and bias memory objects from FC primitive factory in MKLDNN cache. This is required to enable saving INT8 weights and bias tensors from MKLDNN cache. This is the first PR in a series.  See https://github.com/PaddlePaddle/Paddle/issues/26679.

### CODE REVIEW

**Review by grygielski — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
Since network error before, and it doesn't trigger the CI, please re-push again. Thanks very much!

**Review by grygielski — APPROVED** [review]
LGTM

**Review by arlesniak — APPROVED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
