### PR TITLE
"add nccl cmake enforce"

### PR DESCRIPTION
**Pull request by dzhwinter**
To support Multi-GPU, we use [NCCL](https://github.com/NVIDIA/nccl) library to do parameter/gradients integration and distribution. This PR adds an enforce macro helper module, cmake scripts to support NCCL. Cause NCCL library needs to compatible with different CUDA version, we use the `DSO` loading technical, same as other module cublas, cudnn does.

### CODE REVIEW

**Comment by QiJune** [comment]
Please install nccl in dockefile. And make ci pass first.

**Comment by QiJune** [comment]
We have to ways to introduce NCCL to paddle:
- Make sure NCCL has been installed in CI machine first. .h and .so are installed in the correct directory. We can dynamic load .so of NCCL
- We download NCCL source code from github, and just take NCCL as a cmake external project.  Since we fix the version of NCCL, we can use .a of NCCL in our code.

**Comment by dzhwinter** [comment]
NCCL2 has a good back compatible ability, which can used base CUDA 7.0 - CUDA 9.x.
Since the nvidia-docker image can install NCCL2 manually, so I will remove the github clone related cmake scripts.
[nvidia-docker](https://gitlab.com/nvidia/cuda/issues/10#note_44115341)
>NCCL is not bundled in any CUDA image right now, so you will have to install it manually for now. On 8.0 and 9.0.
Yes, I plan to add NCCL 2.0 to all images soon.
In the mean time, we have a new tag called "base" for CUDA 9.0. It adds our package repositories to the official ubuntu 16.04 image. Afterwards you can manually install any package:
FROM nvidia/cuda:9.0-base
RUN apt-get update && apt-get install -y libnccl-dev

**Comment by dzhwinter** [comment]
This will be closed since #5001 cherry-picked this code.

**Pull request closed without merging**
