### PR TITLE
md5 changed

### LINKED ISSUE #12827: python/paddle/dataset/flowers.py wrong md5
The dataset "flowers" is downloaded each time when training is run, even if it was downloaded under earlier iteration

Proposed solution:
change md5 information in file `python/paddle/dataset/flowers.py`
```
from: 33bfc11892f1e405ca193ae9a9f2a118
  to: 52808999861908f626f3c1f4e79d11fa
```

### PR DESCRIPTION
**Pull request by pmajchrzak**
fix #12827

### CODE REVIEW

**Comment by luotao1** [comment]
```
[08:04:11]	Cache file /root/.cache/paddle/dataset/flowers/102flowers.tgz not found, downloading http://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz
[08:04:11]	
[08:04:11]	[                                                  ]
```
The download in TeamCity is too slow. We will find another address to store it.

**Comment by pmajchrzak** [comment]
Does this solve this problem?

**Comment by luotao1** [comment]
Yes, this PR solve the problem. But TeamCity hangs due to the slow download.

**Comment by luotao1** [comment]
@pmajchrzak We update the file in #12910, thanks for your suggestion, and I close this PR.

**Pull request closed without merging**
