### PR TITLE
Fix the bug of test_conv2d_int8_mkldnn case which raised by improper parameter passing

### LINKED ISSUE #17057: One issue found on test_conv2d_int8_mkldnn_op case
我们在做conv/relu6 fusion int8 test case 集成时候发现，当前的test_conv2d_int8_mkldnn_op test case有潜在bug， 具体表现为[init_data_type_with_fusion](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py#L264)并没有传递fuse_relu/fuse_residual 值到父类[TestConv2dInt8Op](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py#L33)中，这就导致从287行至326行的7个子case 使用的都是fuse_relu=True fuse_residual=True的设定。

也正因此， 导致[output_tmp2](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py#L121) 没有定义的潜在bug没有被发现

### PR DESCRIPTION
**Pull request by guomingz**
resolve #17057

~~Fixed the bug that fuse_relu/fuse_residual option couldn't be passed to class TestConv2dInt8Op.~~
Fix the bug of test_conv2d_int8_mkldnn case which raised by improper parameter passing.

test=develop

### CODE REVIEW

**Comment by luotao1** [comment]
please make PR title easy to understand.

**Comment by guomingz** [comment]
> please make PR title easy to understand.

Sorry ， i made the explanation on the issue description.
Shall i copy the corresponding description?

**Comment by luotao1** [comment]
The issue title is easy to understand, you can make the PR title like issue title, not just copy.

**Comment by guomingz** [comment]
> The issue title is easy to understand, you can make the PR title like issue title, not just copy.

thanks for suggestion.
How about the below title:
Fix the bug of test_conv2d_int8_mkldnn case which raised by improper parameter passing.

If the description is ok, i'll update the commit later.

**Comment by luotao1** [comment]
I think it's nice!

**Comment by guomingz** [comment]
> I think it's nice!

Updated. Please help to add Intel Label

**Comment by guomingz** [comment]
hi @luotao1  the pre-ci had been passed, please help to review the PR.

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by guomingz** [comment]
> LGTM

Thank you for your time.

**Pull request merged**
