### PR TITLE
[Paddle-TRT] add generic plugin for lookup_table_v2(embedding) op

### PR DESCRIPTION
**Pull request by yuanlehome**
### PR types

Others
### PR changes

Others
### Description

add generic plugin for lookup_table_v2(embedding) op.

性能不理想，未启用。ref to https://github.com/PaddlePaddle/Paddle/pull/53554

### CODE REVIEW

**Comment by weishengying** [comment]
LGTM

**Review by zhangjun — COMMENTED** [review]
有测试数据吗？

**Comment by yuanlehome** [comment]
> 有测试数据吗？

phi embedding kernel 20us，lookup_table plugin 5us.

**Review by zhangjun — APPROVED** [review]
LGTM

**Pull request merged**
