### PR TITLE
[bf16] add bf16 kernel: gaussian_random  fill_constant  fill_any_like

### PR DESCRIPTION
**Pull request by zhangbo9674**
### PR types
New features

### PR changes
OPs

### Describe
`gaussian_random``fill_constant``fill_any_like`添加 bf16 kernel。

### CODE REVIEW

**Review by zhiqiu — DISMISSED** [review]
LGTM

**Review by zhiqiu — APPROVED** [review]
LGTM

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Review by ZzSean — APPROVED** [review]
LGTM for op benchmark

**Pull request merged**
