### PR TITLE
Add collective communication APIs to improve completeness

### PR DESCRIPTION
**Pull request by HermitSun**
### PR types

New features
### PR changes

APIs
### Describe

对标竞品，增加集合通信相关 API 以提高分布式通信的完备性，包括：
- [x] paddle.distributed.broadcast_object_list
- [x] paddle.distributed.scatter_object_list
- [x] paddle.distributed.get_backend
- [x] paddle.distributed.is_available

对应的中文文档：https://github.com/PaddlePaddle/docs/pull/5534

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM for 
单测时间设置

**Review by jzhang533 — APPROVED** [review]
LGTM for API changes

**Review by LiYuRio — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
