### PR TITLE
[DNNL] Added elementwise_add mkl-dnn inplace

### PR DESCRIPTION
**Pull request by jczaja**
This PR is reimplementing elementwise_add mkldnn kernel so that sum DNNL primitive is replaced with binary primitive as it is a bit more efficient and supports inplace execution. mkldnn inplace pass was updated to support elementwise_add mkl-dnn

Performance improvement : 
~2% on ERNIE (B1 Thread 1 Latency:  252 -> 245 fp32 , 90 -> 87  INT8) : Intel Xeon(R) 6248
~1% on BERT (~162 FPS to ~165 FPS) when tested on Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@jczaja  Why benchmark performance on avx2 machine, not on 6271? It is required? 6271 should bring more improvement? Related issue https://github.com/PaddlePaddle/Paddle/issues/23074

**Comment by jczaja** [comment]
@lidanqing-intel BDW platform is the one I use for development. Tests on 6271 were started yesterday
and at the time of creating this PR description , tests were not completed

**Comment by jczaja** [comment]
@luotao1 Please advise on PR_Windows_CI and/or rerun it.

**Comment by luotao1** [comment]
I rerun it at first.

**Review by grygielski — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao When testing I found some functional problem and still working on it so please do not review it yet

**Review by grygielski — DISMISSED** [review]
LGTM

**Review by grygielski — DISMISSED** [review]
LGTM

**Review by grygielski — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 , @grygielski I updated PR with code that passed all our internal tests. Please continue your review.

**Review by grygielski — DISMISSED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 I have a problem restarting two failing builds. Could you please restart them ?

**Comment by luotao1** [comment]
@jczaja What's your problem with restarting? Could you restart in success now?

**Comment by jczaja** [comment]
@luotao1 It is working now, I just got confused .

**Review by grygielski — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 Could you please start your review?

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
