### PR TITLE
Fix cached scope on inference 

### PR DESCRIPTION
**Pull request by hjchen2**
keep cached scope in memory, otherwise it will be deleted at some where, and if deleted, it will cause crash problem.

### CODE REVIEW

**Comment by panyx0718** [comment]
Can you give more detail? why it will crash if deleted?

**Comment by hjchen2** [comment]
@panyx0718 If keep_kids is false, scope will drop its kids after running a minibatch in Executor::RunPreparedContext. Once the scope kids are dropped, the cached scope are invalid which cause crash. If keep_kids set as true, then the kids scope will never dropped for sequence model, and this maybe lead to large memory usage, even out of memory.

**Comment by Xreki** [comment]
I think caching of scopes created in operator is conflict with `keep_kids`. When `keep_kids` is false, the cache should be disabled.

**Comment by hjchen2** [comment]
@Xreki I think what the original intention of keep_kids is to prevent larger and larger memory occupation in rnn cells.  I agree with you if all the ops in the network are rnn cells, but usually not. Other ops except for sequence ops will need cache the scope but keep_kids is false.

**Pull request closed without merging**
