### PR TITLE
【Prim】Support elementwise related VJP with primitives

### PR DESCRIPTION
**Pull request by JiabinYang**
### PR types

New features
### PR changes

OPs
### Describe

This PR support elemenwise related vjp with composite:
1. Support get_reduce_dims to get reduce dim for elementwise related ops
2. Support reduce_sum, full, bypass api for primitives
3. Support sub, add, div's vjp rules for both eager and static mode
4. Support resnet related and bert with prim

### CODE REVIEW

**Review by XieYunshen — APPROVED** [review]
LGTM
单测名称修改

**Review by zyfncg — APPROVED** [review]
LGTM for code-gen template

**Review by cxxly — APPROVED** [review]
LGTM

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Pull request merged**
