### PR TITLE
[cherry-pick] Squeeze2 and transpose2 fuse using oneDNN

### PR DESCRIPTION
**Pull request by zh794390558**
### PR types

Performance optimization 
### PR changes

Others
### Describe

ref https://github.com/PaddlePaddle/Paddle/pull/47592

### CODE REVIEW

**Review by yeliang2258 — DISMISSED** [review]
LGTM

**Review by qili93 — APPROVED** [review]
LGTM for const_cast

**Review by chenwhql — APPROVED** [review]
LGTM for PADDLE_ENFORCE

**Review by ZeyuChen — APPROVED** [review]
LGTM

**Pull request merged**
