### PR TITLE
Add fusion_lstm INT8 PTQ

### PR DESCRIPTION
**Pull request by wozna**
### PR types

New features
### PR changes

OPs 
### Describe

This PR: 
- adds fusion_lstm op to post-training quantization with calculation scales 
- adds UT for this 
- adds test with PTQ inference for lstm model 
- changes `MKLDNNMemoryFormat` for `any`  for inputs in `fusion_lstm` op. Thanks to this, OneDNN can choose the most optimal format.

### CODE REVIEW

**Comment by lidanqing-vv** [comment]
@XieYunshen  Hi, could you please approve this PR which added a UT and set its timeout property as 120). Thanks !
```
 0. You must have one QA (XieYunshen(Recommend) or chalsliu) approval for setting parameter RUN_TYPE as EXCLUSIVE, DIST, NIGHTLY, EXCLUSIVE:NIGHTLY or DISTNIGHTLY, or setting TIMEOUT properties.
```
@wzzju

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Review by XieYunshen — APPROVED** [review]

**Comment by lidanqing-vv** [comment]
@baoachun @juncaipeng Hi, This is for lstm post-training calibration. INT8 accuracy is the same as FP32 and peformance are improved.
Keeping the post-training calibration, we could use this support to generalize it to continuous integration CI 40 models INT8. This is what we are working now, but we are still solving version compatibility issues.
@wozna  Please put acc and perf here. Thanks!

**Review by jczaja — APPROVED** [review]
LGTM

**Pull request merged**
