### PR TITLE
[Speed] Refine elementwise sub,div,min,max gradient functor

### PR DESCRIPTION
**Pull request by chengduoZH**
fix https://github.com/PaddlePaddle/Paddle/issues/8821
related issue https://github.com/PaddlePaddle/Paddle/issues/8811

### CODE REVIEW

**Comment by jacquesqiao** [comment]
maybe the title should be `refine elementwise sub,div,min,max gradient functor`

**Comment by chengduoZH** [comment]
@jacquesqiao thanks

**Comment by QiJune** [comment]
Could you please show the performance improvement between these two versions code?

**Comment by chengduoZH** [comment]
@QiJune I did not do some experiment but from the results of optimized elementwise_add_grad and elementwise_mul_grad, it will improve nearly ten times.
elementwise_mul_grad: https://github.com/PaddlePaddle/Paddle/pull/8810
elementwise_add_grad: https://github.com/PaddlePaddle/Paddle/pull/8402#pullrequestreview-98765282
elementwise_add_grad: https://github.com/PaddlePaddle/Paddle/pull/8539

**Pull request merged**
