### PR TITLE
WIP: conv+transpose2 fuse for MobileNetSSD

### PR DESCRIPTION
**Pull request by sfraczek**
This PR adds conv+transpose2 fuse pass for CAPI and PYTHON for mkldnn. It does this by setting reorder_output_format attribute of convolution to a string like "NHWC". Currently it is added only for NCHW->NHWC conversion.

@luotao1 I would like to add a test for this. Do you recommend any way of testing this? Is there any SSD model test that would run this pass?

### CODE REVIEW

**Comment by qingqing01** [comment]
I add a [`Transpose-Flatten-Concat fusion`](https://github.com/PaddlePaddle/Paddle/pull/14568) for the SSD model in GPU.  :)

**Comment by luotao1** [comment]
@sfraczek How about to adding http://paddlemodels.bj.bcebos.com/ssd_mobilenet_v1_pascalvoc.tar.gz into `paddle/fluid/inference/tests/api/CMakeLists.txt` to check this PR?

**Comment by sfraczek** [comment]
@luotao1 I can do what you said
>@sfraczek How about to adding http://paddlemodels.bj.bcebos.com/ssd_mobilenet_v1_pascalvoc.tar.gz into paddle/fluid/inference/tests/api/CMakeLists.txt to check this PR?

I have the model here http://download2266.mediafire.com/3ba718i7hcbg/tpri78jc82d8a43/mobilenetssd_v1_model.tar.gz

**Comment by luotao1** [comment]
Is http://download2266.mediafire.com/3ba718i7hcbg/tpri78jc82d8a43/mobilenetssd_v1_model.tar.gz different with http://paddlemodels.bj.bcebos.com/ssd_mobilenet_v1_pascalvoc.tar.gz?

**Comment by luotao1** [comment]
I can't download your dataset, I will ask danqing help me.
In our `ssd_mobilenet_v1_pascalvoc.tar.gz`, the sub-network is 
```
conv2d
elementwise_add
transpose
```
and in our another detect model, the sub-network is
```
conv2d
elementwise_add
transpose2
```
Does this PR only fuse `conv2d+transpose2`, not include `elementwise_add`?

**Comment by sfraczek** [comment]
To download it you can also click download here http://www.mediafire.com/file/tpri78jc82d8a43/mobilenetssd_v1_model.tar.gz. The old link might have expired.
This model is different it has mAP layers. Should I use the one you gave me and convert it instead? 
It only fuses `conv+transpose2` because that is what I see after conv+bias was already fused in this SSD model I have. Are you saying I should also make it work for `transpose`?

**Comment by luotao1** [comment]
> This model is different it has mAP layers

Our open source `ssd_mobilenet_v1_pascalvoc.tar.gz` doesn't have `transpose2` op, but your model has `transpose2` op. I wonder why `transpose` op changes to `transpose2` op?

**Comment by sfraczek** [comment]
I changed to transpose2 because I used different model which had mAP layers because I need to check if everything works. Do you have the same model ssd_mobilenet_v1_pascalvoc.tar.gz but with mAP layers?

**Comment by luotao1** [comment]
Sorry, I don't have the same model `ssd_mobilenet_v1_pascalvoc.tar.gz` but with mAP layers. Could you add mAP layers to ssd_mobilenet_v1_pascalvoc?

**Comment by sfraczek** [comment]
I tried but I end up with transpose2

**Comment by sfraczek** [comment]
This is cancelled. We will have a diffrerent approach by @jczaja .

**Comment by luotao1** [comment]
@sfraczek @jczaja when will the different approach be a new PR?

**Comment by jczaja** [comment]
@luotao1 Early implementation is done, so as soon as I test performance (and the performance is better) then first PR will
set up. So if performance is good then PR is to be setup this week

**Pull request closed without merging**
