### PR TITLE
Fix undefined symbol: shm_open

### PR DESCRIPTION
**Pull request by tsocha**
### PR types
Bug fixes

### PR changes
Others

### Describe
Fix a problem with undefined symbol: shm_open on gcc 8.4:
error log:
```
Error: Can not import paddle core while this file exists: /home/tsocha/dev/paddle/build/python/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "./sh.py", line 1, in <module>
    import paddle
  File "/home/tsocha/dev/paddle/build/python/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/tsocha/dev/paddle/build/python/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/tsocha/dev/paddle/build/python/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/tsocha/dev/paddle/build/python/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/tsocha/dev/paddle/build/python/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/tsocha/dev/paddle/build/python/paddle/fluid/core.py", line 301, in <module>
    raise e
  File "/home/tsocha/dev/paddle/build/python/paddle/fluid/core.py", line 247, in <module>
    from . import libpaddle
ImportError: /home/tsocha/dev/paddle/build/python/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink

```

### CODE REVIEW

**Comment by paulinagacek** [comment]
LGTM

**Comment by tsocha** [comment]
@jiangjiajun could you review this PR?

**Review by jczaja — APPROVED** [review]
LGTM

**Review by jiangjiajun — APPROVED** [review]
LGTM****

**Pull request merged**
