### PR TITLE
[Fluid Clean] remove fluid.layers.continuous_value_model

### PR DESCRIPTION
**Pull request by heyanru01**
### PR types

Others
### PR changes

APIs
### Describe

move fluid.layers.continuous_value_model

### CODE REVIEW

**Comment by yingshengBD** [comment]
LGTM

**Review by jzhang533 — DISMISSED** [review]
LGTM for API removing

**Review by jzhang533 — DISMISSED** [review]

**Review by XiaoguangHu01 — DISMISSED** [review]
LGTM

**Review by jzhang533 — APPROVED** [review]

**Review by jzhang533 — APPROVED** [review]

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by hong19860320 — APPROVED** [review]
LGTM

**Pull request merged**
