### PR TITLE
[ROCM] update fluid operators for rocm (part5), test=develop

### PR DESCRIPTION
**Pull request by qili93**
### PR types

New features

### PR changes

OPs

### Describe

[ROCM] update fluid operators for rocm (part5)

### CODE REVIEW

**Review by shangzhizhou — DISMISSED** [review]
LGTM

**Review by shangzhizhou — DISMISSED** [review]
LGTM

**Review by shangzhizhou — APPROVED** [review]
LGTM

**Review by GaoWei8 — APPROVED** [review]
LGTM for op benchmark ci

**Pull request merged**
