### PR TITLE
Dist transpile can pass startup program by argument

### PR DESCRIPTION
**Pull request by typhoonzero**
Related PR: https://github.com/PaddlePaddle/Paddle/pull/12305

In cases that we need to pass programs explicitly.

### CODE REVIEW

**Comment by typhoonzero** [comment]
@panyx0718 @reyoung @qingqing01 Need approvals for the api change, thanks!

**Review by reyoung — APPROVED** [review]

**Comment by panyx0718** [comment]
why is it related to #12305?
I don't see get_startup_program used there

**Comment by typhoonzero** [comment]
@panyx0718 , I've updated #12305, if we construct train program and test program using `with` guard, the startup program will not be in `fluid.default_startup_program`

**Review by panyx0718 — APPROVED** [review]

**Review by gongweibao — APPROVED** [review]
LGTM++

**Pull request merged**
