### PR TITLE
fix some spelling errors

### PR DESCRIPTION
**Pull request by zhaify**
This PR includes the following changes:

mannually  -> manually
lenght  -> length
defalut -> default
Cann't -> Can't (`cann't` is the nonstandard spelling of `can't`.)
reprenset -> represent
turple -> tuple (in python)
boudding -> bounding
dection -> detection
compressoin -> compression
trainging -> training
inferecne -> inference

### CODE REVIEW

**Review by luotao1 — DISMISSED** [review]
LGTM! Thanks very much!

**Comment by zhaify** [comment]
> LGTM! Thanks very much!
@luotao1 CI failed since some words relates to API files, should I follow the following steps to update API.spec?

```
[02:49:30] :	 [Step 1/1] If you modify/add/delete the API files, including code and comment, please follow these steps in order to pass the CI:
[02:49:30] :	 [Step 1/1]     1. cd ${paddle_path}, compile paddle;
[02:49:30] :	 [Step 1/1]     2. pip install build/python/dist/(build whl package);
[02:49:30] :	 [Step 1/1]     3. run "python tools/print_signatures.py paddle.fluid,paddle.reader > paddle/fluid/API.spec"
[02:49:34]W:	 [Step 1/1] Process exited with code 1
```

**Comment by luotao1** [comment]
why close this PR?

**Comment by zhaify** [comment]
> why close this PR?

I met hard conflict on `paddle/fluid/API.spec`, and I worried that it will lead to some problem if I merge API.spec  generated on my local machine to develop branch.

**Comment by luotao1** [comment]
why delete your branch? I can't see any file in this PR.

**Comment by zhaify** [comment]
> why delete your branch? I can't see any file in this PR.

I made a mistake on this PR, and will resubmit a new one.
BTW, do I need to update the file of `paddle/fluid/API.spec` or only fix these words is enough?

**Comment by luotao1** [comment]
You could not update the `paddle/fluid/API.spec` at first, and if ci fails, please comment me.

**Comment by luotao1** [comment]
Yes, you should update the file of `paddle/fluid/API.spec`, any api document update will trigger the md5sum of this file.

**Comment by zhaify** [comment]
> Yes, you should update the file of `paddle/fluid/API.spec`, any api document update will trigger the md5sum of this file.

I have created a new PR [17941](https://github.com/PaddlePaddle/Paddle/pull/17941)

**Pull request closed without merging**
