### PR TITLE
Add persistable assertion for bias in preln_residual_bias_fuse_pass

### PR DESCRIPTION
**Pull request by wanghaoshuang**
### PR types
Bug fixes

### PR changes
Others

### Describe
Add persistable assertion for bias in preln_residual_bias_fuse_pass

该模型错误地匹配到了preln_residual_bias_pass。如下图所示，将红色方框内的operators融合为了preln_residual_bias op。该行为不符合预期，因为蓝色方框内的elemenwise_add并不是bias.

解决办法: 修改preln_residual_bias_pass，加强bias的判定条件。
image

### CODE REVIEW

**Review by minghaoBD — APPROVED** [review]
LGTM

**Review by Wangzheee — APPROVED** [review]
LGTM

**Comment by wanghaoshuang** [comment]
restart for ci

**Comment by wanghaoshuang** [comment]
restart for ci

**Comment by wanghaoshuang** [comment]
restart for ci

**Comment by wanghaoshuang** [comment]
restart for ci

**Review by chalsliu — APPROVED** [review]

**Pull request merged**
