### PR TITLE
[oneDNN] bump up oneDNN to 2.2.2 

### PR DESCRIPTION
**Pull request by jczaja**
### PR types
Bug fixes

### PR changes
Others

### Describe
This is an update of oneDNN to 2.2.2 it contains some optimizations that should help to some of performance drops reported at (https://github.com/PaddlePaddle/Paddle/issues/32311).

### CODE REVIEW

**Comment by jakpiase** [comment]
LGTM

**Review by jakpiase — DISMISSED** [review]
LGTM

**Review by luotao1 — DISMISSED** [review]

**Comment by luotao1** [comment]
@jczaja If this PR could be merged, please tell me

**Comment by lidanqing-vv** [comment]
Hi, I am tesing ICX for PDT review and for Li Wei. I will provide oneDNN team logs after I finish current work

**Comment by lidanqing-vv** [comment]
I tested on my i9 machine, and it is around 2% perf rise. We should merge it. Thanks! 
LGTM.
@luotao1

**Review by jakpiase — APPROVED** [review]
LGTM

**Review by lidanqing-vv — APPROVED** [review]
LGTM

**Pull request merged**
