### PR TITLE
Revert https://github.com/PaddlePaddle/Paddle/pull/62969

### PR DESCRIPTION
**Pull request by co63oc**
### PR Category

Others

### PR Types

Others

### Description

OMP执行单测有错误 
Revert https://github.com/PaddlePaddle/Paddle/pull/62969

### CODE REVIEW

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Comment by LLee233** [comment]
Hi @co63oc ,我这边是最近跑inference case的时候发现的这个现象。就是之前我们在跑**TA_IC_demark_performance**这个case的时候，会用如下命令：
```
KMP_AFFINITY=granularity=fine,compact,1,0 KMP_BLOCKTIME=1 OMP_NUM_THREADS=32 ./test/cpp/inference/api/test_analyzer_image_classification --gtest_filter=*profile_mkldnn --repeat=1000  --batch_size=1    --infer_model=/paddle/data/demark
```
可以看到这里指定了OMP_NUM_THREADS=32，用32个线程跑单个case。在[PR62969](https://github.com/PaddlePaddle/Paddle/pull/62969)之前，这种指定方式都是行得通的；但在PR之后，我们再用同样的指令跑这个case就会得到大幅的性能下跌。经分析，就是因为omp这个变量失效，实际上只能跑出单线程的性能：

#Before:
I0426 07:31:45.298254 37007 helper.h:416] ====== threads: 1, thread id: 0 ======
I0426 07:31:45.298275 37007 helper.h:418] ====== batch size: 1, iterations: 1, repetitions: 1000 ======
I0426 07:31:45.298280 37007 helper.h:420] ====== batch latency: 6.03725ms, number of samples: 1, sample latency: 6.03725ms, fps: **165.638**, data type: float ======

#After:
I0426 06:36:59.783483    33 helper.h:416] ====== threads: 1, thread id: 0 ======
I0426 06:36:59.783514    33 helper.h:418] ====== batch size: 1, iterations: 1, repetitions: 1000 ======
I0426 06:36:59.783519    33 helper.h:420] ====== batch latency: 112.907ms, number of samples: 1, sample latency: 112.907ms, fps: **8.85687**, data type: float ======

然后我们尝试使用--num_threads 来指定线程，但发现这个option只能决定多个case同时跑单线程，并不能指定多线程跑单个case。

然后我看这个PR之前是为了解决Ubuntu 22.04.2的链接问题，我们在18.04好像没有碰到过类似的情况（用的Paddle以前提供的镜像）。

机器环境如下：
```
#OS
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#gcc
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-8.2/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-8.2.0/configure --prefix=/usr/local/gcc-8.2 --enable-threads=posix --disable-checking --disable-multilib
Thread model: posix
gcc version 8.2.0 (GCC)

#cpu info
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
Stepping:            7
CPU MHz:             999.914
CPU max MHz:         3900.0000
CPU min MHz:         1000.0000
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-23,48-71
NUMA node1 CPU(s):   24-47,72-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni spec_ctrl intel_stibp flush_l1d arch_capabilities
```

**Comment by co63oc** [comment]
> Hi @co63oc ,我这边是最近跑inference case的时候发现的这个现象。就是之前我们在跑**TA_IC_demark_performance**这个case的时候，会用如下命令：
> 
> ```
> KMP_AFFINITY=granularity=fine,compact,1,0 KMP_BLOCKTIME=1 OMP_NUM_THREADS=32 ./test/cpp/inference/api/test_analyzer_image_classification --gtest_filter=*profile_mkldnn --repeat=1000  --batch_size=1    --infer_model=/paddle/data/demark
> ```
> 
> 可以看到这里指定了OMP_NUM_THREADS=32，用32个线程跑单个case。在[PR62969](https://github.com/PaddlePaddle/Paddle/pull/62969)之前，这种指定方式都是行得通的；但在PR之后，我们再用同样的指令跑这个case就会得到大幅的性能下跌。经分析，就是因为omp这个变量失效，实际上只能跑出单线程的性能：
> 
> #Before: I0426 07:31:45.298254 37007 helper.h:416] ====== threads: 1, thread id: 0 ====== I0426 07:31:45.298275 37007 helper.h:418] ====== batch size: 1, iterations: 1, repetitions: 1000 ====== I0426 07:31:45.298280 37007 helper.h:420] ====== batch latency: 6.03725ms, number of samples: 1, sample latency: 6.03725ms, fps: **165.638**, data type: float ======
> 
> #After: I0426 06:36:59.783483 33 helper.h:416] ====== threads: 1, thread id: 0 ====== I0426 06:36:59.783514 33 helper.h:418] ====== batch size: 1, iterations: 1, repetitions: 1000 ====== I0426 06:36:59.783519 33 helper.h:420] ====== batch latency: 112.907ms, number of samples: 1, sample latency: 112.907ms, fps: **8.85687**, data type: float ======
> 
> 然后我们尝试使用--num_threads 来指定线程，但发现这个option只能决定多个case同时跑单线程，并不能指定多线程跑单个case。
> 
> 然后我看这个PR之前是为了解决Ubuntu 22.04.2的链接问题，我们在18.04好像没有碰到过类似的情况（用的Paddle以前提供的镜像）。
> 
> 机器环境如下：
> 
> ```
> #OS
> NAME="Ubuntu"
> VERSION="18.04.6 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.6 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic
> 
> #gcc
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/local/gcc-8.2/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
> Target: x86_64-pc-linux-gnu
> Configured with: ../gcc-8.2.0/configure --prefix=/usr/local/gcc-8.2 --enable-threads=posix --disable-checking --disable-multilib
> Thread model: posix
> gcc version 8.2.0 (GCC)
> 
> #cpu info
> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              96
> On-line CPU(s) list: 0-95
> Thread(s) per core:  2
> Core(s) per socket:  24
> Socket(s):           2
> NUMA node(s):        2
> Vendor ID:           GenuineIntel
> CPU family:          6
> Model:               85
> Model name:          Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
> Stepping:            7
> CPU MHz:             999.914
> CPU max MHz:         3900.0000
> CPU min MHz:         1000.0000
> BogoMIPS:            5200.00
> Virtualization:      VT-x
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            1024K
> L3 cache:            33792K
> NUMA node0 CPU(s):   0-23,48-71
> NUMA node1 CPU(s):   24-47,72-95
> Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni spec_ctrl intel_stibp flush_l1d arch_capabilities
> ```

@LLee233 是不是能用ldd命令查看文件链接库有变化，如果用不到的链接库，应该编译后程序不会链接
ldd ./test/cpp/inference/api/test_analyzer_image_classification

**Comment by co63oc** [comment]
profile_mkldnn  然后这个过滤不知道有没有影响，部分测试用例有修改过名称mkldnn 改为 onednn

或者CMakeFiles.txt中再增加gcc版本的判断

**Comment by co63oc** [comment]
https://github.com/PaddlePaddle/Paddle/pull/63950 增加gcc版本判断修改

**Comment by co63oc** [comment]
PR-CI-Kunlun-R200 链接错误
image

**Comment by LLee233** [comment]
> @LLee233 是不是能用ldd命令查看文件链接库有变化，如果用不到的链接库，应该编译后程序不会链接 ldd ./test/cpp/inference/api/test_analyzer_image_classification

链接库里倒是只有common用上了：
```
        linux-vdso.so.1 (0x00007ffed23a4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe4526fc000)
        libpaddle_inference.so => /paddle/Paddle/build/paddle/fluid/inference/libpaddle_inference.so (0x00007fe44b003000)
        libpython3.9.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0 (0x00007fe44a86f000)
        libphi.so => /paddle/Paddle/build/paddle/phi/libphi.so (0x00007fe446306000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe4460fe000)
        libcommon.so => /paddle/Paddle/build/paddle/common/libcommon.so (0x00007fe452aea000)
        libdnnl.so.3 => /paddle/Paddle/build/third_party/install/onednn/lib/libdnnl.so.3 (0x00007fe443370000)
        libiomp5.so => /paddle/Paddle/build/third_party/install/mklml/lib/libiomp5.so (0x00007fe442f7b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe442bf3000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe4429db000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe4425ea000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe45291b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe44224c000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fe44201a000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe441dfd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe441bf9000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fe4419f6000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fe4417c7000)
```
但是我试过在CMakeList里删掉common，也没办法enable omp。 
然后我刚刚在common/里发现有个flag叫：
```
/**
 * Paddle initialization related FLAG
 * Name: FLAGS_paddle_num_threads
 * Since Version: 0.15.0
 * Value Range: int32, default=1
 * Example: FLAGS_paddle_num_threads=2, set the maximum thread number per
 * instance to 2
 * Note:
 */

PHI_DEFINE_EXPORTED_int32(paddle_num_threads,
                          1,
                          "Number of threads for each paddle instance.");
```
试着改了一下，好像没用。。。

> profile_mkldnn 然后这个过滤不知道有没有影响，部分测试用例有修改过名称mkldnn 改为 onednn

跟这个应该没关系，因为我是直接回退到 [PR62969](https://github.com/PaddlePaddle/Paddle/pull/62969)前后去试的，那时候mkldnn还没更名为onednn。

> 或者CMakeFiles.txt中再增加gcc版本的判断

这个应该能解决我这边环境碰到的问题，但不确定PR里说的链接失效是不是确实只在gcc-9往上的版本出现欸。

**Comment by co63oc** [comment]
> > @LLee233 是不是能用ldd命令查看文件链接库有变化，如果用不到的链接库，应该编译后程序不会链接 ldd ./test/cpp/inference/api/test_analyzer_image_classification
> 
> 链接库里倒是只有common用上了：
> 
> ```
>         linux-vdso.so.1 (0x00007ffed23a4000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe4526fc000)
>         libpaddle_inference.so => /paddle/Paddle/build/paddle/fluid/inference/libpaddle_inference.so (0x00007fe44b003000)
>         libpython3.9.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0 (0x00007fe44a86f000)
>         libphi.so => /paddle/Paddle/build/paddle/phi/libphi.so (0x00007fe446306000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe4460fe000)
>         libcommon.so => /paddle/Paddle/build/paddle/common/libcommon.so (0x00007fe452aea000)
>         libdnnl.so.3 => /paddle/Paddle/build/third_party/install/onednn/lib/libdnnl.so.3 (0x00007fe443370000)
>         libiomp5.so => /paddle/Paddle/build/third_party/install/mklml/lib/libiomp5.so (0x00007fe442f7b000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe442bf3000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe4429db000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe4425ea000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fe45291b000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe44224c000)
>         libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fe44201a000)
>         libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe441dfd000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe441bf9000)
>         libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fe4419f6000)
>         libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fe4417c7000)
> ```
> 
> 但是我试过在CMakeList里删掉common，也没办法enable omp。 然后我刚刚在common/里发现有个flag叫：
> 
> ```
> /**
>  * Paddle initialization related FLAG
>  * Name: FLAGS_paddle_num_threads
>  * Since Version: 0.15.0
>  * Value Range: int32, default=1
>  * Example: FLAGS_paddle_num_threads=2, set the maximum thread number per
>  * instance to 2
>  * Note:
>  */
> 
> PHI_DEFINE_EXPORTED_int32(paddle_num_threads,
>                           1,
>                           "Number of threads for each paddle instance.");
> ```
> 
> 试着改了一下，好像没用。。。
> 
> > profile_mkldnn 然后这个过滤不知道有没有影响，部分测试用例有修改过名称mkldnn 改为 onednn
> 
> 跟这个应该没关系，因为我是直接回退到 [PR62969](https://github.com/PaddlePaddle/Paddle/pull/62969)前后去试的，那时候mkldnn还没更名为onednn。
> 
> > 或者CMakeFiles.txt中再增加gcc版本的判断
> 
> 这个应该能解决我这边环境碰到的问题，但不确定PR里说的链接失效是不是确实只在gcc-9往上的版本出现欸。

那有其他PR也在回退，不确定回退当前PR 是否能解决问题，如果修改那就是加上版本号的判断，现在是 PR-CI-Kunlun-R200 会有错误

**Comment by LLee233** [comment]
> 那有其他PR也在回退，不确定回退当前PR 是否能解决问题，如果修改那就是加上版本号的判断，现在是 PR-CI-Kunlun-R200 会有错误

是的，看见你的截图了。单纯地回退应该不可取，主要是现在不知道到底什么原因引起的。。。你说的PR是[63950](https://github.com/PaddlePaddle/Paddle/pull/63950)是吧？目前看起来那个应该可以的，至少能解决我这边当前环境碰到的情况。

**Comment by co63oc** [comment]
> OMP_NUM_THREADS



> > 那有其他PR也在回退，不确定回退当前PR 是否能解决问题，如果修改那就是加上版本号的判断，现在是 PR-CI-Kunlun-R200 会有错误
> 
> 是的，看见你的截图了。单纯地回退应该不可取，主要是现在不知道到底什么原因引起的。。。你说的PR是[63950](https://github.com/PaddlePaddle/Paddle/pull/63950)是吧？目前看起来那个应该可以的，至少能解决我这边当前环境碰到的情况。

https://github.com/PaddlePaddle/Paddle/pull/63942
https://github.com/PaddlePaddle/Paddle/pull/63950
加不加版本判断都有CI错误，或者本地是不是用PR的修改试下

> > 那有其他PR也在回退，不确定回退当前PR 是否能解决问题，如果修改那就是加上版本号的判断，现在是 PR-CI-Kunlun-R200 会有错误
> 
> 是的，看见你的截图了。单纯地回退应该不可取，主要是现在不知道到底什么原因引起的。。。你说的PR是[63950](https://github.com/PaddlePaddle/Paddle/pull/63950)是吧？目前看起来那个应该可以的，至少能解决我这边当前环境碰到的情况。

PR-CI-Kunlun-R200 是gcc 8.4，再次修改了版本判断https://github.com/PaddlePaddle/Paddle/pull/63950，再看PR的运行了

**Comment by co63oc** [comment]
PR-CI-Kunlun-R200错误，当前PR关闭，改为 https://github.com/PaddlePaddle/Paddle/pull/63950

**Pull request closed without merging**
