### PR TITLE
[CodeStyle][C405] Unnecessary <list/tuple> literal - rewrite as a set literal.

### PR DESCRIPTION
**Pull request by enkilee**
### PR types

Others
### PR changes

Others
## 1
Add rules C403 C404 C405 in pyproject.toml file.

## 2
Unnecessary list comprehension (rewrite as a set comprehension)
According to https://beta.ruff.rs/docs/rules/unnecessary-generator-set/ and https://pypi.org/project/flake8-comprehensions/
C405 Unnecessary <list/tuple> literal - rewrite as a set literal.

So we can rewrite as follow:

Rewrite set([1, 2]) as {1, 2}
Rewrite set((1, 2)) as {1, 2}
Rewrite set([]) as set()
Rewrite dict([(1, 2)]) as {1: 2}
Rewrite dict(((1, 2),)) as {1: 2}
Rewrite dict([]) as {}

Timing use:
``` python
>>>from timeit import timeit
>>>print("set([1, 2]):", timeit("set([1, 2])"))
set([1, 2]): 0.1881980188190937
>>>print("set((1, 2)):", timeit("set((1, 2))"))
set((1, 2)): 0.15197720006108284
>>>print("set([1, 2]) and set((1, 2)) change to {1,2}:", timeit("{1,2}"))
set([1, 2]) and set((1, 2)) change to {1,2}: 0.05990268290042877
>>>print("set([]):", timeit("set([])"))
set([]): 0.13672637194395065
>>>print("set([]) change to set():", timeit("set()"))
set([]) change to set(): 0.07350808382034302


>>>print("dict([(1, 2)]):", timeit("dict([(1, 2)])"))
dict([(1, 2)]): 0.2214132510125637
>>>print("dict(((1, 2),)):", timeit("dict(((1, 2),))"))
dict(((1, 2),)): 0.18148768320679665
>>>print("dict([(1, 2)]) and dict(((1, 2),)) change to {1: 2}:", timeit("{1: 2}"))
dict([(1, 2)]) and dict(((1, 2),)) change to {1: 2}: 0.05654028430581093
>>>print("dict([]):", timeit("dict([])"))
dict([]): 0.1704074963927269
>>>print("dict([]) change to {}:", timeit("{}"))
dict([]) change to {}: 0.04016955569386482
```

Changed 72 files, no semantic or syntax error. The conclusions are as follows：
using rule：✅ 
auto fix：✅

command as follow：
```bash
# install ruff 0.0.254
pip install ruff==0.0.254
# using command to auto fix:
ruff --select C405 . --fix
```

### CODE REVIEW

**Review by SigureMo — DISMISSED** [review]
LGTM

**Comment by SigureMo** [comment]
@enkilee 需要解决下冲突～

**Comment by luotao1** [comment]
@enkilee 请解决下冲突

**Comment by enkilee** [comment]
收到！已解决冲突
@luotao1 @SigureMo

**Comment by luotao1** [comment]
辛苦再解决下冲突

**Comment by enkilee** [comment]
已解决冲突

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
