### PR TITLE
Fix a code sample bug for function 'mode()'

### PR DESCRIPTION
**Pull request by loserlulin9**
### PR types
Bug fixes
### PR changes
Others
### Describe
For the code example in function `` mode() `` which lies in `` Paddle/python/paddle/tensor/search.py ``, this PR changes its running result.

### CODE REVIEW

**Comment by loserlulin9** [comment]
I don't get useful information from these three automatic checks. Could anyone state my mistakes clearly? Much thanks!!!

**Review by luotao1 — APPROVED** [review]
LGTM

**Comment by loserlulin9** [comment]
> LGTM

This change have passed 23 auto checks, but failed in `` PR-CI-Kunlun-R200-Test ``. I have no idea about the mistake information in it, but it seems that it's **not required**. Could this PR be merged? Or what should I do in addition?

**Comment by luotao1** [comment]
> I have no idea about the mistake information in it, but it seems that it's not required. Could this PR be merged? 

Yes, you can ignore the un-required CI. This PR is merged. Thanks for your contribution.

**Pull request merged**
