### PR TITLE
remove to_variable from paddle 2.0

### PR DESCRIPTION
**Pull request by zhwesky2010**
### PR types

Others
### PR changes

APIs
### Describe

remove to_variable from paddle 2.0.

pleause use `paddle.to_tensor` .
image
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tensor/creation/to_tensor_cn.html#to-tensor

### CODE REVIEW

**Review by jzhang533 — DISMISSED** [review]
lgtm

**Comment by zhwesky2010** [comment]
disable_static 非常多，统一修改，这个PR没有修改

**Review by jzhang533 — APPROVED** [review]
lgtm

**Review by XiaoguangHu01 — APPROVED** [review]
LGTM

**Review by raindrops2sea — APPROVED** [review]

**Pull request merged**
