### PR TITLE
remove async executor python api to fix document

### PR DESCRIPTION
**Pull request by guru4elephant**
test=develop

### CODE REVIEW

**Review by wangguibao — APPROVED** [review]
OK

**Review by shanyi15 — APPROVED** [review]

**Comment by chengduoZH** [comment]
@guru4elephant Can you explain in detail why do you remove those API?

**Comment by guru4elephant** [comment]
> @guru4elephant Can you explain in detail why do you remove those API?

AsyncExecutor and Executor are merge in release 1.4, users can use Executor.train_from_dataset and Executor.infer_from_dataset for AsyncExecutor execution. Previously, the document of these APIs are not public in our official document, so users are not affected except the examples of text classification in Paddle/models. I will refine the text classification example of AsyncExecutor when this pr got merged.

**Comment by chengduoZH** [comment]
@guru4elephant In this case, you need to specify in the release note that these APIs have been deleted and what alternative APIs are when the next version is released.

**Review by chengduoZH — APPROVED** [review]
**Considering the compatibility of versions, it is better not to add and delete APIs at will, which is very unfriendly to users.**

**Pull request merged**
